import { randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { Pool, type PoolClient } from 'pg';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

const databaseUrl = process.env.CUT_INTEGRATION_DATABASE_URL ?? process.env.TEST_DATABASE_URL;
const describeIntegration = databaseUrl ? describe : describe.skip;
const schema = `label_cut_map_${randomUUID().replaceAll('-', '_')}`;
const migration079 = readFileSync(new URL('../../../../db/migrations/079_cut_result_history_expand.sql', import.meta.url), 'utf8');
const migration079Compat = readFileSync(new URL('../../../../db/migrations/079_z_cut_result_jsonb_object_length_compat.sql', import.meta.url), 'utf8');
const migration080 = readFileSync(new URL('../../../../db/migrations/080_cut_result_history_finalize.sql', import.meta.url), 'utf8');
const migration081 = readFileSync(new URL('../../../../db/migrations/081_label_cut_maps.sql', import.meta.url), 'utf8');
const migration082 = readFileSync(new URL('../../../../db/migrations/082_label_cut_maps_backfill.sql', import.meta.url), 'utf8');

describeIntegration('label cut-map migration chain', () => {
  const pool = new Pool({ connectionString: databaseUrl });
  let client: PoolClient;
  let cutJobId: number;
  let snapshot: ReturnType<typeof validSnapshot>;

  beforeAll(async () => {
    client = await pool.connect();
    await client.query(`CREATE SCHEMA ${schema}`);
    await client.query(`SET search_path TO ${schema}, public`);
    await client.query(`
      CREATE TABLE users (user_id BIGINT PRIMARY KEY, username TEXT);
      CREATE TABLE cut_job (
        cut_job_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'ready'
      );
      CREATE TABLE label_template_elements (
        label_template_element_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        kind TEXT NOT NULL,
        CONSTRAINT chk_label_template_elements_kind CHECK (kind IN ('text', 'line', 'rect', 'qr'))
      );
      CREATE TABLE order_label_generations (
        order_label_generation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
      );
    `);
    await client.query(migration079);
    const job = await client.query<{ cut_job_id: string }>(
      `INSERT INTO ${schema}.cut_job (name) VALUES ('Тестовый раскрой') RETURNING cut_job_id`,
    );
    cutJobId = Number(job.rows[0].cut_job_id);
    snapshot = validSnapshot(cutJobId);
    const inserted = await client.query<{ cut_result_id: string }>(
      `INSERT INTO ${schema}.cut_result
         (cut_job_id, result_no, result_kind, source_job_version,
          snapshot_job, snapshot_manifest, snapshot_digest, totals_snapshot)
       VALUES ($1, 1, 'legacy', 1, $2::jsonb, $3::jsonb,
               cut_result_snapshot_digest($2::jsonb), $4::jsonb)
       RETURNING cut_result_id`,
      [cutJobId, JSON.stringify(snapshot), JSON.stringify(manifest(snapshot)), JSON.stringify(snapshot.totals)],
    );
    await client.query(
      `UPDATE ${schema}.cut_job SET current_cut_result_id = $2, next_cut_result_no = 2 WHERE cut_job_id = $1`,
      [cutJobId, inserted.rows[0].cut_result_id],
    );
    await client.query(migration079Compat);
    await client.query(migration080);
    await client.query(migration081);
    const beforeBackfill = await client.query<{ count: number }>(
      `SELECT count(*)::int AS count FROM ${schema}.cut_result_placement`,
    );
    expect(beforeBackfill.rows[0].count).toBe(0);
    const call = 'CALL backfill_cut_result_label_maps();';
    const callIndex = migration082.indexOf(call);
    expect(callIndex).toBeGreaterThan(0);
    await client.query(migration082.slice(0, callIndex));
    // CALL must be a top-level statement so the procedure can commit each
    // projected result independently, exactly as the psql migration runner does.
    await client.query(call);
    await client.query(migration082.slice(callIndex + call.length));
  });

  afterAll(async () => {
    if (client) {
      await client.query('ROLLBACK').catch(() => undefined);
      await client.query('SET search_path TO public');
      await client.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);
      client.release();
    }
    await pool.end();
  });

  it('backfills exact instances, trim-adjusted geometry, and the labels-off SVG', async () => {
    const rows = await client.query<{
      instance: number;
      x_mm: string;
      y_mm: string;
      base_svg: string;
      is_effective: boolean;
    }>(
      `SELECT p.instance, p.x_mm, p.y_mm, s.base_svg, s.is_effective
       FROM ${schema}.cut_result_placement p
       JOIN ${schema}.cut_result_sheet_map s USING (cut_result_sheet_map_id)
       ORDER BY p.instance`,
    );
    expect(rows.rows).toHaveLength(2);
    expect(rows.rows[0]).toMatchObject({ instance: 1, x_mm: '110.000', y_mm: '70.000', is_effective: true });
    expect(rows.rows[0].base_svg).toContain('data-base="labels-off"');
  });

  it('projects later immutable results through the insert trigger', async () => {
    await client.query(
      `INSERT INTO ${schema}.cut_result
         (cut_job_id, result_no, result_kind, source_job_version,
          snapshot_job, snapshot_manifest, snapshot_digest, totals_snapshot)
       VALUES ($1, 2, 'legacy', 1, $2::jsonb, $3::jsonb,
               cut_result_snapshot_digest($2::jsonb), $4::jsonb)`,
      [cutJobId, JSON.stringify(snapshot), JSON.stringify(manifest(snapshot)), JSON.stringify(snapshot.totals)],
    );
    const count = await client.query<{ count: number }>(
      `SELECT count(*)::int AS count FROM ${schema}.cut_result_placement`,
    );
    expect(count.rows[0].count).toBe(4);
  });

  it('keeps projection rows append-only and accepts the cut_map template kind', async () => {
    await client.query(`INSERT INTO ${schema}.label_template_elements (kind) VALUES ('cut_map')`);
    await expect(client.query(
      `UPDATE ${schema}.cut_result_placement SET x_mm = x_mm + 1`,
    )).rejects.toThrow(/append-only/i);
    await expect(client.query(
      `INSERT INTO ${schema}.cut_result_sheet_map
         (cut_result_id, cut_job_id, cut_group_id, group_key, variant, sheet_index,
          sheet_ordinal, is_effective, sheet_width_mm, sheet_height_mm, base_svg)
       VALUES (1, 1, 1, 'forged', 'auto', 99, 1, true, 1, 1, '<svg></svg>')`,
    )).rejects.toThrow(/only by the projection function/i);
  });

  it('clears the insert guard inside the transaction that creates a cut result', async () => {
    await client.query('BEGIN');
    try {
      const inserted = await client.query<{ cut_result_id: string }>(
        `INSERT INTO ${schema}.cut_result
           (cut_job_id, result_no, result_kind, source_job_version,
            snapshot_job, snapshot_manifest, snapshot_digest, totals_snapshot)
         VALUES ($1, 3, 'legacy', 1, $2::jsonb, $3::jsonb,
                 cut_result_snapshot_digest($2::jsonb), $4::jsonb)
         RETURNING cut_result_id`,
        [cutJobId, JSON.stringify(snapshot), JSON.stringify(manifest(snapshot)), JSON.stringify(snapshot.totals)],
      );
      await expect(client.query(
        `INSERT INTO ${schema}.cut_result_sheet_map
           (cut_result_id, cut_job_id, cut_group_id, group_key, variant, sheet_index,
            sheet_ordinal, is_effective, sheet_width_mm, sheet_height_mm, base_svg)
         VALUES ($1, $2, 30, 'forged', 'auto', 99, 2, true, 1, 1, '<svg></svg>')`,
        [inserted.rows[0].cut_result_id, cutJobId],
      )).rejects.toThrow(/only by the projection function/i);
    } finally {
      await client.query('ROLLBACK');
    }
  });
});

function validSnapshot(cutJobId: number) {
  return {
    cutJobId,
    name: 'Тестовый раскрой',
    version: 1,
    items: [{
      orderDetailId: 10,
      orderId: 20,
      qty: 2,
      cutGroupId: 30,
      detail: { width: 500, height: 300 },
    }],
    groups: [{
      cutGroupId: 30,
      groupKey: 'm:1|f:0',
      sheets: [{
        sheetIndex: 7,
        placements: {
          trim_mm: { left: 10, right: 10, top: 20, bottom: 20 },
          sheet_width_mm: 2800,
          sheet_height_mm: 2070,
          pieces: [
            { item_id: 'det-10', instance: 1, x_mm: 100, y_mm: 50, width_mm: 500, height_mm: 300, rotated: false },
            { item_id: 'det-10', instance: 2, x_mm: 620, y_mm: 50, width_mm: 300, height_mm: 500, rotated: true },
          ],
        },
        renderSnapshot: renderSnapshot(),
      }],
      manualLayout: null,
    }],
    totals: { positions: 1, details: 2, area: 0.3, sheets: 1, materialsCount: 1, filmsCount: 0 },
    unplaced: [],
  };
}

function renderSnapshot() {
  return {
    contractVersion: 'cut_sheet_render_v1',
    views: {
      'r0:raw:top-left:labels-off': {
        svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2800 2070" data-base="labels-off"></svg>',
        bathSvg: '<svg/>',
      },
      ...Object.fromEntries(Array.from({ length: 11 }, (_, index) => [`view-${index}`, { svg: '<svg/>', bathSvg: '<svg/>' }])),
    },
    pdfMeta: {},
    pdfDetailRows: [],
  };
}

function manifest(snapshot: ReturnType<typeof validSnapshot>) {
  return {
    groups: 1,
    items: 1,
    instances: 2,
    unplaced: 0,
    variants: [{
      groupKey: 'm:1|f:0',
      autoSheets: [7],
      manualSheets: [],
      renderContract: 'cut_sheet_render_v1',
      autoRenderViews: [12],
      manualRenderViews: [],
      manualState: 'none',
    }],
  };
}
