import type { OrderDto } from '../dto/order.dto';

export function createOrderDtoForQueryTest(orderId: number): OrderDto {
  return {
    header: {
      orderId,
      orderName: 'Test order',
      orderKind: 'production_order',
      sourceSystem: 'erp',
      projectId: 501,
      projectCode: 'МП-501',
      fullNumber: 'МП-501-Test order',
      clientId: 1001,
      clientName: 'Test client',
      orderDate: '2026-04-30',
      priority: 100,
      orderStatusId: 1001,
      paymentStatusId: 1,
      productionStatusId: null,
      productionStatusFromDetailsEnabled: true,
      plannedCompletionDate: null,
      completionDate: null,
      issueDate: null,
      paymentDate: null,
      totalAmount: 0,
      discount: 0,
      surcharge: 0,
      finalAmount: 0,
      paidAmount: 0,
      partsCount: 0,
      totalArea: 0,
      linkCuttingFile: null,
      linkCuttingImageFile: null,
      linkCadFile: null,
      linkPdfFile: null,
      notes: null,
      refKey1c: null,
      createdAt: '2026-04-30T00:00:00.000Z',
      updatedAt: '2026-04-30T00:00:00.000Z',
      createdBy: 15,
      editedBy: 16,
      version: 1,
    },
    details: [],
    payments: [],
    workshops: [],
    requirements: [],
    dowelingLinks: [],
    primaryGroup: null,
    groups: [],
    totals: {
      totalAmount: 0,
      finalAmount: 0,
      paidAmount: 0,
      debtAmount: 0,
      partsCount: 0,
      totalArea: 0,
    },
    version: 1,
    createdAt: '2026-04-30T00:00:00.000Z',
    updatedAt: '2026-04-30T00:00:00.000Z',
    createdBy: 15,
    editedBy: 16,
  };
}
