-- Selected canonical schema snapshot, captured 2026-09-09.
-- Source: spec_erp/docs/reference/postgresql_schema_v_14.sql (outside this repository).
-- Contains the exact production_statuses CREATE TABLE and INSERT statements.
-- Refresh both statements together when canonical seed/constraint changes.
-- This snapshot does not track later edits to the external source automatically.

CREATE TABLE production_statuses (
    production_status_id SMALLINT GENERATED BY DEFAULT AS IDENTITY,
    production_status_name VARCHAR(50) NOT NULL,
    production_status_code VARCHAR(64) NOT NULL,
    sort_order SMALLINT NOT NULL,
    color VARCHAR(7),
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    ref_key_1c UUID NULL,
    created_by BIGINT,
	edited_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    
    CONSTRAINT pk_production_statuses PRIMARY KEY (production_status_id),
    CONSTRAINT uq_production_statuses_name UNIQUE (production_status_name),
    CONSTRAINT uq_production_statuses_code UNIQUE(production_status_code),
    CONSTRAINT uq_production_statuses_sort_order UNIQUE (sort_order),
    CONSTRAINT chk_production_status_color 
        CHECK (color IS NULL OR color ~ '^#[0-9A-Fa-f]{6}$'),
    CONSTRAINT chk_production_status_code_format 
        CHECK(production_status_code~'^[a-z][a-z0-9_]*$')
);

INSERT INTO production_statuses (sort_order, production_status_name, production_status_code, color) VALUES
    (10, 'Новый', 'new', '#2196F3'),
    (11, 'Отрисован', 'drawn', '#2196F3'),
    (12, 'Закуп пленки', 'film_purchase', '#2196F3'),
    (20, 'Распилен', 'cut', '#FF9800'),
    (30, 'Присажен', 'drilled', '#FF9800'),
    (40, 'Отшлифован', 'sanded', '#FFC107'),
    (50, 'Закромлен', 'stocked', '#8BC34A'),
    (60, 'Закатан', 'laminated', '#8BC34A'),
    (70, 'Упакован', 'packed', '#4CAF50'),
    (80, 'Выдан', 'issued', '#009688')
ON CONFLICT (production_status_name) DO NOTHING;
