/**
 * cut-sheet-material.integration.ts
 *
 * Real-DB integration test for the per-job sheet-material override (migration 040).
 *
 * Gated by CUT_INTEGRATION_DATABASE_URL or TEST_DATABASE_URL. When neither is
 * set all tests are skipped (describe.skip). The orchestrator runs this against
 * erp_test using the .env secret.
 *
 * Collected by vitest.cut-integration.config.ts via:
 *   include: ['backend/src/modules/cut/adapters/*.integration.ts']
 *
 * What it verifies (5 scenarios from the task-9 brief):
 *   1. setSheetMaterial to a cuttable sheet → DB column set, version bumped,
 *      exactly one audit_log row (cut_job.sheet_material_changed) with
 *      sheetMaterialTypeIds bridge rows, exactly one outbox_events row;
 *      replay same requestId → no duplicate outbox row (idempotent).
 *   2. setSheetMaterial to a non-cuttable (is_cuttable=false) sheet → 422
 *      CUT_SHEET_MATERIAL_NOT_CUTTABLE, no mutation.
 *   3. calculate with override set on a job whose details span TWO materials
 *      AND include one no_sheet_spec detail → all groups use the chosen sheet;
 *      the no_sheet_spec detail is placed; job reaches 'ready'.
 *   4. calculate after the chosen sheet is deactivated → 422
 *      CUT_SHEET_MATERIAL_NOT_CUTTABLE, job NOT marked 'failed' (status
 *      unchanged from pre-calculate).
 *   5. Override = NULL → unchanged legacy behavior (per-detail sheet; a
 *      no_sheet_spec detail still yields CutNoSheetSpecError).
 */
import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import type { DatabaseService } from '../../../database/database.service';
import type { TransactionClient } from '../../../database/database.types';
import type { CurrentUser } from '../../../permissions/current-user';
import type { FreecutOptimizeResponse } from '../application/cut-freecut-mapping';
import { CUT_AUDIT_EVENTS } from '../application/cut-audit';
import { PgCutRepository } from './pg-cut-repository';

const databaseUrl =
  process.env.CUT_INTEGRATION_DATABASE_URL ?? process.env.TEST_DATABASE_URL;
const describeIntegration = databaseUrl ? describe : describe.skip;

const schemaName = `cut_smt_${randomUUID().replaceAll('-', '_')}`;

// ── Current user fixture ─────────────────────────────────────────────────────

function currentUser(): CurrentUser {
  return {
    id: '1',
    username: 'cutter',
    role: 'operator',
    permissions: ['cut.view', 'cut.manage'],
  } as unknown as CurrentUser;
}

// ── Schema bootstrap ─────────────────────────────────────────────────────────
//
// Mirrors the full schema from pg-cut-repository.integration.ts, with migration
// 040's cut_job.sheet_material_type_id column included from the start.
// The FK references sheet_material_types which is created first.

async function createSchema(pool: Pool): Promise<void> {
  await pool.query(`
    CREATE FUNCTION set_session_user(p_user TEXT) RETURNS void AS $$ BEGIN PERFORM 1; END; $$ LANGUAGE plpgsql;

    CREATE TABLE production_statuses (
      production_status_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      production_status_code TEXT NOT NULL UNIQUE,
      production_status_name TEXT
    );
    INSERT INTO production_statuses (production_status_id, production_status_code, production_status_name)
      VALUES (1, 'new', 'Новый'), (2, 'drawn', 'Начерчен'), (3, 'film_purchase', 'Закуп плёнки'), (4, 'cut', 'Раскроен');

    CREATE TABLE sheet_material_types (
      sheet_material_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL DEFAULT '',
      width_mm NUMERIC(10,2) NOT NULL,
      height_mm NUMERIC(10,2) NOT NULL,
      is_cuttable BOOLEAN NOT NULL DEFAULT true,
      is_active BOOLEAN NOT NULL DEFAULT true
    );
    -- SMT 1: cuttable, active  (2800×2070) — the chosen override sheet in most tests
    -- SMT 2: cuttable, active  (2070×2800) — detail 4's own sheet (multi-material test)
    -- SMT 3: NOT cuttable (is_cuttable=false) — triggers CUT_SHEET_MATERIAL_NOT_CUTTABLE
    INSERT INTO sheet_material_types
      (sheet_material_type_id, name, width_mm, height_mm, is_cuttable, is_active) VALUES
      (1, 'ДСП 2800x2070', 2800, 2070, true,  true),
      (2, 'ДСП 2070x2800', 2070, 2800, true,  true),
      (3, 'Стекло 1000x1000', 1000, 1000, false, true);

    CREATE TABLE films (
      film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      film_name TEXT,
      film_texture BOOLEAN NOT NULL DEFAULT false
    );

    CREATE TABLE milling_types (
      milling_type_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      milling_type_name TEXT
    );
    CREATE TABLE edge_types (
      edge_type_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      edge_type_name TEXT
    );

    CREATE TABLE materials (
      material_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      material_name TEXT,
      sheet_material_type_id BIGINT REFERENCES sheet_material_types(sheet_material_type_id)
    );
    INSERT INTO materials (material_id, material_name, sheet_material_type_id)
      VALUES (1, 'Материал 1', 1), (2, 'Материал 2', NULL), (3, 'Материал 3', 2);

    -- Minimal orders table so the enriched item read's LEFT JOIN orders (order_name) resolves.
    CREATE TABLE orders (
      order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_name TEXT
    );

    CREATE TABLE order_details (
      detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id BIGINT NOT NULL,
      detail_number SMALLINT,
      detail_name VARCHAR(200),
      quantity INTEGER NOT NULL DEFAULT 1,
      width NUMERIC(10,2) NOT NULL,
      height NUMERIC(10,2) NOT NULL,
      area NUMERIC(10,2),
      material_id BIGINT REFERENCES materials(material_id),
      milling_type_id SMALLINT REFERENCES milling_types(milling_type_id),
      edge_type_id SMALLINT REFERENCES edge_types(edge_type_id),
      film_id BIGINT REFERENCES films(film_id),
      priority SMALLINT,
      production_status_id SMALLINT REFERENCES production_statuses(production_status_id),
      joint_order_id BIGINT,
      note TEXT,
      link_cutting_file TEXT,
      link_cutting_image_file TEXT,
      link_cad_file TEXT,
      link_pdf_file TEXT,
      sheet_material_type_id BIGINT REFERENCES sheet_material_types(sheet_material_type_id),
      delete_flag BOOLEAN NOT NULL DEFAULT false
    );
    -- Detail 1 (order 9):  sheet type 1 (2800×2070, cuttable)
    -- Detail 2 (order 9):  sheet type 2 (2070×2800, cuttable) — different from detail 1
    -- Detail 3 (order 10): no_sheet_spec (sheet_material_type_id = NULL)
    -- Detail 4 (order 10): sheet type 1 (cuttable)
    -- Detail 5 (order 11): sheet type 3 (is_cuttable=false) — for explicit guards only
    INSERT INTO order_details
      (detail_id, order_id, quantity, width, height, material_id, production_status_id, sheet_material_type_id) VALUES
      (1, 9,  1, 600, 400, NULL, 1, 1),
      (2, 9,  1, 500, 300, NULL, 1, 2),
      (3, 10, 1, 400, 200, NULL, 1, NULL),
      (4, 10, 1, 600, 400, NULL, 1, 1),
      (5, 11, 1, 600, 400, NULL, 1, 3);

    -- combine-films fixtures: two films (one textured, one plain) and details that
    -- share a sheet material but differ by film, plus one of a different material.
    INSERT INTO films (film_id, film_name, film_texture) VALUES
      (10, 'Текстурная плёнка', true),
      (11, 'Гладкая плёнка', false);
    -- Order 50: details 100 & 101 share sheet type 1 but use films 10 vs 11;
    -- detail 102 is a DIFFERENT material (sheet type 2) so it must never merge.
    INSERT INTO order_details
      (detail_id, order_id, quantity, width, height, material_id, production_status_id, sheet_material_type_id, film_id) VALUES
      (100, 50, 1, 600, 400, NULL, 1, 1, 10),
      (101, 50, 1, 500, 300, NULL, 1, 1, 11),
      (102, 50, 1, 700, 350, NULL, 1, 2, 11);

    -- cut_job with migration 040 column included (sheet_material_type_id).
    CREATE TABLE cut_job (
      cut_job_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(200) NOT NULL,
      status TEXT NOT NULL DEFAULT 'draft',
      source TEXT NOT NULL DEFAULT 'manual',
      selection_criteria JSONB,
      params JSONB,
      request_hash TEXT,
      pdf_prewarm_state TEXT NOT NULL DEFAULT 'pending',
      pdf_prewarm_failure_reason TEXT,
      failure_code TEXT,
      failure_reason TEXT,
      param_profile_id BIGINT,
      sheet_material_type_id BIGINT REFERENCES sheet_material_types(sheet_material_type_id),
      pdf_template_code VARCHAR(100) NOT NULL DEFAULT 'standard',
      combine_films BOOLEAN NOT NULL DEFAULT false,
      split_by_material BOOLEAN NOT NULL DEFAULT true,
      created_by BIGINT,
      version INTEGER NOT NULL DEFAULT 0,
      last_calc_params JSONB,
      last_calc_basis TEXT,
      created_at TIMESTAMP NOT NULL DEFAULT now(),
      updated_at TIMESTAMP NOT NULL DEFAULT now()
    );

    CREATE TABLE cut_group (
      cut_group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cut_job_id BIGINT NOT NULL REFERENCES cut_job(cut_job_id) ON DELETE CASCADE,
      sheet_material_type_id BIGINT,
      film_id BIGINT,
      status TEXT NOT NULL DEFAULT 'pending',
      pdf_template_code VARCHAR(100) NOT NULL DEFAULT 'standard',
      summary JSONB,
      group_key TEXT,
      created_at TIMESTAMP NOT NULL DEFAULT now(),
      updated_at TIMESTAMP NOT NULL DEFAULT now()
    );
    -- Partial unique index: enforces uniqueness only where group_key IS NOT NULL.
    CREATE UNIQUE INDEX uq_cut_group_job_key ON cut_group (cut_job_id, group_key) WHERE group_key IS NOT NULL;

    CREATE TABLE cut_job_item (
      cut_job_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cut_job_id BIGINT NOT NULL REFERENCES cut_job(cut_job_id) ON DELETE CASCADE,
      cut_group_id BIGINT,
      order_detail_id BIGINT NOT NULL,
      order_id BIGINT NOT NULL,
      qty INTEGER NOT NULL,
      is_active BOOLEAN NOT NULL DEFAULT true,
      freecut_item_id TEXT,
      created_at TIMESTAMP NOT NULL DEFAULT now(),
      updated_at TIMESTAMP NOT NULL DEFAULT now()
    );
    CREATE UNIQUE INDEX uq_cut_job_item_active_job_detail
      ON cut_job_item (cut_job_id, order_detail_id)
      WHERE is_active = true;
    CREATE INDEX idx_cut_job_item_order_detail ON cut_job_item (order_detail_id);

    CREATE TABLE cut_group_sheet (
      cut_group_sheet_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cut_group_id BIGINT NOT NULL REFERENCES cut_group(cut_group_id) ON DELETE CASCADE,
      sheet_index INTEGER NOT NULL,
      sheet_material_type_id BIGINT,
      png_cache_key TEXT,
      placements JSONB NOT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT now(),
      updated_at TIMESTAMP NOT NULL DEFAULT now()
    );

    CREATE TABLE outbox_events (
      outbox_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      event_type TEXT NOT NULL,
      aggregate_type TEXT NOT NULL,
      aggregate_id TEXT NOT NULL,
      payload_json JSONB NOT NULL,
      status TEXT NOT NULL DEFAULT 'pending',
      idempotency_key TEXT
    );
    CREATE UNIQUE INDEX uq_outbox_idempotency ON outbox_events (idempotency_key);

    CREATE TABLE audit_log (
      audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      event TEXT NOT NULL, entity_type TEXT, entity_id TEXT,
      user_id BIGINT, username TEXT, role_code TEXT, role TEXT,
      request_id TEXT, source TEXT,
      related_order_id BIGINT, related_client_id BIGINT, related_payment_id BIGINT,
      related_production_event_id BIGINT, related_deadline_id BIGINT, related_user_id BIGINT,
      status_field TEXT, status_id BIGINT, status_name TEXT, status_code TEXT, stage_code TEXT,
      before_json JSONB, after_json JSONB, diff_json JSONB, metadata_json JSONB,
      created_at TIMESTAMP NOT NULL DEFAULT now()
    );

    CREATE TABLE audit_log_related_entity (
      audit_id BIGINT NOT NULL,
      entity_type TEXT NOT NULL,
      entity_id BIGINT NOT NULL,
      UNIQUE (audit_id, entity_type, entity_id)
    );

    CREATE TABLE cut_param_profiles (
      cut_param_profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(200) NOT NULL UNIQUE,
      params JSONB NOT NULL,
      is_default BOOLEAN NOT NULL DEFAULT false,
      is_active BOOLEAN NOT NULL DEFAULT true,
      version INTEGER NOT NULL DEFAULT 0
    );
    CREATE TABLE cut_render_presets (
      cut_render_preset_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(100) NOT NULL UNIQUE,
      target_px INTEGER NOT NULL,
      background TEXT NOT NULL DEFAULT '#ffffff',
      is_active BOOLEAN NOT NULL DEFAULT true,
      version INTEGER NOT NULL DEFAULT 0
    );
    CREATE TABLE cut_settings (
      key TEXT PRIMARY KEY,
      value JSONB NOT NULL,
      version INTEGER NOT NULL DEFAULT 0
    );

    -- Task 4 (migration 045): manual layout store. No FK to users in throwaway schema.
    CREATE TABLE cut_group_manual_layout (
      cut_group_manual_layout_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cut_job_id                 BIGINT NOT NULL REFERENCES cut_job(cut_job_id) ON DELETE CASCADE,
      group_key                  TEXT NOT NULL,
      sheets                     JSONB NOT NULL,
      is_active                  BOOLEAN NOT NULL DEFAULT FALSE,
      is_stale                   BOOLEAN NOT NULL DEFAULT FALSE,
      based_on_job_version       INTEGER NOT NULL,
      version                    INTEGER NOT NULL DEFAULT 1,
      created_by                 BIGINT,
      created_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
      CONSTRAINT uq_cut_group_manual_layout_job_key UNIQUE (cut_job_id, group_key)
    );
    CREATE INDEX idx_cut_group_manual_layout_job ON cut_group_manual_layout (cut_job_id);
  `);
}

// ── DatabaseService wrapper ───────────────────────────────────────────────────

function makeDatabase(pool: Pool): DatabaseService {
  const query = (text: string, params: readonly unknown[] = []) =>
    pool.query(text, [...params]);
  return {
    isConfigured: true,
    query,
    async transaction<T>(handler: (client: TransactionClient) => Promise<T>): Promise<T> {
      const client = await pool.connect();
      try {
        await client.query('BEGIN');
        await client.query(`SET search_path TO ${schemaName}`);
        const tx: TransactionClient = {
          raw: client as never,
          query: (text: string, params: readonly unknown[] = []) =>
            client.query(text, [...params]),
        };
        const result = await handler(tx);
        await client.query('COMMIT');
        return result;
      } catch (error) {
        await client.query('ROLLBACK').catch(() => undefined);
        throw error;
      } finally {
        client.release();
      }
    },
  } as unknown as DatabaseService;
}

// ── FreecutClient stub ────────────────────────────────────────────────────────
//
// Echo optimizer: returns every item placed on the first (and only) stock from
// the request. Mirrors the echo pattern used in pg-cut-repository.integration.ts
// so the calculate path reaches 'ready' in the test environment.

type FreecutRequest = {
  stock: Array<{ id: string; width_mm: number; height_mm: number }>;
  items: Array<{ id: string; width_mm: number; height_mm: number }>;
};

function makeEchoFreecut() {
  return {
    optimize: (req: FreecutRequest): Promise<FreecutOptimizeResponse> =>
      Promise.resolve({
        status: 'ok',
        summary: { used_stock_count: 1, waste_percent: 5 },
        solutions: [
          {
            stock_id: req.stock[0].id,
            index: 0,
            width_mm: req.stock[0].width_mm,
            height_mm: req.stock[0].height_mm,
            trim_mm: { left: 10, right: 10, top: 10, bottom: 10 },
            placements: req.items.map((it, i) => ({
              item_id: it.id,
              instance: 1,
              x_mm: i * 620,
              y_mm: 0,
              width_mm: it.width_mm,
              height_mm: it.height_mm,
              rotated: false,
            })),
          },
        ],
      }),
  };
}

// ── Helpers ───────────────────────────────────────────────────────────────────

async function makeJobWithDetails(
  repo: PgCutRepository,
  detailIds: number[],
  name: string,
  requestId: string,
) {
  return repo.createJob({
    currentUser: currentUser(),
    dto: { name, detailIds },
    requestId,
  });
}

// ── Integration suite ─────────────────────────────────────────────────────────

describeIntegration('PgCutRepository — per-job sheet override (integration)', () => {
  let pool: Pool;
  let database: DatabaseService;

  beforeAll(async () => {
    pool = new Pool({ connectionString: databaseUrl, max: 4 });
    await pool.query(`CREATE SCHEMA ${schemaName}`);
    await pool.query(`SET search_path TO ${schemaName}`);
    await createSchema(pool);
    pool.on('connect', (client) => void client.query(`SET search_path TO ${schemaName}`));
    database = makeDatabase(pool);
  });

  afterAll(async () => {
    if (pool) {
      await pool.query(`DROP SCHEMA IF EXISTS ${schemaName} CASCADE`);
      await pool.end();
    }
  });

  beforeEach(async () => {
    await pool.query(
      'TRUNCATE cut_group_manual_layout, cut_group_sheet, cut_group, cut_job_item, cut_job, outbox_events, audit_log, audit_log_related_entity RESTART IDENTITY CASCADE',
    );
  });

  // ── Scenario 1: setSheetMaterial to a cuttable sheet ────────────────────

  it('Scenario 1: setSheetMaterial to cuttable sheet sets DB column, bumps version, writes audit + bridge + outbox; replay is idempotent', async () => {
    const repo = new PgCutRepository(database, makeEchoFreecut());
    const job = await makeJobWithDetails(repo, [1], 'Тест SMT set', 's1-create');

    const beforeVersion = job.version;

    // Set the sheet override to SMT 1 (cuttable, active).
    const updated = await repo.setSheetMaterial({
      currentUser: currentUser(),
      cutJobId: job.cutJobId,
      sheetMaterialTypeId: 1,
      version: beforeVersion,
      requestId: 's1-set',
    });

    // Return value carries the new sheet id.
    expect(updated.sheetMaterialTypeId).toBe(1);
    // Version must be bumped exactly once.
    expect(updated.version).toBe(beforeVersion + 1);

    // DB column is persisted.
    const dbRow = await pool.query(
      `SELECT sheet_material_type_id, version FROM cut_job WHERE cut_job_id = $1`,
      [job.cutJobId],
    );
    expect(Number(dbRow.rows[0].sheet_material_type_id)).toBe(1);
    expect(Number(dbRow.rows[0].version)).toBe(beforeVersion + 1);

    // Exactly one audit row for the event.
    const auditRows = await pool.query(
      `SELECT audit_id, before_json, after_json FROM audit_log WHERE event = $1 AND entity_id = $2`,
      [CUT_AUDIT_EVENTS.sheetMaterialChanged, String(job.cutJobId)],
    );
    expect(auditRows.rows).toHaveLength(1);
    expect(auditRows.rows[0].before_json).toMatchObject({ sheetMaterialTypeId: null });
    expect(auditRows.rows[0].after_json).toMatchObject({ sheetMaterialTypeId: 1 });

    // Related entity bridge must include at least one sheet_material_type row.
    const bridgeRows = await pool.query(
      `SELECT entity_type, entity_id FROM audit_log_related_entity WHERE audit_id = $1`,
      [auditRows.rows[0].audit_id],
    );
    const sheetBridge = bridgeRows.rows.filter((r) => r.entity_type === 'sheet_material_type');
    expect(sheetBridge.length).toBeGreaterThan(0);
    // The new sheet type id must appear in the bridge.
    expect(sheetBridge.some((r) => Number(r.entity_id) === 1)).toBe(true);

    // Exactly one outbox row, keyed by requestId (sheetMaterialChangedOutboxKey).
    const expectedKey = `${CUT_AUDIT_EVENTS.sheetMaterialChanged}:${job.cutJobId}:s1-set`;
    const outboxRows = await pool.query(
      `SELECT idempotency_key FROM outbox_events WHERE event_type = $1`,
      [CUT_AUDIT_EVENTS.sheetMaterialChanged],
    );
    expect(outboxRows.rows).toHaveLength(1);
    expect(String(outboxRows.rows[0].idempotency_key)).toBe(expectedKey);

    // ── End-to-end command-path idempotency ──────────────────────────────────
    // The outbox idempotency_key is derived from requestId, so a transport-level
    // duplicate of the SAME request (same requestId) must NOT emit a second outbox
    // row even though it flows through the real command path. Drive this through
    // repo.setSheetMaterial (NOT a hand-inserted row).
    //
    // First-line dedupe: a literal retry of the SAME (requestId, version) hits the
    // optimistic version guard — the first call already bumped 0 -> 1, so a retry
    // at the original version is rejected 409 before any write.
    await expect(
      repo.setSheetMaterial({
        currentUser: currentUser(),
        cutJobId: job.cutJobId,
        sheetMaterialTypeId: 1,
        version: beforeVersion, // stale: already consumed by the first call
        requestId: 's1-set',
      }),
    ).rejects.toMatchObject({ statusCode: 409, code: 'CUT_STALE_VERSION' });

    // Second-line dedupe (the outbox ON CONFLICT path): a duplicate that DOES pass
    // the version guard and IS a real change (1 -> 2) but reuses the SAME requestId
    // must still collide on the requestId-derived outbox key -> ON CONFLICT DO
    // NOTHING. This exercises the command's outbox insert end-to-end: no second row
    // with that key is created.
    const replay = await repo.setSheetMaterial({
      currentUser: currentUser(),
      cutJobId: job.cutJobId,
      sheetMaterialTypeId: 2, // genuine change so it is not the no-op short-circuit
      version: updated.version, // current version after the first bump
      requestId: 's1-set', // SAME requestId -> SAME outbox key
    });
    expect(replay.sheetMaterialTypeId).toBe(2);

    // Outbox: still exactly ONE row with the requestId-derived key (the second
    // command call hit ON CONFLICT DO NOTHING — proven through the command path).
    const outboxAfterReplay = await pool.query(
      `SELECT COUNT(*)::int AS n FROM outbox_events WHERE idempotency_key = $1`,
      [expectedKey],
    );
    expect(outboxAfterReplay.rows[0].n).toBe(1);
    // And no other sheet-material outbox row leaked under a different key.
    const outboxTotal = await pool.query(
      `SELECT COUNT(*)::int AS n FROM outbox_events WHERE event_type = $1`,
      [CUT_AUDIT_EVENTS.sheetMaterialChanged],
    );
    expect(outboxTotal.rows[0].n).toBe(1);
  });

  // ── Scenario 2: setSheetMaterial to a non-cuttable sheet ────────────────

  it('Scenario 2: setSheetMaterial to non-cuttable (is_cuttable=false) sheet → 422 CUT_SHEET_MATERIAL_NOT_CUTTABLE, no mutation', async () => {
    const repo = new PgCutRepository(database, makeEchoFreecut());
    const job = await makeJobWithDetails(repo, [1], 'Тест SMT not-cuttable', 's2-create');

    const versionBefore = job.version;

    await expect(
      repo.setSheetMaterial({
        currentUser: currentUser(),
        cutJobId: job.cutJobId,
        sheetMaterialTypeId: 3, // is_cuttable=false
        version: versionBefore,
        requestId: 's2-set',
      }),
    ).rejects.toMatchObject({ statusCode: 422, code: 'CUT_SHEET_MATERIAL_NOT_CUTTABLE' });

    // No DB mutation: sheet column stays NULL, version unchanged.
    const dbRow = await pool.query(
      `SELECT sheet_material_type_id, version FROM cut_job WHERE cut_job_id = $1`,
      [job.cutJobId],
    );
    expect(dbRow.rows[0].sheet_material_type_id).toBeNull();
    expect(Number(dbRow.rows[0].version)).toBe(versionBefore);

    // No audit or outbox rows written.
    const auditCount = await pool.query(
      `SELECT COUNT(*)::int AS n FROM audit_log WHERE event = $1`,
      [CUT_AUDIT_EVENTS.sheetMaterialChanged],
    );
    expect(auditCount.rows[0].n).toBe(0);
    const outboxCount = await pool.query(
      `SELECT COUNT(*)::int AS n FROM outbox_events WHERE event_type = $1`,
      [CUT_AUDIT_EVENTS.sheetMaterialChanged],
    );
    expect(outboxCount.rows[0].n).toBe(0);
  });

  // ── Scenario 3: calculate with override on mixed-material + no_sheet_spec ─

  it('Scenario 3: calculate with override — details spanning two materials + one no_sheet_spec → all placed on chosen sheet (split=true, Variant B), job = ready, requiresRecalc=false', async () => {
    // Details used:
    //   detail 1 (SMT 1), detail 2 (SMT 2), detail 3 (no_sheet_spec = NULL)
    // Variant B: applySheetOverride rewrites ALL items to the override sheet
    // regardless of split_by_material. split_by_material stays at the DEFAULT (true)
    // to prove the new behavior — no need to flip it off.
    const repo = new PgCutRepository(database, makeEchoFreecut());

    // detail 3 has no_sheet_spec → createJob would reject it via the eligibility
    // check (CUT_DETAIL_NOT_ELIGIBLE). We need to bypass the eligibility guard by
    // either: (a) setting a production_status_id that the eligibility resolver
    // does NOT consider "ready" (so it would be excluded), or (b) inserting into
    // cut_job_item directly. The cleaner way is option (b): create the job with
    // details 1 and 2 (both eligible), then manually insert detail 3 (no_sheet_spec)
    // into cut_job_item directly, mirroring the approach used in pg-cut-repository
    // integration tests (see "placements report ONLY eligible details").
    const job = await makeJobWithDetails(repo, [1, 2], 'Тест SMT override mixed', 's3-create');

    // Manually insert detail 3 (no_sheet_spec) to simulate a job that may have
    // been built when no_sheet_spec was allowed, or that was carried over.
    // The override makes it cuttable at calculate time.
    await pool.query(
      `INSERT INTO cut_job_item (cut_job_id, order_detail_id, order_id, qty, is_active)
       VALUES ($1, 3, 10, 1, true)`,
      [job.cutJobId],
    );

    // Set the override to SMT 1 (2800×2070, cuttable, active).
    const afterSet = await repo.setSheetMaterial({
      currentUser: currentUser(),
      cutJobId: job.cutJobId,
      sheetMaterialTypeId: 1,
      version: job.version,
      requestId: 's3-set',
    });
    expect(afterSet.sheetMaterialTypeId).toBe(1);
    // split_by_material is still true (default) — Variant B: override forces all regardless.
    expect(afterSet.splitByMaterial).toBe(true);

    // Calculate: with Variant B override, all items (detail 1, 2, 3) must be cut on
    // SMT 1 → one group, even though split_by_material=true.
    const calculated = await repo.calculate({
      currentUser: currentUser(),
      cutJobId: job.cutJobId,
      version: afterSet.version,
      requestId: 's3-calc',
    });

    expect(calculated.status).toBe('ready');
    // With the override applied to ALL items, freecut sees ONE group with override sheet.
    expect(calculated.groups).toHaveLength(1);
    expect(calculated.groups[0].sheetMaterialTypeId).toBe(1);

    // Every item (including the previously no_sheet_spec detail 3) has a group.
    const assignRows = await pool.query(
      `SELECT order_detail_id, cut_group_id FROM cut_job_item WHERE cut_job_id = $1 AND is_active = true ORDER BY order_detail_id`,
      [job.cutJobId],
    );
    expect(assignRows.rows).toHaveLength(3);
    for (const row of assignRows.rows) {
      expect(row.cut_group_id).not.toBeNull();
    }
    // All items assigned to the same group.
    const groupIds = new Set(assignRows.rows.map((r) => Number(r.cut_group_id)));
    expect(groupIds.size).toBe(1);

    // Variant B consistency check: basisOf is identical between calculate and
    // loadCurrentCalcBasisInputs (both use onlyNoSheetSpec=false), so the job
    // must report requiresRecalc=false immediately after a successful calculate.
    const afterCalcJob = await repo.getJob({ currentUser: currentUser(), cutJobId: job.cutJobId });
    expect(afterCalcJob.requiresRecalc).toBe(false);
  });

  // ── Scenario 4: calculate after chosen sheet is deactivated ─────────────

  it('Scenario 4: calculate after chosen sheet deactivated → 422 CUT_SHEET_MATERIAL_NOT_CUTTABLE, job NOT marked failed', async () => {
    const repo = new PgCutRepository(database, makeEchoFreecut());
    const job = await makeJobWithDetails(repo, [1], 'Тест SMT deactivated', 's4-create');

    // Choose SMT 2 as the override.
    const afterSet = await repo.setSheetMaterial({
      currentUser: currentUser(),
      cutJobId: job.cutJobId,
      sheetMaterialTypeId: 2,
      version: job.version,
      requestId: 's4-set',
    });
    const versionBeforeCalc = afterSet.version;

    // Deactivate SMT 2 (simulate operator retiring a sheet type after selection).
    await pool.query(
      `UPDATE sheet_material_types SET is_active = false WHERE sheet_material_type_id = 2`,
    );

    // calculate must reject with 422 CUT_SHEET_MATERIAL_NOT_CUTTABLE.
    await expect(
      repo.calculate({
        currentUser: currentUser(),
        cutJobId: job.cutJobId,
        version: versionBeforeCalc,
        requestId: 's4-calc',
      }),
    ).rejects.toMatchObject({ statusCode: 422, code: 'CUT_SHEET_MATERIAL_NOT_CUTTABLE' });

    // Restore SMT 2 for subsequent tests.
    await pool.query(
      `UPDATE sheet_material_types SET is_active = true WHERE sheet_material_type_id = 2`,
    );

    // Job status must remain 'draft' (NOT 'failed'): this is a precondition 422, not
    // a freecut failure. PASSTHROUGH_CODES contains CUT_SHEET_MATERIAL_NOT_CUTTABLE.
    const dbRow = await pool.query(
      `SELECT status, failure_code, version FROM cut_job WHERE cut_job_id = $1`,
      [job.cutJobId],
    );
    expect(dbRow.rows[0].status).toBe('draft');
    expect(dbRow.rows[0].failure_code).toBeNull();
    // Version must be unchanged (the calculate transaction rolled back).
    expect(Number(dbRow.rows[0].version)).toBe(versionBeforeCalc);
  });

  // ── Scenario 5: Override = NULL → legacy per-detail sheet behavior ────────

  it('Scenario 5: override = NULL → legacy behavior; no_sheet_spec detail raises CutNoSheetSpecError', async () => {
    const repo = new PgCutRepository(database, makeEchoFreecut());

    // Create a job with only a no_sheet_spec detail (inserted directly), plus one
    // eligible detail. Then set override = null (default) and calculate.
    const job = await makeJobWithDetails(repo, [1], 'Тест SMT null override', 's5-create');

    // Confirm override is null from the start (default behavior).
    expect(job.sheetMaterialTypeId).toBeNull();

    // Manually insert detail 3 (no_sheet_spec): sheet_material_type_id = NULL.
    await pool.query(
      `INSERT INTO cut_job_item (cut_job_id, order_detail_id, order_id, qty, is_active)
       VALUES ($1, 3, 10, 1, true)`,
      [job.cutJobId],
    );

    // With no override, calculate must encounter detail 3 (group with no sheet) and
    // throw CutNoSheetSpecError (code 'CUT_NO_SHEET_SPEC').
    // Note: the job WILL be marked failed (CUT_NO_SHEET_SPEC is not in PASSTHROUGH_CODES).
    await expect(
      repo.calculate({
        currentUser: currentUser(),
        cutJobId: job.cutJobId,
        version: job.version,
        requestId: 's5-calc',
      }),
    ).rejects.toMatchObject({ statusCode: 422, code: 'CUT_NO_SHEET_SPEC' });

    // Confirm the job is marked failed (CUT_NO_SHEET_SPEC marks it, unlike
    // CUT_SHEET_MATERIAL_NOT_CUTTABLE which does not).
    const dbRow = await pool.query(
      `SELECT status, failure_code FROM cut_job WHERE cut_job_id = $1`,
      [job.cutJobId],
    );
    expect(dbRow.rows[0].status).toBe('failed');
    expect(dbRow.rows[0].failure_code).toBe('CUT_NO_SHEET_SPEC');
  });

  // ── Combine-films scenarios (migration 042) ─────────────────────────────────

  // Capturing freecut stub: records each optimize request so a test can assert
  // the per-group item set and its per-item grain fields.
  function makeCapturingFreecut() {
    const requests: Array<{ stockId: string; items: Array<{ id: string; rotation?: string; pattern_direction?: string }> }> = [];
    const echo = makeEchoFreecut();
    return {
      requests,
      optimize: (req: FreecutRequest & { items: Array<Record<string, unknown>> }): Promise<FreecutOptimizeResponse> => {
        requests.push({
          stockId: req.stock[0].id,
          items: req.items.map((it) => ({ id: String(it.id), rotation: it.rotation as string | undefined, pattern_direction: it.pattern_direction as string | undefined })),
        });
        return echo.optimize(req);
      },
    };
  }

  it('Combine 1: setCombineFilms false→true persists + audits + outbox; stale replay 409, same-requestId duplicate hits outbox ON CONFLICT; unchanged value is a no-op', async () => {
    const repo = new PgCutRepository(database, makeEchoFreecut());
    const job = await makeJobWithDetails(repo, [100, 101], 'Тест combine set', 'c1-create');
    expect(job.combineFilms).toBe(false);
    const beforeVersion = job.version;

    const updated = await repo.setCombineFilms({ currentUser: currentUser(), cutJobId: job.cutJobId, combineFilms: true, version: beforeVersion, requestId: 'c1-set' });
    expect(updated.combineFilms).toBe(true);
    expect(updated.version).toBe(beforeVersion + 1);

    const dbRow = await pool.query(`SELECT combine_films FROM cut_job WHERE cut_job_id = $1`, [job.cutJobId]);
    expect(dbRow.rows[0].combine_films).toBe(true);

    const expectedKey = `${CUT_AUDIT_EVENTS.combineFilmsChanged}:${job.cutJobId}:c1-set`;
    const audit = await pool.query(`SELECT count(*)::int AS n FROM audit_log WHERE event = $1`, [CUT_AUDIT_EVENTS.combineFilmsChanged]);
    expect(audit.rows[0].n).toBe(1);
    const outbox = await pool.query(`SELECT idempotency_key FROM outbox_events WHERE event_type = $1`, [CUT_AUDIT_EVENTS.combineFilmsChanged]);
    expect(outbox.rows).toHaveLength(1);
    expect(String(outbox.rows[0].idempotency_key)).toBe(expectedKey);

    // First-line dedupe: a literal retry of the SAME (requestId, version) hits the
    // optimistic version guard — the first call already bumped, so 409 before any write.
    await expect(
      repo.setCombineFilms({ currentUser: currentUser(), cutJobId: job.cutJobId, combineFilms: true, version: beforeVersion, requestId: 'c1-set' }),
    ).rejects.toMatchObject({ statusCode: 409, code: 'CUT_STALE_VERSION' });

    // Second-line dedupe (outbox ON CONFLICT): a duplicate that DOES pass the version
    // guard and IS a real change (true→false) but reuses the SAME requestId collides
    // on the requestId-derived key -> ON CONFLICT DO NOTHING. No second row for that key.
    const replay = await repo.setCombineFilms({ currentUser: currentUser(), cutJobId: job.cutJobId, combineFilms: false, version: updated.version, requestId: 'c1-set' });
    expect(replay.combineFilms).toBe(false);
    const outboxAfterReplay = await pool.query(`SELECT count(*)::int AS n FROM outbox_events WHERE idempotency_key = $1`, [expectedKey]);
    expect(outboxAfterReplay.rows[0].n).toBe(1);

    // No-op short-circuit: setting the current value (false→false) bumps nothing.
    const noop = await repo.setCombineFilms({ currentUser: currentUser(), cutJobId: job.cutJobId, combineFilms: false, version: replay.version, requestId: 'c1-noop' });
    expect(noop.version).toBe(replay.version);
    const auditAfterNoop = await pool.query(`SELECT count(*)::int AS n FROM audit_log WHERE event = $1`, [CUT_AUDIT_EVENTS.combineFilmsChanged]);
    expect(auditAfterNoop.rows[0].n).toBe(2); // the false→true and the true→false changes only
  });

  it('Combine 5: toggling combine_films re-cuts (request_hash folds the flag) even when the resolved groups are physically identical', async () => {
    // Details 1 & 4 share sheet type 1 and have NO film (film_id NULL), so OFF and
    // ON produce the SAME single group with film_id NULL — identical item set. Only
    // the folded combineFilms flag distinguishes the two request hashes.
    const repo = new PgCutRepository(database, makeEchoFreecut());
    const job = await makeJobWithDetails(repo, [1, 4], 'Тест combine rehash', 'c5-create');

    const readyOff = await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: job.version, requestId: 'c5-off' });
    expect(readyOff.status).toBe('ready');
    const h1 = (await pool.query(`SELECT request_hash FROM cut_job WHERE cut_job_id = $1`, [job.cutJobId])).rows[0].request_hash as string;
    expect(h1).toBeTruthy();

    const set = await repo.setCombineFilms({ currentUser: currentUser(), cutJobId: job.cutJobId, combineFilms: true, version: readyOff.version, requestId: 'c5-set' });
    const readyOn = await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: set.version, requestId: 'c5-on' });
    expect(readyOn.status).toBe('ready');
    const h2 = (await pool.query(`SELECT request_hash FROM cut_job WHERE cut_job_id = $1`, [job.cutJobId])).rows[0].request_hash as string;

    // The fold guarantees the toggle changes the hash → re-cut is NOT suppressed.
    expect(h2).not.toBe(h1);
    // Both calculate runs emitted their own calculated outbox row (distinct requestIds).
    const calcOutbox = await pool.query(`SELECT count(*)::int AS n FROM outbox_events WHERE event_type = $1`, [CUT_AUDIT_EVENTS.calculated]);
    expect(calcOutbox.rows[0].n).toBe(2);
  });

  it('Combine 2: calculate OFF (default) groups a 2-film same-material job by film → 2 groups', async () => {
    const repo = new PgCutRepository(database, makeEchoFreecut());
    const job = await makeJobWithDetails(repo, [100, 101], 'Тест combine off', 'c2-create');
    const ready = await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: job.version, requestId: 'c2-calc' });
    expect(ready.status).toBe('ready');

    const groups = await pool.query(`SELECT film_id FROM cut_group WHERE cut_job_id = $1 ORDER BY film_id`, [job.cutJobId]);
    expect(groups.rows).toHaveLength(2);
    expect(groups.rows.map((r) => Number(r.film_id)).sort()).toEqual([10, 11]);
  });

  it('Combine 3: calculate ON merges a 2-film same-material job into ONE group (film_id NULL) with per-detail grain', async () => {
    const freecut = makeCapturingFreecut();
    const repo = new PgCutRepository(database, freecut);
    const job = await makeJobWithDetails(repo, [100, 101], 'Тест combine on', 'c3-create');
    const set = await repo.setCombineFilms({ currentUser: currentUser(), cutJobId: job.cutJobId, combineFilms: true, version: job.version, requestId: 'c3-set' });
    const ready = await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: set.version, requestId: 'c3-calc' });
    expect(ready.status).toBe('ready');

    // ONE merged group, film_id NULL (films mixed).
    const groups = await pool.query(`SELECT film_id, sheet_material_type_id FROM cut_group WHERE cut_job_id = $1`, [job.cutJobId]);
    expect(groups.rows).toHaveLength(1);
    expect(groups.rows[0].film_id).toBeNull();
    expect(Number(groups.rows[0].sheet_material_type_id)).toBe(1);

    // Exactly one freecut call (one group) carrying BOTH details; grain stays
    // per-detail — the textured film forbids rotation, the plain one allows 90°.
    expect(freecut.requests).toHaveLength(1);
    const items = freecut.requests[0].items;
    expect(items).toHaveLength(2);
    const rotations = items.map((i) => i.rotation).sort();
    expect(rotations).toEqual(['allow_90', 'forbid']);
  });

  it('Combine 4: calculate ON NEVER merges different materials → one group per material', async () => {
    const repo = new PgCutRepository(database, makeEchoFreecut());
    const job = await makeJobWithDetails(repo, [100, 101, 102], 'Тест combine cross-material', 'c4-create');
    const set = await repo.setCombineFilms({ currentUser: currentUser(), cutJobId: job.cutJobId, combineFilms: true, version: job.version, requestId: 'c4-set' });
    const ready = await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: set.version, requestId: 'c4-calc' });
    expect(ready.status).toBe('ready');

    const groups = await pool.query(`SELECT sheet_material_type_id, film_id FROM cut_group WHERE cut_job_id = $1 ORDER BY sheet_material_type_id`, [job.cutJobId]);
    // Material 1 (films 10+11 merged → film_id NULL) and material 2 (single detail).
    expect(groups.rows).toHaveLength(2);
    expect(groups.rows.map((r) => Number(r.sheet_material_type_id))).toEqual([1, 2]);
    expect(groups.rows[0].film_id).toBeNull();
  });

  // ── Split-by-material scenarios (migration 043) ─────────────────────────────

  it('Split 1: split_by_material=true (default) never merges materials — details 100/101/102 (materials 1,1,2) split into per-(material,film) groups', async () => {
    const repo = new PgCutRepository(database, makeEchoFreecut());
    const job = await makeJobWithDetails(repo, [100, 101, 102], 'Тест split default', 's1m-create');
    expect(job.splitByMaterial).toBe(true);
    const ready = await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: job.version, requestId: 's1m-calc' });
    expect(ready.status).toBe('ready');

    const groups = await pool.query(`SELECT sheet_material_type_id FROM cut_group WHERE cut_job_id = $1 ORDER BY sheet_material_type_id, film_id`, [job.cutJobId]);
    // (1,10),(1,11),(2,11) → 3 groups; every group is a SINGLE material; both 1 and 2 present.
    expect(groups.rows).toHaveLength(3);
    expect(groups.rows.every((r) => r.sheet_material_type_id !== null)).toBe(true);
    expect([...new Set(groups.rows.map((r) => Number(r.sheet_material_type_id)))].sort()).toEqual([1, 2]);
    // header «Материалов» reflects the effective grouping: materials {1, 2} → 2.
    expect(ready.totals.materialsCount).toBe(2);
  });

  it('Split 2: split_by_material=false puts ALL details (materials 1,1,2) into ONE group together', async () => {
    const repo = new PgCutRepository(database, makeEchoFreecut());
    const job = await makeJobWithDetails(repo, [100, 101, 102], 'Тест split off', 's2m-create');
    const set = await repo.setSplitByMaterial({ currentUser: currentUser(), cutJobId: job.cutJobId, splitByMaterial: false, version: job.version, requestId: 's2m-set' });
    expect(set.splitByMaterial).toBe(false);
    const ready = await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: set.version, requestId: 's2m-calc' });
    expect(ready.status).toBe('ready');

    const groups = await pool.query(`SELECT cut_group_id, film_id FROM cut_group WHERE cut_job_id = $1`, [job.cutJobId]);
    expect(groups.rows).toHaveLength(1);
    expect(groups.rows[0].film_id).toBeNull();
    const items = await pool.query(`SELECT count(*)::int AS n FROM cut_job_item WHERE cut_job_id = $1 AND cut_group_id = $2`, [job.cutJobId, groups.rows[0].cut_group_id]);
    expect(items.rows[0].n).toBe(3); // all three details in the one group
    // header «Материалов» reflects ONE all-in-one group when not split → 1.
    expect(ready.totals.materialsCount).toBe(1);
  });

  it('Split 3 (Variant B): split_by_material=true + sheet override forces ALL details onto the override sheet — materialed detail no longer keeps its own sheet', async () => {
    const repo = new PgCutRepository(database, makeEchoFreecut());
    // Detail 100 = SMT 1, film_id=10; detail 3 = no_sheet_spec (SMT null, film null).
    // OLD behavior: override only filled no-sheet detail 3 onto SMT 2; detail 100 (own SMT 1)
    //   stayed on SMT 1 → 2 groups: {SMT 1, film 10} and {SMT 2, film null}.
    // Variant B: override forces ALL details onto SMT 2 regardless of split_by_material.
    //   Both details are rewritten to SMT 2. With split_by_material=true and different
    //   films (10 vs null), groupByCuttableKey still makes 2 groups — but now BOTH are
    //   on SMT 2, not SMT 1+2 as before.
    const job = await makeJobWithDetails(repo, [100], 'Тест split override fill', 's3m-create');
    await pool.query(`INSERT INTO cut_job_item (cut_job_id, order_detail_id, order_id, qty, is_active) VALUES ($1, 3, 10, 1, true)`, [job.cutJobId]);
    // Set the override sheet to SMT 2 (cuttable). split stays true (default).
    const set = await repo.setSheetMaterial({ currentUser: currentUser(), cutJobId: job.cutJobId, sheetMaterialTypeId: 2, version: job.version, requestId: 's3m-sheet' });
    const ready = await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: set.version, requestId: 's3m-calc' });
    expect(ready.status).toBe('ready');

    const groups = await pool.query(
      `SELECT sheet_material_type_id FROM cut_group WHERE cut_job_id = $1 ORDER BY sheet_material_type_id`,
      [job.cutJobId],
    );
    // Variant B: detail 100 is forced from SMT 1 to SMT 2 by the override.
    // Both groups land on SMT 2 (not SMT 1+2 as in old behavior).
    expect(groups.rows).toHaveLength(2); // 2 groups because film_id differs (10 vs null)
    expect(groups.rows.map((r) => Number(r.sheet_material_type_id))).toEqual([2, 2]); // BOTH on override sheet!

    // Variant B consistency: basisOf is identical in calculate and loadCurrentCalcBasisInputs
    // (both use onlyNoSheetSpec=false), so requiresRecalc must be false right after calculate.
    const afterCalcJob = await repo.getJob({ currentUser: currentUser(), cutJobId: job.cutJobId });
    expect(afterCalcJob.requiresRecalc).toBe(false);
  });

  it('Split 4: setSplitByMaterial true→false persists + audits + outbox; stale 409, same-requestId duplicate hits ON CONFLICT; unchanged is a no-op', async () => {
    const repo = new PgCutRepository(database, makeEchoFreecut());
    const job = await makeJobWithDetails(repo, [100], 'Тест split set', 's4m-create');
    expect(job.splitByMaterial).toBe(true);
    const beforeVersion = job.version;

    const updated = await repo.setSplitByMaterial({ currentUser: currentUser(), cutJobId: job.cutJobId, splitByMaterial: false, version: beforeVersion, requestId: 's4m-set' });
    expect(updated.splitByMaterial).toBe(false);
    expect(updated.version).toBe(beforeVersion + 1);

    const expectedKey = `${CUT_AUDIT_EVENTS.splitByMaterialChanged}:${job.cutJobId}:s4m-set`;
    const audit = await pool.query(`SELECT count(*)::int AS n FROM audit_log WHERE event = $1`, [CUT_AUDIT_EVENTS.splitByMaterialChanged]);
    expect(audit.rows[0].n).toBe(1);
    const outbox = await pool.query(`SELECT idempotency_key FROM outbox_events WHERE event_type = $1`, [CUT_AUDIT_EVENTS.splitByMaterialChanged]);
    expect(outbox.rows).toHaveLength(1);
    expect(String(outbox.rows[0].idempotency_key)).toBe(expectedKey);

    // stale replay → 409
    await expect(
      repo.setSplitByMaterial({ currentUser: currentUser(), cutJobId: job.cutJobId, splitByMaterial: false, version: beforeVersion, requestId: 's4m-set' }),
    ).rejects.toMatchObject({ statusCode: 409, code: 'CUT_STALE_VERSION' });

    // genuine change reusing the same requestId → outbox ON CONFLICT, no second row
    const replay = await repo.setSplitByMaterial({ currentUser: currentUser(), cutJobId: job.cutJobId, splitByMaterial: true, version: updated.version, requestId: 's4m-set' });
    expect(replay.splitByMaterial).toBe(true);
    const outboxAfter = await pool.query(`SELECT count(*)::int AS n FROM outbox_events WHERE idempotency_key = $1`, [expectedKey]);
    expect(outboxAfter.rows[0].n).toBe(1);

    // no-op: setting the current value bumps nothing
    const noop = await repo.setSplitByMaterial({ currentUser: currentUser(), cutJobId: job.cutJobId, splitByMaterial: true, version: replay.version, requestId: 's4m-noop' });
    expect(noop.version).toBe(replay.version);
  });

  it('Split 5: split_by_material=false with a no_sheet_spec FIRST item + a materialed item → ONE group on the materialed sheet (no CUT_NO_SHEET_SPEC), all placed', async () => {
    const repo = new PgCutRepository(database, makeEchoFreecut());
    // Create an eligible job, then replace its items so the no_sheet_spec detail (3)
    // is the FIRST active item (lowest cut_job_item_id, which loadCalcItems orders
    // by) and the materialed detail (100, material 1) is second. No override.
    const job = await makeJobWithDetails(repo, [100], 'Тест split off no-spec first', 's5m-create');
    await pool.query(`DELETE FROM cut_job_item WHERE cut_job_id = $1`, [job.cutJobId]);
    await pool.query(`INSERT INTO cut_job_item (cut_job_id, order_detail_id, order_id, qty, is_active) VALUES ($1, 3, 10, 1, true)`, [job.cutJobId]);
    await pool.query(`INSERT INTO cut_job_item (cut_job_id, order_detail_id, order_id, qty, is_active) VALUES ($1, 100, 50, 1, true)`, [job.cutJobId]);
    const set = await repo.setSplitByMaterial({ currentUser: currentUser(), cutJobId: job.cutJobId, splitByMaterial: false, version: job.version, requestId: 's5m-set' });

    const ready = await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: set.version, requestId: 's5m-calc' });
    expect(ready.status).toBe('ready');

    const groups = await pool.query(`SELECT cut_group_id, sheet_material_type_id FROM cut_group WHERE cut_job_id = $1`, [job.cutJobId]);
    expect(groups.rows).toHaveLength(1);
    // The all-group adopted detail 100's material (1) rather than failing on the
    // no_sheet_spec first item.
    expect(Number(groups.rows[0].sheet_material_type_id)).toBe(1);
    const items = await pool.query(`SELECT count(*)::int AS n FROM cut_job_item WHERE cut_job_id = $1 AND cut_group_id = $2`, [job.cutJobId, groups.rows[0].cut_group_id]);
    expect(items.rows[0].n).toBe(2);
  });
});
