import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import type { DatabaseService } from '../../../database/database.service';
import type { TransactionClient } from '../../../database/database.types';
import type { CurrentUser } from '../../../permissions/current-user';
import type { FreecutOptimizeResponse } from '../application/cut-freecut-mapping';
import { ApiError } from '../../../common/errors/api-error';
import { PgCutRepository } from './pg-cut-repository';

// Full-stack repository integration: createJob reserve -> 409 duplicate, addItems
// stale-version 409, calculate happy path (stubbed FreecutClient) persisting
// cut_group/cut_group_sheet + audit row + N related-entity bridge rows + the
// idempotent outbox row, and the freecut-failure path persisting status=failed +
// cut_job.calculate_failed. Gated on CUT_INTEGRATION_DATABASE_URL (falls back to
// TEST_DATABASE_URL); skips cleanly without a database. Throwaway schema only.
const databaseUrl = process.env.CUT_INTEGRATION_DATABASE_URL ?? process.env.TEST_DATABASE_URL;
const describeIntegration = databaseUrl ? describe : describe.skip;

const schemaName = `cut_repo_${randomUUID().replaceAll('-', '_')}`;

function currentUser(): CurrentUser {
  return { id: '1', username: 'cutter', role: 'operator', permissions: ['cut.view', 'cut.manage'] } as unknown as CurrentUser;
}

const happyResponse: FreecutOptimizeResponse = {
  status: 'ok',
  summary: { used_stock_count: 1, waste_percent: 10 },
  solutions: [
    {
      stock_id: 'smt-1',
      index: 0,
      width_mm: 2800,
      height_mm: 2070,
      trim_mm: { left: 10, right: 10, top: 10, bottom: 10 },
      placements: [
        { item_id: 'det-1', instance: 1, x_mm: 0, y_mm: 0, width_mm: 600, height_mm: 400, rotated: false },
        { item_id: 'det-2', instance: 1, x_mm: 620, y_mm: 0, width_mm: 600, height_mm: 400, rotated: false },
      ],
    },
  ],
};

async function createSchema(pool: Pool): Promise<void> {
  await pool.query(`
    CREATE FUNCTION set_session_user(p_user TEXT) RETURNS void AS $$ BEGIN PERFORM 1; END; $$ LANGUAGE plpgsql;

    CREATE TABLE production_statuses (
      production_status_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      production_status_code TEXT NOT NULL UNIQUE
    );
    INSERT INTO production_statuses (production_status_id, production_status_code)
      VALUES (1, 'new'), (2, 'drawn'), (3, 'film_purchase'), (4, 'cut');

    CREATE TABLE sheet_material_types (
      sheet_material_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      width_mm NUMERIC(10,2) NOT NULL,
      height_mm NUMERIC(10,2) NOT NULL
    );
    INSERT INTO sheet_material_types (sheet_material_type_id, width_mm, height_mm) VALUES (1, 2800, 2070), (2, 2070, 2800);

    CREATE TABLE films (
      film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      film_texture BOOLEAN NOT NULL DEFAULT false
    );

    CREATE TABLE materials (
      material_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      sheet_material_type_id BIGINT REFERENCES sheet_material_types(sheet_material_type_id)
    );
    INSERT INTO materials (material_id, sheet_material_type_id) VALUES (1, 1), (2, NULL), (3, 2);

    CREATE TABLE order_details (
      detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id BIGINT NOT NULL,
      quantity INTEGER NOT NULL DEFAULT 1,
      width NUMERIC(10,2) NOT NULL,
      height NUMERIC(10,2) NOT NULL,
      material_id BIGINT NOT NULL REFERENCES materials(material_id),
      film_id BIGINT REFERENCES films(film_id),
      production_status_id SMALLINT REFERENCES production_statuses(production_status_id),
      sheet_material_type_id BIGINT REFERENCES sheet_material_types(sheet_material_type_id),
      delete_flag BOOLEAN NOT NULL DEFAULT false
    );
    -- detail 5 mirrors the SP3 sheet model: its material (2) carries NO SP2
    -- sheet link, but the detail itself carries sheet_material_type_id = 2 (the
    -- authoritative per-detail sheet type, as bulk-migrated orders do).
    INSERT INTO order_details (detail_id, order_id, quantity, width, height, material_id, production_status_id, sheet_material_type_id) VALUES
      (1, 9, 1, 600, 400, 1, 1, NULL),
      (2, 9, 1, 600, 400, 1, 1, NULL),
      (3, 10, 1, 600, 400, 2, 1, NULL),
      (4, 10, 1, 600, 400, 3, 1, NULL),
      (5, 11, 1, 600, 400, 2, 1, 2);

    CREATE TABLE cut_job (
      cut_job_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(200) NOT NULL,
      status TEXT NOT NULL DEFAULT 'draft',
      source TEXT NOT NULL DEFAULT 'manual',
      selection_criteria JSONB,
      params JSONB,
      request_hash TEXT,
      pdf_prewarm_state TEXT NOT NULL DEFAULT 'pending',
      pdf_prewarm_failure_reason TEXT,
      created_by BIGINT,
      version INTEGER NOT NULL DEFAULT 0,
      created_at TIMESTAMP NOT NULL DEFAULT now(),
      updated_at TIMESTAMP NOT NULL DEFAULT now()
    );

    CREATE TABLE cut_group (
      cut_group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cut_job_id BIGINT NOT NULL REFERENCES cut_job(cut_job_id) ON DELETE CASCADE,
      sheet_material_type_id BIGINT,
      film_id BIGINT,
      status TEXT NOT NULL DEFAULT 'pending',
      summary JSONB,
      created_at TIMESTAMP NOT NULL DEFAULT now(),
      updated_at TIMESTAMP NOT NULL DEFAULT now()
    );

    CREATE TABLE cut_job_item (
      cut_job_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cut_job_id BIGINT NOT NULL REFERENCES cut_job(cut_job_id) ON DELETE CASCADE,
      cut_group_id BIGINT,
      order_detail_id BIGINT NOT NULL,
      order_id BIGINT NOT NULL,
      qty INTEGER NOT NULL,
      is_active BOOLEAN NOT NULL DEFAULT true,
      freecut_item_id TEXT,
      created_at TIMESTAMP NOT NULL DEFAULT now(),
      updated_at TIMESTAMP NOT NULL DEFAULT now()
    );
    -- migration 031: non-exclusive ACROSS jobs, but unique-and-idempotent WITHIN a
    -- job (per-job partial unique index) + a non-unique lookup index for placements.
    CREATE UNIQUE INDEX uq_cut_job_item_active_job_detail ON cut_job_item (cut_job_id, order_detail_id) WHERE is_active = true;
    CREATE INDEX idx_cut_job_item_active_order_detail ON cut_job_item (order_detail_id) WHERE is_active = true;

    CREATE TABLE cut_group_sheet (
      cut_group_sheet_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cut_group_id BIGINT NOT NULL REFERENCES cut_group(cut_group_id) ON DELETE CASCADE,
      sheet_index INTEGER NOT NULL,
      sheet_material_type_id BIGINT,
      png_cache_key TEXT,
      placements JSONB NOT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT now(),
      updated_at TIMESTAMP NOT NULL DEFAULT now()
    );

    CREATE TABLE outbox_events (
      outbox_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      event_type TEXT NOT NULL,
      aggregate_type TEXT NOT NULL,
      aggregate_id TEXT NOT NULL,
      payload_json JSONB NOT NULL,
      status TEXT NOT NULL DEFAULT 'pending',
      idempotency_key TEXT
    );
    CREATE UNIQUE INDEX uq_outbox_idempotency ON outbox_events (idempotency_key);

    CREATE TABLE audit_log (
      audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      event TEXT NOT NULL, entity_type TEXT, entity_id TEXT,
      user_id BIGINT, username TEXT, role_code TEXT, role TEXT,
      request_id TEXT, source TEXT,
      related_order_id BIGINT, related_client_id BIGINT, related_payment_id BIGINT,
      related_production_event_id BIGINT, related_deadline_id BIGINT, related_user_id BIGINT,
      status_field TEXT, status_id BIGINT, status_name TEXT, status_code TEXT, stage_code TEXT,
      before_json JSONB, after_json JSONB, diff_json JSONB, metadata_json JSONB,
      created_at TIMESTAMP NOT NULL DEFAULT now()
    );

    CREATE TABLE audit_log_related_entity (
      audit_id BIGINT NOT NULL,
      entity_type TEXT NOT NULL,
      entity_id BIGINT NOT NULL,
      UNIQUE (audit_id, entity_type, entity_id)
    );

    -- cut_config tables (migration 023). Left empty here so the config repo
    -- exercises its documented empty-table fallback to the in-code defaults.
    CREATE TABLE cut_param_profiles (
      cut_param_profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(200) NOT NULL UNIQUE,
      params JSONB NOT NULL,
      is_default BOOLEAN NOT NULL DEFAULT false,
      is_active BOOLEAN NOT NULL DEFAULT true,
      version INTEGER NOT NULL DEFAULT 0
    );
    CREATE TABLE cut_render_presets (
      cut_render_preset_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(100) NOT NULL UNIQUE,
      target_px INTEGER NOT NULL,
      background TEXT NOT NULL DEFAULT '#ffffff',
      is_active BOOLEAN NOT NULL DEFAULT true,
      version INTEGER NOT NULL DEFAULT 0
    );
    CREATE TABLE cut_settings (
      key TEXT PRIMARY KEY,
      value JSONB NOT NULL,
      version INTEGER NOT NULL DEFAULT 0
    );
  `);
}

/** Minimal DatabaseService over a single pooled connection in the throwaway schema. */
function makeDatabase(pool: Pool): DatabaseService {
  const query = (text: string, params: readonly unknown[] = []) => pool.query(text, [...params]);
  return {
    isConfigured: true,
    query,
    async transaction<T>(handler: (client: TransactionClient) => Promise<T>): Promise<T> {
      const client = await pool.connect();
      try {
        await client.query('BEGIN');
        await client.query(`SET search_path TO ${schemaName}`);
        const tx: TransactionClient = {
          raw: client as never,
          query: (text: string, params: readonly unknown[] = []) => client.query(text, [...params]),
        };
        const result = await handler(tx);
        await client.query('COMMIT');
        return result;
      } catch (error) {
        await client.query('ROLLBACK').catch(() => undefined);
        throw error;
      } finally {
        client.release();
      }
    },
  } as unknown as DatabaseService;
}

function stubFreecut(impl: () => Promise<FreecutOptimizeResponse>) {
  return { optimize: impl };
}

describeIntegration('PgCutRepository (integration)', () => {
  let pool: Pool;
  let database: DatabaseService;

  beforeAll(async () => {
    pool = new Pool({ connectionString: databaseUrl, max: 4 });
    await pool.query(`CREATE SCHEMA ${schemaName}`);
    await pool.query(`SET search_path TO ${schemaName}`);
    await createSchema(pool);
    // pin search_path for every pooled connection
    pool.on('connect', (client) => void client.query(`SET search_path TO ${schemaName}`));
    database = makeDatabase(pool);
  });

  afterAll(async () => {
    if (pool) {
      await pool.query(`DROP SCHEMA IF EXISTS ${schemaName} CASCADE`);
      await pool.end();
    }
  });

  beforeEach(async () => {
    await pool.query('TRUNCATE cut_group_sheet, cut_group, cut_job_item, cut_job, outbox_events, audit_log, audit_log_related_entity RESTART IDENTITY CASCADE');
  });

  it('places the SAME detail into multiple jobs (placement is non-exclusive, migration 031)', async () => {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const job1 = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест', detailIds: [1] }, requestId: 'r1' });
    expect(job1.items).toHaveLength(1);

    // Same detail into a second job no longer fails — both hold it actively.
    const job2 = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест2', detailIds: [1] }, requestId: 'r2' });
    expect(job2.items).toHaveLength(1);

    const active = await pool.query(
      'SELECT count(*)::int AS n FROM cut_job_item WHERE order_detail_id = 1 AND is_active = true',
    );
    expect(active.rows[0].n).toBe(2);

    // ...and placements surface both jobs for the detail (informational).
    const placements = await repo.listDetailPlacements({ currentUser: currentUser(), detailIds: [1], requestId: 'rp' });
    expect(placements.jobs.map((j) => j.cutJobId).sort((a, b) => a - b)).toEqual(
      [job1.cutJobId, job2.cutJobId].sort((a, b) => a - b),
    );
    expect(placements.hasArchived).toBe(false);
  });

  it('re-adding the SAME detail to the SAME job is idempotent (no qty doubling)', async () => {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест idem', detailIds: [1] }, requestId: 'ri1' });
    // add the same detail again to the SAME job
    const after = await repo.addItems({ currentUser: currentUser(), cutJobId: job.cutJobId, version: job.version, dto: { detailIds: [1] }, requestId: 'ri2' });
    expect(after.items.filter((i) => i.orderDetailId === 1)).toHaveLength(1);
    const active = await pool.query(
      'SELECT count(*)::int AS n FROM cut_job_item WHERE cut_job_id = $1 AND order_detail_id = 1 AND is_active = true',
      [job.cutJobId],
    );
    expect(active.rows[0].n).toBe(1);
  });

  it('placements: archived placement sets hasArchived (and is NOT listed in active jobs)', async () => {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест arch', detailIds: [1] }, requestId: 'ra1' });
    await repo.archive({ currentUser: currentUser(), cutJobId: job.cutJobId, version: job.version, requestId: 'ra2' });
    const placements = await repo.listDetailPlacements({ currentUser: currentUser(), detailIds: [1], requestId: 'ra3' });
    expect(placements.jobs).toHaveLength(0);
    expect(placements.hasArchived).toBe(true);
  });

  it('placements: aggregates distinct active jobs across multiple details', async () => {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const jobA = await repo.createJob({ currentUser: currentUser(), dto: { name: 'A', detailIds: [1] }, requestId: 'ag1' });
    const jobB = await repo.createJob({ currentUser: currentUser(), dto: { name: 'B', detailIds: [4] }, requestId: 'ag2' });
    const placements = await repo.listDetailPlacements({ currentUser: currentUser(), detailIds: [1, 4], requestId: 'ag3' });
    expect(placements.jobs.map((j) => j.cutJobId).sort((a, b) => a - b)).toEqual(
      [jobA.cutJobId, jobB.cutJobId].sort((a, b) => a - b),
    );
    expect(placements.hasArchived).toBe(false);
  });

  it('calculate fans out multi-material to N cut_groups, assigns items per group, one outbox row', async () => {
    // detail 1 -> material 1 -> sheet_material_type 1; detail 4 -> material 3 ->
    // sheet_material_type 2: two cuttable keys => two groups => two freecut calls.
    const echo = {
      optimize: (req: { stock: Array<{ id: string; width_mm: number; height_mm: number }>; items: Array<{ id: string; width_mm: number; height_mm: number }> }) =>
        Promise.resolve({
          status: 'ok',
          summary: { used_stock_count: 1, waste_percent: 7 },
          solutions: [
            {
              stock_id: req.stock[0].id,
              index: 0,
              width_mm: req.stock[0].width_mm,
              height_mm: req.stock[0].height_mm,
              trim_mm: { left: 10, right: 10, top: 10, bottom: 10 },
              placements: req.items.map((it, i) => ({
                item_id: it.id,
                instance: 1,
                x_mm: i * 620,
                y_mm: 0,
                width_mm: it.width_mm,
                height_mm: it.height_mm,
                rotated: false,
              })),
            },
          ],
        }),
    };
    const repo = new PgCutRepository(database, echo);
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест fanout', detailIds: [1, 4] }, requestId: 'rf1' });

    const calculated = await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: job.version, requestId: 'rf2' });
    expect(calculated.status).toBe('ready');
    expect(calculated.groups).toHaveLength(2);

    const groups = await pool.query('SELECT count(*)::int AS n FROM cut_group');
    expect(groups.rows[0].n).toBe(2);

    // Each detail is assigned to a DISTINCT cut_group matching its sheet spec.
    const assign = await pool.query('SELECT order_detail_id, cut_group_id FROM cut_job_item WHERE is_active = true ORDER BY order_detail_id');
    expect(assign.rows).toHaveLength(2);
    expect(assign.rows[0].cut_group_id).not.toBeNull();
    expect(assign.rows[0].cut_group_id).not.toBe(assign.rows[1].cut_group_id);

    // One audit + one outbox row for the whole job calc (not one-per-group).
    const calcAudit = await pool.query(`SELECT count(*)::int AS n FROM audit_log WHERE event = 'cut_job.calculated'`);
    expect(calcAudit.rows[0].n).toBe(1);
    const outbox = await pool.query(`SELECT count(*)::int AS n FROM outbox_events WHERE event_type = 'cut_job.calculated'`);
    expect(outbox.rows[0].n).toBe(1);
  });

  it('snapshots freecut params at createJob (config edit after creation does not retro-mutate)', async () => {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест snapshot', detailIds: [1] }, requestId: 'rs1' });
    const stored = await pool.query('SELECT params FROM cut_job WHERE cut_job_id = $1', [job.cutJobId]);
    expect(stored.rows[0].params).not.toBeNull();
    expect(stored.rows[0].params).toHaveProperty('kerf_mm');
  });

  it('recalculation replaces the prior result set (no stale groups), and a failed re-cut leaves none', async () => {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест recut', detailIds: [1, 2] }, requestId: 'rr1' });
    const first = await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: job.version, requestId: 'rr2' });
    expect((await pool.query('SELECT count(*)::int AS n FROM cut_group WHERE cut_job_id = $1', [job.cutJobId])).rows[0].n).toBe(1);

    // Recalculate -> exactly the new group(s), not accumulated stale ones.
    const second = await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: first.version, requestId: 'rr3' });
    expect((await pool.query('SELECT count(*)::int AS n FROM cut_group WHERE cut_job_id = $1', [job.cutJobId])).rows[0].n).toBe(1);
    expect(second.groups).toHaveLength(1);

    // A failed re-cut after a ready run leaves ZERO groups (no stale layout).
    const failRepo = new PgCutRepository(database, stubFreecut(() => Promise.reject(new ApiError(504, 'FREECUT_TIMEOUT', 't'))));
    await expect(
      failRepo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: second.version, requestId: 'rr4' }),
    ).rejects.toMatchObject({ code: 'FREECUT_TIMEOUT' });
    expect((await pool.query('SELECT count(*)::int AS n FROM cut_group WHERE cut_job_id = $1', [job.cutJobId])).rows[0].n).toBe(0);
    expect((await pool.query('SELECT status FROM cut_job WHERE cut_job_id = $1', [job.cutJobId])).rows[0].status).toBe('failed');
  });

  it('refuses to reserve an ineligible detail (no_sheet_spec) server-side', async () => {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    // detail 3 -> material 2 -> no sheet_material_type.
    await expect(
      repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест ineligible', detailIds: [3] }, requestId: 'ri' }),
    ).rejects.toMatchObject({ statusCode: 422, code: 'CUT_DETAIL_NOT_ELIGIBLE' });
  });

  it('resolves the sheet type from order_details.sheet_material_type_id when the material has no SP2 link (SP3 shadow orders)', async () => {
    // freecut stub that echoes whatever stock/items the repo sends (adapts to det-5/smt-2).
    const echo = {
      optimize: (req: { stock: Array<{ id: string; width_mm: number; height_mm: number }>; items: Array<{ id: string; width_mm: number; height_mm: number }> }) =>
        Promise.resolve({
          status: 'ok' as const,
          summary: { used_stock_count: 1, waste_percent: 5 },
          solutions: [
            {
              stock_id: req.stock[0].id,
              index: 0,
              width_mm: req.stock[0].width_mm,
              height_mm: req.stock[0].height_mm,
              trim_mm: { left: 10, right: 10, top: 10, bottom: 10 },
              placements: req.items.map((it, i) => ({
                item_id: it.id,
                instance: 1,
                x_mm: i * 620,
                y_mm: 0,
                width_mm: it.width_mm,
                height_mm: it.height_mm,
                rotated: false,
              })),
            },
          ],
        }),
    };
    const repo = new PgCutRepository(database, echo);
    // detail 5 -> material 2 (no material.sheet_material_type_id) but
    // order_details.sheet_material_type_id = 2, so it must be eligible.
    const eligible = await repo.listEligibleDetails({ currentUser: currentUser(), criteria: { orderIds: [11] }, requestId: 're-sp3' });
    const row = eligible.details.find((d) => d.orderDetailId === 5);
    expect(row?.eligible).toBe(true);
    expect(row?.ineligibleReason).toBeNull();
    expect(row?.sheetMaterialTypeId).toBe(2);

    // ...and it can be reserved + calculated (sheet dims resolved via the same path).
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест SP3 shadow', detailIds: [5] }, requestId: 'ri-sp3' });
    const calculated = await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: job.version, requestId: 'rc-sp3' });
    expect(calculated.groups.length).toBeGreaterThan(0);
    expect(calculated.groups[0]?.sheetMaterialTypeId).toBe(2);
  });

  it('eligibility codes that resolve to zero status ids return nothing (no leakage)', async () => {
    await pool.query(
      `INSERT INTO cut_settings (key, value) VALUES ('eligibility.statuses', '{"codes":["__nope__"]}'::jsonb)
       ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value`,
    );
    try {
      const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
      const result = await repo.listEligibleDetails({ currentUser: currentUser(), criteria: { orderIds: [9, 10] }, requestId: 'rz' });
      expect(result.details).toHaveLength(0);
    } finally {
      await pool.query(`DELETE FROM cut_settings WHERE key = 'eligibility.statuses'`);
    }
  });

  it('pdf prewarm state is version-scoped (a stale-version write is a no-op)', async () => {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест prewarm', detailIds: [1] }, requestId: 'pw1' });
    const calc = await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: job.version, requestId: 'pw2' });
    await repo.setPdfPrewarmState({ cutJobId: job.cutJobId, version: calc.version - 1, state: 'ready' });
    expect((await pool.query('SELECT pdf_prewarm_state FROM cut_job WHERE cut_job_id = $1', [job.cutJobId])).rows[0].pdf_prewarm_state).toBe('pending');
    await repo.setPdfPrewarmState({ cutJobId: job.cutJobId, version: calc.version, state: 'ready' });
    expect((await pool.query('SELECT pdf_prewarm_state FROM cut_job WHERE cut_job_id = $1', [job.cutJobId])).rows[0].pdf_prewarm_state).toBe('ready');

    // Recalculating bumps the version and resets the pre-warm state to pending
    // (the new version's PDF is not yet rendered).
    await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: calc.version, requestId: 'pw3' });
    expect((await pool.query('SELECT pdf_prewarm_state FROM cut_job WHERE cut_job_id = $1', [job.cutJobId])).rows[0].pdf_prewarm_state).toBe('pending');
  });

  it('renders per-sheet SVG and on-demand group/job PDFs from stored placements', async () => {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест pdf', detailIds: [1, 2] }, requestId: 'rp1' });
    const calculated = await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: job.version, requestId: 'rp2' });
    const cutGroupId = calculated.groups[0].cutGroupId;

    const svg = await repo.renderSheetSvg({ currentUser: currentUser(), cutGroupId, sheetIndex: 0 });
    expect(svg).toContain('<svg');

    const groupPdf = await repo.renderGroupPdf({ currentUser: currentUser(), cutGroupId });
    expect(groupPdf.subarray(0, 5).toString('latin1')).toBe('%PDF-');

    const jobPdf = await repo.renderJobPdf({ currentUser: currentUser(), cutJobId: job.cutJobId });
    expect(jobPdf.subarray(0, 5).toString('latin1')).toBe('%PDF-');

    await repo.setPdfPrewarmState({ cutJobId: job.cutJobId, version: calculated.version, state: 'ready' });
    const state = await pool.query('SELECT pdf_prewarm_state FROM cut_job WHERE cut_job_id = $1', [job.cutJobId]);
    expect(state.rows[0].pdf_prewarm_state).toBe('ready');
  });

  it('addItems rejects a stale version with 409', async () => {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест' }, requestId: 'r1' });
    await expect(
      repo.addItems({ currentUser: currentUser(), cutJobId: job.cutJobId, version: 99, dto: { detailIds: [1] }, requestId: 'r2' }),
    ).rejects.toMatchObject({ statusCode: 409, code: 'CUT_STALE_VERSION' });
  });

  it('calculate persists cut_group/sheets, audit + bridge rows, and one idempotent outbox row', async () => {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест', detailIds: [1, 2] }, requestId: 'r1' });

    const calculated = await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: job.version, requestId: 'r2' });
    expect(calculated.status).toBe('ready');
    expect(calculated.groups).toHaveLength(1);
    expect(calculated.groups[0].sheets).toHaveLength(1);

    const groups = await pool.query('SELECT count(*)::int AS n FROM cut_group');
    expect(groups.rows[0].n).toBe(1);
    const sheets = await pool.query('SELECT count(*)::int AS n FROM cut_group_sheet');
    expect(sheets.rows[0].n).toBe(1);

    const calcAudit = await pool.query(`SELECT audit_id FROM audit_log WHERE event = 'cut_job.calculated'`);
    expect(calcAudit.rows).toHaveLength(1);
    const bridge = await pool.query('SELECT entity_type FROM audit_log_related_entity WHERE audit_id = $1', [calcAudit.rows[0].audit_id]);
    const types = bridge.rows.map((r) => r.entity_type).sort();
    expect(types).toContain('order');
    expect(types).toContain('sheet_material_type');
    expect(types).toContain('cut_group');

    const outbox = await pool.query(`SELECT idempotency_key FROM outbox_events WHERE event_type = 'cut_job.calculated'`);
    expect(outbox.rows).toHaveLength(1);
    expect(String(outbox.rows[0].idempotency_key)).toMatch(/^cut_job\.calculated:/);

    // Recalculate with the same item set -> same request_hash -> no duplicate outbox row.
    await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: calculated.version, requestId: 'r3' });
    const outbox2 = await pool.query(`SELECT count(*)::int AS n FROM outbox_events WHERE event_type = 'cut_job.calculated'`);
    expect(outbox2.rows[0].n).toBe(1);
  });

  it('freecut failure persists status=failed + cut_job.calculate_failed and rethrows', async () => {
    const repo = new PgCutRepository(
      database,
      stubFreecut(() => Promise.reject(new ApiError(504, 'FREECUT_TIMEOUT', 'timeout'))),
    );
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест', detailIds: [1] }, requestId: 'r1' });

    await expect(
      repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: job.version, requestId: 'r2' }),
    ).rejects.toMatchObject({ code: 'FREECUT_TIMEOUT' });

    const status = await pool.query('SELECT status FROM cut_job WHERE cut_job_id = $1', [job.cutJobId]);
    expect(status.rows[0].status).toBe('failed');
    const failAudit = await pool.query(`SELECT count(*)::int AS n FROM audit_log WHERE event = 'cut_job.calculate_failed'`);
    expect(failAudit.rows[0].n).toBe(1);
  });

  it('listEligibleDetails surfaces no_sheet_spec for an unlinked material', async () => {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const result = await repo.listEligibleDetails({ currentUser: currentUser(), criteria: { orderIds: [9, 10] }, requestId: 'r' });
    // details 1,2 (smt 1), 3 (no sheet spec), 4 (smt 2).
    expect(result.details).toHaveLength(4);
    expect(result.noSheetSpecCount).toBe(1);
    expect(result.details.find((d) => d.orderDetailId === 3)?.ineligibleReason).toBe('no_sheet_spec');
  });
});
