import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import type { DatabaseService } from '../../../database/database.service';
import type { TransactionClient } from '../../../database/database.types';
import type { CurrentUser } from '../../../permissions/current-user';
import type { FreecutOptimizeResponse } from '../application/cut-freecut-mapping';
import { ApiError } from '../../../common/errors/api-error';
import { PgCutRepository } from './pg-cut-repository';

// Full-stack repository integration: createJob reserve -> 409 duplicate, addItems
// stale-version 409, calculate happy path (stubbed FreecutClient) persisting
// cut_group/cut_group_sheet + audit row + N related-entity bridge rows + the
// idempotent outbox row, and the freecut-failure path persisting status=failed +
// cut_job.calculate_failed. Gated on CUT_INTEGRATION_DATABASE_URL (falls back to
// TEST_DATABASE_URL); skips cleanly without a database. Throwaway schema only.
const databaseUrl = process.env.CUT_INTEGRATION_DATABASE_URL ?? process.env.TEST_DATABASE_URL;
const describeIntegration = databaseUrl ? describe : describe.skip;

const schemaName = `cut_repo_${randomUUID().replaceAll('-', '_')}`;

function currentUser(): CurrentUser {
  return { id: '1', username: 'cutter', role: 'operator', permissions: ['cut.view', 'cut.manage'] } as unknown as CurrentUser;
}

const happyResponse: FreecutOptimizeResponse = {
  status: 'ok',
  summary: { used_stock_count: 1, waste_percent: 10 },
  solutions: [
    {
      stock_id: 'smt-1',
      index: 0,
      width_mm: 2800,
      height_mm: 2070,
      trim_mm: { left: 10, right: 10, top: 10, bottom: 10 },
      placements: [
        { item_id: 'det-1', instance: 1, x_mm: 0, y_mm: 0, width_mm: 600, height_mm: 400, rotated: false },
        { item_id: 'det-2', instance: 1, x_mm: 620, y_mm: 0, width_mm: 600, height_mm: 400, rotated: false },
      ],
    },
  ],
};

async function createSchema(pool: Pool): Promise<void> {
  await pool.query(`
    CREATE FUNCTION set_session_user(p_user TEXT) RETURNS void AS $$ BEGIN PERFORM 1; END; $$ LANGUAGE plpgsql;

    CREATE TABLE production_statuses (
      production_status_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      production_status_code TEXT NOT NULL UNIQUE,
      production_status_name TEXT
    );
    INSERT INTO production_statuses (production_status_id, production_status_code, production_status_name)
      VALUES (1, 'new', 'Новый'), (2, 'drawn', 'Начерчен'), (3, 'film_purchase', 'Закуп плёнки'), (4, 'cut', 'Раскроен');

    CREATE TABLE sheet_material_types (
      sheet_material_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL DEFAULT '',
      width_mm NUMERIC(10,2) NOT NULL,
      height_mm NUMERIC(10,2) NOT NULL,
      is_cuttable BOOLEAN NOT NULL DEFAULT true,
      is_active BOOLEAN NOT NULL DEFAULT true
    );
    -- Types 1,2: cuttable panels (active). Type 3: non-cuttable (e.g. glass, MDF) for not_cuttable path.
    INSERT INTO sheet_material_types (sheet_material_type_id, name, width_mm, height_mm, is_cuttable, is_active) VALUES
      (1, 'ДСП 2800x2070', 2800, 2070, true, true),
      (2, 'ДСП 2070x2800', 2070, 2800, true, true),
      (3, 'Стекло 1000x1000', 1000, 1000, false, true);

    CREATE TABLE films (
      film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      film_name TEXT,
      film_texture BOOLEAN NOT NULL DEFAULT false
    );

    -- Dictionary tables resolved by the enriched single-job item read (names, not ids).
    CREATE TABLE milling_types (
      milling_type_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      milling_type_name TEXT
    );
    CREATE TABLE edge_types (
      edge_type_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      edge_type_name TEXT
    );

    CREATE TABLE materials (
      material_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      material_name TEXT,
      sheet_material_type_id BIGINT REFERENCES sheet_material_types(sheet_material_type_id)
    );
    INSERT INTO materials (material_id, material_name, sheet_material_type_id) VALUES (1, 'Материал 1', 1), (2, 'Материал 2', NULL), (3, 'Материал 3', 2);

    CREATE TABLE order_details (
      detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id BIGINT NOT NULL,
      detail_number SMALLINT,
      detail_name VARCHAR(200),
      quantity INTEGER NOT NULL DEFAULT 1,
      width NUMERIC(10,2) NOT NULL,
      height NUMERIC(10,2) NOT NULL,
      area NUMERIC(10,2),
      -- Variant B (migration 034): material_id is NULL for all order_details post-sunset.
      -- Kept nullable here; NOT NULL + CHECK is enforced in prod after 034 applies.
      material_id BIGINT REFERENCES materials(material_id),
      milling_type_id SMALLINT REFERENCES milling_types(milling_type_id),
      edge_type_id SMALLINT REFERENCES edge_types(edge_type_id),
      film_id BIGINT REFERENCES films(film_id),
      priority SMALLINT,
      production_status_id SMALLINT REFERENCES production_statuses(production_status_id),
      joint_order_id BIGINT,
      note TEXT,
      link_cutting_file TEXT,
      link_cutting_image_file TEXT,
      link_cad_file TEXT,
      link_pdf_file TEXT,
      sheet_material_type_id BIGINT REFERENCES sheet_material_types(sheet_material_type_id),
      delete_flag BOOLEAN NOT NULL DEFAULT false
    );
    -- Variant B seed: material_id = NULL; sheet_material_type_id is authoritative.
    -- Details 1,2 (order 9) -> sheet type 1 (2800x2070, cuttable).
    -- Detail  3  (order 10) -> sheet_material_type_id = NULL (no_sheet_spec path).
    -- Detail  4  (order 10) -> sheet type 2 (2070x2800, cuttable).
    -- Detail  5  (order 11) -> sheet type 2 (cuttable, SP3 shadow test).
    -- Detail  6  (order 12) -> sheet type 3 (is_cuttable=false) -> not_cuttable path.
    INSERT INTO order_details (detail_id, order_id, quantity, width, height, material_id, production_status_id, sheet_material_type_id) VALUES
      (1, 9, 1, 600, 400, NULL, 1, 1),
      (2, 9, 1, 600, 400, NULL, 1, 1),
      (3, 10, 1, 600, 400, NULL, 1, NULL),
      (4, 10, 1, 600, 400, NULL, 1, 2),
      (5, 11, 1, 600, 400, NULL, 1, 2),
      (6, 12, 1, 600, 400, NULL, 1, 3);

    CREATE TABLE cut_job (
      cut_job_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(200) NOT NULL,
      status TEXT NOT NULL DEFAULT 'draft',
      source TEXT NOT NULL DEFAULT 'manual',
      selection_criteria JSONB,
      params JSONB,
      request_hash TEXT,
      pdf_prewarm_state TEXT NOT NULL DEFAULT 'pending',
      pdf_prewarm_failure_reason TEXT,
      failure_code TEXT,
      failure_reason TEXT,
      param_profile_id BIGINT,
      created_by BIGINT,
      version INTEGER NOT NULL DEFAULT 0,
      created_at TIMESTAMP NOT NULL DEFAULT now(),
      updated_at TIMESTAMP NOT NULL DEFAULT now()
    );

    CREATE TABLE cut_group (
      cut_group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cut_job_id BIGINT NOT NULL REFERENCES cut_job(cut_job_id) ON DELETE CASCADE,
      sheet_material_type_id BIGINT,
      film_id BIGINT,
      status TEXT NOT NULL DEFAULT 'pending',
      summary JSONB,
      created_at TIMESTAMP NOT NULL DEFAULT now(),
      updated_at TIMESTAMP NOT NULL DEFAULT now()
    );

    CREATE TABLE cut_job_item (
      cut_job_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cut_job_id BIGINT NOT NULL REFERENCES cut_job(cut_job_id) ON DELETE CASCADE,
      cut_group_id BIGINT,
      order_detail_id BIGINT NOT NULL,
      order_id BIGINT NOT NULL,
      qty INTEGER NOT NULL,
      is_active BOOLEAN NOT NULL DEFAULT true,
      freecut_item_id TEXT,
      created_at TIMESTAMP NOT NULL DEFAULT now(),
      updated_at TIMESTAMP NOT NULL DEFAULT now()
    );
    -- migration 031: non-exclusive ACROSS jobs, but unique-and-idempotent WITHIN a
    -- job (per-job partial unique index) + a non-unique lookup index for placements.
    CREATE UNIQUE INDEX uq_cut_job_item_active_job_detail ON cut_job_item (cut_job_id, order_detail_id) WHERE is_active = true;
    CREATE INDEX idx_cut_job_item_order_detail ON cut_job_item (order_detail_id);

    CREATE TABLE cut_group_sheet (
      cut_group_sheet_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cut_group_id BIGINT NOT NULL REFERENCES cut_group(cut_group_id) ON DELETE CASCADE,
      sheet_index INTEGER NOT NULL,
      sheet_material_type_id BIGINT,
      png_cache_key TEXT,
      placements JSONB NOT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT now(),
      updated_at TIMESTAMP NOT NULL DEFAULT now()
    );

    CREATE TABLE outbox_events (
      outbox_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      event_type TEXT NOT NULL,
      aggregate_type TEXT NOT NULL,
      aggregate_id TEXT NOT NULL,
      payload_json JSONB NOT NULL,
      status TEXT NOT NULL DEFAULT 'pending',
      idempotency_key TEXT
    );
    CREATE UNIQUE INDEX uq_outbox_idempotency ON outbox_events (idempotency_key);

    CREATE TABLE audit_log (
      audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      event TEXT NOT NULL, entity_type TEXT, entity_id TEXT,
      user_id BIGINT, username TEXT, role_code TEXT, role TEXT,
      request_id TEXT, source TEXT,
      related_order_id BIGINT, related_client_id BIGINT, related_payment_id BIGINT,
      related_production_event_id BIGINT, related_deadline_id BIGINT, related_user_id BIGINT,
      status_field TEXT, status_id BIGINT, status_name TEXT, status_code TEXT, stage_code TEXT,
      before_json JSONB, after_json JSONB, diff_json JSONB, metadata_json JSONB,
      created_at TIMESTAMP NOT NULL DEFAULT now()
    );

    CREATE TABLE audit_log_related_entity (
      audit_id BIGINT NOT NULL,
      entity_type TEXT NOT NULL,
      entity_id BIGINT NOT NULL,
      UNIQUE (audit_id, entity_type, entity_id)
    );

    -- cut_config tables (migration 023). Left empty here so the config repo
    -- exercises its documented empty-table fallback to the in-code defaults.
    CREATE TABLE cut_param_profiles (
      cut_param_profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(200) NOT NULL UNIQUE,
      params JSONB NOT NULL,
      is_default BOOLEAN NOT NULL DEFAULT false,
      is_active BOOLEAN NOT NULL DEFAULT true,
      version INTEGER NOT NULL DEFAULT 0
    );
    CREATE TABLE cut_render_presets (
      cut_render_preset_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(100) NOT NULL UNIQUE,
      target_px INTEGER NOT NULL,
      background TEXT NOT NULL DEFAULT '#ffffff',
      is_active BOOLEAN NOT NULL DEFAULT true,
      version INTEGER NOT NULL DEFAULT 0
    );
    CREATE TABLE cut_settings (
      key TEXT PRIMARY KEY,
      value JSONB NOT NULL,
      version INTEGER NOT NULL DEFAULT 0
    );
  `);
}

/** Minimal DatabaseService over a single pooled connection in the throwaway schema. */
function makeDatabase(pool: Pool): DatabaseService {
  const query = (text: string, params: readonly unknown[] = []) => pool.query(text, [...params]);
  return {
    isConfigured: true,
    query,
    async transaction<T>(handler: (client: TransactionClient) => Promise<T>): Promise<T> {
      const client = await pool.connect();
      try {
        await client.query('BEGIN');
        await client.query(`SET search_path TO ${schemaName}`);
        const tx: TransactionClient = {
          raw: client as never,
          query: (text: string, params: readonly unknown[] = []) => client.query(text, [...params]),
        };
        const result = await handler(tx);
        await client.query('COMMIT');
        return result;
      } catch (error) {
        await client.query('ROLLBACK').catch(() => undefined);
        throw error;
      } finally {
        client.release();
      }
    },
  } as unknown as DatabaseService;
}

function stubFreecut(impl: () => Promise<FreecutOptimizeResponse>) {
  return { optimize: impl };
}

async function insertProfile(pool: Pool, name: string, params: Record<string, unknown>, isDefault = false): Promise<number> {
  const r = await pool.query(
    `INSERT INTO cut_param_profiles (name, params, is_default, is_active) VALUES ($1, $2::jsonb, $3, true) RETURNING cut_param_profile_id`,
    [name, JSON.stringify(params), isDefault],
  );
  return Number(r.rows[0].cut_param_profile_id);
}

async function seedDetail(pool: Pool, opts: { detailId: number; area: number; quantity: number }): Promise<void> {
  await pool.query(
    `INSERT INTO order_details (detail_id, order_id, quantity, width, height, area, material_id, production_status_id, sheet_material_type_id)
     VALUES ($1, 9, $2, 600, 400, $3, NULL, 1, 1)`,
    [opts.detailId, opts.quantity, opts.area],
  );
}

describeIntegration('PgCutRepository (integration)', () => {
  let pool: Pool;
  let database: DatabaseService;

  beforeAll(async () => {
    pool = new Pool({ connectionString: databaseUrl, max: 4 });
    await pool.query(`CREATE SCHEMA ${schemaName}`);
    await pool.query(`SET search_path TO ${schemaName}`);
    await createSchema(pool);
    // pin search_path for every pooled connection
    pool.on('connect', (client) => void client.query(`SET search_path TO ${schemaName}`));
    database = makeDatabase(pool);
  });

  afterAll(async () => {
    if (pool) {
      await pool.query(`DROP SCHEMA IF EXISTS ${schemaName} CASCADE`);
      await pool.end();
    }
  });

  beforeEach(async () => {
    await pool.query('TRUNCATE cut_group_sheet, cut_group, cut_job_item, cut_job, outbox_events, audit_log, audit_log_related_entity RESTART IDENTITY CASCADE');
  });

  it('places the SAME detail into multiple jobs (placement is non-exclusive, migration 031)', async () => {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const job1 = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест', detailIds: [1] }, requestId: 'r1' });
    expect(job1.items).toHaveLength(1);

    // Same detail into a second job no longer fails — both hold it actively.
    const job2 = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест2', detailIds: [1] }, requestId: 'r2' });
    expect(job2.items).toHaveLength(1);

    const active = await pool.query(
      'SELECT count(*)::int AS n FROM cut_job_item WHERE order_detail_id = 1 AND is_active = true',
    );
    expect(active.rows[0].n).toBe(2);

    // ...and placements surface both jobs for the detail (informational).
    const placements = await repo.listDetailPlacements({ currentUser: currentUser(), detailIds: [1], requestId: 'rp' });
    expect(placements.jobs.map((j) => j.cutJobId).sort((a, b) => a - b)).toEqual(
      [job1.cutJobId, job2.cutJobId].sort((a, b) => a - b),
    );
    expect(placements.hasArchived).toBe(false);
  });

  it('enriched item detail hydrates for a live detail (even with null position) and collapses to null after soft-delete', async () => {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест detail', detailIds: [1] }, requestId: 'd1' });

    const opened = await repo.getJob({ currentUser: currentUser(), cutJobId: job.cutJobId, requestId: 'd2' });
    expect(opened.items).toHaveLength(1);
    // Detail 1 has a NULL detail_number in the fixture, yet the enriched block must
    // still hydrate — existence is keyed off the joined PK, not user data
    // (REGRESSION-DEBT guard).
    expect(opened.items[0].detail).not.toBeNull();
    expect(opened.items[0].detail?.detailNumber).toBeNull();
    // Variant B: the cut detail's material resolves from its sheet type
    // (order_details.material_id is NULL post-034); detail 1 -> sheet type 1.
    expect(opened.items[0].detail?.materialName).toBe('ДСП 2800x2070');

    // Soft-delete the source detail: the item row stays, but the detail collapses
    // to null instead of leaking stale fields (DATA-INTEGRITY-DEBT guard).
    // order_details is seeded once (beforeEach truncates only cut_* tables), so
    // restore the flag in finally to keep detail 1 live for later tests.
    try {
      await pool.query('UPDATE order_details SET delete_flag = true WHERE detail_id = 1');
      const afterDelete = await repo.getJob({ currentUser: currentUser(), cutJobId: job.cutJobId, requestId: 'd3' });
      expect(afterDelete.items).toHaveLength(1);
      expect(afterDelete.items[0].orderDetailId).toBe(1);
      expect(afterDelete.items[0].detail).toBeNull();
    } finally {
      await pool.query('UPDATE order_details SET delete_flag = false WHERE detail_id = 1');
    }
  });

  it('re-adding the SAME detail to the SAME job is a no-op (no qty doubling, no version/audit churn)', async () => {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест idem', detailIds: [1] }, requestId: 'ri1' });
    // add the same detail again to the SAME job
    const after = await repo.addItems({ currentUser: currentUser(), cutJobId: job.cutJobId, version: job.version, dto: { detailIds: [1] }, requestId: 'ri2' });
    expect(after.items.filter((i) => i.orderDetailId === 1)).toHaveLength(1);
    const active = await pool.query(
      'SELECT count(*)::int AS n FROM cut_job_item WHERE cut_job_id = $1 AND order_detail_id = 1 AND is_active = true',
      [job.cutJobId],
    );
    expect(active.rows[0].n).toBe(1);
    // no-op: version unchanged and NO itemAdded audit row written (Critic AUDIT-DEBT)
    expect(after.version).toBe(job.version);
    const itemAdded = await pool.query(`SELECT count(*)::int AS n FROM audit_log WHERE event = 'cut_job.item_added'`);
    expect(itemAdded.rows[0].n).toBe(0);
  });

  it('placements report ONLY eligible details (ineligible placed rows are not surfaced)', async () => {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    // detail 3 -> sheet_material_type_id = NULL (no_sheet_spec) is INELIGIBLE; force it into a job at the
    // DB level (the API would reject it) to prove placements filters it out.
    const j = await pool.query(`INSERT INTO cut_job (name, status) VALUES ('forced', 'draft') RETURNING cut_job_id`);
    const forcedJobId = j.rows[0].cut_job_id;
    await pool.query(
      `INSERT INTO cut_job_item (cut_job_id, order_detail_id, order_id, qty, is_active) VALUES ($1, 3, 10, 1, true)`,
      [forcedJobId],
    );
    const placements = await repo.listDetailPlacements({ currentUser: currentUser(), detailIds: [3], requestId: 'pe1' });
    expect(placements.jobs).toHaveLength(0);
    expect(placements.hasArchived).toBe(false);
  });

  it('placements: archived placement sets hasArchived (and is NOT listed in active jobs)', async () => {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест arch', detailIds: [1] }, requestId: 'ra1' });
    await repo.archive({ currentUser: currentUser(), cutJobId: job.cutJobId, version: job.version, requestId: 'ra2' });
    const placements = await repo.listDetailPlacements({ currentUser: currentUser(), detailIds: [1], requestId: 'ra3' });
    expect(placements.jobs).toHaveLength(0);
    expect(placements.hasArchived).toBe(true);
  });

  it('placements: aggregates distinct active jobs across multiple details', async () => {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const jobA = await repo.createJob({ currentUser: currentUser(), dto: { name: 'A', detailIds: [1] }, requestId: 'ag1' });
    const jobB = await repo.createJob({ currentUser: currentUser(), dto: { name: 'B', detailIds: [4] }, requestId: 'ag2' });
    const placements = await repo.listDetailPlacements({ currentUser: currentUser(), detailIds: [1, 4], requestId: 'ag3' });
    expect(placements.jobs.map((j) => j.cutJobId).sort((a, b) => a - b)).toEqual(
      [jobA.cutJobId, jobB.cutJobId].sort((a, b) => a - b),
    );
    expect(placements.hasArchived).toBe(false);
  });

  it('calculate fans out multi-sheet-type to N cut_groups, assigns items per group, one outbox row', async () => {
    // Variant B: detail 1 -> sheet_material_type_id 1 (2800x2070); detail 4 ->
    // sheet_material_type_id 2 (2070x2800): two cuttable keys => two groups => two freecut calls.
    const echo = {
      optimize: (req: { stock: Array<{ id: string; width_mm: number; height_mm: number }>; items: Array<{ id: string; width_mm: number; height_mm: number }> }) =>
        Promise.resolve({
          status: 'ok',
          summary: { used_stock_count: 1, waste_percent: 7 },
          solutions: [
            {
              stock_id: req.stock[0].id,
              index: 0,
              width_mm: req.stock[0].width_mm,
              height_mm: req.stock[0].height_mm,
              trim_mm: { left: 10, right: 10, top: 10, bottom: 10 },
              placements: req.items.map((it, i) => ({
                item_id: it.id,
                instance: 1,
                x_mm: i * 620,
                y_mm: 0,
                width_mm: it.width_mm,
                height_mm: it.height_mm,
                rotated: false,
              })),
            },
          ],
        }),
    };
    const repo = new PgCutRepository(database, echo);
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест fanout', detailIds: [1, 4] }, requestId: 'rf1' });

    const calculated = await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: job.version, requestId: 'rf2' });
    expect(calculated.status).toBe('ready');
    expect(calculated.groups).toHaveLength(2);

    const groups = await pool.query('SELECT count(*)::int AS n FROM cut_group');
    expect(groups.rows[0].n).toBe(2);

    // Each detail is assigned to a DISTINCT cut_group matching its sheet spec.
    const assign = await pool.query('SELECT order_detail_id, cut_group_id FROM cut_job_item WHERE is_active = true ORDER BY order_detail_id');
    expect(assign.rows).toHaveLength(2);
    expect(assign.rows[0].cut_group_id).not.toBeNull();
    expect(assign.rows[0].cut_group_id).not.toBe(assign.rows[1].cut_group_id);

    // One audit + one outbox row for the whole job calc (not one-per-group).
    const calcAudit = await pool.query(`SELECT count(*)::int AS n FROM audit_log WHERE event = 'cut_job.calculated'`);
    expect(calcAudit.rows[0].n).toBe(1);
    const outbox = await pool.query(`SELECT count(*)::int AS n FROM outbox_events WHERE event_type = 'cut_job.calculated'`);
    expect(outbox.rows[0].n).toBe(1);
  });

  it('snapshots freecut params at createJob (config edit after creation does not retro-mutate)', async () => {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест snapshot', detailIds: [1] }, requestId: 'rs1' });
    const stored = await pool.query('SELECT params FROM cut_job WHERE cut_job_id = $1', [job.cutJobId]);
    expect(stored.rows[0].params).not.toBeNull();
    expect(stored.rows[0].params).toHaveProperty('kerf_mm');
  });

  it('recalculation replaces the prior result set (no stale groups), and a failed re-cut leaves none', async () => {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест recut', detailIds: [1, 2] }, requestId: 'rr1' });
    const first = await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: job.version, requestId: 'rr2' });
    expect((await pool.query('SELECT count(*)::int AS n FROM cut_group WHERE cut_job_id = $1', [job.cutJobId])).rows[0].n).toBe(1);

    // Recalculate -> exactly the new group(s), not accumulated stale ones.
    const second = await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: first.version, requestId: 'rr3' });
    expect((await pool.query('SELECT count(*)::int AS n FROM cut_group WHERE cut_job_id = $1', [job.cutJobId])).rows[0].n).toBe(1);
    expect(second.groups).toHaveLength(1);

    // A failed re-cut after a ready run leaves ZERO groups (no stale layout).
    const failRepo = new PgCutRepository(database, stubFreecut(() => Promise.reject(new ApiError(504, 'FREECUT_TIMEOUT', 't'))));
    await expect(
      failRepo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: second.version, requestId: 'rr4' }),
    ).rejects.toMatchObject({ code: 'FREECUT_TIMEOUT' });
    expect((await pool.query('SELECT count(*)::int AS n FROM cut_group WHERE cut_job_id = $1', [job.cutJobId])).rows[0].n).toBe(0);
    expect((await pool.query('SELECT status FROM cut_job WHERE cut_job_id = $1', [job.cutJobId])).rows[0].status).toBe('failed');
  });

  it('a Phase 1 failure after a ready run also clears the prior layout (no stale groups)', async () => {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест p1clear', detailIds: [1] }, requestId: 'p1' });
    const ready = await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: job.version, requestId: 'p2' });
    expect(ready.status).toBe('ready');
    expect((await pool.query('SELECT count(*)::int AS n FROM cut_group WHERE cut_job_id = $1', [job.cutJobId])).rows[0].n).toBe(1);

    // Empty the basket, then recalc -> Phase 1 CUT_NO_ITEMS, whose prep tx rolls
    // back (it does NOT drop the old groups). markCalcFailed must still clear them.
    const afterRemove = await repo.removeItem({
      currentUser: currentUser(),
      cutJobId: job.cutJobId,
      cutJobItemId: ready.items[0].cutJobItemId,
      version: ready.version,
      requestId: 'p3',
    });
    await expect(
      repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: afterRemove.version, requestId: 'p4' }),
    ).rejects.toMatchObject({ code: 'CUT_NO_ITEMS', statusCode: 422 });

    const row = await pool.query('SELECT status, failure_code FROM cut_job WHERE cut_job_id = $1', [job.cutJobId]);
    expect(row.rows[0].status).toBe('failed');
    expect(row.rows[0].failure_code).toBe('CUT_NO_ITEMS');
    // Invariant: a failed job carries NO stale layout, even via the Phase 1 path.
    expect((await pool.query('SELECT count(*)::int AS n FROM cut_group WHERE cut_job_id = $1', [job.cutJobId])).rows[0].n).toBe(0);
  });

  it('refuses to reserve an ineligible detail (no_sheet_spec) server-side', async () => {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    // detail 3 -> sheet_material_type_id = NULL (no_sheet_spec in Variant B).
    await expect(
      repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест ineligible', detailIds: [3] }, requestId: 'ri' }),
    ).rejects.toMatchObject({ statusCode: 422, code: 'CUT_DETAIL_NOT_ELIGIBLE' });
  });

  it('resolves the sheet type from order_details.sheet_material_type_id when the material has no SP2 link (SP3 shadow orders)', async () => {
    // freecut stub that echoes whatever stock/items the repo sends (adapts to det-5/smt-2).
    const echo = {
      optimize: (req: { stock: Array<{ id: string; width_mm: number; height_mm: number }>; items: Array<{ id: string; width_mm: number; height_mm: number }> }) =>
        Promise.resolve({
          status: 'ok' as const,
          summary: { used_stock_count: 1, waste_percent: 5 },
          solutions: [
            {
              stock_id: req.stock[0].id,
              index: 0,
              width_mm: req.stock[0].width_mm,
              height_mm: req.stock[0].height_mm,
              trim_mm: { left: 10, right: 10, top: 10, bottom: 10 },
              placements: req.items.map((it, i) => ({
                item_id: it.id,
                instance: 1,
                x_mm: i * 620,
                y_mm: 0,
                width_mm: it.width_mm,
                height_mm: it.height_mm,
                rotated: false,
              })),
            },
          ],
        }),
    };
    const repo = new PgCutRepository(database, echo);
    // detail 5 -> material 2 (no material.sheet_material_type_id) but
    // order_details.sheet_material_type_id = 2, so it must be eligible.
    const eligible = await repo.listEligibleDetails({ currentUser: currentUser(), criteria: { orderIds: [11] }, requestId: 're-sp3' });
    const row = eligible.details.find((d) => d.orderDetailId === 5);
    expect(row?.eligible).toBe(true);
    expect(row?.ineligibleReason).toBeNull();
    expect(row?.sheetMaterialTypeId).toBe(2);

    // ...and it can be reserved + calculated (sheet dims resolved via the same path).
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест SP3 shadow', detailIds: [5] }, requestId: 'ri-sp3' });
    const calculated = await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: job.version, requestId: 'rc-sp3' });
    expect(calculated.groups.length).toBeGreaterThan(0);
    expect(calculated.groups[0]?.sheetMaterialTypeId).toBe(2);
  });

  it('eligibility codes that resolve to zero status ids return nothing (no leakage)', async () => {
    await pool.query(
      `INSERT INTO cut_settings (key, value) VALUES ('eligibility.statuses', '{"codes":["__nope__"]}'::jsonb)
       ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value`,
    );
    try {
      const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
      const result = await repo.listEligibleDetails({ currentUser: currentUser(), criteria: { orderIds: [9, 10] }, requestId: 'rz' });
      expect(result.details).toHaveLength(0);
    } finally {
      await pool.query(`DELETE FROM cut_settings WHERE key = 'eligibility.statuses'`);
    }
  });

  it('pdf prewarm state is version-scoped (a stale-version write is a no-op)', async () => {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест prewarm', detailIds: [1] }, requestId: 'pw1' });
    const calc = await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: job.version, requestId: 'pw2' });
    await repo.setPdfPrewarmState({ cutJobId: job.cutJobId, version: calc.version - 1, state: 'ready' });
    expect((await pool.query('SELECT pdf_prewarm_state FROM cut_job WHERE cut_job_id = $1', [job.cutJobId])).rows[0].pdf_prewarm_state).toBe('pending');
    await repo.setPdfPrewarmState({ cutJobId: job.cutJobId, version: calc.version, state: 'ready' });
    expect((await pool.query('SELECT pdf_prewarm_state FROM cut_job WHERE cut_job_id = $1', [job.cutJobId])).rows[0].pdf_prewarm_state).toBe('ready');

    // Recalculating bumps the version and resets the pre-warm state to pending
    // (the new version's PDF is not yet rendered).
    await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: calc.version, requestId: 'pw3' });
    expect((await pool.query('SELECT pdf_prewarm_state FROM cut_job WHERE cut_job_id = $1', [job.cutJobId])).rows[0].pdf_prewarm_state).toBe('pending');
  });

  it('renders per-sheet SVG and on-demand group/job PDFs from stored placements', async () => {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест pdf', detailIds: [1, 2] }, requestId: 'rp1' });
    const calculated = await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: job.version, requestId: 'rp2' });
    const cutGroupId = calculated.groups[0].cutGroupId;

    const svg = await repo.renderSheetSvg({ currentUser: currentUser(), cutGroupId, sheetIndex: 0 });
    expect(svg).toContain('<svg');

    const groupPdf = await repo.renderGroupPdf({ currentUser: currentUser(), cutGroupId });
    expect(groupPdf.subarray(0, 5).toString('latin1')).toBe('%PDF-');

    const jobPdf = await repo.renderJobPdf({ currentUser: currentUser(), cutJobId: job.cutJobId });
    expect(jobPdf.subarray(0, 5).toString('latin1')).toBe('%PDF-');

    await repo.setPdfPrewarmState({ cutJobId: job.cutJobId, version: calculated.version, state: 'ready' });
    const state = await pool.query('SELECT pdf_prewarm_state FROM cut_job WHERE cut_job_id = $1', [job.cutJobId]);
    expect(state.rows[0].pdf_prewarm_state).toBe('ready');
  });

  it('addItems rejects a stale version with 409', async () => {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест' }, requestId: 'r1' });
    await expect(
      repo.addItems({ currentUser: currentUser(), cutJobId: job.cutJobId, version: 99, dto: { detailIds: [1] }, requestId: 'r2' }),
    ).rejects.toMatchObject({ statusCode: 409, code: 'CUT_STALE_VERSION' });
  });

  it('calculate persists cut_group/sheets, audit + bridge rows, and one idempotent outbox row', async () => {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест', detailIds: [1, 2] }, requestId: 'r1' });

    const calculated = await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: job.version, requestId: 'r2' });
    expect(calculated.status).toBe('ready');
    expect(calculated.groups).toHaveLength(1);
    expect(calculated.groups[0].sheets).toHaveLength(1);

    const groups = await pool.query('SELECT count(*)::int AS n FROM cut_group');
    expect(groups.rows[0].n).toBe(1);
    const sheets = await pool.query('SELECT count(*)::int AS n FROM cut_group_sheet');
    expect(sheets.rows[0].n).toBe(1);

    const calcAudit = await pool.query(`SELECT audit_id FROM audit_log WHERE event = 'cut_job.calculated'`);
    expect(calcAudit.rows).toHaveLength(1);
    const bridge = await pool.query('SELECT entity_type FROM audit_log_related_entity WHERE audit_id = $1', [calcAudit.rows[0].audit_id]);
    const types = bridge.rows.map((r) => r.entity_type).sort();
    expect(types).toContain('order');
    expect(types).toContain('sheet_material_type');
    expect(types).toContain('cut_group');

    const outbox = await pool.query(`SELECT idempotency_key FROM outbox_events WHERE event_type = 'cut_job.calculated'`);
    expect(outbox.rows).toHaveLength(1);
    expect(String(outbox.rows[0].idempotency_key)).toMatch(/^cut_job\.calculated:/);

    // Recalculate with the same item set -> same request_hash -> no duplicate outbox row.
    await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: calculated.version, requestId: 'r3' });
    const outbox2 = await pool.query(`SELECT count(*)::int AS n FROM outbox_events WHERE event_type = 'cut_job.calculated'`);
    expect(outbox2.rows[0].n).toBe(1);
  });

  it('two DIFFERENT jobs with the SAME detail set both emit an outbox row (key scoped by job)', async () => {
    const echo = {
      optimize: (req: { stock: Array<{ id: string; width_mm: number; height_mm: number }>; items: Array<{ id: string; width_mm: number; height_mm: number }> }) =>
        Promise.resolve({
          status: 'ok' as const,
          summary: { used_stock_count: 1, waste_percent: 5 },
          solutions: [
            {
              stock_id: req.stock[0].id,
              index: 0,
              width_mm: req.stock[0].width_mm,
              height_mm: req.stock[0].height_mm,
              trim_mm: { left: 10, right: 10, top: 10, bottom: 10 },
              placements: req.items.map((it, i) => ({
                item_id: it.id, instance: 1, x_mm: i * 620, y_mm: 0, width_mm: it.width_mm, height_mm: it.height_mm, rotated: false,
              })),
            },
          ],
        }),
    };
    const repo = new PgCutRepository(database, echo);
    // identical detail set [1] in two separate jobs (allowed post-031) => identical
    // requestHash; the calculated outbox key must be scoped by cutJobId so BOTH emit.
    const jobA = await repo.createJob({ currentUser: currentUser(), dto: { name: 'A', detailIds: [1] }, requestId: 'xa1' });
    const jobB = await repo.createJob({ currentUser: currentUser(), dto: { name: 'B', detailIds: [1] }, requestId: 'xb1' });
    const cA = await repo.calculate({ currentUser: currentUser(), cutJobId: jobA.cutJobId, version: jobA.version, requestId: 'xa2' });
    const cB = await repo.calculate({ currentUser: currentUser(), cutJobId: jobB.cutJobId, version: jobB.version, requestId: 'xb2' });
    expect(cA.status).toBe('ready');
    expect(cB.status).toBe('ready');
    const outbox = await pool.query(`SELECT count(*)::int AS n FROM outbox_events WHERE event_type = 'cut_job.calculated'`);
    expect(outbox.rows[0].n).toBe(2);
  });

  it('freecut failure persists status=failed + reason + audit, and a failed job is recalculable', async () => {
    const failRepo = new PgCutRepository(
      database,
      stubFreecut(() => Promise.reject(new ApiError(504, 'FREECUT_TIMEOUT', 'timeout'))),
    );
    const job = await failRepo.createJob({ currentUser: currentUser(), dto: { name: 'Тест', detailIds: [1] }, requestId: 'r1' });

    await expect(
      failRepo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: job.version, requestId: 'r2' }),
    ).rejects.toMatchObject({ code: 'FREECUT_TIMEOUT' });

    const row = await pool.query(
      'SELECT status, failure_code, failure_reason FROM cut_job WHERE cut_job_id = $1',
      [job.cutJobId],
    );
    expect(row.rows[0].status).toBe('failed');
    expect(row.rows[0].failure_code).toBe('FREECUT_TIMEOUT');
    expect(String(row.rows[0].failure_reason)).toMatch(/не успел/i);
    const failAudit = await pool.query(`SELECT count(*)::int AS n FROM audit_log WHERE event = 'cut_job.calculate_failed'`);
    expect(failAudit.rows[0].n).toBe(1);

    // The failed job is mutable again: a fresh calculate (happy freecut) recovers
    // it to ready on the SAME job and clears the persisted failure reason.
    const failed = await failRepo.getJob({ currentUser: currentUser(), cutJobId: job.cutJobId });
    expect(failed.failureReason).toMatch(/не успел/i);
    const okRepo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const recovered = await okRepo.calculate({
      currentUser: currentUser(),
      cutJobId: job.cutJobId,
      version: failed.version,
      requestId: 'r3',
    });
    expect(recovered.status).toBe('ready');
    expect(recovered.failureCode).toBeNull();
    expect(recovered.failureReason).toBeNull();
  });

  it('listEligibleDetails surfaces no_sheet_spec for an unlinked material', async () => {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const result = await repo.listEligibleDetails({ currentUser: currentUser(), criteria: { orderIds: [9, 10] }, requestId: 'r' });
    // details 1,2 (smt 1), 3 (no sheet spec), 4 (smt 2).
    expect(result.details).toHaveLength(4);
    expect(result.noSheetSpecCount).toBe(1);
    expect(result.details.find((d) => d.orderDetailId === 3)?.ineligibleReason).toBe('no_sheet_spec');
  });

  // --- Finding 2 (MAJOR): /cut-jobs/sheet-types must exclude non-cuttable types ---

  it('listSheetTypesForCut returns ONLY cuttable types (sheet_type 3, is_cuttable=false, must be excluded)', async () => {
    // Schema has 3 types: ids 1 and 2 are cuttable, id 3 is not (is_cuttable=false).
    // The endpoint contract says "Only cuttable sheet types are included."
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const types = await repo.listSheetTypesForCut({ currentUser: currentUser() });
    // Only the two cuttable types should appear.
    expect(types.every((t) => t.isCuttable)).toBe(true);
    expect(types.find((t) => t.sheetMaterialTypeId === 3)).toBeUndefined();
    expect(types.map((t) => t.sheetMaterialTypeId).sort()).toEqual([1, 2]);
  });

  // --- Finding 1 (BLOCKER): create/addItems/removeItem/archive audits must include sheet_material_type related-entity rows ---

  it('createJob audit writes sheet_material_type related-entity rows for the reserved details sheet types', async () => {
    // details 1,2 -> sheet_material_type_id = 1. createJob must emit one sheet_material_type bridge row (distinct).
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    await repo.createJob({ currentUser: currentUser(), dto: { name: 'Аудит создание', detailIds: [1, 2] }, requestId: 'audit-create' });
    const audit = await pool.query(`SELECT audit_id FROM audit_log WHERE event = 'cut_job.created'`);
    expect(audit.rows).toHaveLength(1);
    const bridge = await pool.query(
      `SELECT entity_type, entity_id FROM audit_log_related_entity WHERE audit_id = $1`,
      [audit.rows[0].audit_id],
    );
    const types = bridge.rows.map((r) => r.entity_type);
    expect(types).toContain('order');
    expect(types).toContain('sheet_material_type');
    // sheet_material_type_id = 1 must appear exactly once (distinct).
    const sheetRows = bridge.rows.filter((r) => r.entity_type === 'sheet_material_type');
    expect(sheetRows).toHaveLength(1);
    expect(Number(sheetRows[0].entity_id)).toBe(1);
  });

  it('addItems audit writes sheet_material_type related-entity rows for the newly added detail sheet type', async () => {
    // detail 1 -> sheet type 1; detail 4 -> sheet type 2. Create with detail 1, then add detail 4.
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Аудит добавление', detailIds: [1] }, requestId: 'aa-c' });
    await repo.addItems({ currentUser: currentUser(), cutJobId: job.cutJobId, version: job.version, dto: { detailIds: [4] }, requestId: 'aa-a' });
    const audit = await pool.query(`SELECT audit_id FROM audit_log WHERE event = 'cut_job.item_added'`);
    expect(audit.rows).toHaveLength(1);
    const bridge = await pool.query(
      `SELECT entity_type, entity_id FROM audit_log_related_entity WHERE audit_id = $1`,
      [audit.rows[0].audit_id],
    );
    const sheetRows = bridge.rows.filter((r) => r.entity_type === 'sheet_material_type');
    // Only detail 4 was newly added (detail 1 was a no-op duplicate check — but here it's a new job,
    // so detail 4 is truly new). Its sheet type is 2.
    expect(sheetRows).toHaveLength(1);
    expect(Number(sheetRows[0].entity_id)).toBe(2);
  });

  it('removeItem audit writes sheet_material_type related-entity row for the removed detail sheet type', async () => {
    // detail 1 -> sheet type 1.
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Аудит удаление', detailIds: [1] }, requestId: 'ar-c' });
    const itemId = job.items[0].cutJobItemId;
    await repo.removeItem({ currentUser: currentUser(), cutJobId: job.cutJobId, cutJobItemId: itemId, version: job.version, requestId: 'ar-r' });
    const audit = await pool.query(`SELECT audit_id FROM audit_log WHERE event = 'cut_job.item_removed'`);
    expect(audit.rows).toHaveLength(1);
    const bridge = await pool.query(
      `SELECT entity_type, entity_id FROM audit_log_related_entity WHERE audit_id = $1`,
      [audit.rows[0].audit_id],
    );
    const sheetRows = bridge.rows.filter((r) => r.entity_type === 'sheet_material_type');
    expect(sheetRows).toHaveLength(1);
    expect(Number(sheetRows[0].entity_id)).toBe(1);
  });

  it('archive audit writes sheet_material_type related-entity rows for all released detail sheet types', async () => {
    // details 1 (smt 1) and 4 (smt 2) -> two distinct sheet types.
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Аудит архив', detailIds: [1, 4] }, requestId: 'aw-c' });
    await repo.archive({ currentUser: currentUser(), cutJobId: job.cutJobId, version: job.version, requestId: 'aw-a' });
    const audit = await pool.query(`SELECT audit_id FROM audit_log WHERE event = 'cut_job.archived'`);
    expect(audit.rows).toHaveLength(1);
    const bridge = await pool.query(
      `SELECT entity_type, entity_id FROM audit_log_related_entity WHERE audit_id = $1`,
      [audit.rows[0].audit_id],
    );
    const sheetRows = bridge.rows.filter((r) => r.entity_type === 'sheet_material_type');
    const sheetIds = sheetRows.map((r) => Number(r.entity_id)).sort();
    expect(sheetIds).toEqual([1, 2]);
  });

  // --- setProfile integration tests (Step 8b) ---

  async function makeJob(requestId: string): Promise<{ repo: PgCutRepository; cutJobId: number }> {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест', detailIds: [1, 2] }, requestId });
    return { repo, cutJobId: job.cutJobId };
  }

  it('setProfile persists, bumps version, audits before/after, writes one outbox row', async () => {
    const { repo, cutJobId } = await makeJob('mk-1');
    const profileId = await insertProfile(pool, 'P-int', { kerf_mm: 4 });
    const job = await repo.getJob({ currentUser: currentUser(), cutJobId });
    const updated = await repo.setProfile({ currentUser: currentUser(), cutJobId, paramProfileId: profileId, version: job.version, requestId: 'req-1' });
    expect(updated.paramProfileId).toBe(profileId);
    expect(updated.version).toBe(job.version + 1);
    const audit = await pool.query(`SELECT after_json FROM audit_log WHERE event = 'cut_job.profile_changed' AND entity_id = $1 ORDER BY audit_id DESC LIMIT 1`, [String(cutJobId)]);
    expect(audit.rows[0].after_json).toMatchObject({ paramProfileId: profileId });
    const outbox = await pool.query(`SELECT COUNT(*)::int n FROM outbox_events WHERE idempotency_key = $1`, ['cut_job.profile_changed:' + cutJobId + ':req-1']);
    expect(outbox.rows[0].n).toBe(1);
  });

  it('outbox ON CONFLICT dedupes a duplicate idempotency_key (mechanism)', async () => {
    const { cutJobId } = await makeJob('mk-2');
    // prove the ON CONFLICT DO NOTHING clause: insert the same key twice directly
    const key = 'cut_job.profile_changed:' + cutJobId + ':dup-1';
    const ins = `INSERT INTO outbox_events (event_type, aggregate_type, aggregate_id, payload_json, idempotency_key) VALUES ('cut_job.profile_changed','cut_job',$1,'{}'::jsonb,$2) ON CONFLICT (idempotency_key) DO NOTHING`;
    await pool.query(ins, [String(cutJobId), key]);
    await pool.query(ins, [String(cutJobId), key]);
    const n = await pool.query(`SELECT COUNT(*)::int n FROM outbox_events WHERE idempotency_key = $1`, [key]);
    expect(n.rows[0].n).toBe(1);
  });

  it('setProfile no-op (same profile) does NOT bump version, audit, or write outbox', async () => {
    const { repo, cutJobId } = await makeJob('mk-3');
    const profileId = await insertProfile(pool, 'P-noop', { kerf_mm: 4 });
    const job = await repo.getJob({ currentUser: currentUser(), cutJobId });
    const set = await repo.setProfile({ currentUser: currentUser(), cutJobId, paramProfileId: profileId, version: job.version, requestId: 'noop-a' });
    const auditBefore = await pool.query(`SELECT COUNT(*)::int n FROM audit_log WHERE event = 'cut_job.profile_changed' AND entity_id = $1`, [String(cutJobId)]);
    const again = await repo.setProfile({ currentUser: currentUser(), cutJobId, paramProfileId: profileId, version: set.version, requestId: 'noop-b' });
    expect(again.version).toBe(set.version);
    const auditAfter = await pool.query(`SELECT COUNT(*)::int n FROM audit_log WHERE event = 'cut_job.profile_changed' AND entity_id = $1`, [String(cutJobId)]);
    expect(auditAfter.rows[0].n).toBe(auditBefore.rows[0].n);
    const outbox = await pool.query(`SELECT COUNT(*)::int n FROM outbox_events WHERE idempotency_key = $1`, ['cut_job.profile_changed:' + cutJobId + ':noop-b']);
    expect(outbox.rows[0].n).toBe(0);
  });

  it('rejects an inactive/unknown profile with 422', async () => {
    const { repo, cutJobId } = await makeJob('mk-4');
    const job = await repo.getJob({ currentUser: currentUser(), cutJobId });
    await expect(repo.setProfile({ currentUser: currentUser(), cutJobId, paramProfileId: 10_000_000, version: job.version })).rejects.toMatchObject({ statusCode: 422 });
  });

  it('rejects a stale version with 409', async () => {
    const { repo, cutJobId } = await makeJob('mk-5');
    await expect(repo.setProfile({ currentUser: currentUser(), cutJobId, paramProfileId: null, version: 999 })).rejects.toMatchObject({ statusCode: 409, code: 'CUT_STALE_VERSION' });
  });

  it('reset to default with paramProfileId=null', async () => {
    const { repo, cutJobId } = await makeJob('mk-6');
    const profileId = await insertProfile(pool, 'P-reset', { kerf_mm: 4 });
    const job = await repo.getJob({ currentUser: currentUser(), cutJobId });
    const set = await repo.setProfile({ currentUser: currentUser(), cutJobId, paramProfileId: profileId, version: job.version });
    const reset = await repo.setProfile({ currentUser: currentUser(), cutJobId, paramProfileId: null, version: set.version });
    expect(reset.paramProfileId).toBeNull();
  });

  it('rejects an archived job with 409 (status gate)', async () => {
    const { repo, cutJobId } = await makeJob('mk-7');
    const profileId = await insertProfile(pool, 'P-arch', { kerf_mm: 4 });
    const job = await repo.getJob({ currentUser: currentUser(), cutJobId });
    await repo.archive({ currentUser: currentUser(), cutJobId, version: job.version });
    const archived = await repo.getJob({ currentUser: currentUser(), cutJobId });
    await expect(repo.setProfile({ currentUser: currentUser(), cutJobId, paramProfileId: profileId, version: archived.version }))
      .rejects.toMatchObject({ statusCode: 409 });
  });

  // --- Task 6 integration tests: calculate resolves params from chosen profile ---

  it('calculate uses the chosen profile params (not the create-time default); job.params unchanged', async () => {
    const DISTINCT_KERF = 9;
    const profileId = await insertProfile(pool, 'P-distinct', { kerf_mm: DISTINCT_KERF });
    let captured: ReturnType<typeof import('../application/cut-freecut-mapping').buildOptimizeRequest> | undefined;
    // build the repo with a request-capturing freecut stub, then create a job
    // reserving the harness's eligible details 1/2:
    const repo = new PgCutRepository(database, {
      optimize: (req: ReturnType<typeof import('../application/cut-freecut-mapping').buildOptimizeRequest>) => {
        captured = req;
        return Promise.resolve(happyResponse);
      },
    } as never);
    const created = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест calc', detailIds: [1, 2] }, requestId: 'c1' });
    const cutJobId = created.cutJobId;
    const set = await repo.setProfile({ currentUser: currentUser(), cutJobId, paramProfileId: profileId, version: created.version });
    await repo.calculate({ currentUser: currentUser(), cutJobId, version: set.version });
    expect((captured as { params?: { kerf_mm?: unknown } } | undefined)?.params?.kerf_mm).toBe(DISTINCT_KERF);
    const paramsAfter = await pool.query(`SELECT params FROM cut_job WHERE cut_job_id = $1`, [cutJobId]);
    expect(paramsAfter.rows[0].params?.kerf_mm).not.toBe(DISTINCT_KERF); // snapshot NOT rewritten
  });

  it('calculate REJECTS 422 when the chosen profile was deactivated after selection', async () => {
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const created = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест gone', detailIds: [1, 2] }, requestId: 'g1' });
    const cutJobId = created.cutJobId;
    const profileId = await insertProfile(pool, 'P-gone', { kerf_mm: 9 });
    const set = await repo.setProfile({ currentUser: currentUser(), cutJobId, paramProfileId: profileId, version: created.version });
    await pool.query(`UPDATE cut_param_profiles SET is_active = false WHERE cut_param_profile_id = $1`, [profileId]);
    await expect(repo.calculate({ currentUser: currentUser(), cutJobId, version: set.version }))
      .rejects.toMatchObject({ statusCode: 422, code: 'CUT_PARAM_PROFILE_NOT_FOUND' });
  });

  it('totals: positions excludes deleted details; details=Σqty; area=Σ(area*qty); sheets pre-calc=0', async () => {
    // Seed two details with known area/qty mirroring createSchema's detail-seed INSERT
    // (use fresh detail ids, e.g. 101 area=1.5 qty=2 and 102 area=0.5 qty=3, with the
    // ready status + sheet spec the harness gives details 1/2 so they are eligible).
    await seedDetail(pool, { detailId: 101, area: 1.5, quantity: 2 });
    await seedDetail(pool, { detailId: 102, area: 0.5, quantity: 3 });
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Тест totals', detailIds: [101, 102] }, requestId: 't1' });
    try {
      await pool.query('UPDATE order_details SET delete_flag = true WHERE detail_id = 102');
      const reread = await repo.getJob({ currentUser: currentUser(), cutJobId: job.cutJobId, requestId: 't2' });
      expect(reread.totals.positions).toBe(1);          // deleted (102) excluded
      expect(reread.totals.details).toBe(2);            // only 101's qty
      expect(reread.totals.area).toBeCloseTo(3.0, 2);   // 1.5 * 2
      expect(reread.totals.sheets).toBe(0);
    } finally {
      await pool.query('UPDATE order_details SET delete_flag = false WHERE detail_id = 102');
    }
  });

  // --- listDetailLastReady integration tests (Task 2) ---

  it('listDetailLastReady returns the latest-created ready job per detail, ignoring drafts', async () => {
    // dA = detail 1 (sheet type 1, eligible); dB = detail 2 (sheet type 1, eligible).
    // job1: contains dA, calculated → ready.
    // job2: contains dA, NOT calculated → stays draft.
    // Result: dA maps to job1 (the ready one); dB (no ready job) is absent.
    const dA = 1;
    const dB = 2;
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const job1 = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Ready A', detailIds: [dA] }, requestId: 'ldr-c1' });
    const readyJob = await repo.calculate({ currentUser: currentUser(), cutJobId: job1.cutJobId, version: job1.version, requestId: 'ldr-calc1' });
    expect(readyJob.status).toBe('ready');
    const readyJobId = job1.cutJobId;

    // job2 with the same dA: draft only.
    const job2 = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Draft A', detailIds: [dA] }, requestId: 'ldr-c2' });
    expect(job2.cutJobId).toBeGreaterThan(readyJobId); // sanity

    const res = await repo.listDetailLastReady({ currentUser: currentUser(), detailIds: [dA, dB] });
    const byDetail = new Map(res.details.map((d) => [d.orderDetailId, d]));
    expect(byDetail.get(dA)?.cutJobId).toBe(readyJobId);
    expect(byDetail.has(dB)).toBe(false);
  });

  it('listDetailLastReady excludes items where is_active=false', async () => {
    // dA = detail 1. Create a ready job, then mark dA's item is_active=false.
    // listDetailLastReady must return nothing for dA.
    const dA = 1;
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));
    const job = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Ready inactive', detailIds: [dA] }, requestId: 'ldr-ia-c' });
    await repo.calculate({ currentUser: currentUser(), cutJobId: job.cutJobId, version: job.version, requestId: 'ldr-ia-calc' });

    // Deactivate the item directly (simulates what archive/remove does internally).
    await pool.query(
      `UPDATE cut_job_item SET is_active = false WHERE cut_job_id = $1 AND order_detail_id = $2`,
      [job.cutJobId, dA],
    );

    const res = await repo.listDetailLastReady({ currentUser: currentUser(), detailIds: [dA] });
    expect(res.details).toHaveLength(0);
  });

  it('listDetailLastReady ignores updated_at noise — picks the latest-created ready job (highest id)', async () => {
    // dA = detail 1. Two ready jobs: jobOld (lower id) and jobNew (higher id).
    // After calculation, bump jobOld.updated_at to now() so it is the most-recently-
    // touched — but listDetailLastReady must still return jobNew (higher cut_job_id).
    const dA = 1;
    const repo = new PgCutRepository(database, stubFreecut(() => Promise.resolve(happyResponse)));

    const createdOld = await repo.createJob({ currentUser: currentUser(), dto: { name: 'Old ready', detailIds: [dA] }, requestId: 'ldr-upd-c1' });
    const readyOld = await repo.calculate({ currentUser: currentUser(), cutJobId: createdOld.cutJobId, version: createdOld.version, requestId: 'ldr-upd-calc1' });
    expect(readyOld.status).toBe('ready');
    const jobOldId = createdOld.cutJobId;

    const createdNew = await repo.createJob({ currentUser: currentUser(), dto: { name: 'New ready', detailIds: [dA] }, requestId: 'ldr-upd-c2' });
    const readyNew = await repo.calculate({ currentUser: currentUser(), cutJobId: createdNew.cutJobId, version: createdNew.version, requestId: 'ldr-upd-calc2' });
    expect(readyNew.status).toBe('ready');
    const jobNewId = createdNew.cutJobId;

    expect(jobNewId).toBeGreaterThan(jobOldId); // sanity: identity sequence is monotonic

    // Bump jobOld's updated_at to now() so it is the most-recently-touched job.
    await pool.query(`UPDATE cut_job SET updated_at = now() WHERE cut_job_id = $1`, [jobOldId]);

    // Despite jobOld having the newest updated_at, the HIGHER-id job must win.
    const res = await repo.listDetailLastReady({ currentUser: currentUser(), detailIds: [dA] });
    expect(res.details.find((d) => d.orderDetailId === dA)?.cutJobId).toBe(jobNewId);
  });
});
