import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

// Reservation guard race test (plan §4.2, BLOCKER-1). Proves the partial UNIQUE
// INDEX `uq_cut_job_item_active_detail` is the ONLY enforcement needed: under two
// concurrent transactions inserting the SAME order_detail_id active, exactly one
// commits and the other raises 23505 — NOT relying on an app-layer pre-check.
//
// Gated on CUT_INTEGRATION_DATABASE_URL (falls back to TEST_DATABASE_URL); skips
// cleanly when no database is configured (mirrors the deadline/outbox integration
// pattern). Run: `npm run test:backend:cut-integration` with the env var set.
const databaseUrl =
  process.env.CUT_INTEGRATION_DATABASE_URL ?? process.env.TEST_DATABASE_URL;
const describeIntegration = databaseUrl ? describe : describe.skip;

const schemaName = `cut_reservation_${randomUUID().replaceAll('-', '_')}`;

// Mirrors migration 022's cut_job_item reservation columns + partial unique index.
async function createMinimalSchema(pool: Pool): Promise<void> {
  await pool.query(`
    CREATE TABLE cut_job_item (
      cut_job_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_detail_id BIGINT NOT NULL,
      is_active BOOLEAN NOT NULL DEFAULT true
    );
    CREATE UNIQUE INDEX uq_cut_job_item_active_detail
      ON cut_job_item (order_detail_id)
      WHERE is_active = true;
  `);
}

describeIntegration('cut reservation partial unique index', () => {
  let pool: Pool;

  beforeAll(async () => {
    pool = new Pool({ connectionString: databaseUrl, max: 1 });
    await pool.query(`CREATE SCHEMA ${schemaName}`);
    await pool.query(`SET search_path TO ${schemaName}`);
    await createMinimalSchema(pool);
  });

  afterAll(async () => {
    if (pool) {
      await pool.query(`DROP SCHEMA IF EXISTS ${schemaName} CASCADE`);
      await pool.end();
    }
  });

  it('rejects a duplicate active reservation in the same transaction (23505)', async () => {
    const detailId = 1001;
    await pool.query('BEGIN');
    try {
      await pool.query(
        `INSERT INTO ${schemaName}.cut_job_item (order_detail_id, is_active) VALUES ($1, true)`,
        [detailId],
      );
      await expect(
        pool.query(
          `INSERT INTO ${schemaName}.cut_job_item (order_detail_id, is_active) VALUES ($1, true)`,
          [detailId],
        ),
      ).rejects.toMatchObject({ code: '23505' });
    } finally {
      await pool.query('ROLLBACK');
    }
  });

  it('allows re-reservation after release (is_active=false leaves the partial index)', async () => {
    const detailId = 1002;
    await pool.query(
      `INSERT INTO ${schemaName}.cut_job_item (order_detail_id, is_active) VALUES ($1, true)`,
      [detailId],
    );
    await pool.query(
      `UPDATE ${schemaName}.cut_job_item SET is_active = false WHERE order_detail_id = $1`,
      [detailId],
    );
    await expect(
      pool.query(
        `INSERT INTO ${schemaName}.cut_job_item (order_detail_id, is_active) VALUES ($1, true)`,
        [detailId],
      ),
    ).resolves.toBeTruthy();
  });

  it('two concurrent transactions: exactly one commits, the other gets a unique violation', async () => {
    const detailId = 2002;
    const racePool = new Pool({ connectionString: databaseUrl, max: 2 });
    const clientA = await racePool.connect();
    const clientB = await racePool.connect();
    try {
      await clientA.query(`SET search_path TO ${schemaName}`);
      await clientB.query(`SET search_path TO ${schemaName}`);
      await clientA.query('BEGIN');
      await clientB.query('BEGIN');

      // A takes the index lock first.
      await clientA.query(
        'INSERT INTO cut_job_item (order_detail_id, is_active) VALUES ($1, true)',
        [detailId],
      );

      // B inserts the same detail; it blocks on the index until A resolves.
      const bInsert = clientB
        .query('INSERT INTO cut_job_item (order_detail_id, is_active) VALUES ($1, true)', [
          detailId,
        ])
        .then(() => null)
        .catch((error: unknown) => error);

      await clientA.query('COMMIT');
      const bError = (await bInsert) as { code?: string } | null;

      expect(bError).not.toBeNull();
      expect(bError?.code).toBe('23505');
      await clientB.query('ROLLBACK');

      const { rows } = await clientA.query(
        'SELECT count(*)::int AS n FROM cut_job_item WHERE order_detail_id = $1 AND is_active = true',
        [detailId],
      );
      expect(rows[0].n).toBe(1);
    } finally {
      clientA.release();
      clientB.release();
      await racePool.end();
    }
  });
});
