import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import type { DatabaseService } from '../../../database/database.service';
import type { TransactionClient } from '../../../database/database.types';
import type { CurrentUser } from '../../../permissions/current-user';
import { PgCutConfigAdminRepository } from './pg-cut-config-admin-repository';

const databaseUrl = process.env.CUT_INTEGRATION_DATABASE_URL ?? process.env.TEST_DATABASE_URL;
const describeIntegration = databaseUrl ? describe : describe.skip;
const schemaName = `cut_cfg_${randomUUID().replaceAll('-', '_')}`;

function currentUser(): CurrentUser {
  return { id: '1', username: 'cfg', role: 'operator', permissions: ['cut.view', 'cut.manage'] } as unknown as CurrentUser;
}

async function createSchema(pool: Pool): Promise<void> {
  await pool.query(`
    CREATE FUNCTION set_session_user(p_user TEXT) RETURNS void AS $$ BEGIN PERFORM 1; END; $$ LANGUAGE plpgsql;

    CREATE TABLE material_types (material_type_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT);
    INSERT INTO material_types (material_type_id, name) VALUES (1, 'ЛДСП');

    CREATE TABLE sheet_material_types (
      sheet_material_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(200) NOT NULL UNIQUE,
      material_type_id SMALLINT NOT NULL REFERENCES material_types(material_type_id),
      thickness_mm NUMERIC(10,2) NOT NULL,
      width_mm NUMERIC(10,2) NOT NULL,
      height_mm NUMERIC(10,2) NOT NULL,
      is_active BOOLEAN NOT NULL DEFAULT true,
      created_by BIGINT, edited_by BIGINT,
      created_at TIMESTAMP NOT NULL DEFAULT now(), updated_at TIMESTAMP NOT NULL DEFAULT now(),
      version INTEGER NOT NULL DEFAULT 0
    );
    CREATE TABLE cut_param_profiles (
      cut_param_profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(200) NOT NULL UNIQUE, params JSONB NOT NULL,
      is_default BOOLEAN NOT NULL DEFAULT false, is_active BOOLEAN NOT NULL DEFAULT true,
      created_by BIGINT, edited_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT now(),
      updated_at TIMESTAMP NOT NULL DEFAULT now(), version INTEGER NOT NULL DEFAULT 0
    );
    CREATE UNIQUE INDEX uq_cut_param_profiles_default ON cut_param_profiles (is_default) WHERE is_default = true;
    CREATE TABLE cut_render_presets (
      cut_render_preset_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(100) NOT NULL UNIQUE, target_px INTEGER NOT NULL, background TEXT NOT NULL DEFAULT '#ffffff',
      is_active BOOLEAN NOT NULL DEFAULT true, created_by BIGINT, edited_by BIGINT,
      created_at TIMESTAMP NOT NULL DEFAULT now(), updated_at TIMESTAMP NOT NULL DEFAULT now(), version INTEGER NOT NULL DEFAULT 0
    );
    CREATE TABLE cut_pdf_templates (
      cut_pdf_template_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code VARCHAR(100) NOT NULL UNIQUE,
      name VARCHAR(200) NOT NULL,
      layout JSONB NOT NULL DEFAULT '{}'::jsonb,
      is_active BOOLEAN NOT NULL DEFAULT true,
      created_by BIGINT, edited_by BIGINT,
      created_at TIMESTAMP NOT NULL DEFAULT now(), updated_at TIMESTAMP NOT NULL DEFAULT now(), version INTEGER NOT NULL DEFAULT 0
    );
    CREATE TABLE cut_settings (
      key TEXT PRIMARY KEY, value JSONB NOT NULL, version INTEGER NOT NULL DEFAULT 0,
      updated_by BIGINT, updated_at TIMESTAMP NOT NULL DEFAULT now()
    );
    INSERT INTO cut_settings (key, value) VALUES
      ('grain.rules', '{"textured":{"rotation":"forbid","pattern_direction":"along_height"},"plain":{"rotation":"allow_90","pattern_direction":"none"}}'::jsonb);

    CREATE TABLE audit_log (
      audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      event TEXT NOT NULL, entity_type TEXT, entity_id TEXT,
      user_id BIGINT, username TEXT, role_code TEXT, role TEXT, request_id TEXT, source TEXT,
      related_order_id BIGINT, related_client_id BIGINT, related_payment_id BIGINT,
      related_production_event_id BIGINT, related_deadline_id BIGINT, related_user_id BIGINT,
      status_field TEXT, status_id BIGINT, status_name TEXT, status_code TEXT, stage_code TEXT,
      before_json JSONB, after_json JSONB, diff_json JSONB, metadata_json JSONB,
      created_at TIMESTAMP NOT NULL DEFAULT now()
    );
    CREATE TABLE audit_log_related_entity (
      audit_id BIGINT NOT NULL, entity_type TEXT NOT NULL, entity_id BIGINT NOT NULL,
      UNIQUE (audit_id, entity_type, entity_id)
    );
  `);
}

function makeDatabase(pool: Pool): DatabaseService {
  const query = (text: string, params: readonly unknown[] = []) => pool.query(text, [...params]);
  return {
    isConfigured: true,
    query,
    async transaction<T>(handler: (client: TransactionClient) => Promise<T>): Promise<T> {
      const client = await pool.connect();
      try {
        await client.query('BEGIN');
        await client.query(`SET search_path TO ${schemaName}`);
        const tx: TransactionClient = {
          raw: client as never,
          query: (text: string, params: readonly unknown[] = []) => client.query(text, [...params]),
        };
        const result = await handler(tx);
        await client.query('COMMIT');
        return result;
      } catch (error) {
        await client.query('ROLLBACK').catch(() => undefined);
        throw error;
      } finally {
        client.release();
      }
    },
  } as unknown as DatabaseService;
}

describeIntegration('PgCutConfigAdminRepository (integration)', () => {
  let pool: Pool;
  let repo: PgCutConfigAdminRepository;

  beforeAll(async () => {
    pool = new Pool({ connectionString: databaseUrl, max: 4 });
    await pool.query(`CREATE SCHEMA ${schemaName}`);
    await pool.query(`SET search_path TO ${schemaName}`);
    await createSchema(pool);
    pool.on('connect', (client) => void client.query(`SET search_path TO ${schemaName}`));
    repo = new PgCutConfigAdminRepository(makeDatabase(pool));
  });

  afterAll(async () => {
    if (pool) {
      await pool.query(`DROP SCHEMA IF EXISTS ${schemaName} CASCADE`);
      await pool.end();
    }
  });

  beforeEach(async () => {
    await pool.query('TRUNCATE cut_param_profiles, cut_render_presets, cut_pdf_templates, audit_log, audit_log_related_entity RESTART IDENTITY CASCADE');
  });

  it('updates a setting with a version guard and rejects an invalid grain rule', async () => {
    const updated = await repo.updateSetting({
      currentUser: currentUser(),
      key: 'grain.rules',
      value: { textured: { rotation: 'allow_90', pattern_direction: 'along_width' }, plain: { rotation: 'allow_90', pattern_direction: 'none' } },
      expectedVersion: 0,
    });
    expect(updated.version).toBe(1);

    await expect(
      repo.updateSetting({
        currentUser: currentUser(),
        key: 'grain.rules',
        value: { textured: { rotation: 'spin', pattern_direction: 'none' }, plain: { rotation: 'allow_90', pattern_direction: 'none' } },
        expectedVersion: 1,
      }),
    ).rejects.toMatchObject({ code: 'CUT_INVALID_GRAIN_RULE' });

    await expect(
      repo.updateSetting({ currentUser: currentUser(), key: 'grain.rules', value: { textured: { rotation: 'forbid', pattern_direction: 'none' }, plain: { rotation: 'allow_90', pattern_direction: 'none' } }, expectedVersion: 0 }),
    ).rejects.toMatchObject({ code: 'CUT_STALE_VERSION' });
  });

  it('audits the full param-profile shape (params change is in the diff, not just name)', async () => {
    const created = await repo.upsertParamProfile({ currentUser: currentUser(), input: { name: 'P', params: { kerf_mm: 2 } } });
    await repo.upsertParamProfile({
      currentUser: currentUser(),
      cutParamProfileId: created.cutParamProfileId,
      expectedVersion: 0,
      input: { name: 'P', params: { kerf_mm: 4 } },
    });
    const audit = await pool.query(
      `SELECT after_json, diff_json FROM audit_log WHERE event = 'cut_config.param_profile_upserted' ORDER BY audit_id DESC LIMIT 1`,
    );
    expect(audit.rows[0].after_json.params).toEqual({ kerf_mm: 4 });
    expect(audit.rows[0].diff_json).toHaveProperty('params');
  });

  it('getConfig returns settings + param profiles, render presets and PDF templates', async () => {
    await pool.query(
      `INSERT INTO cut_pdf_templates (code, name) VALUES ('standard', 'Стандартный'), ('bath_profiles', 'Профили ванны')`,
    );
    const config = await repo.getConfig({ currentUser: currentUser() });
    expect(config.settings.map((s) => s.key)).toContain('grain.rules');
    expect(config).toHaveProperty('paramProfiles');
    expect(config).toHaveProperty('renderPresets');
    expect(config).toHaveProperty('pdfTemplates');
    expect(config.pdfTemplates.map((t) => t.code)).toEqual(['bath_profiles', 'standard']);
    expect(config.pdfTemplates[0]).toHaveProperty('layout');
  });

  it('maps a duplicate-name conflict to 409 (not a raw 500)', async () => {
    await repo.upsertParamProfile({ currentUser: currentUser(), input: { name: 'dup', params: { kerf_mm: 2 } } });
    await expect(
      repo.upsertParamProfile({ currentUser: currentUser(), input: { name: 'dup', params: { kerf_mm: 3 } } }),
    ).rejects.toMatchObject({ statusCode: 409, code: 'CUT_CONFIG_CONFLICT' });
  });

  it('records an audited RBAC denial row for cut-config', async () => {
    await repo.recordPermissionDenied({ currentUser: currentUser(), requiredPermissions: ['cut.manage'], requestId: 'rqd' });
    const denied = await pool.query(`SELECT event, entity_type FROM audit_log WHERE event = 'cut_config.permission_denied'`);
    expect(denied.rows).toHaveLength(1);
    expect(denied.rows[0].entity_type).toBe('cut_config');
  });

  it('keeps a single default param profile when a new default is set', async () => {
    const a = await repo.upsertParamProfile({ currentUser: currentUser(), input: { name: 'A', params: { kerf_mm: 2 }, isDefault: true } });
    const b = await repo.upsertParamProfile({ currentUser: currentUser(), input: { name: 'B', params: { kerf_mm: 3 }, isDefault: true } });
    const defaults = await pool.query('SELECT cut_param_profile_id FROM cut_param_profiles WHERE is_default = true');
    expect(defaults.rows).toHaveLength(1);
    expect(Number(defaults.rows[0].cut_param_profile_id)).toBe(b.cutParamProfileId);
    // Profile A was default at creation but must have been cleared when B became default.
    const aNow = await pool.query('SELECT is_default FROM cut_param_profiles WHERE cut_param_profile_id = $1', [a.cutParamProfileId]);
    expect(aNow.rows[0].is_default).toBe(false);
  });
});
