import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

// Placement guard test (migration 031). Placement is NON-exclusive ACROSS jobs but
// unique-and-idempotent WITHIN a job: the same order_detail_id may be active in many
// DIFFERENT jobs, but at most once active in the SAME job (the per-job partial
// unique index `uq_cut_job_item_active_job_detail`). This prevents silently doubling
// the requested cut quantity by re-adding the same line to one job.
//
// Gated on CUT_INTEGRATION_DATABASE_URL (falls back to TEST_DATABASE_URL); skips
// cleanly when no database is configured. Run: `npm run test:backend:cut-integration`.
const databaseUrl =
  process.env.CUT_INTEGRATION_DATABASE_URL ?? process.env.TEST_DATABASE_URL;
const describeIntegration = databaseUrl ? describe : describe.skip;

const schemaName = `cut_reservation_${randomUUID().replaceAll('-', '_')}`;

// Mirrors migration 022 columns + migration 031 per-job unique + lookup indexes.
async function createMinimalSchema(pool: Pool): Promise<void> {
  await pool.query(`
    CREATE TABLE cut_job_item (
      cut_job_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cut_job_id BIGINT NOT NULL,
      order_detail_id BIGINT NOT NULL,
      is_active BOOLEAN NOT NULL DEFAULT true
    );
    CREATE UNIQUE INDEX uq_cut_job_item_active_job_detail
      ON cut_job_item (cut_job_id, order_detail_id)
      WHERE is_active = true;
    CREATE INDEX idx_cut_job_item_order_detail
      ON cut_job_item (order_detail_id);
  `);
}

describeIntegration('cut placement: non-exclusive across jobs, unique within a job (migration 031)', () => {
  let pool: Pool;

  beforeAll(async () => {
    pool = new Pool({ connectionString: databaseUrl, max: 1 });
    await pool.query(`CREATE SCHEMA ${schemaName}`);
    await pool.query(`SET search_path TO ${schemaName}`);
    await createMinimalSchema(pool);
  });

  afterAll(async () => {
    if (pool) {
      await pool.query(`DROP SCHEMA IF EXISTS ${schemaName} CASCADE`);
      await pool.end();
    }
  });

  it('allows the same detail active in DIFFERENT jobs', async () => {
    const detailId = 1001;
    await pool.query(
      `INSERT INTO ${schemaName}.cut_job_item (cut_job_id, order_detail_id, is_active) VALUES (10, $1, true)`,
      [detailId],
    );
    await expect(
      pool.query(
        `INSERT INTO ${schemaName}.cut_job_item (cut_job_id, order_detail_id, is_active) VALUES (11, $1, true)`,
        [detailId],
      ),
    ).resolves.toBeTruthy();

    const { rows } = await pool.query(
      `SELECT count(*)::int AS n FROM ${schemaName}.cut_job_item WHERE order_detail_id = $1 AND is_active = true`,
      [detailId],
    );
    expect(rows[0].n).toBe(2);
  });

  it('rejects the same detail active TWICE in the SAME job (23505)', async () => {
    const detailId = 1002;
    await pool.query(
      `INSERT INTO ${schemaName}.cut_job_item (cut_job_id, order_detail_id, is_active) VALUES (20, $1, true)`,
      [detailId],
    );
    await expect(
      pool.query(
        `INSERT INTO ${schemaName}.cut_job_item (cut_job_id, order_detail_id, is_active) VALUES (20, $1, true)`,
        [detailId],
      ),
    ).rejects.toMatchObject({ code: '23505' });
  });

  it('ON CONFLICT DO NOTHING makes a same-job re-add idempotent (the production path)', async () => {
    const detailId = 1003;
    const insert = `
      INSERT INTO ${schemaName}.cut_job_item (cut_job_id, order_detail_id, is_active)
      VALUES (30, $1, true)
      ON CONFLICT (cut_job_id, order_detail_id) WHERE is_active = true DO NOTHING
    `;
    await pool.query(insert, [detailId]);
    await expect(pool.query(insert, [detailId])).resolves.toBeTruthy(); // no throw
    const { rows } = await pool.query(
      `SELECT count(*)::int AS n FROM ${schemaName}.cut_job_item WHERE cut_job_id = 30 AND order_detail_id = $1 AND is_active = true`,
      [detailId],
    );
    expect(rows[0].n).toBe(1);
  });
});
