import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

// Non-exclusive placement test (migration 031). Proves the OLD partial UNIQUE
// reservation guard is gone: the SAME order_detail_id may be active in any number
// of cut_job_item rows (i.e. placed in many jobs at once). The non-unique lookup
// index `idx_cut_job_item_active_order_detail` keeps "which jobs is this detail in"
// fast WITHOUT enforcing exclusivity.
//
// Gated on CUT_INTEGRATION_DATABASE_URL (falls back to TEST_DATABASE_URL); skips
// cleanly when no database is configured. Run: `npm run test:backend:cut-integration`.
const databaseUrl =
  process.env.CUT_INTEGRATION_DATABASE_URL ?? process.env.TEST_DATABASE_URL;
const describeIntegration = databaseUrl ? describe : describe.skip;

const schemaName = `cut_reservation_${randomUUID().replaceAll('-', '_')}`;

// Mirrors migration 022 columns + migration 031 NON-unique lookup index.
async function createMinimalSchema(pool: Pool): Promise<void> {
  await pool.query(`
    CREATE TABLE cut_job_item (
      cut_job_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_detail_id BIGINT NOT NULL,
      is_active BOOLEAN NOT NULL DEFAULT true
    );
    CREATE INDEX idx_cut_job_item_active_order_detail
      ON cut_job_item (order_detail_id)
      WHERE is_active = true;
  `);
}

describeIntegration('cut placement is non-exclusive (migration 031)', () => {
  let pool: Pool;

  beforeAll(async () => {
    pool = new Pool({ connectionString: databaseUrl, max: 1 });
    await pool.query(`CREATE SCHEMA ${schemaName}`);
    await pool.query(`SET search_path TO ${schemaName}`);
    await createMinimalSchema(pool);
  });

  afterAll(async () => {
    if (pool) {
      await pool.query(`DROP SCHEMA IF EXISTS ${schemaName} CASCADE`);
      await pool.end();
    }
  });

  it('allows the same detail active in multiple rows (no unique violation)', async () => {
    const detailId = 1001;
    await pool.query(
      `INSERT INTO ${schemaName}.cut_job_item (order_detail_id, is_active) VALUES ($1, true)`,
      [detailId],
    );
    await expect(
      pool.query(
        `INSERT INTO ${schemaName}.cut_job_item (order_detail_id, is_active) VALUES ($1, true)`,
        [detailId],
      ),
    ).resolves.toBeTruthy();

    const { rows } = await pool.query(
      `SELECT count(*)::int AS n FROM ${schemaName}.cut_job_item WHERE order_detail_id = $1 AND is_active = true`,
      [detailId],
    );
    expect(rows[0].n).toBe(2);
  });

  it('two concurrent transactions: BOTH commit the same active detail', async () => {
    const detailId = 2002;
    const racePool = new Pool({ connectionString: databaseUrl, max: 2 });
    const clientA = await racePool.connect();
    const clientB = await racePool.connect();
    try {
      await clientA.query(`SET search_path TO ${schemaName}`);
      await clientB.query(`SET search_path TO ${schemaName}`);
      await clientA.query('BEGIN');
      await clientB.query('BEGIN');

      await clientA.query('INSERT INTO cut_job_item (order_detail_id, is_active) VALUES ($1, true)', [detailId]);
      // B inserts the same detail concurrently; with no unique index it does NOT block.
      await clientB.query('INSERT INTO cut_job_item (order_detail_id, is_active) VALUES ($1, true)', [detailId]);

      await clientA.query('COMMIT');
      await clientB.query('COMMIT');

      const { rows } = await clientA.query(
        'SELECT count(*)::int AS n FROM cut_job_item WHERE order_detail_id = $1 AND is_active = true',
        [detailId],
      );
      expect(rows[0].n).toBe(2);
    } finally {
      clientA.release();
      clientB.release();
      await racePool.end();
    }
  });
});
