/**
 * seed-vacuum-migration.integration.ts
 *
 * Executable migration integration test for 037 + 038.
 *
 * Gated by CUT_INTEGRATION_DATABASE_URL or TEST_DATABASE_URL. When neither is
 * set all tests are skipped (describe.skip). The orchestrator runs this against
 * erp_test using the .env secret.
 *
 * Collected by vitest.cut-integration.config.ts via:
 *   include: ['backend/src/modules/cut/adapters/*.integration.ts']
 *
 * What it verifies (R2/R3/R4 from the Codex review):
 *   - Idempotency: running 038 twice yields exactly ONE row per seed_key.
 *   - Exact params: each seeded row has layout_mode='vacuum_table' + the correct
 *     vacuum.direction (guards against a typo'd seeded direction — R4 MAJOR).
 *   - Seeded rows is_default=false, is_active=true.
 *   - No clobber/no adoption: an unrelated pre-existing row (different name,
 *     NULL seed_key, custom params) is completely untouched after 038.
 *   - Rollback order (038-down then 037-down): only the 3 seed rows are deleted,
 *     the unrelated row remains, 037-down drops the seed_key column cleanly.
 *   - Name-collision → loud abort: a NON-seed row holding a seed name causes the
 *     INSERT to fail on the unique-name constraint (038 must not claim it silently).
 */
import { readFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

const databaseUrl =
  process.env.CUT_INTEGRATION_DATABASE_URL ?? process.env.TEST_DATABASE_URL;
const describeIntegration = databaseUrl ? describe : describe.skip;

// Each test suite run gets its own throwaway schema so parallel runs don't
// collide and so we never touch the real public schema.
const schemaName = `seed_vac_${randomUUID().replaceAll('-', '_')}`;

// ── SQL helpers ──────────────────────────────────────────────────────────────

function readMigration(filename: string): string {
  return readFileSync(
    new URL(
      `../../../../db/migrations/${filename}`,
      import.meta.url,
    ),
    'utf8',
  );
}

/** Return only the live (non-Down) section of a migration SQL file. */
function liveSql(sql: string): string {
  return sql.split(/--[^\n]*Down/i)[0];
}

/** Return only the Down section comment body (strip leading `-- ` from each line). */
function downSql(sql: string): string {
  const parts = sql.split(/--[^\n]*Down/i);
  if (parts.length < 2) return '';
  // Each Down statement is on its own comment line: `--   DELETE ...`
  return parts[1]
    .split('\n')
    .filter((l) => l.trim().startsWith('--'))
    .map((l) => l.replace(/^\s*--\s?/, ''))
    .join('\n');
}

// ── Base schema (migration 023 shape of cut_param_profiles only) ─────────────

async function createBaseSchema(pool: Pool): Promise<void> {
  await pool.query(`
    CREATE TABLE cut_param_profiles (
      cut_param_profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(200) NOT NULL,
      params JSONB NOT NULL,
      is_default BOOLEAN NOT NULL DEFAULT false,
      is_active BOOLEAN NOT NULL DEFAULT true,
      created_by BIGINT,
      edited_by BIGINT,
      created_at TIMESTAMP NOT NULL DEFAULT now(),
      updated_at TIMESTAMP NOT NULL DEFAULT now(),
      version INTEGER NOT NULL DEFAULT 0,
      CONSTRAINT uq_cut_param_profiles_name UNIQUE (name)
    );
    CREATE UNIQUE INDEX uq_cut_param_profiles_default
      ON cut_param_profiles (is_default)
      WHERE is_default = true;
  `);
}

// ── Integration test suite ────────────────────────────────────────────────────

describeIntegration('038_seed_vacuum_cut_profiles (integration)', () => {
  let pool: Pool;

  beforeAll(async () => {
    pool = new Pool({ connectionString: databaseUrl, max: 2 });
    await pool.query(`CREATE SCHEMA ${schemaName}`);
    // All subsequent queries on this pool go into the temp schema.
    pool.on('connect', (client) => void client.query(`SET search_path TO ${schemaName}`));
    await pool.query(`SET search_path TO ${schemaName}`);
    await createBaseSchema(pool);
  });

  afterAll(async () => {
    if (pool) {
      await pool.query(`DROP SCHEMA IF EXISTS ${schemaName} CASCADE`);
      await pool.end();
    }
  });

  // ── Main: idempotency + exact params + unrelated row untouched ───────────

  it('idempotent: 1 row per seed_key after 2 runs; exact params; is_default=false; unrelated row untouched', async () => {
    const sql037 = readMigration('037_cut_param_profile_seed_key.sql');
    const sql038 = readMigration('038_seed_vacuum_cut_profiles.sql');

    // Step 1: apply migration 037 (adds seed_key column + partial unique index)
    await pool.query(liveSql(sql037));

    // Step 2: insert one UNRELATED pre-existing row with a custom name and NULL
    // seed_key to prove that 038 never clobbers or claims non-seed rows.
    const unrelatedResult = await pool.query(`
      INSERT INTO cut_param_profiles (name, params, seed_key, is_default, is_active)
      VALUES (
        'E2E-Тест unrelated profile',
        '{"kerf_mm":3,"layout_mode":"guillotine","custom":true}'::jsonb,
        NULL,
        false,
        false
      )
      RETURNING cut_param_profile_id
    `);
    const unrelatedId = Number(unrelatedResult.rows[0].cut_param_profile_id);

    // Step 3: apply migration 038 ONCE
    await pool.query(liveSql(sql038));

    // Step 4: apply migration 038 a SECOND TIME (idempotency check)
    await pool.query(liveSql(sql038));

    // ── Idempotency: exactly 1 row per seed_key ──────────────────────────────
    const counts = await pool.query(`
      SELECT seed_key, COUNT(*) AS cnt
      FROM cut_param_profiles
      WHERE seed_key IN ('vacuum_optimal', 'vacuum_width', 'vacuum_height')
      GROUP BY seed_key
    `);
    expect(counts.rows).toHaveLength(3);
    for (const row of counts.rows) {
      expect(Number(row.cnt)).toBe(1);
    }

    // ── Exact params: layout_mode + vacuum.direction ─────────────────────────
    const profiles = await pool.query(`
      SELECT
        seed_key,
        params->>'layout_mode'              AS layout_mode,
        params->'vacuum'->>'direction'      AS direction,
        is_default,
        is_active
      FROM cut_param_profiles
      WHERE seed_key IN ('vacuum_optimal', 'vacuum_width', 'vacuum_height')
    `);
    const byKey = Object.fromEntries(profiles.rows.map((r) => [r.seed_key, r]));

    expect(byKey['vacuum_optimal'].layout_mode).toBe('vacuum_table');
    expect(byKey['vacuum_optimal'].direction).toBe('optimal');
    expect(byKey['vacuum_optimal'].is_default).toBe(false);
    expect(byKey['vacuum_optimal'].is_active).toBe(true);

    expect(byKey['vacuum_width'].layout_mode).toBe('vacuum_table');
    expect(byKey['vacuum_width'].direction).toBe('width');
    expect(byKey['vacuum_width'].is_default).toBe(false);
    expect(byKey['vacuum_width'].is_active).toBe(true);

    expect(byKey['vacuum_height'].layout_mode).toBe('vacuum_table');
    expect(byKey['vacuum_height'].direction).toBe('height');
    expect(byKey['vacuum_height'].is_default).toBe(false);
    expect(byKey['vacuum_height'].is_active).toBe(true);

    // ── Unrelated row: completely untouched ──────────────────────────────────
    const unrelated = await pool.query(
      `SELECT cut_param_profile_id, params, is_active, seed_key
       FROM cut_param_profiles
       WHERE name = 'E2E-Тест unrelated profile'`,
    );
    expect(unrelated.rows).toHaveLength(1);
    const u = unrelated.rows[0];
    expect(Number(u.cut_param_profile_id)).toBe(unrelatedId);
    expect(u.params).toMatchObject({ kerf_mm: 3, custom: true });
    expect(u.is_active).toBe(false); // was inserted as false, must remain false
    expect(u.seed_key).toBeNull();   // no seed_key was assigned

    // ── Rollback: 038-down then 037-down ────────────────────────────────────
    // Execute 038 Down (DELETE by seed_key)
    const down038 = downSql(sql038);
    await pool.query(down038);

    // Assert: only the 3 seeded rows are gone; unrelated row remains.
    const afterDown038 = await pool.query(
      `SELECT cut_param_profile_id FROM cut_param_profiles WHERE seed_key IN ('vacuum_optimal','vacuum_width','vacuum_height')`,
    );
    expect(afterDown038.rows).toHaveLength(0);

    const unrelatedAfterDown038 = await pool.query(
      `SELECT cut_param_profile_id FROM cut_param_profiles WHERE name = 'E2E-Тест unrelated profile'`,
    );
    expect(unrelatedAfterDown038.rows).toHaveLength(1);

    // Execute 037 Down (DROP INDEX + DROP COLUMN)
    const down037 = downSql(sql037);
    await pool.query(down037);

    // Assert: seed_key column no longer exists.
    const colCheck = await pool.query(`
      SELECT column_name
      FROM information_schema.columns
      WHERE table_schema = $1
        AND table_name = 'cut_param_profiles'
        AND column_name = 'seed_key'
    `, [schemaName]);
    expect(colCheck.rows).toHaveLength(0);
  });

  // ── Name-collision: fresh state, pre-insert a name-stealing row ─────────

  it('name-collision: 038 fails loudly when a non-seed row holds a seed name', async () => {
    // Use a fresh sub-schema to avoid state from the previous test.
    const colSchemaName = `seed_vac_col_${randomUUID().replaceAll('-', '_')}`;
    const colPool = new Pool({ connectionString: databaseUrl, max: 1 });
    colPool.on('connect', (client) => void client.query(`SET search_path TO ${colSchemaName}`));

    try {
      await colPool.query(`CREATE SCHEMA ${colSchemaName}`);
      await colPool.query(`SET search_path TO ${colSchemaName}`);
      await createBaseSchema(colPool);

      // Apply 037 first (038 requires seed_key column).
      const sql037 = readMigration('037_cut_param_profile_seed_key.sql');
      await colPool.query(liveSql(sql037));

      // Insert a NON-seed row that holds one of the seed names (simulates a user
      // who already created a profile with the same display name).
      await colPool.query(`
        INSERT INTO cut_param_profiles (name, params, seed_key, is_default, is_active)
        VALUES (
          'E2E Вакуумный стол (авто)',
          '{"kerf_mm":5,"layout_mode":"guillotine"}'::jsonb,
          NULL,
          false,
          true
        )
      `);

      // Now manually patch the name to match the seed name to trigger the collision.
      // (We insert with a temp name above to avoid an issue if the seed name is
      // already reserved by some check. Then we update to the exact seed name.)
      await colPool.query(`
        UPDATE cut_param_profiles
        SET name = 'Вакуумный стол (авто)'
        WHERE name = 'E2E Вакуумный стол (авто)'
      `);

      // Running 038 now must throw a unique-violation (23505) on the name constraint.
      const sql038 = readMigration('038_seed_vacuum_cut_profiles.sql');
      await expect(colPool.query(liveSql(sql038))).rejects.toMatchObject({
        code: '23505', // PostgreSQL unique_violation
      });
    } finally {
      await colPool.query(`DROP SCHEMA IF EXISTS ${colSchemaName} CASCADE`);
      await colPool.end();
    }
  });
});
