import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import type { TransactionClient } from '../../../database/database.types';
import { loadOrderAssignedUserIds } from './pg-production-action-repository';

// Real-DB proof that loadOrderAssignedUserIds enforces the security-critical SQL
// filters the unit mock cannot (delete_flag = false, users.is_active = true,
// responsible_employee_id IS NOT NULL). Gated on
// PRODUCTION_ACTIONS_INTEGRATION_DATABASE_URL (falls back to TEST_DATABASE_URL);
// skips cleanly without a database. Throwaway schema only.
const databaseUrl =
  process.env.PRODUCTION_ACTIONS_INTEGRATION_DATABASE_URL ?? process.env.TEST_DATABASE_URL;
const describeIntegration = databaseUrl ? describe : describe.skip;

const schemaName = `prodact_assign_${randomUUID().replaceAll('-', '_')}`;

const ORDER_ID = 15;
const U1_USER_ID = 20; // active user on a non-deleted workshop -> should resolve
const U2_USER_ID = 21; // inactive user -> must be excluded

async function createSchema(pool: Pool): Promise<void> {
  await pool.query('CREATE TABLE employees (employee_id BIGINT PRIMARY KEY)');
  await pool.query(
    'CREATE TABLE users (user_id BIGINT PRIMARY KEY, employee_id BIGINT, is_active BOOLEAN NOT NULL DEFAULT true)',
  );
  await pool.query(
    `CREATE TABLE order_workshops (
       order_workshop_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       order_id BIGINT NOT NULL,
       responsible_employee_id BIGINT,
       delete_flag BOOLEAN NOT NULL DEFAULT false
     )`,
  );

  await pool.query('INSERT INTO employees (employee_id) VALUES (1), (2)');
  await pool.query(
    'INSERT INTO users (user_id, employee_id, is_active) VALUES ($1, 1, true), ($2, 2, false)',
    [U1_USER_ID, U2_USER_ID],
  );
  // (a) active user on a non-deleted workshop -> resolved
  // (b) soft-deleted workshop (same responsible) -> excluded
  // (c) responsible mapped to an inactive user -> excluded
  // (d) null responsible -> excluded
  await pool.query(
    `INSERT INTO order_workshops (order_id, responsible_employee_id, delete_flag) VALUES
       ($1, 1, false),
       ($1, 1, true),
       ($1, 2, false),
       ($1, NULL, false)`,
    [ORDER_ID],
  );
}

describeIntegration('loadOrderAssignedUserIds (real DB filters)', () => {
  let pool: Pool;

  beforeAll(async () => {
    pool = new Pool({ connectionString: databaseUrl, max: 4 });
    await pool.query(`CREATE SCHEMA ${schemaName}`);
    await pool.query(`SET search_path TO ${schemaName}`);
    pool.on('connect', (client) => void client.query(`SET search_path TO ${schemaName}`));
    await createSchema(pool);
  });

  afterAll(async () => {
    if (pool) {
      await pool.query(`DROP SCHEMA IF EXISTS ${schemaName} CASCADE`);
      await pool.end();
    }
  });

  it('filters soft-deleted workshops, inactive users, and null responsibles', async () => {
    const ids = await loadOrderAssignedUserIds(
      pool as unknown as TransactionClient,
      ORDER_ID,
    );
    expect(ids).toEqual([String(U1_USER_ID)]);
    expect(ids).not.toContain(String(U2_USER_ID));
  });
});
