import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { Pool, type PoolClient, type QueryResultRow } from 'pg';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import { ApiError } from '../../common/errors/api-error';
import type { DatabaseService } from '../../database/database.service';
import type { CurrentUser } from '../../permissions/current-user';
import { normalizeClientPhone } from '../whatsapp/order-send/order-send-phone';
import { PartyContactsRepository } from './party-contacts.repository';
import { SupplierCounterpartyRepository, parseRefKey1c } from './supplier-counterparty.repository';

const databaseUrl = process.env.TEST_DATABASE_URL;
const admin: CurrentUser = { id: '11', username: 'contacts-admin', role: 'admin', roleId: 1, permissions: ['suppliers.manage'] };
const REF = (n: number) => `00000000-0000-4000-8000-${String(n).padStart(12, '0')}`;

describe.skipIf(!databaseUrl)('party contacts and the supplier ↔ 1C counterparty link (PostgreSQL, isolated schema)', () => {
  const schema = `e2e_party_contacts_${randomUUID().replaceAll('-', '')}`;
  let pool: Pool;
  let client: PoolClient;
  let contacts: PartyContactsRepository;
  let counterparties: SupplierCounterpartyRepository;
  const q = <T extends QueryResultRow = QueryResultRow>(text: string, params: unknown[] = []) => client.query<T>(text, params);
  const code = (promise: Promise<unknown>) => promise.then(() => 'ok', (error: unknown) => (error instanceof ApiError ? error.code : String(error)));
  const migration = () => readFile(new URL('../../../db/migrations/236_party_contacts.sql', import.meta.url), 'utf8');

  beforeAll(async () => {
    pool = new Pool({ connectionString: databaseUrl, max: 4 });
    pool.on('connect', (connection) => { void connection.query(`SET search_path="${schema}",public`); });
    client = await pool.connect();
    await q(`CREATE SCHEMA IF NOT EXISTS "${schema}"`);
    await q(`SET search_path="${schema}",public`);
    // Extensions live in public: created inside a test schema they vanish with it (or hide in a leftover one).
    await q(`CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public; CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public`);
    // Owner tables with the real column types (smallint keys, citext client name, uuid 1C key with its unique index).
    await q(`CREATE TABLE users(user_id bigint PRIMARY KEY, username citext);
      INSERT INTO users VALUES (11, 'contacts-admin'), (12, 'other-admin');
      CREATE TABLE audit_log(audit_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),event text NOT NULL,entity_type text,entity_id text,
        user_id bigint REFERENCES users(user_id) ON DELETE SET NULL,
        username text,role_code text,role text,request_id text NOT NULL,source text,related_order_id bigint,related_client_id bigint,related_payment_id bigint,
        related_production_event_id bigint,related_deadline_id bigint,related_user_id bigint,status_field text,status_id bigint,status_name text,status_code text,
        stage_code text,before_json jsonb,after_json jsonb,diff_json jsonb,metadata_json jsonb,created_at timestamptz DEFAULT clock_timestamp());
      CREATE TABLE audit_log_related_entity(audit_id uuid NOT NULL,entity_type text NOT NULL,entity_id bigint NOT NULL,PRIMARY KEY(audit_id,entity_type,entity_id));
      CREATE TABLE suppliers(supplier_id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, supplier_name varchar(250) NOT NULL UNIQUE,
        phone varchar(50), is_active boolean NOT NULL DEFAULT true, ref_key_1c uuid, created_by bigint, edited_by bigint, updated_at timestamptz DEFAULT now());
      CREATE UNIQUE INDEX idx_suppliers__ref_key_1c ON suppliers(ref_key_1c) WHERE ref_key_1c IS NOT NULL;
      CREATE TABLE vendors(vendor_id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, vendor_name varchar(250) NOT NULL);
      CREATE TABLE clients(client_id bigint PRIMARY KEY, client_name citext NOT NULL);
      -- Stands for the CRM-sync trigger of clients: any UPDATE of a client row is counted.
      CREATE TABLE client_updates(client_id bigint);
      CREATE FUNCTION count_client_update() RETURNS trigger AS $$ BEGIN INSERT INTO client_updates VALUES (NEW.client_id); RETURN NEW; END $$ LANGUAGE plpgsql;
      CREATE TRIGGER trg_crm_sync_clients AFTER UPDATE ON clients FOR EACH ROW EXECUTE FUNCTION count_client_update();
      CREATE TABLE onec_etl_mirror_rows(source_id bigint, entity_code text, source_key text, deleted boolean NOT NULL DEFAULT false,
        data jsonb NOT NULL, missing_in_source_at timestamptz);
      CREATE TABLE resource_suppliers(supplier_key text, counterparty_name text);
      INSERT INTO suppliers(supplier_id, supplier_name, phone) VALUES (1, 'Тест Поставщик Один', '+7 (701) 555-01-01'), (2, 'Тест Поставщик Два', 'офис, доб. 12'),
        (3, 'Тест Поставщик Три', NULL);
      -- Phones for the backfill parity check (ids 100+): what the backend normalizer reads must be copied, the rest must not.
      INSERT INTO suppliers(supplier_id, supplier_name, phone) SELECT 100 + n, 'Тест Телефон ' || n, p
        FROM unnest(ARRAY['87015550101 доб. 12', 'Тел: +7 (701) 555-01-01', '8 701 555 01 01, 87771234567', '8(701)555-01-01', '+77015550101-897',
          '7 701 555 01 01 вн 5', '8701555010', '870155501011', '+7 701 555 01 0a', '  87015550102  ', '8-701-555-01-03/04', 'нет']) WITH ORDINALITY AS t(p, n);
      SELECT setval(pg_get_serial_sequence('suppliers', 'supplier_id'), 200);
      INSERT INTO vendors(vendor_id, vendor_name) VALUES (1, 'Тест Производитель');
      INSERT INTO clients VALUES (1, 'Тест Клиент');`);
    await q(await migration());
    const database = {
      isConfigured: true,
      query: <T extends QueryResultRow = QueryResultRow>(text: string, params: readonly unknown[] = []) => pool.query<T>(text, [...params]),
      transaction: async <T>(handler: (tx: unknown) => Promise<T>) => {
        const connection = await pool.connect();
        try {
          await connection.query(`SET search_path="${schema}",public`);
          await connection.query('BEGIN');
          try {
            const value = await handler({ query: <R extends QueryResultRow = QueryResultRow>(text: string, params: readonly unknown[] = []) => connection.query<R>(text, [...params]) });
            await connection.query('COMMIT');
            return value;
          } catch (error) {
            await connection.query('ROLLBACK');
            throw error;
          }
        } finally {
          connection.release();
        }
      },
    } as unknown as DatabaseService;
    contacts = new PartyContactsRepository(database);
    counterparties = new SupplierCounterpartyRepository(database);
  }, 60_000);

  afterAll(async () => {
    if (client) {
      try { await q(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`); } finally { client.release(); }
    }
    await pool?.end();
  });

  beforeEach(async () => {
    await q(`DELETE FROM vendor_contacts; DELETE FROM client_contacts; DELETE FROM supplier_contacts WHERE supplier_id NOT IN (1) AND supplier_id < 100;
      DELETE FROM party_contact_versions; DELETE FROM client_updates; DELETE FROM audit_log_related_entity; DELETE FROM audit_log;
      DELETE FROM supplier_contacts WHERE supplier_id > 200; DELETE FROM suppliers WHERE supplier_id > 200; UPDATE suppliers SET ref_key_1c = NULL;
      DELETE FROM onec_etl_mirror_rows; DELETE FROM resource_suppliers;`);
  });

  it('the migration turns a readable supplier phone into its primary contact, leaves the rest, and reruns cleanly', async () => {
    const copied = (await q(`SELECT supplier_id, value, value_normalized, is_primary FROM supplier_contacts WHERE supplier_id < 100 ORDER BY supplier_id`)).rows;
    expect(copied).toEqual([{ supplier_id: 1, value: '+7 (701) 555-01-01', value_normalized: '77015550101', is_primary: true }]);
    const before = (await q(`SELECT count(*)::int n FROM supplier_contacts`)).rows[0].n;
    await q(await migration());
    expect((await q(`SELECT count(*)::int n FROM supplier_contacts`)).rows[0].n).toBe(before);
    // The copied contact is an ordinary one: the set starts at version 0 and is edited by the command.
    const set = await contacts.get('supplier', 1);
    expect(set).toMatchObject({ version: 0, contacts: [{ kind: 'phone', valueNormalized: '77015550101', isPrimary: true }] });
    expect((await q(`SELECT phone FROM suppliers WHERE supplier_id = 2`)).rows[0].phone).toBe('офис, доб. 12');
  });

  it('the backfill reads phones exactly as the backend normalizer: every copied value can be saved again, the rest is left', async () => {
    const rows = (await q<{ supplier_id: number; phone: string; value: string | null; value_normalized: string | null }>(
      `SELECT s.supplier_id, s.phone, c.value, c.value_normalized FROM suppliers s LEFT JOIN supplier_contacts c ON c.supplier_id = s.supplier_id
        WHERE s.supplier_id BETWEEN 100 AND 200 ORDER BY s.supplier_id`)).rows;
    expect(rows.length).toBe(12);
    for (const row of rows) {
      let expected: string | null = null;
      try { expected = normalizeClientPhone(row.phone); } catch { expected = null; }
      expect([row.phone, row.value_normalized]).toEqual([row.phone, expected]);
      if (expected) expect(normalizeClientPhone(row.value)).toBe(expected);
    }
    expect(rows.filter((row) => row.value_normalized).length).toBe(7);
    // A copied phone with an extension is an ordinary contact: the set saves again with an email added.
    const withExtension = rows.find((row) => row.phone === '87015550101 доб. 12')!;
    const set = await contacts.get('supplier', withExtension.supplier_id);
    const saved = await contacts.replace('supplier', withExtension.supplier_id, set.version, [
      ...set.contacts.map((contact) => ({ contactId: contact.contactId, kind: contact.kind, value: contact.value, isPrimary: contact.isPrimary, note: contact.note })),
      { contactId: null, kind: 'email' as const, value: 'supplier@test.kz', isPrimary: true, note: null },
    ], admin, 'req-resave');
    expect(saved.contacts).toHaveLength(2);
  });

  it('a rerun of the migration never brings back a contact the user removed', async () => {
    const supplierId = 110;
    const set = await contacts.get('supplier', supplierId);
    expect(set.contacts).toHaveLength(1);
    await contacts.replace('supplier', supplierId, set.version, [], admin, 'req-clear');
    await q(await migration());
    expect(await contacts.get('supplier', supplierId)).toMatchObject({ version: 1, contacts: [] });
  });

  it('replaces a vendor set under its version: ids kept, values swapped, a stale version and a repeated id refused', async () => {
    const first = await contacts.replace('vendor', 1, 0, [
      { contactId: null, kind: 'phone', value: '87015550101', isPrimary: true, note: null },
      { contactId: null, kind: 'phone', value: '87015550102', isPrimary: false, note: 'склад' },
      { contactId: null, kind: 'email', value: 'Sales@Vendor.kz', isPrimary: false, note: null },
    ], admin, 'req-v1');
    expect(first.version).toBe(1);
    const [a, b] = first.contacts.filter((contact) => contact.kind === 'phone');
    const swapped = await contacts.replace('vendor', 1, 1, [
      { contactId: a.contactId, kind: 'phone', value: b.value, isPrimary: false, note: null },
      { contactId: b.contactId, kind: 'phone', value: a.value, isPrimary: true, note: null },
    ], admin, 'req-v2');
    expect(swapped.version).toBe(2);
    expect(Object.fromEntries(swapped.contacts.map((contact) => [contact.contactId, [contact.valueNormalized, contact.isPrimary]]))).toEqual({
      [a.contactId]: [b.valueNormalized, false], [b.contactId]: [a.valueNormalized, true] });
    expect(await code(contacts.replace('vendor', 1, 1, [], admin, 'req-stale'))).toBe('PARTY_CONTACTS_VERSION_CONFLICT');
    expect(await code(contacts.replace('vendor', 1, 2, [
      { contactId: a.contactId, kind: 'phone', value: '87015550101', isPrimary: true, note: null },
      { contactId: a.contactId, kind: 'phone', value: '87015550109', isPrimary: false, note: null },
    ], admin, 'req-dup'))).toBe('PARTY_CONTACT_INVALID');
    expect((await contacts.get('vendor', 1)).version).toBe(2);
    expect(await code(contacts.get('vendor', 404))).toBe('VENDOR_NOT_FOUND');
    expect((await contacts.listFor('vendor', [1])).get(1)).toHaveLength(2);
  });

  it('two editors of one set: one wins, the other gets a conflict', async () => {
    const results = await Promise.all([
      code(contacts.replace('supplier', 3, 0, [{ contactId: null, kind: 'phone', value: '87015550111', isPrimary: true, note: null }], admin, 'req-a')),
      code(contacts.replace('supplier', 3, 0, [{ contactId: null, kind: 'phone', value: '87015550112', isPrimary: true, note: null }], admin, 'req-b')),
    ]);
    expect(results.sort()).toEqual(['PARTY_CONTACTS_VERSION_CONFLICT', 'ok']);
    expect((await contacts.get('supplier', 3)).contacts).toHaveLength(1);
  });

  it('a client keeps emails and Telegram here, never phones; the client row is not touched (no CRM sync)', async () => {
    expect(await code(contacts.replace('client', 1, 0, [{ contactId: null, kind: 'phone', value: '87015550101', isPrimary: true, note: null }],
      admin, 'req-c-phone'))).toBe('PARTY_CONTACT_INVALID');
    const saved = await contacts.replace('client', 1, 0, [
      { contactId: null, kind: 'email', value: 'Client@Mail.kz', isPrimary: false, note: 'личное примечание' },
      { contactId: null, kind: 'telegram', value: '@client_test', isPrimary: false, note: null },
    ], admin, 'req-c1');
    expect(saved.contacts.map((contact) => [contact.kind, contact.valueNormalized, contact.isPrimary])).toEqual([
      ['email', 'client@mail.kz', true], ['telegram', 'client_test', true]]);
    expect((await q(`SELECT count(*)::int n FROM client_updates`)).rows[0].n).toBe(0);
    const audit = (await q(`SELECT a.*, r.entity_type related_type, r.entity_id related FROM audit_log a JOIN audit_log_related_entity r ON r.audit_id = a.audit_id
      WHERE a.request_id = 'req-c1'`)).rows[0];
    expect(audit).toMatchObject({ event: 'client.contacts.updated', entity_type: 'client', entity_id: '1', related_client_id: '1',
      related_type: 'client', related: '1', user_id: '11', source: 'erp_party_contacts' });
    const text = JSON.stringify(audit);
    expect(text).toContain('cl***@mail.kz');
    expect(text).not.toContain('client@mail.kz');
    expect(text).not.toContain('client_test');
    expect(text).not.toContain('личное');
    // The DB itself refuses a phone in client contacts, and deleting an owner with contacts.
    expect(await code(q(`INSERT INTO client_contacts(client_id, kind, value, value_normalized) VALUES (1, 'phone', '87015550101', '77015550101')`))).toContain('check constraint');
    expect(await code(q(`DELETE FROM clients WHERE client_id = 1`))).toContain('foreign key');
  });

  const mirror = async (ref: string, name: string, extra: Record<string, unknown> = {}, row: { deleted?: boolean; missing?: boolean } = {}) => {
    await q(`INSERT INTO onec_etl_mirror_rows(source_id, entity_code, source_key, deleted, data, missing_in_source_at) VALUES (1, 'counterparties', $1, $2, $3, $4)`,
      [ref, row.deleted ?? false, JSON.stringify({ Ref_Key: ref, Description: name, IsFolder: false, DeletionMark: false, 'Поставщик': false, ...extra }),
        row.missing ? new Date() : null]);
  };

  it('offers counterparties from the 1C mirror (suppliers first; no folders, deleted or gone ones), else from procurement', async () => {
    await mirror(REF(1), 'Тест Контрагент Б', { 'Поставщик': true });
    await mirror(REF(2), 'Тест Контрагент А');
    await mirror(REF(3), 'Тест Папка', { IsFolder: true });
    await mirror(REF(4), 'Тест Помеченный', { DeletionMark: true });
    await mirror(REF(5), 'Тест Исчезнувший', {}, { missing: true });
    await mirror(REF(6), 'Тест Удалённый', {}, { deleted: true });
    await q(`UPDATE suppliers SET ref_key_1c = $1 WHERE supplier_id = 3`, [REF(2)]);
    expect(await counterparties.counterparties(null)).toEqual([
      { refKey1c: REF(1), name: 'Тест Контрагент Б', isSupplier: true, supplierId: null, supplierName: null },
      { refKey1c: REF(2), name: 'Тест Контрагент А', isSupplier: false, supplierId: 3, supplierName: 'Тест Поставщик Три' },
    ]);
    expect((await counterparties.counterparties('агент а')).map((item) => item.refKey1c)).toEqual([REF(2)]);
    expect(await counterparties.counterparties('100%_')).toEqual([]);
    // No mirror rows: what procurement has seen in 1C documents (keys c:<uuid>); other key kinds are not counterparties.
    await q(`DELETE FROM onec_etl_mirror_rows`);
    await q(`INSERT INTO resource_suppliers VALUES ($1, 'Тест Из Закупок'), ($1, 'Тест Из Закупок'), ('n:abc', 'Без ссылки'), ('s:1', 'Справочник')`, [`c:${REF(7)}`]);
    expect(await counterparties.counterparties(null)).toEqual([
      { refKey1c: REF(7), name: 'Тест Из Закупок', isSupplier: null, supplierId: null, supplierName: null }]);
  });

  it('links a supplier by compare-and-swap: a repeat is silent, a stale or taken or unknown key is refused, unlink is audited', async () => {
    await mirror(REF(1), 'Тест Контрагент 1');
    await mirror(REF(2), 'Тест Контрагент 2');
    expect(parseRefKey1c(REF(1).toUpperCase())).toBe(REF(1));
    expect(await code(Promise.resolve().then(() => parseRefKey1c(`c:${REF(1)}`)))).toBe('VALIDATION_ERROR');
    const linked = await counterparties.setLink(2, REF(1), null, admin, 'req-l1');
    expect(linked).toEqual({ supplierId: 2, supplierName: 'Тест Поставщик Два', refKey1c: REF(1), counterpartyName: 'Тест Контрагент 1' });
    // The answer was lost and the command repeated: same state, no second audit.
    await counterparties.setLink(2, REF(1), null, admin, 'req-l1-repeat');
    // A second editor still sees «not linked» and tries to link another counterparty / unlink: refused, nothing overwritten.
    expect(await code(counterparties.setLink(2, REF(2), null, admin, 'req-l-stale'))).toBe('SUPPLIER_COUNTERPARTY_CONFLICT');
    expect(await code(counterparties.setLink(2, null, REF(2), admin, 'req-l-stale2'))).toBe('SUPPLIER_COUNTERPARTY_CONFLICT');
    expect(await code(counterparties.setLink(3, REF(1), null, admin, 'req-l-taken'))).toBe('SUPPLIER_COUNTERPARTY_TAKEN');
    expect(await code(counterparties.setLink(3, REF(9), null, admin, 'req-l-unknown'))).toBe('SUPPLIER_COUNTERPARTY_UNKNOWN');
    expect(await code(counterparties.setLink(404, REF(2), null, admin, 'req-l-404'))).toBe('SUPPLIER_NOT_FOUND');
    const relinked = await counterparties.setLink(2, REF(2), REF(1), admin, 'req-l2');
    expect(relinked.refKey1c).toBe(REF(2));
    expect((await counterparties.setLink(2, null, REF(2), admin, 'req-l3')).refKey1c).toBeNull();
    const audit = (await q(`SELECT a.event, a.request_id, a.before_json->>'refKey1c' b, a.after_json->>'refKey1c' a, r.entity_id related
      FROM audit_log a JOIN audit_log_related_entity r ON r.audit_id = a.audit_id AND r.entity_type = 'supplier' ORDER BY a.created_at`)).rows;
    expect(audit).toEqual([
      { event: 'supplier.counterparty_linked', request_id: 'req-l1', b: null, a: REF(1), related: '2' },
      { event: 'supplier.counterparty_linked', request_id: 'req-l2', b: REF(1), a: REF(2), related: '2' },
      { event: 'supplier.counterparty_unlinked', request_id: 'req-l3', b: REF(2), a: null, related: '2' },
    ]);
    expect((await q(`SELECT edited_by FROM suppliers WHERE supplier_id = 2`)).rows[0].edited_by).toBe('11');
  });

  it('without any 1C data: nothing to choose, nothing to create from; a manual link is still allowed', async () => {
    expect(await counterparties.counterparties(null)).toEqual([]);
    expect(await code(counterparties.createFromCounterparty(REF(1), admin, 'req-none'))).toBe('SUPPLIER_COUNTERPARTY_UNKNOWN');
    await q(`ALTER TABLE onec_etl_mirror_rows RENAME TO onec_etl_mirror_rows_off; ALTER TABLE resource_suppliers RENAME TO resource_suppliers_off`);
    try {
      expect(await counterparties.counterparties(null)).toEqual([]);
      expect(await code(counterparties.createFromCounterparty(REF(1), admin, 'req-none2'))).toBe('SUPPLIER_COUNTERPARTY_UNKNOWN');
      expect(await counterparties.setLink(3, REF(1), null, admin, 'req-manual')).toMatchObject({ refKey1c: REF(1), counterpartyName: null });
    } finally {
      await q(`ALTER TABLE onec_etl_mirror_rows_off RENAME TO onec_etl_mirror_rows; ALTER TABLE resource_suppliers_off RENAME TO resource_suppliers`);
    }
  });

  it('a database failure that is not a name or key clash is not reported as one', async () => {
    await mirror(REF(1), 'Тест Сдвиг Последовательности');
    await q(`SELECT setval(pg_get_serial_sequence('suppliers', 'supplier_id'), 1)`);
    const failure = await counterparties.createFromCounterparty(REF(1), admin, 'req-drift').catch((error: unknown) => error);
    await q(`SELECT setval(pg_get_serial_sequence('suppliers', 'supplier_id'), 200)`);
    expect(failure).not.toBeInstanceOf(ApiError);
    expect((failure as { code?: string }).code).toBe('23505');
  });

  it('concurrent link and unlink of one supplier from the same view: one wins, the other conflicts', async () => {
    await mirror(REF(1), 'Тест Контрагент 1');
    await mirror(REF(2), 'Тест Контрагент 2');
    await counterparties.setLink(2, REF(1), null, admin, 'req-base');
    const results = await Promise.all([
      code(counterparties.setLink(2, REF(2), REF(1), admin, 'req-x')),
      code(counterparties.setLink(2, null, REF(1), admin, 'req-y')),
    ]);
    expect(results.sort()).toEqual(['SUPPLIER_COUNTERPARTY_CONFLICT', 'ok']);
  });

  it('adds a counterparty to the directory once: a repeat returns the same supplier without a second audit', async () => {
    await mirror(REF(1), 'Тест Новый Контрагент');
    await mirror(REF(2), 'тест поставщик три');
    const settled = await Promise.allSettled([
      counterparties.createFromCounterparty(REF(1), admin, 'req-n1'), counterparties.createFromCounterparty(REF(1), admin, 'req-n2')]);
    expect(settled.map((result) => result.status)).toEqual(['fulfilled', 'fulfilled']);
    const [first, second] = settled.map((result) => (result as PromiseFulfilledResult<Awaited<ReturnType<typeof counterparties.createFromCounterparty>>>).value);
    expect(first.supplierId).toBe(second.supplierId);
    expect([first.created, second.created].sort()).toEqual([false, true]);
    expect(first).toMatchObject({ supplierName: 'Тест Новый Контрагент', refKey1c: REF(1), counterpartyName: 'Тест Новый Контрагент' });
    expect((await counterparties.createFromCounterparty(REF(1), admin, 'req-n3')).created).toBe(false);
    expect((await q(`SELECT count(*)::int n FROM audit_log WHERE event = 'supplier.created_from_counterparty'`)).rows[0].n).toBe(1);
    expect((await q(`SELECT created_by, is_active FROM suppliers WHERE supplier_id = $1`, [first.supplierId])).rows[0]).toEqual({ created_by: '11', is_active: true });
    // A supplier with the same name (any case) is already there: link it instead of making a twin.
    const taken = await counterparties.createFromCounterparty(REF(2), admin, 'req-n4').catch((error: ApiError) => error);
    expect(taken).toMatchObject({ code: 'SUPPLIER_NAME_TAKEN', details: { supplierId: 3 } });
    expect(await code(counterparties.createFromCounterparty(REF(9), admin, 'req-n5'))).toBe('SUPPLIER_COUNTERPARTY_UNKNOWN');
  });
});
