// bootstrap029.ts — reusable pre-029 schema-create + migration 029 apply.
// Extracted so the Variant B fixture can import the proven DDL without also
// importing the 029 test suite (which would register duplicate describe blocks).
// Critic R16 B1: do NOT hand-roll the schema; this is the single source of truth.
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const MIGRATIONS = resolve(__dirname, '../../../../db/migrations');

function migrationSql(file: string): string {
  return readFileSync(resolve(MIGRATIONS, file), 'utf8');
}

// ---------------------------------------------------------------------------
// bootstrap029: builds the MINIMAL pre-029 schema and applies migration 029.
// Accepts any query-capable client (Pool, PoolClient, Client — all share .query).
// Does NOT apply migration 030 (the Variant B fixture applies it separately).
// ---------------------------------------------------------------------------
export async function bootstrap029(client: { query(text: string, values?: unknown[]): Promise<unknown> }): Promise<void> {
  await client.query(`
    CREATE TABLE material_types (
      material_type_id SMALLINT PRIMARY KEY,
      material_type_name TEXT
    );
    INSERT INTO material_types VALUES (1, 'Листовой материал'), (3, 'Прочее');

    CREATE TABLE units (
      unit_id SMALLINT PRIMARY KEY,
      unit_name TEXT
    );
    INSERT INTO units VALUES (1, 'шт');

    -- Stub tables required by orders_view and order_details_view JOINs
    CREATE TABLE clients (
      client_id BIGINT PRIMARY KEY,
      client_name TEXT,
      ref_key_1c UUID
    );
    CREATE TABLE employees (
      employee_id BIGINT PRIMARY KEY,
      full_name TEXT
    );
    CREATE TABLE order_statuses (
      order_status_id SMALLINT PRIMARY KEY,
      order_status_name TEXT
    );
    CREATE TABLE payment_statuses (
      payment_status_id SMALLINT PRIMARY KEY,
      payment_status_name TEXT
    );
    CREATE TABLE production_statuses (
      production_status_id SMALLINT PRIMARY KEY,
      production_status_name TEXT
    );
    CREATE TABLE milling_types (
      milling_type_id SMALLINT PRIMARY KEY,
      milling_type_name TEXT
    );
    INSERT INTO milling_types VALUES (1, 'Без фрезеровки');
    CREATE TABLE edge_types (
      edge_type_id SMALLINT PRIMARY KEY,
      edge_type_name TEXT
    );
    INSERT INTO edge_types VALUES (1, 'Без обката');
    CREATE TABLE films (
      film_id SMALLINT PRIMARY KEY,
      film_name TEXT
    );
    -- doweling_orders with all columns referenced by doweling_orders_view (034)
    CREATE TABLE doweling_orders (
      doweling_order_id BIGINT PRIMARY KEY,
      order_id BIGINT,
      doweling_order_name TEXT,
      design_engineer_id BIGINT,
      payment_status_id SMALLINT,
      production_status_id SMALLINT,
      doweling_order_date DATE,
      issue_date DATE,
      total_amount NUMERIC,
      final_amount NUMERIC,
      discount NUMERIC,
      surcharge NUMERIC,
      paid_amount NUMERIC,
      payment_date DATE,
      parts_count INT,
      operator_id BIGINT,
      link_cad_file TEXT,
      link_pdf_file TEXT,
      ref_key_1c UUID,
      created_by BIGINT,
      edited_by BIGINT,
      created_at TIMESTAMP DEFAULT now(),
      updated_at TIMESTAMP DEFAULT now(),
      version INT DEFAULT 0,
      delete_flag BOOLEAN NOT NULL DEFAULT false
    );
    -- order_doweling_links required by doweling_orders_view (034)
    CREATE TABLE order_doweling_links (
      order_doweling_link_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id BIGINT NOT NULL,
      doweling_order_id BIGINT NOT NULL,
      delete_flag BOOLEAN NOT NULL DEFAULT false,
      version INTEGER NOT NULL DEFAULT 0,
      ref_key_1c UUID NULL,
      created_by BIGINT NOT NULL,
      edited_by BIGINT,
      created_at TIMESTAMP NOT NULL DEFAULT now(),
      updated_at TIMESTAMP NOT NULL DEFAULT now()
    );

    -- sheet_material_types (post-SP1/SP2 shape)
    CREATE TABLE sheet_material_types (
      sheet_material_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(200) NOT NULL,
      material_type_id SMALLINT,
      thickness_mm NUMERIC(10,2),
      width_mm NUMERIC(10,2),
      height_mm NUMERIC(10,2),
      is_active BOOLEAN DEFAULT true,
      unit_id SMALLINT
    );

    -- materials in current post-SP1/SP2 shape (has sheet_material_type_id from migr 021)
    CREATE TABLE materials (
      material_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      material_name VARCHAR(200) NOT NULL UNIQUE,
      unit_id SMALLINT NOT NULL DEFAULT 1,
      material_type_id SMALLINT,
      is_active BOOLEAN NOT NULL DEFAULT true,
      sheet_material_type_id BIGINT NULL,
      created_at TIMESTAMP DEFAULT now(),
      updated_at TIMESTAMP DEFAULT now()
    );

    -- orders table with all columns referenced by orders_view (plus material_id for the view JOIN)
    CREATE TABLE orders (
      order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_name TEXT,
      client_id BIGINT,
      order_date DATE,
      priority INT,
      completion_date DATE,
      planned_completion_date DATE,
      order_status_id SMALLINT,
      payment_status_id SMALLINT,
      production_status_id SMALLINT,
      issue_date DATE,
      total_amount NUMERIC,
      final_amount NUMERIC,
      discount NUMERIC,
      surcharge NUMERIC,
      paid_amount NUMERIC,
      payment_date DATE,
      parts_count INT,
      total_area NUMERIC,
      milling_type_id SMALLINT,
      edge_type_id SMALLINT,
      film_id SMALLINT,
      material_id BIGINT,
      notes TEXT,
      link_cutting_file TEXT,
      link_cutting_image_file TEXT,
      ref_key_1c UUID,
      manager_id BIGINT,
      created_by BIGINT,
      edited_by BIGINT,
      created_at TIMESTAMP DEFAULT now(),
      updated_at TIMESTAMP DEFAULT now(),
      version INT DEFAULT 1,
      delete_flag BOOLEAN NOT NULL DEFAULT false
    );

    -- order_details with columns referenced by order_details_view
    CREATE TABLE order_details (
      detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id BIGINT,
      detail_number INT,
      detail_name TEXT,
      height NUMERIC,
      width NUMERIC,
      quantity NUMERIC,
      area NUMERIC,
      material_id BIGINT,
      milling_type_id SMALLINT DEFAULT 1,
      hdf_parameter_override_mm NUMERIC(10,2),
      edge_type_id SMALLINT DEFAULT 1,
      film_id SMALLINT,
      milling_cost_per_sqm NUMERIC,
      detail_cost NUMERIC,
      priority INT DEFAULT 100,
      production_status_id SMALLINT,
      joint_order_id BIGINT,
      note TEXT,
      link_cutting_file TEXT,
      link_cutting_image_file TEXT,
      link_cad_file TEXT,
      link_pdf_file TEXT,
      ref_key_1c UUID,
      created_by BIGINT,
      edited_by BIGINT,
      created_at TIMESTAMP DEFAULT now(),
      updated_at TIMESTAMP DEFAULT now(),
      delete_flag BOOLEAN NOT NULL DEFAULT false
    );

    -- orders_view in its migration-004 shape (ends with ord.version — NO sheet column)
    CREATE OR REPLACE VIEW orders_view AS
    SELECT
        ord.order_id,
        ord.order_name,
        CASE
            WHEN order_name_digits.value = '' THEN NULL
            WHEN length(order_name_digits.value) > 10 THEN NULL
            WHEN order_name_digits.value::BIGINT > 2147483647 THEN NULL
            ELSE order_name_digits.value::INTEGER
        END AS order_name_numeric,
        ord.client_id,
        c.client_name,
        ord.order_date,
        ord.priority,
        d.doweling_order_id,
        d.doweling_order_name,
        emd.full_name AS design_engineer,
        ord.completion_date,
        ord.planned_completion_date,
        os.order_status_name,
        ps.payment_status_name,
        pr.production_status_name,
        ord.issue_date,
        ord.total_amount,
        ord.final_amount,
        ord.discount,
        ord.surcharge,
        ord.paid_amount,
        ord.payment_date,
        ord.parts_count,
        ord.total_area,
        mt.milling_type_name,
        et.edge_type_name,
        f.film_name,
        m.material_name,
        ord.notes,
        ord.link_cutting_file,
        ord.link_cutting_image_file,
        ord.ref_key_1c AS order_ref_key_1c,
        c.ref_key_1c AS client_ref_key_1c,
        ord.manager_id,
        ord.created_by,
        ord.edited_by,
        ord.created_at,
        ord.updated_at,
        ord.version
    FROM orders ord
    CROSS JOIN LATERAL (
        VALUES (regexp_replace(COALESCE(ord.order_name, ''), '\\D', '', 'g'))
    ) AS order_name_digits(value)
    LEFT JOIN clients c ON ord.client_id = c.client_id
    LEFT JOIN doweling_orders d ON ord.order_id = d.order_id
    LEFT JOIN employees emd ON d.design_engineer_id = emd.employee_id
    LEFT JOIN order_statuses os ON ord.order_status_id = os.order_status_id
    LEFT JOIN payment_statuses ps ON ord.payment_status_id = ps.payment_status_id
    LEFT JOIN production_statuses pr ON ord.production_status_id = pr.production_status_id
    LEFT JOIN milling_types mt ON ord.milling_type_id = mt.milling_type_id
    LEFT JOIN edge_types et ON ord.edge_type_id = et.edge_type_id
    LEFT JOIN films f ON ord.film_id = f.film_id
    LEFT JOIN materials m ON ord.material_id = m.material_id
    WHERE ord.delete_flag = false
    ORDER BY ord.order_id DESC;
  `);
  // Apply migration 029 (adds sheet_material_type_id columns, rebuilds views, etc.)
  await client.query(migrationSql('029_order_sheet_material_type.sql'));
}
