import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { randomUUID } from 'node:crypto';
import { Pool, type PoolClient } from 'pg';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

// Fail-fast: the dedicated `test:backend:sheet-integration` script sets
// SHEET_INTEGRATION_REQUIRED=1. In that mode ONLY SHEET_INTEGRATION_DATABASE_URL
// is honored (no TEST_DATABASE_URL fallback that could silently route the suite to
// a different database); a missing value is a hard error, not a silent skip.
const required = process.env.SHEET_INTEGRATION_REQUIRED === '1';
const databaseUrl = required
  ? process.env.SHEET_INTEGRATION_DATABASE_URL
  : process.env.SHEET_INTEGRATION_DATABASE_URL ?? process.env.TEST_DATABASE_URL;
if (required && !databaseUrl) {
  throw new Error('SHEET_INTEGRATION_DATABASE_URL is required for test:backend:sheet-integration');
}
const describeIntegration = databaseUrl ? describe : describe.skip;
const schemaName = `migration_029_${randomUUID().replaceAll('-', '_')}`;

const MIGRATIONS = resolve(__dirname, '../../../../db/migrations');
function migration(file: string): string {
  return readFileSync(resolve(MIGRATIONS, file), 'utf8');
}

// Pre-029 orders_view columns (migration 004 shape — ends with ord.version, NO sheet column).
const PRE_029_ORDERS_VIEW_COLUMNS = [
  'order_id',
  'order_name',
  'order_name_numeric',
  'client_id',
  'client_name',
  'order_date',
  'priority',
  'doweling_order_id',
  'doweling_order_name',
  'design_engineer',
  'completion_date',
  'planned_completion_date',
  'order_status_name',
  'payment_status_name',
  'production_status_name',
  'issue_date',
  'total_amount',
  'final_amount',
  'discount',
  'surcharge',
  'paid_amount',
  'payment_date',
  'parts_count',
  'total_area',
  'milling_type_name',
  'edge_type_name',
  'film_name',
  'material_name',
  'notes',
  'link_cutting_file',
  'link_cutting_image_file',
  'order_ref_key_1c',
  'client_ref_key_1c',
  'manager_id',
  'created_by',
  'edited_by',
  'created_at',
  'updated_at',
  'version',
];

/**
 * Build a MINIMAL pre-029 base:
 * - lookup tables (material_types, units, reference stubs)
 * - materials in current post-SP1/SP2 shape
 * - sheet_material_types
 * - orders and order_details
 * - orders_view in its migration-004 shape (pre-029, column list ends with ord.version)
 *
 * Does NOT run migrations 001-028; only the minimum DDL for migration 029 to apply
 * and for both views to compile.
 */
async function createSchema(client: PoolClient): Promise<void> {
  // Lookup/reference tables
  await client.query(`
    CREATE TABLE material_types (
      material_type_id SMALLINT PRIMARY KEY,
      material_type_name TEXT
    );
    INSERT INTO material_types VALUES (1, 'Листовой материал');

    CREATE TABLE units (
      unit_id SMALLINT PRIMARY KEY,
      unit_name TEXT
    );
    INSERT INTO units VALUES (1, 'шт');

    -- Stub tables required by orders_view and order_details_view JOINs
    CREATE TABLE clients (
      client_id BIGINT PRIMARY KEY,
      client_name TEXT,
      ref_key_1c UUID
    );
    CREATE TABLE employees (
      employee_id BIGINT PRIMARY KEY,
      full_name TEXT
    );
    CREATE TABLE order_statuses (
      order_status_id SMALLINT PRIMARY KEY,
      order_status_name TEXT
    );
    CREATE TABLE payment_statuses (
      payment_status_id SMALLINT PRIMARY KEY,
      payment_status_name TEXT
    );
    CREATE TABLE production_statuses (
      production_status_id SMALLINT PRIMARY KEY,
      production_status_name TEXT
    );
    CREATE TABLE milling_types (
      milling_type_id SMALLINT PRIMARY KEY,
      milling_type_name TEXT
    );
    CREATE TABLE edge_types (
      edge_type_id SMALLINT PRIMARY KEY,
      edge_type_name TEXT
    );
    CREATE TABLE films (
      film_id SMALLINT PRIMARY KEY,
      film_name TEXT
    );
    CREATE TABLE doweling_orders (
      doweling_order_id BIGINT PRIMARY KEY,
      order_id BIGINT,
      doweling_order_name TEXT,
      design_engineer_id BIGINT
    );

    -- sheet_material_types (post-SP1/SP2 shape)
    CREATE TABLE sheet_material_types (
      sheet_material_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(200) NOT NULL,
      material_type_id SMALLINT,
      thickness_mm NUMERIC(10,2),
      width_mm NUMERIC(10,2),
      height_mm NUMERIC(10,2),
      is_active BOOLEAN DEFAULT true
    );

    -- materials in current post-SP1/SP2 shape (has sheet_material_type_id from migr 021)
    CREATE TABLE materials (
      material_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      material_name VARCHAR(200) NOT NULL UNIQUE,
      unit_id SMALLINT NOT NULL,
      material_type_id SMALLINT,
      is_active BOOLEAN NOT NULL DEFAULT true,
      sheet_material_type_id BIGINT NULL,
      created_at TIMESTAMP DEFAULT now(),
      updated_at TIMESTAMP DEFAULT now()
    );

    -- orders table with all columns referenced by orders_view (plus material_id for the view JOIN)
    CREATE TABLE orders (
      order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_name TEXT,
      client_id BIGINT,
      order_date DATE,
      priority INT,
      completion_date DATE,
      planned_completion_date DATE,
      order_status_id SMALLINT,
      payment_status_id SMALLINT,
      production_status_id SMALLINT,
      issue_date DATE,
      total_amount NUMERIC,
      final_amount NUMERIC,
      discount NUMERIC,
      surcharge NUMERIC,
      paid_amount NUMERIC,
      payment_date DATE,
      parts_count INT,
      total_area NUMERIC,
      milling_type_id SMALLINT,
      edge_type_id SMALLINT,
      film_id SMALLINT,
      material_id BIGINT,
      notes TEXT,
      link_cutting_file TEXT,
      link_cutting_image_file TEXT,
      ref_key_1c UUID,
      manager_id BIGINT,
      created_by BIGINT,
      edited_by BIGINT,
      created_at TIMESTAMP DEFAULT now(),
      updated_at TIMESTAMP DEFAULT now(),
      version INT DEFAULT 1,
      delete_flag BOOLEAN NOT NULL DEFAULT false
    );

    -- order_details with columns referenced by order_details_view
    CREATE TABLE order_details (
      detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id BIGINT,
      detail_number INT,
      detail_name TEXT,
      height NUMERIC,
      width NUMERIC,
      quantity NUMERIC,
      area NUMERIC,
      material_id BIGINT,
      milling_type_id SMALLINT,
      edge_type_id SMALLINT,
      film_id SMALLINT,
      milling_cost_per_sqm NUMERIC,
      detail_cost NUMERIC,
      priority INT,
      production_status_id SMALLINT,
      joint_order_id BIGINT,
      note TEXT,
      link_cutting_file TEXT,
      link_cutting_image_file TEXT,
      link_cad_file TEXT,
      link_pdf_file TEXT,
      ref_key_1c UUID,
      delete_flag BOOLEAN NOT NULL DEFAULT false
    );

    -- orders_view in its migration-004 shape (ends with ord.version — NO sheet column)
    CREATE OR REPLACE VIEW orders_view AS
    SELECT
        ord.order_id,
        ord.order_name,
        CASE
            WHEN order_name_digits.value = '' THEN NULL
            WHEN length(order_name_digits.value) > 10 THEN NULL
            WHEN order_name_digits.value::BIGINT > 2147483647 THEN NULL
            ELSE order_name_digits.value::INTEGER
        END AS order_name_numeric,
        ord.client_id,
        c.client_name,
        ord.order_date,
        ord.priority,
        d.doweling_order_id,
        d.doweling_order_name,
        emd.full_name AS design_engineer,
        ord.completion_date,
        ord.planned_completion_date,
        os.order_status_name,
        ps.payment_status_name,
        pr.production_status_name,
        ord.issue_date,
        ord.total_amount,
        ord.final_amount,
        ord.discount,
        ord.surcharge,
        ord.paid_amount,
        ord.payment_date,
        ord.parts_count,
        ord.total_area,
        mt.milling_type_name,
        et.edge_type_name,
        f.film_name,
        m.material_name,
        ord.notes,
        ord.link_cutting_file,
        ord.link_cutting_image_file,
        ord.ref_key_1c AS order_ref_key_1c,
        c.ref_key_1c AS client_ref_key_1c,
        ord.manager_id,
        ord.created_by,
        ord.edited_by,
        ord.created_at,
        ord.updated_at,
        ord.version
    FROM orders ord
    CROSS JOIN LATERAL (
        VALUES (regexp_replace(COALESCE(ord.order_name, ''), '\\D', '', 'g'))
    ) AS order_name_digits(value)
    LEFT JOIN clients c ON ord.client_id = c.client_id
    LEFT JOIN doweling_orders d ON ord.order_id = d.order_id
    LEFT JOIN employees emd ON d.design_engineer_id = emd.employee_id
    LEFT JOIN order_statuses os ON ord.order_status_id = os.order_status_id
    LEFT JOIN payment_statuses ps ON ord.payment_status_id = ps.payment_status_id
    LEFT JOIN production_statuses pr ON ord.production_status_id = pr.production_status_id
    LEFT JOIN milling_types mt ON ord.milling_type_id = mt.milling_type_id
    LEFT JOIN edge_types et ON ord.edge_type_id = et.edge_type_id
    LEFT JOIN films f ON ord.film_id = f.film_id
    LEFT JOIN materials m ON ord.material_id = m.material_id
    WHERE ord.delete_flag = false
    ORDER BY ord.order_id DESC;
  `);
}

async function applyMigration029(client: PoolClient): Promise<void> {
  await client.query(migration('029_order_sheet_material_type.sql'));
}

async function getViewColumns(pool: Pool, viewName: string): Promise<string[]> {
  const result = await pool.query<{ column_name: string }>(
    `SELECT column_name FROM information_schema.columns
     WHERE table_schema = $1 AND table_name = $2
     ORDER BY ordinal_position`,
    [schemaName, viewName],
  );
  return result.rows.map((r) => r.column_name);
}

describeIntegration('Migration 029: order-side sheet material link (integration, DDL assertions)', () => {
  let pool: Pool;

  beforeAll(async () => {
    pool = new Pool({ connectionString: databaseUrl, max: 4 });
    const client = await pool.connect();
    try {
      await client.query(`CREATE SCHEMA ${schemaName}`);
      await client.query(`SET search_path TO ${schemaName}`);
      await createSchema(client);
      await applyMigration029(client);
    } finally {
      client.release();
    }
    pool.on('connect', (c) => void c.query(`SET search_path TO ${schemaName}`));
  });

  afterAll(async () => {
    if (pool) {
      await pool.query(`DROP SCHEMA IF EXISTS ${schemaName} CASCADE`);
      await pool.end();
    }
  });

  it('1. order_details.sheet_material_type_id and orders.sheet_material_type_id are NULLABLE columns', async () => {
    const result = await pool.query<{ table_name: string; column_name: string; is_nullable: string }>(
      `SELECT table_name, column_name, is_nullable
       FROM information_schema.columns
       WHERE table_schema = $1
         AND table_name IN ('order_details', 'orders')
         AND column_name = 'sheet_material_type_id'
       ORDER BY table_name`,
      [schemaName],
    );
    expect(result.rowCount).toBe(2);
    for (const row of result.rows) {
      expect(row.is_nullable).toBe('YES');
    }
  });

  it('2. FK constraints fk_order_details_sheet_material_type, fk_orders_sheet_material_type, fk_materials_shadow_of_sheet_material_type exist', async () => {
    const result = await pool.query<{ conname: string }>(
      `SELECT c.conname
       FROM pg_constraint c
       JOIN pg_namespace n ON n.oid = c.connamespace
       WHERE n.nspname = $1
         AND c.conname IN (
           'fk_order_details_sheet_material_type',
           'fk_orders_sheet_material_type',
           'fk_materials_shadow_of_sheet_material_type'
         )
       ORDER BY c.conname`,
      [schemaName],
    );
    const names = result.rows.map((r) => r.conname).sort();
    expect(names).toEqual([
      'fk_materials_shadow_of_sheet_material_type',
      'fk_order_details_sheet_material_type',
      'fk_orders_sheet_material_type',
    ]);
  });

  it('3. materials.is_sheet_shadow (NOT NULL, default false) and materials.shadow_of_sheet_material_type_id (nullable) exist', async () => {
    const result = await pool.query<{ column_name: string; is_nullable: string; column_default: string }>(
      `SELECT column_name, is_nullable, column_default
       FROM information_schema.columns
       WHERE table_schema = $1
         AND table_name = 'materials'
         AND column_name IN ('is_sheet_shadow', 'shadow_of_sheet_material_type_id')
       ORDER BY column_name`,
      [schemaName],
    );
    expect(result.rowCount).toBe(2);
    const byShadow = Object.fromEntries(result.rows.map((r) => [r.column_name, r]));
    expect(byShadow['is_sheet_shadow'].is_nullable).toBe('NO');
    expect(byShadow['is_sheet_shadow'].column_default).toMatch(/false/i);
    expect(byShadow['shadow_of_sheet_material_type_id'].is_nullable).toBe('YES');
  });

  it('4. orders.sheet_eligible exists, NOT NULL, default true', async () => {
    const result = await pool.query<{ is_nullable: string; column_default: string }>(
      `SELECT is_nullable, column_default
       FROM information_schema.columns
       WHERE table_schema = $1
         AND table_name = 'orders'
         AND column_name = 'sheet_eligible'`,
      [schemaName],
    );
    expect(result.rowCount).toBe(1);
    expect(result.rows[0].is_nullable).toBe('NO');
    expect(result.rows[0].column_default).toMatch(/true/i);
  });

  it('5. Unique index uq_materials_shadow_of_sheet_material_type_id exists', async () => {
    const result = await pool.query<{ indexname: string }>(
      `SELECT indexname
       FROM pg_indexes
       WHERE schemaname = $1
         AND indexname = 'uq_materials_shadow_of_sheet_material_type_id'`,
      [schemaName],
    );
    expect(result.rowCount).toBe(1);
  });

  it('6. orders_view column order: pre-029 columns first in original order, then sheet_material_type_id appended last', async () => {
    const afterColumns = await getViewColumns(pool, 'orders_view');
    // The after list must start with all pre-029 columns in the same order
    const firstN = afterColumns.slice(0, PRE_029_ORDERS_VIEW_COLUMNS.length);
    expect(firstN).toEqual(PRE_029_ORDERS_VIEW_COLUMNS);
    // sheet_material_type_id is the last column
    expect(afterColumns[afterColumns.length - 1]).toBe('sheet_material_type_id');
    // Total = pre-029 count + 1
    expect(afterColumns.length).toBe(PRE_029_ORDERS_VIEW_COLUMNS.length + 1);
  });

  it('7. order_details_view exists and has a material_name column', async () => {
    const columns = await getViewColumns(pool, 'order_details_view');
    expect(columns).toContain('material_name');
  });

  it('8. COALESCE: order_details_view.material_name prefers sheet type name when sheet_material_type_id set', async () => {
    const client = await pool.connect();
    try {
      await client.query(`SET search_path TO ${schemaName}`);

      // Insert a sheet type
      const smt = await client.query<{ sheet_material_type_id: number }>(
        `INSERT INTO sheet_material_types (name, material_type_id) VALUES ('МДФ 16 мм ТЕСТ', 1) RETURNING sheet_material_type_id`,
      );
      const smtId = smt.rows[0].sheet_material_type_id;

      // Insert a real material (used as fallback)
      const mat = await client.query<{ material_id: number }>(
        `INSERT INTO materials (material_name, unit_id) VALUES ('Материал резерв ТЕСТ', 1) RETURNING material_id`,
      );
      const matId = mat.rows[0].material_id;

      // Insert an order
      const ord = await client.query<{ order_id: number }>(
        `INSERT INTO orders (order_name) VALUES ('Тест-SP3-COALESCE') RETURNING order_id`,
      );
      const orderId = ord.rows[0].order_id;

      // Insert a detail with both sheet_material_type_id and material_id set
      await client.query(
        `INSERT INTO order_details (order_id, detail_name, sheet_material_type_id, material_id)
         VALUES ($1, 'Деталь-ТЕСТ', $2, $3)`,
        [orderId, smtId, matId],
      );

      // COALESCE should prefer the sheet type name
      const view = await client.query<{ material_name: string }>(
        `SELECT material_name FROM order_details_view WHERE order_id = $1`,
        [orderId],
      );
      expect(view.rowCount).toBe(1);
      expect(view.rows[0].material_name).toBe('МДФ 16 мм ТЕСТ');

      // Also check orders_view header material_name COALESCE for a sheet order
      const ordSheet = await client.query<{ order_id: number }>(
        `INSERT INTO orders (order_name, sheet_material_type_id) VALUES ('Тест-SP3-Header', $1) RETURNING order_id`,
        [smtId],
      );
      const headerOrderId = ordSheet.rows[0].order_id;
      const ordView = await client.query<{ material_name: string }>(
        `SELECT material_name FROM orders_view WHERE order_id = $1`,
        [headerOrderId],
      );
      expect(ordView.rowCount).toBe(1);
      expect(ordView.rows[0].material_name).toBe('МДФ 16 мм ТЕСТ');

      // Cleanup
      await client.query(`DELETE FROM order_details WHERE order_id = $1`, [orderId]);
      await client.query(`DELETE FROM orders WHERE order_id IN ($1, $2)`, [orderId, headerOrderId]);
      await client.query(`DELETE FROM materials WHERE material_id = $1`, [matId]);
      await client.query(`DELETE FROM sheet_material_types WHERE sheet_material_type_id = $1`, [smtId]);
    } finally {
      client.release();
    }
  });

  it('9. Soft-delete exclusion: order_details_view excludes details of delete_flag=true orders', async () => {
    const client = await pool.connect();
    try {
      await client.query(`SET search_path TO ${schemaName}`);

      // Insert a soft-deleted order
      const ord = await client.query<{ order_id: number }>(
        `INSERT INTO orders (order_name, delete_flag) VALUES ('Тест-удалённый-SP3', true) RETURNING order_id`,
      );
      const orderId = ord.rows[0].order_id;

      // Insert a detail for the deleted order
      await client.query(
        `INSERT INTO order_details (order_id, detail_name) VALUES ($1, 'Деталь-удалённая-SP3')`,
        [orderId],
      );

      // detail should NOT appear in the view
      const view = await client.query(
        `SELECT detail_id FROM order_details_view WHERE order_id = $1`,
        [orderId],
      );
      expect(view.rowCount).toBe(0);

      // Cleanup
      await client.query(`DELETE FROM order_details WHERE order_id = $1`, [orderId]);
      await client.query(`DELETE FROM orders WHERE order_id = $1`, [orderId]);
    } finally {
      client.release();
    }
  });
});
