import { randomUUID } from 'node:crypto';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Pool, type PoolClient, type QueryResultRow } from 'pg';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import type { TransactionClient } from '../../../database/database.types';
import type { OrderSnapshotDto } from '../dto/order-snapshot.dto';
import { _testOnlyUpsertClient as upsertClient } from './pg-order-snapshot';

const databaseUrl = process.env.TEST_DATABASE_URL;
const REF = (n: number) => `00000000-0000-4000-8000-${String(n).padStart(12, '0')}`;
const SRC = fileURLToPath(new URL('../../..', import.meta.url));

function sources(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    if (statSync(path).isDirectory()) return sources(path);
    return /\.ts$/.test(name) && !/\.test\.ts$/.test(name) ? [path] : [];
  });
}

describe('clients.ref_key_1c has one writer', () => {
  it('no backend statement but the client card command writes the 1C key of a client', () => {
    const writers = sources(SRC).filter((path) => {
      const text = readFileSync(path, 'utf8');
      return /UPDATE\s+(public\.)?clients\b[^;`'"]*\bSET\b[^;`'"]*\bref_key_1c\s*=/i.test(text)
        || /INSERT\s+INTO\s+(public\.)?clients\s*\([^)]*\bref_key_1c\b/i.test(text);
    }).map((path) => path.slice(SRC.length).replaceAll('\\', '/'));
    expect(writers).toEqual(['modules/party-contacts/client-counterparty.repository.ts']);
  });
});

describe.skipIf(!databaseUrl)('order snapshot import keeps the client ↔ 1C counterparty link (PostgreSQL, isolated schema)', () => {
  const schema = `e2e_snapshot_client_link_${randomUUID().replaceAll('-', '')}`;
  let pool: Pool;
  let client: PoolClient;
  const q = <T extends QueryResultRow = QueryResultRow>(text: string, params: unknown[] = []) => client.query<T>(text, params);
  const tx = { query: <T extends QueryResultRow = QueryResultRow>(text: string, params: readonly unknown[] = []) => client.query<T>(text, [...params]) } as unknown as TransactionClient;
  const snapshot = (sourceId: string, clientName: string, refKey1c: string | null): OrderSnapshotDto => ({
    source: { sourceInstanceId: 'erp-other' },
    data: { client: { sourceId, clientName, refKey1c, notes: null, isActive: true } },
  }) as unknown as OrderSnapshotDto;
  const key = async (clientId: number) => (await q<{ ref_key_1c: string | null }>('SELECT ref_key_1c FROM clients WHERE client_id = $1', [clientId])).rows[0].ref_key_1c;

  beforeAll(async () => {
    pool = new Pool({ connectionString: databaseUrl, max: 2 });
    client = await pool.connect();
    await q(`CREATE SCHEMA IF NOT EXISTS "${schema}"`);
    await q(`SET search_path="${schema}",public`);
    await q(`CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;
      CREATE TABLE clients(client_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, client_name citext NOT NULL UNIQUE, ref_key_1c uuid,
        notes text, is_active boolean NOT NULL DEFAULT true);
      CREATE UNIQUE INDEX idx_clients__ref_key_1c ON clients(ref_key_1c) WHERE ref_key_1c IS NOT NULL;
      CREATE TABLE order_import_entity_map(source_instance_id text NOT NULL, entity_type text NOT NULL, source_entity_id text NOT NULL,
        local_entity_id text NOT NULL, local_order_id bigint, payload_hash text, updated_at timestamptz DEFAULT now(),
        PRIMARY KEY(source_instance_id, entity_type, source_entity_id));`);
  }, 60_000);

  afterAll(async () => {
    if (client) {
      try { await q(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`); } finally { client.release(); }
    }
    await pool?.end();
  });

  beforeEach(async () => { await q('DELETE FROM order_import_entity_map; DELETE FROM clients'); });

  it('a client imported before keeps the link set, replaced or removed in its card — the snapshot key never comes back', async () => {
    const clientId = await upsertClient(tx, snapshot('s-1', 'Тест Импорт Клиент', REF(1)), 'h1');
    // The card command linked the client to another counterparty.
    await q('UPDATE clients SET ref_key_1c = $2 WHERE client_id = $1', [clientId, REF(2)]);
    expect(await upsertClient(tx, snapshot('s-1', 'Тест Импорт Клиент', REF(1)), 'h2')).toBe(clientId);
    expect(await key(clientId)).toBe(REF(2));
    // The link was removed in the card: the next import of another order of the client does not restore it.
    await q('UPDATE clients SET ref_key_1c = NULL WHERE client_id = $1', [clientId]);
    expect(await upsertClient(tx, snapshot('s-1', 'Тест Импорт Клиент Новое Имя', REF(1)), 'h3')).toBe(clientId);
    expect(await key(clientId)).toBeNull();
    expect((await q('SELECT client_name::text AS name FROM clients WHERE client_id = $1', [clientId])).rows[0].name).toBe('Тест Импорт Клиент Новое Имя');
  });

  it('a new client is created without a 1C counterparty, whatever key the snapshot carries (unknown or taken)', async () => {
    const holder = Number((await q<{ client_id: string }>(`INSERT INTO clients(client_name, ref_key_1c) VALUES ('Тест Держатель', $1) RETURNING client_id`, [REF(5)])).rows[0].client_id);
    const created = await upsertClient(tx, snapshot('s-2', 'Тест Новый Из Импорта', REF(9)), 'h1');
    expect(await key(created)).toBeNull();
    // The snapshot key still finds the client that holds it: no second client, the link untouched.
    expect(await upsertClient(tx, snapshot('s-3', 'Тест Другое Имя', REF(5)), 'h1')).toBe(holder);
    expect(await key(holder)).toBe(REF(5));
    expect((await q('SELECT count(*)::int n FROM clients')).rows[0].n).toBe(2);
  });
});
