// backend/src/modules/orders/adapters/pg-order-read-repository.integration.ts
//
// Ephemeral-PG integration tests for PgOrderReadRepository.
// Gated on SHEET_INTEGRATION_DATABASE_URL (same pool as sheet-materials tests).
//
// ISOLATION: all DDL/DML runs inside a dedicated schema (vb_read_repo_<hrtime>)
// so it cannot collide with sibling integration files running in parallel.
//
// Critic R3: covers FINDING 1 (flag-ON listOrders GROUP BY SQL must not throw)
// and FINDING 2 (flag-ON getOrderById must preserve milling_type_id/edge_type_id/film_id).
import { Client } from 'pg';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import {
  bootstrapVariantBSchema,
  seedVariantAMain,
} from './__fixtures__/variant-b-migration-fixture';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { PgOrderReadRepository } from './pg-order-read-repository';
import type { DatabaseClient } from '../../../database/database.types';
import type { QueryResult, QueryResultRow } from 'pg';

const url = process.env.SHEET_INTEGRATION_DATABASE_URL;
const d = url ? describe : describe.skip;

function mig(n: string): string {
  return readFileSync(join(__dirname, '../../../../db/migrations', n), 'utf8');
}

// Wraps a pg.Client into the DatabaseClient interface expected by PgOrderReadRepository.
function makeDbClient(client: Client, schema: string): DatabaseClient {
  return {
    async query<T extends QueryResultRow = QueryResultRow>(
      text: string,
      params?: readonly unknown[],
    ): Promise<QueryResult<T>> {
      // Ensure each query runs with the correct search_path (the schema can be shared
      // across tests in a suite that re-uses the same Client, so we always set it).
      await client.query(`SET search_path TO ${schema}, public`);
      return client.query<T>(text, params as unknown[]);
    },
  };
}

function minimalListCommand() {
  return {
    currentUser: { id: '1', username: 'admin', role: 'admin', permissions: [] } as never,
    query: {
      page: 1,
      pageSize: 20,
      sortBy: 'orderId' as const,
      sortOrder: 'desc' as const,
      onlyMyOrders: false,
    },
  };
}

function getByIdCommand(orderId: number) {
  return {
    currentUser: { id: '1', username: 'admin', role: 'admin', permissions: [] } as never,
    orderId,
  };
}

// ---------------------------------------------------------------------------
// Helper: create stub tables that the repo queries but bootstrap029 doesn't include.
// ---------------------------------------------------------------------------
async function createStubTables(client: Client): Promise<void> {
  // Orders table: add columns not present in bootstrap029 but required by the repo.
  await client.query(`
    ALTER TABLE orders ADD COLUMN IF NOT EXISTS production_status_from_details_enabled BOOLEAN NOT NULL DEFAULT false;
    ALTER TABLE orders ADD COLUMN IF NOT EXISTS link_cad_file TEXT;
    ALTER TABLE orders ADD COLUMN IF NOT EXISTS link_pdf_file TEXT;
    -- production_status_code is used in the production_status_events lateral join
    ALTER TABLE production_statuses ADD COLUMN IF NOT EXISTS production_status_code TEXT;
    -- sort_order is used in the production_status_events lateral join ORDER BY
    ALTER TABLE production_statuses ADD COLUMN IF NOT EXISTS sort_order INT;
  `);

  // payments table: new (not in bootstrapVariantBSchema).
  await client.query(`
    CREATE TABLE IF NOT EXISTS payments (
      payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id BIGINT NOT NULL,
      type_paid_id BIGINT NOT NULL DEFAULT 1,
      amount NUMERIC NOT NULL DEFAULT 0,
      payment_date DATE NOT NULL DEFAULT now(),
      notes TEXT,
      ref_key_1c UUID,
      delete_flag BOOLEAN NOT NULL DEFAULT false
    );
  `);

  // order_workshops table: new.
  await client.query(`
    CREATE TABLE IF NOT EXISTS order_workshops (
      order_workshop_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id BIGINT NOT NULL,
      workshop_id BIGINT NOT NULL DEFAULT 1,
      production_status_id SMALLINT NOT NULL DEFAULT 1,
      received_date DATE,
      started_date DATE,
      completed_date DATE,
      planned_completion_date DATE,
      sequence_order INT,
      responsible_employee_id BIGINT,
      notes TEXT,
      ref_key_1c UUID,
      delete_flag BOOLEAN NOT NULL DEFAULT false
    );
  `);

  // order_resource_requirements: the fixture creates it with only material_id.
  // Add the columns the repo queries (order_id, is_active) via ALTER TABLE.
  await client.query(`
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS requirement_id BIGINT;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS order_id BIGINT;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS resource_type TEXT NOT NULL DEFAULT 'material';
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS film_id BIGINT;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS edge_type_id BIGINT;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS required_quantity NUMERIC NOT NULL DEFAULT 0;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS unit_id SMALLINT NOT NULL DEFAULT 1;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS waste_percentage NUMERIC;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS final_quantity NUMERIC;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS requirement_status_id SMALLINT NOT NULL DEFAULT 1;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS supplier_id BIGINT;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS purchase_price NUMERIC;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS requisition_id BIGINT;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS warehouse_id BIGINT;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS reserved_at TIMESTAMP;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS consumed_at TIMESTAMP;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS notes TEXT;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS calculation_details JSONB;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS ref_key_1c UUID;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true;
  `);

  // production_status_events: new.
  await client.query(`
    CREATE TABLE IF NOT EXISTS production_status_events (
      event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id BIGINT NOT NULL,
      production_status_id SMALLINT NOT NULL
    );
  `);

  // project_order_projects and project_projects must be in public schema.
  // The repo queries them as public.project_order_projects / public.project_projects.
  await client.query(`
    CREATE TABLE IF NOT EXISTS public.project_projects (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      code TEXT NOT NULL DEFAULT '',
      name TEXT NOT NULL DEFAULT ''
    );
  `);
  await client.query(`
    CREATE TABLE IF NOT EXISTS public.project_order_projects (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id BIGINT NOT NULL,
      project_id UUID NOT NULL,
      relation_type TEXT NOT NULL DEFAULT 'related',
      is_primary BOOLEAN NOT NULL DEFAULT false,
      valid_from DATE NOT NULL DEFAULT now(),
      valid_to DATE
    );
  `);
}

// ---------------------------------------------------------------------------
// Seed: an order with milling_type_id/edge_type_id/film_id set on the header,
// and a detail with sheet_material_type_id set, material_id = NULL (post-034).
// ---------------------------------------------------------------------------
async function seedVariantBOrder(client: Client): Promise<{ orderId: number; smtId: number }> {
  // Ensure milling_type_id=1, edge_type_id=1 exist (inserted by bootstrap029).
  // Insert a film row for film_id reference.
  await client.query(`INSERT INTO films (film_id, film_name) VALUES (1, 'Плёнка тест') ON CONFLICT DO NOTHING`);

  // Insert order_statuses and payment_statuses needed by the header query joins.
  await client.query(`INSERT INTO order_statuses (order_status_id, order_status_name) VALUES (1, 'Новый') ON CONFLICT DO NOTHING`);
  await client.query(`INSERT INTO payment_statuses (payment_status_id, payment_status_name) VALUES (1, 'Не оплачен') ON CONFLICT DO NOTHING`);

  // Insert a sheet_material_type.
  const smtRes = await client.query<{ sheet_material_type_id: number }>(
    `INSERT INTO sheet_material_types (name, unit_id, material_type_id, width_mm, height_mm, is_active)
     VALUES ('МДФ VB read-repo тест', 1, 1, 2800, 2070, true)
     RETURNING sheet_material_type_id`,
  );
  const smtId = smtRes.rows[0].sheet_material_type_id;

  // Insert order with header refs set (milling_type_id=1, edge_type_id=1, film_id=1).
  // post-034: material_id=NULL on the order (sheet_material_type_id is authoritative).
  const orderRes = await client.query<{ order_id: number }>(
    `INSERT INTO orders (order_name, sheet_eligible, sheet_material_type_id, milling_type_id, edge_type_id, film_id,
       order_status_id, payment_status_id, total_amount, final_amount, paid_amount, parts_count, total_area,
       discount, surcharge)
     VALUES ('VB read-repo тест заказ', true, $1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0.24, 0, 0)
     RETURNING order_id`,
    [smtId],
  );
  const orderId = orderRes.rows[0].order_id;

  // Detail: material_id=NULL (Variant B), sheet_material_type_id=smtId.
  await client.query(
    `INSERT INTO order_details (order_id, detail_number, detail_name, height, width, quantity, area,
       material_id, sheet_material_type_id, milling_type_id, edge_type_id, priority)
     VALUES ($1, 1, 'VB read-repo деталь', 600, 400, 1, 0.24, NULL, $2, 1, 1, 100)`,
    [orderId, smtId],
  );

  return { orderId, smtId };
}

d('PgOrderReadRepository integration — both flag states (critic R3)', () => {
  const client = new Client({ connectionString: url });
  const schema = `vb_read_repo_${process.hrtime.bigint()}`;
  let orderId: number;
  let smtId: number;

  beforeAll(async () => {
    await client.connect();

    // Isolated schema — all objects land here, not in public.
    await client.query(`CREATE SCHEMA ${schema}`);
    await client.query(`SET search_path TO ${schema}, public`);

    // Apply the full Variant B forward chain.
    await bootstrapVariantBSchema(client);
    await seedVariantAMain(client);
    await client.query(mig('034_order_material_sunset_legacy.sql'));

    // Add stub tables required by the repository.
    await createStubTables(client);

    // Seed one Variant-B order (material_id=NULL on detail, header refs set).
    const seed = await seedVariantBOrder(client);
    orderId = seed.orderId;
    smtId = seed.smtId;
  });

  afterAll(async () => {
    try { await client.query('SET search_path TO public'); } catch { /* ignore */ }
    try { await client.query(`DROP SCHEMA ${schema} CASCADE`); } catch { /* ignore */ }
    // Clean up public stub tables created during this run (best-effort).
    try {
      await client.query('DROP TABLE IF EXISTS public.project_order_projects CASCADE');
      await client.query('DROP TABLE IF EXISTS public.project_projects CASCADE');
    } catch { /* ignore */ }
    await client.end();
  });

  // -----------------------------------------------------------------------
  // FINDING 1 — flag-ON listOrders GROUP BY SQL must not throw
  // -----------------------------------------------------------------------
  it('flag-ON: listOrders executes without SQL error (GROUP BY regression catch)', async () => {
    // sheetOrdersReads=true is the flag-ON state.
    const db = makeDbClient(client, schema);
    const repo = new PgOrderReadRepository(db, true);
    const result = await repo.listOrders(minimalListCommand());
    expect(result).toBeDefined();
    expect(result.data).toBeInstanceOf(Array);
    // Our seeded order should be in the results.
    expect(result.data.length).toBeGreaterThan(0);
  });

  it('flag-OFF: listOrders executes without SQL error (legacy path)', async () => {
    // sheetOrdersReads=false is the flag-OFF (legacy) state.
    const db = makeDbClient(client, schema);
    const repo = new PgOrderReadRepository(db, false);
    const result = await repo.listOrders(minimalListCommand());
    expect(result).toBeDefined();
    expect(result.data).toBeInstanceOf(Array);
  });

  it('flag-ON: listOrders returns sheetMaterialTypeIds populated and materialIds empty', async () => {
    const db = makeDbClient(client, schema);
    const repo = new PgOrderReadRepository(db, true);
    const result = await repo.listOrders(minimalListCommand());

    // Find our VB read-repo test order.
    const item = result.data.find((o) => o.orderId === Number(orderId));
    expect(item).toBeDefined();
    if (!item) return;

    // post-034: material_id is NULL → materialIds array should be empty.
    expect(item.materialIds).toEqual([]);
    // sheet_material_type_id is authoritative → sheetMaterialTypeIds should have smtId.
    expect(item.sheetMaterialTypeIds).toContain(Number(smtId));
  });

  // -----------------------------------------------------------------------
  // FINDING 2 — flag-ON getOrderById must preserve header milling/edge/film refs
  // -----------------------------------------------------------------------
  it('flag-ON: getOrderById executes without SQL error', async () => {
    const db = makeDbClient(client, schema);
    const repo = new PgOrderReadRepository(db, true);
    const order = await repo.getOrderById(getByIdCommand(orderId));
    expect(order).not.toBeNull();
  });

  it('flag-OFF: getOrderById executes without SQL error (legacy path)', async () => {
    const db = makeDbClient(client, schema);
    const repo = new PgOrderReadRepository(db, false);
    // Use the legacy-seeded order from seedVariantAMain (order_id=1).
    const order = await repo.getOrderById(getByIdCommand(1));
    expect(order).not.toBeNull();
  });

  it('flag-ON: getOrderById preserves milling_type_id in header', async () => {
    const db = makeDbClient(client, schema);
    const repo = new PgOrderReadRepository(db, true);
    const order = await repo.getOrderById(getByIdCommand(orderId));
    expect(order).not.toBeNull();
    // milling_type_id=1 was set on the order; must survive backend read.
    expect(order!.header.millingTypeId).toBe(1);
  });

  it('flag-ON: getOrderById preserves edge_type_id in header', async () => {
    const db = makeDbClient(client, schema);
    const repo = new PgOrderReadRepository(db, true);
    const order = await repo.getOrderById(getByIdCommand(orderId));
    expect(order).not.toBeNull();
    // edge_type_id=1 was set on the order; must survive backend read.
    expect(order!.header.edgeTypeId).toBe(1);
  });

  it('flag-ON: getOrderById preserves film_id in header', async () => {
    const db = makeDbClient(client, schema);
    const repo = new PgOrderReadRepository(db, true);
    const order = await repo.getOrderById(getByIdCommand(orderId));
    expect(order).not.toBeNull();
    // film_id=1 was set on the order; must survive backend read.
    expect(order!.header.filmId).toBe(1);
  });

  it('flag-ON: getOrderById returns materialId=null in header (Variant B contract)', async () => {
    const db = makeDbClient(client, schema);
    const repo = new PgOrderReadRepository(db, true);
    const order = await repo.getOrderById(getByIdCommand(orderId));
    expect(order).not.toBeNull();
    // Variant B: order.material_id is NULL post-034 (material_id sunset).
    expect(order!.header.materialId).toBeNull();
  });

  it('flag-ON: getOrderById detail has materialId=null and sheetMaterialTypeId set', async () => {
    const db = makeDbClient(client, schema);
    const repo = new PgOrderReadRepository(db, true);
    const order = await repo.getOrderById(getByIdCommand(orderId));
    expect(order).not.toBeNull();
    const detail = order!.details[0];
    expect(detail).toBeDefined();
    // Variant B: material_id is NULL on detail.
    expect(detail.materialId).toBeNull();
    // sheet_material_type_id is authoritative.
    expect(detail.sheetMaterialTypeId).toBe(Number(smtId));
  });

  it('flag-OFF: getOrderById returns basic data (legacy path sanity)', async () => {
    const db = makeDbClient(client, schema);
    const repo = new PgOrderReadRepository(db, false);
    // The legacy-seeded order (order_id=1) from seedVariantAMain
    const order = await repo.getOrderById(getByIdCommand(1));
    expect(order).not.toBeNull();
    expect(order!.header.orderId).toBe(1);
  });
});

// ---------------------------------------------------------------------------
// Critic R8: header-only order must expose headerMaterialName + headerSheetMaterialTypeId
// in the listOrders response (no details → empty materialNames aggregate → fallback).
// ---------------------------------------------------------------------------
d('PgOrderReadRepository integration — header-only order list fallback (critic R8)', () => {
  const client = new Client({ connectionString: url });
  const schema = `vb_r8_header_only_${process.hrtime.bigint()}`;
  let headerOnlyOrderId: number;
  let headerSmtId: number;

  beforeAll(async () => {
    await client.connect();
    await client.query(`CREATE SCHEMA ${schema}`);
    await client.query(`SET search_path TO ${schema}, public`);

    // Apply the full Variant B forward chain.
    await bootstrapVariantBSchema(client);
    await seedVariantAMain(client);
    await client.query(mig('034_order_material_sunset_legacy.sql'));
    await createStubTables(client);

    // Ensure required lookup rows exist.
    await client.query(`INSERT INTO films (film_id, film_name) VALUES (1, 'Плёнка тест') ON CONFLICT DO NOTHING`);
    await client.query(`INSERT INTO order_statuses (order_status_id, order_status_name) VALUES (1, 'Новый') ON CONFLICT DO NOTHING`);
    await client.query(`INSERT INTO payment_statuses (payment_status_id, payment_status_name) VALUES (1, 'Не оплачен') ON CONFLICT DO NOTHING`);

    // Insert a sheet_material_type.
    const smtRes = await client.query<{ sheet_material_type_id: number }>(
      `INSERT INTO sheet_material_types (name, unit_id, material_type_id, width_mm, height_mm, is_active)
       VALUES ('МДФ R8 header-only тест', 1, 1, 2800, 2070, true)
       RETURNING sheet_material_type_id`,
    );
    headerSmtId = smtRes.rows[0].sheet_material_type_id;

    // Insert a HEADER-ONLY order: has sheet_material_type_id on header, NO details.
    const orderRes = await client.query<{ order_id: number }>(
      `INSERT INTO orders (order_name, sheet_eligible, sheet_material_type_id,
         order_status_id, payment_status_id, total_amount, final_amount, paid_amount,
         parts_count, total_area, discount, surcharge)
       VALUES ('R8 Header-only тест заказ', true, $1, 1, 1, 0, 0, 0, 0, 0, 0, 0)
       RETURNING order_id`,
      [headerSmtId],
    );
    headerOnlyOrderId = orderRes.rows[0].order_id;
    // No details inserted — this is a header-only order.
  });

  afterAll(async () => {
    try { await client.query('SET search_path TO public'); } catch { /* ignore */ }
    try { await client.query(`DROP SCHEMA ${schema} CASCADE`); } catch { /* ignore */ }
    try {
      await client.query('DROP TABLE IF EXISTS public.project_order_projects CASCADE');
      await client.query('DROP TABLE IF EXISTS public.project_projects CASCADE');
    } catch { /* ignore */ }
    await client.end();
  });

  it('flag-ON: header-only order returns headerMaterialName populated in list item', async () => {
    const db = makeDbClient(client, schema);
    const repo = new PgOrderReadRepository(db, true);
    const result = await repo.listOrders(minimalListCommand());

    const item = result.data.find((o) => o.orderId === Number(headerOnlyOrderId));
    expect(item).toBeDefined();
    if (!item) return;

    // No details → materialNames/sheetMaterialTypeIds from detail aggregate must be empty.
    expect(item.materialNames).toEqual([]);
    expect(item.sheetMaterialTypeIds).toEqual([]);

    // Header fallback fields must be populated from orders.sheet_material_type_id.
    expect(item.headerMaterialName).toBe('МДФ R8 header-only тест');
    expect(item.headerSheetMaterialTypeId).toBe(Number(headerSmtId));
  });
});
