// backend/src/modules/orders/adapters/pg-order-read-repository-legacy.integration.ts
//
// Ephemeral-PG integration tests for PgOrderReadRepository with sheetOrdersReads=false
// on PRE-034 data — i.e. the real runtime state at fresh boot, rollback, or before
// BACKEND_SHEET_ORDERS_READS is flipped on.
//
// Critic R6 MAJOR fix: the original pg-order-read-repository.integration.ts ran
// "flag-OFF" tests on POST-034 data (material_id already NULL), so they only proved
// "no throw / not null" — not that the legacy SQL paths produce correct output.
//
// THIS file fixes that by building a dedicated isolated schema that applies migrations
// 029 + 030 + 033 (the Variant B pre-requisites) but NOT 034, then seeds LEGACY data
// (order_details.material_id POPULATED, real materials rows with material_name, and
// SP2-linked sheet types for context) and asserts REAL legacy outputs:
//   - detail.materialId is populated (non-null, matching seeded id)
//   - detail.materialName resolves from the materials catalog (legacy JOIN path)
//   - listOrders aggregate materialIds is non-empty and contains the seeded material id
//   - listOrders aggregate materialNames contains the seeded material_name
//   - sheetMaterialTypeIds is null/empty (flag-OFF produces NULL::bigint[])
//   - header.materialId (getOrderById) is populated (legacy o.material_id path)
//
// ISOLATION: runs inside a dedicated schema (vb_legacy_read_<hrtime>) — mirrors the
// approach in migration-034-rollback.integration.ts. Drop in afterAll.
//
// Gated on SHEET_INTEGRATION_DATABASE_URL.
import { Client } from 'pg';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import {
  bootstrapVariantBSchema,
} from './__fixtures__/variant-b-migration-fixture';
import { PgOrderReadRepository } from './pg-order-read-repository';
import type { DatabaseClient } from '../../../database/database.types';
import type { QueryResult, QueryResultRow } from 'pg';

const url = process.env.SHEET_INTEGRATION_DATABASE_URL;
const d = url ? describe : describe.skip;

// Wraps a pg.Client into the DatabaseClient interface expected by PgOrderReadRepository.
// Always sets the search_path before each query to ensure the correct schema is used.
function makeDbClient(client: Client, schema: string): DatabaseClient {
  return {
    async query<T extends QueryResultRow = QueryResultRow>(
      text: string,
      params?: readonly unknown[],
    ): Promise<QueryResult<T>> {
      await client.query(`SET search_path TO ${schema}, public`);
      return client.query<T>(text, params as unknown[]);
    },
  };
}

function minimalListCommand() {
  return {
    currentUser: { id: '1', username: 'admin', role: 'admin', permissions: [] } as never,
    query: {
      page: 1,
      pageSize: 20,
      sortBy: 'orderId' as const,
      sortOrder: 'desc' as const,
      onlyMyOrders: false,
    },
  };
}

function getByIdCommand(orderId: number) {
  return {
    currentUser: { id: '1', username: 'admin', role: 'admin', permissions: [] } as never,
    orderId,
  };
}

// ---------------------------------------------------------------------------
// Helper: create stub tables that the repo queries but are not in bootstrapVariantBSchema.
// Mirrors the approach in pg-order-read-repository.integration.ts.
// ---------------------------------------------------------------------------
async function createStubTables(client: Client): Promise<void> {
  await client.query(`
    ALTER TABLE orders ADD COLUMN IF NOT EXISTS production_status_from_details_enabled BOOLEAN NOT NULL DEFAULT false;
    ALTER TABLE orders ADD COLUMN IF NOT EXISTS link_cad_file TEXT;
    ALTER TABLE orders ADD COLUMN IF NOT EXISTS link_pdf_file TEXT;
    ALTER TABLE production_statuses ADD COLUMN IF NOT EXISTS production_status_code TEXT;
    ALTER TABLE production_statuses ADD COLUMN IF NOT EXISTS sort_order INT;
  `);

  await client.query(`
    CREATE TABLE IF NOT EXISTS payments (
      payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id BIGINT NOT NULL,
      type_paid_id BIGINT NOT NULL DEFAULT 1,
      amount NUMERIC NOT NULL DEFAULT 0,
      payment_date DATE NOT NULL DEFAULT now(),
      notes TEXT,
      ref_key_1c UUID,
      delete_flag BOOLEAN NOT NULL DEFAULT false
    );
  `);

  await client.query(`
    CREATE TABLE IF NOT EXISTS order_workshops (
      order_workshop_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id BIGINT NOT NULL,
      workshop_id BIGINT NOT NULL DEFAULT 1,
      production_status_id SMALLINT NOT NULL DEFAULT 1,
      received_date DATE,
      started_date DATE,
      completed_date DATE,
      planned_completion_date DATE,
      sequence_order INT,
      responsible_employee_id BIGINT,
      notes TEXT,
      ref_key_1c UUID,
      delete_flag BOOLEAN NOT NULL DEFAULT false
    );
  `);

  await client.query(`
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS requirement_id BIGINT;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS order_id BIGINT;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS resource_type TEXT NOT NULL DEFAULT 'material';
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS film_id BIGINT;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS edge_type_id BIGINT;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS required_quantity NUMERIC NOT NULL DEFAULT 0;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS unit_id SMALLINT NOT NULL DEFAULT 1;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS waste_percentage NUMERIC;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS final_quantity NUMERIC;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS requirement_status_id SMALLINT NOT NULL DEFAULT 1;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS supplier_id BIGINT;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS purchase_price NUMERIC;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS requisition_id BIGINT;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS warehouse_id BIGINT;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS reserved_at TIMESTAMP;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS consumed_at TIMESTAMP;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS notes TEXT;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS calculation_details JSONB;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS ref_key_1c UUID;
    ALTER TABLE order_resource_requirements ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true;
  `);

  await client.query(`
    CREATE TABLE IF NOT EXISTS production_status_events (
      event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id BIGINT NOT NULL,
      production_status_id SMALLINT NOT NULL
    );
  `);

  // Group-link tables must live in public schema (repo queries them as public.*)
  await client.query(`
    CREATE TABLE IF NOT EXISTS public.group_groups (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      code TEXT NOT NULL DEFAULT '',
      name TEXT NOT NULL DEFAULT ''
    );
  `);
  await client.query(`
    CREATE TABLE IF NOT EXISTS public.group_order_groups (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id BIGINT NOT NULL,
      group_id UUID NOT NULL,
      relation_type TEXT NOT NULL DEFAULT 'related',
      is_primary BOOLEAN NOT NULL DEFAULT false,
      valid_from DATE NOT NULL DEFAULT now(),
      valid_to DATE
    );
  `);
}

// ---------------------------------------------------------------------------
// Seed LEGACY (pre-034) data:
//   - a real (non-shadow) material with a known material_name
//   - an order with order_details.material_id POPULATED (non-null, pointing to that material)
//   - an SP2-linked sheet type (for context, but detail does NOT reference it — pure legacy)
//   - order_statuses / payment_statuses rows needed by the header query joins
// This simulates the exact data shape that exists on fresh boot (before 034 runs).
// ---------------------------------------------------------------------------
interface LegacySeed {
  orderId: number;
  materialId: number;
  materialName: string;
}

async function seedLegacyOrder(client: Client): Promise<LegacySeed> {
  const MATERIAL_NAME = 'ЛДСП Дуб 16мм (legacy-тест)';

  // Lookup rows for header query joins
  await client.query(`INSERT INTO order_statuses (order_status_id, order_status_name) VALUES (1, 'Новый') ON CONFLICT DO NOTHING`);
  await client.query(`INSERT INTO payment_statuses (payment_status_id, payment_status_name) VALUES (1, 'Не оплачен') ON CONFLICT DO NOTHING`);

  // A real (non-shadow) material — this is the legacy path material_id points to.
  // is_sheet_shadow=false (default added by migration 029 which bootstrapVariantBSchema applies).
  const matRes = await client.query<{ material_id: number }>(
    `INSERT INTO materials (material_name, unit_id, material_type_id, is_sheet_shadow)
     VALUES ($1, 1, 1, false)
     RETURNING material_id`,
    [MATERIAL_NAME],
  );
  const materialId = matRes.rows[0].material_id;

  // Order with material_id on header (legacy header-material path).
  // sheet_material_type_id is NULL (pre-034 fresh order that never used SP3).
  const orderRes = await client.query<{ order_id: number }>(
    `INSERT INTO orders (order_name, material_id, sheet_eligible, order_status_id, payment_status_id,
       total_amount, final_amount, paid_amount, parts_count, total_area, discount, surcharge)
     VALUES ('Legacy-тест заказ (pre-034)', $1, false, 1, 1, 0, 0, 0, 1, 0.24, 0, 0)
     RETURNING order_id`,
    [materialId],
  );
  const orderId = orderRes.rows[0].order_id;

  // Detail: material_id POPULATED (non-null) — legacy shape, sheet_material_type_id NULL.
  // The 030 trigger only fires on shadow materials; non-shadow passes through freely.
  await client.query(
    `INSERT INTO order_details (order_id, detail_number, detail_name, height, width, quantity, area,
       material_id, sheet_material_type_id, milling_type_id, edge_type_id, priority)
     VALUES ($1, 1, 'Legacy-тест деталь', 600, 400, 1, 0.24, $2, NULL, 1, 1, 100)`,
    [orderId, materialId],
  );

  return { orderId, materialId, materialName: MATERIAL_NAME };
}

// ---------------------------------------------------------------------------
// Test suite: flag-OFF on pre-034 data — real legacy output assertions
// ---------------------------------------------------------------------------
d('PgOrderReadRepository — flag-OFF legacy-path on PRE-034 data (critic R6 MAJOR fix)', () => {
  const client = new Client({ connectionString: url });
  // Unique schema — never collides with sibling integration suites
  const schema = `vb_legacy_read_${process.hrtime.bigint()}`;
  let seed: LegacySeed;

  beforeAll(async () => {
    await client.connect();

    // Create isolated schema; all DDL/DML lands here, not in public.
    await client.query(`CREATE SCHEMA ${schema}`);
    await client.query(`SET search_path TO ${schema}, public`);

    // Apply bootstrap + 030 + 033 only — NOT 034. This is the real pre-cutover state.
    await bootstrapVariantBSchema(client);

    // Add stub tables required by the repository (same as the post-034 suite).
    await createStubTables(client);

    // Seed legacy data: material_id populated on detail, materialName in materials catalog.
    seed = await seedLegacyOrder(client);
  });

  afterAll(async () => {
    try { await client.query('SET search_path TO public'); } catch { /* ignore */ }
    try { await client.query(`DROP SCHEMA ${schema} CASCADE`); } catch { /* ignore */ }
    // best-effort cleanup of public stub tables
    try {
      await client.query('DROP TABLE IF EXISTS public.group_order_groups CASCADE');
      await client.query('DROP TABLE IF EXISTS public.group_groups CASCADE');
    } catch { /* ignore */ }
    await client.end();
  });

  // -------------------------------------------------------------------------
  // listOrders: flag-OFF legacy path assertions
  // -------------------------------------------------------------------------

  it('flag-OFF/pre-034: listOrders executes without SQL error', async () => {
    const db = makeDbClient(client, schema);
    const repo = new PgOrderReadRepository(db, false);
    const result = await repo.listOrders(minimalListCommand());
    expect(result).toBeDefined();
    expect(result.data).toBeInstanceOf(Array);
    expect(result.data.length).toBeGreaterThan(0);
  });

  it('flag-OFF/pre-034: listOrders materialIds is POPULATED (non-empty) from legacy material_id path', async () => {
    // This is the key assertion: if the flag-OFF branch were broken (e.g. wrong JOIN),
    // materialIds would be empty/null instead of containing the seeded material_id.
    const db = makeDbClient(client, schema);
    const repo = new PgOrderReadRepository(db, false);
    const result = await repo.listOrders(minimalListCommand());

    const item = result.data.find((o) => o.orderId === Number(seed.orderId));
    expect(item).toBeDefined();
    if (!item) return;

    // Legacy path: material_id on detail is non-null → materialIds must be non-empty.
    expect(item.materialIds).not.toBeNull();
    expect(item.materialIds.length).toBeGreaterThan(0);
    // Must contain the exact seeded material_id.
    expect(item.materialIds).toContain(Number(seed.materialId));
  });

  it('flag-OFF/pre-034: listOrders materialNames resolved from materials catalog (legacy JOIN)', async () => {
    // If the legacy LEFT JOIN materials were missing or broken, materialNames would be null/empty.
    const db = makeDbClient(client, schema);
    const repo = new PgOrderReadRepository(db, false);
    const result = await repo.listOrders(minimalListCommand());

    const item = result.data.find((o) => o.orderId === Number(seed.orderId));
    expect(item).toBeDefined();
    if (!item) return;

    // The legacy m.material_name path must resolve the seeded name.
    expect(item.materialNames).not.toBeNull();
    expect(item.materialNames.length).toBeGreaterThan(0);
    expect(item.materialNames).toContain(seed.materialName);
  });

  it('flag-OFF/pre-034: listOrders sheetMaterialTypeIds is null/empty (legacy flag-OFF contract)', async () => {
    // flag-OFF produces NULL::bigint[] for sheetMaterialTypeIds — never populated.
    const db = makeDbClient(client, schema);
    const repo = new PgOrderReadRepository(db, false);
    const result = await repo.listOrders(minimalListCommand());

    const item = result.data.find((o) => o.orderId === Number(seed.orderId));
    expect(item).toBeDefined();
    if (!item) return;

    // NULL::bigint[] maps to empty array via toNumberArray.
    expect(item.sheetMaterialTypeIds).toEqual([]);
  });

  // -------------------------------------------------------------------------
  // getOrderById: flag-OFF legacy path assertions
  // -------------------------------------------------------------------------

  it('flag-OFF/pre-034: getOrderById executes without SQL error', async () => {
    const db = makeDbClient(client, schema);
    const repo = new PgOrderReadRepository(db, false);
    const order = await repo.getOrderById(getByIdCommand(seed.orderId));
    expect(order).not.toBeNull();
  });

  it('flag-OFF/pre-034: getOrderById header.materialId is POPULATED (non-null) from o.material_id', async () => {
    // The legacy flag-OFF branch reads o.material_id directly on the header SELECT.
    // If broken (e.g. uses NULL::bigint like flag-ON), materialId would be null.
    const db = makeDbClient(client, schema);
    const repo = new PgOrderReadRepository(db, false);
    const order = await repo.getOrderById(getByIdCommand(seed.orderId));
    expect(order).not.toBeNull();

    // header.materialId must be the seeded material_id (non-null, legacy path).
    expect(order!.header.materialId).toBe(Number(seed.materialId));
  });

  it('flag-OFF/pre-034: getOrderById header.materialName resolved from materials JOIN (legacy path)', async () => {
    // Legacy header: LEFT JOIN materials m ON m.material_id = o.material_id → m.material_name.
    // If the JOIN is absent or wrong, materialName would be null.
    const db = makeDbClient(client, schema);
    const repo = new PgOrderReadRepository(db, false);
    const order = await repo.getOrderById(getByIdCommand(seed.orderId));
    expect(order).not.toBeNull();

    expect(order!.header.materialName).toBe(seed.materialName);
  });

  it('flag-OFF/pre-034: getOrderById detail.materialId is POPULATED (non-null, legacy material_id)', async () => {
    // The legacy flag-OFF detail SELECT reads od.material_id directly.
    // If broken, detail.materialId would be null.
    const db = makeDbClient(client, schema);
    const repo = new PgOrderReadRepository(db, false);
    const order = await repo.getOrderById(getByIdCommand(seed.orderId));
    expect(order).not.toBeNull();
    expect(order!.details.length).toBeGreaterThan(0);

    const detail = order!.details[0];
    expect(detail.materialId).toBe(Number(seed.materialId));
  });

  it('flag-OFF/pre-034: getOrderById detail.materialName resolved from materials catalog (legacy JOIN)', async () => {
    // Legacy detail: LEFT JOIN materials m ON m.material_id = od.material_id → m.material_name.
    // If the JOIN were broken, materialName would be null.
    const db = makeDbClient(client, schema);
    const repo = new PgOrderReadRepository(db, false);
    const order = await repo.getOrderById(getByIdCommand(seed.orderId));
    expect(order).not.toBeNull();
    expect(order!.details.length).toBeGreaterThan(0);

    const detail = order!.details[0];
    expect(detail.materialName).toBe(seed.materialName);
  });

  it('flag-OFF/pre-034: getOrderById detail.sheetMaterialTypeId is null (pre-034 legacy, no sheet column set)', async () => {
    // Pre-034 legacy detail: sheet_material_type_id IS NULL on the row.
    const db = makeDbClient(client, schema);
    const repo = new PgOrderReadRepository(db, false);
    const order = await repo.getOrderById(getByIdCommand(seed.orderId));
    expect(order).not.toBeNull();
    expect(order!.details.length).toBeGreaterThan(0);

    const detail = order!.details[0];
    expect(detail.sheetMaterialTypeId).toBeNull();
  });
});
