import { randomUUID } from 'node:crypto';
import { Pool, type PoolClient } from 'pg';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import type { DatabaseService } from '../../../database/database.service';
import type { TransactionClient } from '../../../database/database.types';
import {
  resolveShadowMaterialId,
  allocateUniqueShadowName,
  ShadowNameConflictError,
  type ShadowContext,
  type ShadowMaterialAuditInput,
} from './shadow-material';

// ---------------------------------------------------------------------------
// Env gating — mirrors pg-sheet-materials.integration.ts exactly.
// ---------------------------------------------------------------------------
const required = process.env.SHEET_INTEGRATION_REQUIRED === '1';
const databaseUrl = required
  ? process.env.SHEET_INTEGRATION_DATABASE_URL
  : process.env.SHEET_INTEGRATION_DATABASE_URL ?? process.env.TEST_DATABASE_URL;
if (required && !databaseUrl) {
  throw new Error('SHEET_INTEGRATION_DATABASE_URL is required for test:backend:sheet-integration');
}
const describeIntegration = databaseUrl ? describe : describe.skip;

// Per-run isolated schema.
const schemaName = `shadow_material_${randomUUID().replaceAll('-', '_')}`;

// ---------------------------------------------------------------------------
// Schema: minimal tables the resolver touches.
// ---------------------------------------------------------------------------
async function createSchema(client: PoolClient): Promise<void> {
  await client.query(`
    CREATE TABLE material_types (
      material_type_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      material_type_name TEXT
    );
    INSERT INTO material_types (material_type_id, material_type_name) VALUES (1,'ЛДСП'),(2,'МДФ');

    CREATE TABLE units (
      unit_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      unit_name TEXT
    );
    INSERT INTO units (unit_id, unit_name) VALUES (1,'шт'),(2,'м2');

    CREATE TABLE sheet_material_types (
      sheet_material_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(200) NOT NULL UNIQUE,
      material_type_id SMALLINT NOT NULL,
      unit_id SMALLINT NOT NULL,
      thickness_mm NUMERIC(10,2) NOT NULL,
      width_mm NUMERIC(10,2) NOT NULL,
      height_mm NUMERIC(10,2) NOT NULL,
      is_active BOOLEAN NOT NULL DEFAULT true,
      ref_key_1c UUID NULL
    );

    CREATE TABLE materials (
      material_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      material_name VARCHAR(200) NOT NULL,
      unit_id SMALLINT NOT NULL,
      material_type_id SMALLINT,
      is_active BOOLEAN NOT NULL DEFAULT true,
      ref_key_1c UUID NULL,
      is_sheet_shadow BOOLEAN NOT NULL DEFAULT false,
      shadow_of_sheet_material_type_id BIGINT NULL,
      sheet_material_type_id BIGINT NULL,
      created_by BIGINT,
      edited_by BIGINT,
      created_at TIMESTAMP DEFAULT now(),
      updated_at TIMESTAMP DEFAULT now(),
      CONSTRAINT uq_materials_name UNIQUE (material_name)
    );
    CREATE UNIQUE INDEX uq_materials_shadow_of
      ON materials(shadow_of_sheet_material_type_id)
      WHERE shadow_of_sheet_material_type_id IS NOT NULL;
  `);
}

// ---------------------------------------------------------------------------
// makeDatabase helper — mirrors the harness in pg-sheet-materials.integration.ts.
// ---------------------------------------------------------------------------
function makeDatabase(pool: Pool): DatabaseService {
  const query = (text: string, params: readonly unknown[] = []) => pool.query(text, [...params]);
  return {
    isConfigured: true,
    query,
    async transaction<T>(handler: (client: TransactionClient) => Promise<T>): Promise<T> {
      const client = await pool.connect();
      try {
        await client.query('BEGIN');
        await client.query(`SET search_path TO ${schemaName}`);
        const tx: TransactionClient = {
          raw: client as never,
          query: (text: string, params: readonly unknown[] = []) => client.query(text, [...params]),
        };
        const result = await handler(tx);
        await client.query('COMMIT');
        return result;
      } catch (error) {
        await client.query('ROLLBACK').catch(() => undefined);
        throw error;
      } finally {
        client.release();
      }
    },
  } as unknown as DatabaseService;
}

// ---------------------------------------------------------------------------
// Test helpers.
// ---------------------------------------------------------------------------
function makeCtx(overrides: Partial<ShadowContext> = {}): ShadowContext {
  return {
    actorUserId: 1,
    requestId: randomUUID(),
    source: 'backend-orders-command',
    clientId: null,
    orderId: null,
    ...overrides,
  };
}

function makeAuditCollector(): { calls: ShadowMaterialAuditInput[]; fn: (i: ShadowMaterialAuditInput) => Promise<void> } {
  const calls: ShadowMaterialAuditInput[] = [];
  return {
    calls,
    fn: async (i) => {
      calls.push(i);
    },
  };
}

// ---------------------------------------------------------------------------
// Suite.
// ---------------------------------------------------------------------------
describeIntegration('resolveShadowMaterialId (integration)', () => {
  let pool: Pool;
  let db: DatabaseService;

  beforeAll(async () => {
    pool = new Pool({ connectionString: databaseUrl, max: 5 });
    const client = await pool.connect();
    try {
      await client.query(`CREATE SCHEMA ${schemaName}`);
      await client.query(`SET search_path TO ${schemaName}`);
      await createSchema(client);
    } finally {
      client.release();
    }
    pool.on('connect', (c) => void c.query(`SET search_path TO ${schemaName}`));
    db = makeDatabase(pool);
  });

  afterAll(async () => {
    if (pool) {
      await pool.query(`DROP SCHEMA IF EXISTS ${schemaName} CASCADE`);
      await pool.end();
    }
  });

  beforeEach(async () => {
    await pool.query('TRUNCATE sheet_material_types, materials RESTART IDENTITY CASCADE');
  });

  // -------------------------------------------------------------------------
  // Helper: insert a sheet_material_type row, return its id.
  // -------------------------------------------------------------------------
  async function insertSheetType(opts: {
    name: string;
    materialTypeId?: number;
    unitId?: number;
    isActive?: boolean;
    refKey1c?: string | null;
  }): Promise<number> {
    const { name, materialTypeId = 1, unitId = 1, isActive = true, refKey1c = null } = opts;
    const res = await pool.query(
      `INSERT INTO sheet_material_types (name, material_type_id, unit_id, thickness_mm, width_mm, height_mm, is_active, ref_key_1c)
       VALUES ($1, $2, $3, 16, 2800, 2070, $4, $5)
       RETURNING sheet_material_type_id`,
      [name, materialTypeId, unitId, isActive, refKey1c],
    );
    return Number(res.rows[0].sheet_material_type_id);
  }

  // =========================================================================
  // Group 1: REAL SP2 ROW NOT TOUCHED
  // =========================================================================
  it('Group 1 — real SP2 row not touched; shadow created with correct flags', async () => {
    const sheetId = await insertSheetType({ name: 'ЛДСП 16' });

    // Insert a REAL catalog material linked to this sheet type via sheet_material_type_id
    // (SP2-style), but NOT a shadow (is_sheet_shadow=false, shadow_of_sheet_material_type_id=NULL).
    await pool.query(
      `INSERT INTO materials (material_name, unit_id, material_type_id, is_active, is_sheet_shadow, shadow_of_sheet_material_type_id, sheet_material_type_id)
       VALUES ('Реальный', 1, 1, true, false, NULL, $1)`,
      [sheetId],
    );

    const { calls, fn } = makeAuditCollector();
    const shadowId = await db.transaction((tx) => resolveShadowMaterialId(tx, sheetId, makeCtx(), fn));

    // Must NOT have returned the real row's id.
    const realRow = await pool.query(
      `SELECT material_id FROM materials WHERE material_name='Реальный'`,
    );
    const realId = Number(realRow.rows[0].material_id);
    expect(shadowId).not.toBe(realId);

    // Real row untouched.
    const realCheck = await pool.query(
      `SELECT material_name, unit_id, material_type_id, is_active FROM materials WHERE material_id=$1`,
      [realId],
    );
    expect(realCheck.rows[0].material_name).toBe('Реальный');
    expect(Number(realCheck.rows[0].unit_id)).toBe(1);
    expect(Number(realCheck.rows[0].material_type_id)).toBe(1);
    expect(realCheck.rows[0].is_active).toBe(true);

    // Created shadow row has correct flags.
    const shadowRow = await pool.query(
      `SELECT is_sheet_shadow, shadow_of_sheet_material_type_id, sheet_material_type_id, ref_key_1c
       FROM materials WHERE material_id=$1`,
      [shadowId],
    );
    expect(shadowRow.rows[0].is_sheet_shadow).toBe(true);
    expect(Number(shadowRow.rows[0].shadow_of_sheet_material_type_id)).toBe(sheetId);
    expect(shadowRow.rows[0].sheet_material_type_id).toBeNull();
    expect(shadowRow.rows[0].ref_key_1c).toBeNull();

    // Audit: one shadow_create.
    expect(calls).toHaveLength(1);
    expect(calls[0].action).toBe('shadow_create');
  });

  // =========================================================================
  // Group 2: CREATE + IDEMPOTENT
  // =========================================================================
  it('Group 2 — first resolve creates shadow with disambiguated name; second is idempotent', async () => {
    const sheetId = await insertSheetType({ name: 'МДФ 8', unitId: 2, materialTypeId: 2, isActive: true });

    const { calls: calls1, fn: fn1 } = makeAuditCollector();
    const id1 = await db.transaction((tx) => resolveShadowMaterialId(tx, sheetId, makeCtx(), fn1));

    // Shadow name must be disambiguated (always `<name> [лист #id]`).
    const expectedName = `МДФ 8 [лист #${sheetId}]`;
    const row = await pool.query(`SELECT material_name, unit_id, material_type_id, is_active FROM materials WHERE material_id=$1`, [id1]);
    expect(row.rows[0].material_name).toBe(expectedName);
    expect(Number(row.rows[0].unit_id)).toBe(2);
    expect(Number(row.rows[0].material_type_id)).toBe(2);
    expect(row.rows[0].is_active).toBe(true);

    // Audit: one shadow_create with that name.
    expect(calls1).toHaveLength(1);
    expect(calls1[0].action).toBe('shadow_create');
    expect(calls1[0].name).toBe(expectedName);

    // Second resolve: same id, no new audit.
    const { calls: calls2, fn: fn2 } = makeAuditCollector();
    const id2 = await db.transaction((tx) => resolveShadowMaterialId(tx, sheetId, makeCtx(), fn2));
    expect(id2).toBe(id1);
    expect(calls2).toHaveLength(0);
  });

  // =========================================================================
  // Group 3: PLAIN NAME STAYS FREE
  // =========================================================================
  it('Group 3 — plain sheet name not claimed by shadow; real material can use it', async () => {
    const sheetId = await insertSheetType({ name: 'Z-type' });
    const { fn } = makeAuditCollector();
    await db.transaction((tx) => resolveShadowMaterialId(tx, sheetId, makeCtx(), fn));

    // Now insert a real material with the EXACT plain name — must not violate uq_materials_name.
    await expect(
      pool.query(`INSERT INTO materials (material_name, unit_id, material_type_id) VALUES ('Z-type', 1, 1)`),
    ).resolves.not.toThrow();
  });

  // =========================================================================
  // Group 4: CONCURRENCY
  // =========================================================================
  it('Group 4 — concurrent resolves produce exactly one shadow row, both return same id', async () => {
    const sheetId = await insertSheetType({ name: 'Concurrent sheet' });

    const { fn: fn1 } = makeAuditCollector();
    const { fn: fn2 } = makeAuditCollector();

    const [idA, idB] = await Promise.all([
      db.transaction((tx) => resolveShadowMaterialId(tx, sheetId, makeCtx({ requestId: 'req-A' }), fn1)),
      db.transaction((tx) => resolveShadowMaterialId(tx, sheetId, makeCtx({ requestId: 'req-B' }), fn2)),
    ]);

    // Both calls returned the same id.
    expect(idA).toBe(idB);

    // Exactly one shadow row in DB.
    const count = await pool.query(
      `SELECT count(*) FROM materials WHERE shadow_of_sheet_material_type_id=$1`,
      [sheetId],
    );
    expect(Number(count.rows[0].count)).toBe(1);
  });

  // =========================================================================
  // Group 5: REF_KEY SAFETY
  // =========================================================================
  it('Group 5 — shadow ref_key_1c is NULL even when sheet type and a real material share same ref_key_1c', async () => {
    const refKey = randomUUID();
    const sheetId = await insertSheetType({ name: 'RefKey sheet', refKey1c: refKey });

    // Real material with same ref_key_1c.
    await pool.query(
      `INSERT INTO materials (material_name, unit_id, material_type_id, ref_key_1c) VALUES ('Реальный с ref_key', 1, 1, $1)`,
      [refKey],
    );

    const { fn } = makeAuditCollector();
    // Must not throw a unique violation.
    const shadowId = await db.transaction((tx) => resolveShadowMaterialId(tx, sheetId, makeCtx(), fn));

    const shadowRow = await pool.query(`SELECT ref_key_1c FROM materials WHERE material_id=$1`, [shadowId]);
    expect(shadowRow.rows[0].ref_key_1c).toBeNull();
  });

  // =========================================================================
  // Group 6a: MAX-LENGTH name fits in VARCHAR(200)
  // =========================================================================
  it('Group 6a — very long sheet name produces shadow name ≤ 200 chars', async () => {
    // 200-character name.
    const longName = 'Л'.repeat(200);
    const sheetId = await insertSheetType({ name: longName });

    const { fn } = makeAuditCollector();
    const shadowId = await db.transaction((tx) => resolveShadowMaterialId(tx, sheetId, makeCtx(), fn));

    const row = await pool.query(`SELECT material_name FROM materials WHERE material_id=$1`, [shadowId]);
    const shadowName: string = row.rows[0].material_name;
    expect(shadowName.length).toBeLessThanOrEqual(200);
  });

  // =========================================================================
  // Group 6b: MANY COLLISIONS — open-ended search finds a free slot
  // =========================================================================
  it('Group 6b — 8 pre-seeded collisions; resolver finds slot at collision 9', async () => {
    const baseName = 'Столешница';
    const sheetId = await insertSheetType({ name: baseName });

    // Pre-seed collisions: `<name> [лист #id]`, `<name> [лист #id-2]` .. `<name> [лист #id-8]`
    const suffix1 = ` [лист #${sheetId}]`;
    await pool.query(`INSERT INTO materials (material_name, unit_id, material_type_id) VALUES ($1, 1, 1)`, [
      `${baseName.slice(0, 200 - suffix1.length)}${suffix1}`,
    ]);
    for (let k = 2; k <= 8; k++) {
      const suffixK = ` [лист #${sheetId}-${k}]`;
      await pool.query(`INSERT INTO materials (material_name, unit_id, material_type_id) VALUES ($1, 1, 1)`, [
        `${baseName.slice(0, 200 - suffixK.length)}${suffixK}`,
      ]);
    }

    const { calls, fn } = makeAuditCollector();
    const shadowId = await db.transaction((tx) => resolveShadowMaterialId(tx, sheetId, makeCtx(), fn));

    // Must succeed (no error) and produce a row with a valid name.
    const row = await pool.query(`SELECT material_name FROM materials WHERE material_id=$1`, [shadowId]);
    const shadowName: string = row.rows[0].material_name;
    expect(shadowName.length).toBeLessThanOrEqual(200);
    expect(shadowName).toContain(`[лист #${sheetId}`);

    // Audit: one shadow_create.
    expect(calls).toHaveLength(1);
    expect(calls[0].action).toBe('shadow_create');
  });

  // =========================================================================
  // Group 7: SYNC-ON-REUSE + NO-OP
  // =========================================================================
  it('Group 7 — shadow syncs when sheet type changes; no-op on second call with no change', async () => {
    const sheetId = await insertSheetType({ name: 'Старое имя', unitId: 1, materialTypeId: 1, isActive: true });

    // First resolve: create shadow.
    const { fn: fn1 } = makeAuditCollector();
    const shadowId = await db.transaction((tx) => resolveShadowMaterialId(tx, sheetId, makeCtx(), fn1));

    // Mutate the sheet type: name, is_active, unit_id, material_type_id.
    await pool.query(
      `UPDATE sheet_material_types SET name='Новое имя', is_active=false, unit_id=2, material_type_id=2 WHERE sheet_material_type_id=$1`,
      [sheetId],
    );

    // Second resolve: shadow must sync.
    const { calls: calls2, fn: fn2 } = makeAuditCollector();
    const id2 = await db.transaction((tx) => resolveShadowMaterialId(tx, sheetId, makeCtx(), fn2));
    expect(id2).toBe(shadowId);
    expect(calls2).toHaveLength(1);
    expect(calls2[0].action).toBe('shadow_sync');

    // Shadow row reflects the new sheet name (still disambiguated).
    const row = await pool.query(
      `SELECT material_name, unit_id, material_type_id, is_active FROM materials WHERE material_id=$1`,
      [shadowId],
    );
    const expectedSyncName = `Новое имя [лист #${sheetId}]`;
    expect(row.rows[0].material_name).toBe(expectedSyncName);
    expect(Number(row.rows[0].unit_id)).toBe(2);
    expect(Number(row.rows[0].material_type_id)).toBe(2);
    expect(row.rows[0].is_active).toBe(false);

    // Third resolve: no further change → true no-op (no new audit).
    const { calls: calls3, fn: fn3 } = makeAuditCollector();
    const id3 = await db.transaction((tx) => resolveShadowMaterialId(tx, sheetId, makeCtx(), fn3));
    expect(id3).toBe(shadowId);
    expect(calls3).toHaveLength(0);

    // Row stable.
    const rowAfter = await pool.query(`SELECT material_name FROM materials WHERE material_id=$1`, [shadowId]);
    expect(rowAfter.rows[0].material_name).toBe(expectedSyncName);
  });
});
