import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { Pool, type QueryResultRow } from 'pg';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { AuditService } from '../../common/audit/audit.service';
import type { DatabaseService } from '../../database/database.service';
import type { TransactionClient } from '../../database/database.types';
import { PgCrmSourceRepository } from './adapters/pg-crm-source-repository';
import { PgCrmSyncMappingRepository } from './adapters/pg-crm-sync-mapping-repository';
import { PgCrmSyncOutboxRepository } from './adapters/pg-crm-sync-outbox-repository';
import {
  Bitrix24ApiError,
  type Bitrix24ApiPort,
} from './adapters/bitrix24-api-client';
import { Bitrix24SyncConsumer } from './application/bitrix24-sync-consumer';
import { CrmSyncRelayService } from './application/crm-sync-relay.service';
import type { CrmSyncRuntimeConfigService } from './http/crm-sync-runtime-config.service';

const databaseUrl =
  process.env.CRM_SYNC_INTEGRATION_DATABASE_URL ?? process.env.TEST_DATABASE_URL;
const describeIntegration = databaseUrl ? describe : describe.skip;
const schemaName = `bitrix_sync_${randomUUID().replaceAll('-', '_')}`;

async function bootstrap(pool: Pool): Promise<void> {
  await pool.query(`
    CREATE TABLE order_statuses (
      order_status_id SMALLINT PRIMARY KEY,
      order_status_name TEXT NOT NULL
    );
    CREATE TABLE payment_statuses (
      payment_status_id SMALLINT PRIMARY KEY,
      payment_status_name TEXT NOT NULL
    );
    CREATE TABLE payment_types (
      type_paid_id BIGINT PRIMARY KEY,
      type_paid_name TEXT NOT NULL
    );
    INSERT INTO order_statuses VALUES (1, 'Новый');
    INSERT INTO payment_statuses VALUES (1, 'Не оплачен');
    INSERT INTO payment_types VALUES (1, 'Наличные');

    CREATE TABLE clients (
      client_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      client_name TEXT NOT NULL,
      notes TEXT,
      is_active BOOLEAN NOT NULL DEFAULT true
    );
    CREATE TABLE client_phones (
      phone_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      client_id BIGINT NOT NULL REFERENCES clients(client_id) ON DELETE CASCADE,
      phone_number TEXT NOT NULL,
      phone_type TEXT NOT NULL DEFAULT 'mobile',
      is_primary BOOLEAN NOT NULL DEFAULT false
    );
    CREATE TABLE orders (
      order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_name TEXT NOT NULL,
      client_id BIGINT NOT NULL REFERENCES clients(client_id),
      total_amount NUMERIC(12,2),
      final_amount NUMERIC(12,2),
      paid_amount NUMERIC(12,2),
      order_date DATE,
      completion_date DATE,
      delete_flag BOOLEAN NOT NULL DEFAULT false,
      order_status_id SMALLINT REFERENCES order_statuses(order_status_id),
      payment_status_id SMALLINT REFERENCES payment_statuses(payment_status_id)
    );
    CREATE TABLE payments (
      payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id BIGINT NOT NULL REFERENCES orders(order_id),
      type_paid_id BIGINT NOT NULL REFERENCES payment_types(type_paid_id),
      amount NUMERIC(12,2) NOT NULL,
      payment_date DATE NOT NULL,
      notes TEXT,
      delete_flag BOOLEAN NOT NULL DEFAULT false
    );

    CREATE TABLE audit_log (
      audit_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      event TEXT NOT NULL,
      action TEXT GENERATED ALWAYS AS (event) STORED,
      entity_type TEXT,
      entity_id TEXT,
      user_id BIGINT,
      username TEXT,
      role_code TEXT,
      role TEXT,
      request_id TEXT NOT NULL,
      source TEXT,
      related_order_id BIGINT,
      related_client_id BIGINT,
      related_payment_id BIGINT,
      related_production_event_id BIGINT,
      related_deadline_id BIGINT,
      related_user_id BIGINT,
      status_field TEXT,
      status_id BIGINT,
      status_name TEXT,
      status_code TEXT,
      stage_code TEXT,
      before_json JSONB,
      after_json JSONB,
      diff_json JSONB,
      metadata_json JSONB,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE TABLE audit_log_related_entity (
      audit_id UUID NOT NULL REFERENCES audit_log(audit_id) ON DELETE CASCADE,
      entity_type TEXT NOT NULL,
      entity_id BIGINT NOT NULL,
      PRIMARY KEY (audit_id, entity_type, entity_id)
    );
  `);

  for (const migration of [
    '025_twenty_crm_sync.sql',
    '028_crm_sync_enqueue_field_fix.sql',
    '073_bitrix24_crm_sync.sql',
    '074_bitrix24_payment_delivery_guards.sql',
  ]) {
    const sql = readFileSync(
      join(__dirname, `../../../db/migrations/${migration}`),
      'utf8',
    );
    await pool.query(sql);
  }
}

interface StubPayment {
  dealId: string;
  fields: Record<string, unknown>;
}

class StubBitrix24 implements Bitrix24ApiPort {
  private sequence = 100;
  readonly crm = new Map<string, {
    entityTypeId: number;
    fields: Record<string, unknown>;
  }>();
  readonly payments = new Map<string, StubPayment>();
  readonly productRows = new Map<string, Array<Record<string, unknown>>>();
  readonly deleteOrder: string[] = [];
  paymentCreates = 0;

  withRequestGuard<T>(
    _guard: () => Promise<void>,
    operation: () => Promise<T>,
  ): Promise<T> {
    return operation();
  }

  async createCrmItem(
    entityTypeId: number,
    fields: Record<string, unknown>,
  ): Promise<string> {
    const id = String(this.sequence++);
    this.crm.set(id, { entityTypeId, fields: { ...fields } });
    return id;
  }

  async updateCrmItem(
    entityTypeId: number,
    id: string,
    fields: Record<string, unknown>,
  ): Promise<void> {
    const current = this.crm.get(id);
    if (!current || current.entityTypeId !== entityTypeId) {
      throw new Bitrix24ApiError('crm.item.update', 'ENTITY_NOT_FOUND', 404, 'not found');
    }
    current.fields = { ...current.fields, ...fields };
  }

  async findCrmItemByOrigin(entityTypeId: number, originId: string): Promise<string | null> {
    for (const [id, item] of this.crm) {
      if (item.entityTypeId === entityTypeId && item.fields.originId === originId) return id;
    }
    return null;
  }

  async deleteCrmItem(entityTypeId: number, id: string): Promise<void> {
    const item = this.crm.get(id);
    if (item?.entityTypeId === entityTypeId) this.crm.delete(id);
    this.deleteOrder.push(`crm:${entityTypeId}:${id}`);
  }

  async setDealProductRows(
    dealId: string,
    rows: Array<Record<string, unknown>>,
  ): Promise<void> {
    this.productRows.set(dealId, rows.map((row) => ({ ...row })));
  }

  async findPaymentByXmlId(xmlId: string): Promise<string | null> {
    for (const [id, payment] of this.payments) {
      if (payment.fields.xmlId === xmlId) return id;
    }
    return null;
  }

  async listDealPaymentIds(dealId: string): Promise<string[]> {
    return [...this.payments]
      .filter(([, payment]) => payment.dealId === dealId)
      .map(([id]) => id);
  }

  async createDealPayment(dealId: string): Promise<string> {
    const id = String(this.sequence++);
    this.paymentCreates++;
    this.payments.set(id, { dealId, fields: {} });
    return id;
  }

  async updatePayment(id: string, fields: Record<string, unknown>): Promise<void> {
    const payment = this.payments.get(id);
    if (!payment) {
      throw new Bitrix24ApiError('sale.payment.update', 'ENTITY_NOT_FOUND', 404, 'not found');
    }
    payment.fields = { ...payment.fields, ...fields };
  }

  async deletePayment(id: string): Promise<void> {
    this.payments.delete(id);
    this.deleteOrder.push(`payment:${id}`);
  }
}

function database(pool: Pool): DatabaseService {
  return {
    isConfigured: true,
    query<T extends QueryResultRow = QueryResultRow>(
      text: string,
      params: readonly unknown[] = [],
    ) {
      return pool.query<T>(text, [...params]);
    },
    async transaction<T>(handler: (tx: TransactionClient) => Promise<T>): Promise<T> {
      const raw = await pool.connect();
      try {
        await raw.query('BEGIN');
        const tx: TransactionClient = {
          raw,
          query: (text, params = []) => raw.query(text, [...params]),
        };
        const result = await handler(tx);
        await raw.query('COMMIT');
        return result;
      } catch (error) {
        await raw.query('ROLLBACK').catch(() => undefined);
        throw error;
      } finally {
        raw.release();
      }
    },
    async withAdvisoryLock<T>(
      key: string,
      handler: (assertOwned: () => Promise<void>) => Promise<T>,
    ): Promise<T | null> {
      const raw = await pool.connect();
      const acquired = await raw.query<{ acquired: boolean }>(
        'SELECT pg_try_advisory_lock(hashtextextended($1, 0)) AS acquired',
        [key],
      );
      if (!acquired.rows[0]?.acquired) {
        raw.release();
        return null;
      }
      try {
        return await handler(async () => {
          await raw.query('SELECT 1');
        });
      } finally {
        await raw.query(
          'SELECT pg_advisory_unlock(hashtextextended($1, 0))',
          [key],
        );
        raw.release();
      }
    },
  } as unknown as DatabaseService;
}

function config(): CrmSyncRuntimeConfigService {
  return {
    getFlags: () => ({
      enabled: true,
      relayOwner: 'in_process',
      dryRun: false,
      pollIntervalMs: 10,
      batchSize: 20,
      maxAttempts: 3,
      workerId: 'bitrix-integration',
      leaseMs: 60_000,
    }),
  } as CrmSyncRuntimeConfigService;
}

describeIntegration('Bitrix24 trigger → relay → mapping pipeline', () => {
  let pool: Pool;
  let bitrix: StubBitrix24;
  let relay: CrmSyncRelayService;

  beforeAll(async () => {
    pool = new Pool({
      connectionString: databaseUrl,
      max: 5,
      options: `-c search_path=${schemaName},public`,
    });
    const setup = await pool.connect();
    try {
      await setup.query(`CREATE SCHEMA ${schemaName}`);
    } finally {
      setup.release();
    }
    await bootstrap(pool);

    const db = database(pool);
    const source = new PgCrmSourceRepository(db);
    const mapping = new PgCrmSyncMappingRepository();
    const outbox = new PgCrmSyncOutboxRepository();
    bitrix = new StubBitrix24();
    const consumer = new Bitrix24SyncConsumer({
      source,
      bitrix,
      mapping,
      db,
      durablePaymentCreates: true,
      options: {
        erpBaseUrl: 'https://erp.example',
        currencyId: 'KZT',
        assignedById: null,
        paySystemId: 6,
      },
    });
    relay = new CrmSyncRelayService({
      outboxRepo: outbox,
      consumer,
      dryRunConsumer: consumer,
      mapping,
      audit: new AuditService(),
      db,
      config: config(),
      logger: { log() {}, error() {} },
    });
  });

  afterAll(async () => {
    if (pool) {
      await pool.query(`DROP SCHEMA IF EXISTS ${schemaName} CASCADE`);
      await pool.end();
    }
  });

  let clientId: string;
  let orderId: string;
  let paymentId: string;

  it('projects a direct SQL client/order/payment write with exact native payment fields', async () => {
    const client = await pool.query<{ client_id: string }>(
      `INSERT INTO clients (client_name, person_type)
       VALUES ('Иван', 'individual') RETURNING client_id`,
    );
    clientId = String(client.rows[0].client_id);
    await pool.query(
      `INSERT INTO client_phones (client_id, phone_number, is_primary)
       VALUES ($1, '+77001234567', true)`,
      [clientId],
    );
    const order = await pool.query<{ order_id: string }>(
      `INSERT INTO orders (
         order_name, client_id, total_amount, final_amount, paid_amount,
         order_date, order_status_id, payment_status_id
       ) VALUES ('24001', $1, 100, 90, 50, DATE '2026-07-20', 1, 1)
       RETURNING order_id`,
      [clientId],
    );
    orderId = String(order.rows[0].order_id);
    const payment = await pool.query<{ payment_id: string }>(
      `INSERT INTO payments (order_id, type_paid_id, amount, payment_date)
       VALUES ($1, 1, 50, DATE '2026-07-20') RETURNING payment_id`,
      [orderId],
    );
    paymentId = String(payment.rows[0].payment_id);

    const result = await relay.runTick();
    expect(result.failed).toBe(0);
    expect(result.processed).toBe(2);

    const mappings = await pool.query<{
      entity_type: string;
      bitrix_id: string;
      parent_erp_id: string | null;
    }>(
      `SELECT entity_type, bitrix_id, parent_erp_id
         FROM crm_sync_mapping ORDER BY entity_type`,
    );
    expect(mappings.rows.map((row) => row.entity_type).sort())
      .toEqual(['client', 'order', 'payment']);
    const paymentMapping = mappings.rows.find((row) => row.entity_type === 'payment');
    expect(paymentMapping?.parent_erp_id).toBe(orderId);
    const remotePayment = bitrix.payments.get(String(paymentMapping?.bitrix_id));
    expect(remotePayment?.fields).toMatchObject({
      xmlId: `MEBELKZ_ERP_PAYMENT_${paymentId}`,
      sum: 50,
      psSum: 50,
      psCurrency: 'KZT',
    });
    expect(bitrix.productRows.get(remotePayment!.dealId)).toEqual([
      expect.objectContaining({ price: 90, quantity: 1 }),
    ]);
    const guardCount = await pool.query<{ count: string }>(
      'SELECT count(*)::text AS count FROM crm_sync_payment_create_guard',
    );
    expect(guardCount.rows[0].count).toBe('0');
    const audit = await pool.query<{ count: string }>(
      `SELECT count(*)::text AS count FROM audit_log
        WHERE request_id IS NOT NULL AND source='crm-sync'`,
    );
    expect(Number(audit.rows[0].count)).toBeGreaterThanOrEqual(3);
  });

  it('payment update trigger reasserts the same remote payment without a duplicate', async () => {
    await pool.query(
      'UPDATE payments SET amount=75 WHERE payment_id=$1',
      [paymentId],
    );
    const pending = await pool.query<{ count: string }>(
      `SELECT count(*)::text AS count FROM crm_sync_outbox
        WHERE idempotency_key=$1 AND status='pending'`,
      [`order:${orderId}`],
    );
    expect(pending.rows[0].count).toBe('1');

    await relay.runTick();

    expect(bitrix.paymentCreates).toBe(1);
    expect([...bitrix.payments.values()][0]?.fields).toMatchObject({
      sum: 75,
      psSum: 75,
    });
  });

  it('payment move enqueues old and new orders and re-parents through delete/recreate', async () => {
    const second = await pool.query<{ order_id: string }>(
      `INSERT INTO orders (
         order_name, client_id, total_amount, final_amount, paid_amount,
         order_date, order_status_id, payment_status_id
       ) VALUES ('24002', $1, 75, 75, 75, DATE '2026-07-20', 1, 1)
       RETURNING order_id`,
      [clientId],
    );
    const secondOrderId = String(second.rows[0].order_id);
    await relay.runTick();

    await pool.query(
      'UPDATE payments SET order_id=$1 WHERE payment_id=$2',
      [secondOrderId, paymentId],
    );
    const pending = await pool.query<{ aggregate_id: string }>(
      `SELECT aggregate_id FROM crm_sync_outbox
        WHERE status='pending' AND aggregate_id IN ($1,$2)
        ORDER BY created_at`,
      [orderId, secondOrderId],
    );
    expect(new Set(pending.rows.map((row) => row.aggregate_id)))
      .toEqual(new Set([orderId, secondOrderId]));

    await relay.runTick();

    expect(bitrix.payments.size).toBe(1);
    const mapping = await pool.query<{
      parent_erp_id: string;
      bitrix_id: string;
    }>(
      `SELECT parent_erp_id, bitrix_id FROM crm_sync_mapping
        WHERE entity_type='payment' AND erp_id=$1`,
      [paymentId],
    );
    expect(mapping.rows[0].parent_erp_id).toBe(secondOrderId);
    expect(bitrix.payments.get(mapping.rows[0].bitrix_id)).toBeDefined();
  });

  it('soft-deleting the owning order deletes payment before Deal', async () => {
    const mapping = await pool.query<{ parent_erp_id: string }>(
      `SELECT parent_erp_id FROM crm_sync_mapping
        WHERE entity_type='payment' AND erp_id=$1`,
      [paymentId],
    );
    const owningOrderId = mapping.rows[0].parent_erp_id;
    bitrix.deleteOrder.length = 0;
    await pool.query(
      'UPDATE orders SET delete_flag=true WHERE order_id=$1',
      [owningOrderId],
    );

    await relay.runTick();

    const paymentDelete = bitrix.deleteOrder.findIndex((value) =>
      value.startsWith('payment:'));
    const dealDelete = bitrix.deleteOrder.findIndex((value) =>
      value.startsWith('crm:2:'));
    expect(paymentDelete).toBeGreaterThanOrEqual(0);
    expect(dealDelete).toBeGreaterThan(paymentDelete);
  });
});
