import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { AuditService } from '../../common/audit/audit.service';
import type { DatabaseService } from '../../database/database.service';
import type { TransactionClient } from '../../database/database.types';
import { PgCrmSourceRepository } from './adapters/pg-crm-source-repository';
import { PgCrmSyncMappingRepository } from './adapters/pg-crm-sync-mapping-repository';
import { PgCrmSyncOutboxRepository } from './adapters/pg-crm-sync-outbox-repository';
import type { TwentyApiPort, TwentyObject } from './adapters/twenty-api-client';
import { TwentySyncConsumer } from './application/twenty-sync-consumer';
import type { CrmSyncRuntimeConfigService } from './http/crm-sync-runtime-config.service';
import { CrmSyncRelayService } from './application/crm-sync-relay.service';

// ── Gate ──────────────────────────────────────────────────────────────────────
// Skips cleanly when no database URL is set. CI must supply one of these envs.
const databaseUrl =
  process.env.CRM_SYNC_INTEGRATION_DATABASE_URL ?? process.env.TEST_DATABASE_URL;
const describeIntegration = databaseUrl ? describe : describe.skip;

// ── Throwaway schema name (unique per run) ────────────────────────────────────
const schemaName = `crm_e2e_${randomUUID().replaceAll('-', '_')}`;

// ── Schema bootstrap ──────────────────────────────────────────────────────────
// Applies:
//  1. Minimal base tables: order_statuses, payment_statuses, clients, orders
//  2. Real audit_log schema from migrations 001, 004, 012, 017, 020
//     (NOT NULL request_id is the critical contract under test)
//  3. Full migration 025: crm_sync_mapping, crm_sync_outbox, triggers, functions

async function bootstrapSchema(pool: Pool): Promise<void> {
  // ── 1. Minimal base tables ────────────────────────────────────────────────
  await pool.query(`
    CREATE TABLE ${schemaName}.order_statuses (
      order_status_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_status_name TEXT NOT NULL
    );

    CREATE TABLE ${schemaName}.payment_statuses (
      payment_status_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      payment_status_name TEXT NOT NULL
    );

    CREATE TABLE ${schemaName}.clients (
      client_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      client_name TEXT NOT NULL,
      notes TEXT,
      is_active BOOLEAN NOT NULL DEFAULT true
    );

    CREATE TABLE ${schemaName}.orders (
      order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_name TEXT NOT NULL,
      client_id BIGINT NOT NULL REFERENCES ${schemaName}.clients(client_id),
      total_amount NUMERIC(12,2),
      final_amount NUMERIC(12,2),
      paid_amount NUMERIC(12,2),
      order_date DATE,
      completion_date DATE,
      delete_flag BOOLEAN NOT NULL DEFAULT false,
      order_status_id SMALLINT REFERENCES ${schemaName}.order_statuses(order_status_id),
      payment_status_id SMALLINT REFERENCES ${schemaName}.payment_statuses(payment_status_id)
    );
  `);

  // ── 2. audit_log from migrations 001 + 004 + 012 + 017 + 020 ────────────
  // Migration 001: CREATE TABLE audit_log (with NOT NULL request_id)
  await pool.query(`
    CREATE TABLE ${schemaName}.audit_log (
      audit_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      event TEXT NOT NULL,
      action TEXT GENERATED ALWAYS AS (event) STORED,
      entity_type TEXT,
      entity_id TEXT,
      user_id BIGINT,
      username TEXT,
      role_code TEXT,
      role TEXT,
      request_id TEXT NOT NULL,
      ip_address INET,
      user_agent TEXT,
      before_json JSONB,
      after_json JSONB,
      diff_json JSONB,
      metadata_json JSONB,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );
  `);

  // Migration 004: ALTER TABLE audit_log ADD COLUMN source, related_order_id, etc.
  await pool.query(`
    ALTER TABLE ${schemaName}.audit_log
      ADD COLUMN source TEXT,
      ADD COLUMN related_order_id BIGINT,
      ADD COLUMN related_client_id BIGINT,
      ADD COLUMN related_production_event_id BIGINT,
      ADD COLUMN status_field TEXT,
      ADD COLUMN status_id BIGINT,
      ADD COLUMN status_name TEXT,
      ADD COLUMN status_code TEXT,
      ADD COLUMN stage_code TEXT;
  `);

  // Migration 012: ADD COLUMN related_payment_id, related_deadline_id
  await pool.query(`
    ALTER TABLE ${schemaName}.audit_log
      ADD COLUMN related_payment_id BIGINT,
      ADD COLUMN related_deadline_id BIGINT;
  `);

  // Migration 017: ADD COLUMN related_user_id
  await pool.query(`
    ALTER TABLE ${schemaName}.audit_log
      ADD COLUMN related_user_id BIGINT;
  `);

  // Migration 020: audit_log_related_entity bridge table
  await pool.query(`
    CREATE TABLE ${schemaName}.audit_log_related_entity (
      audit_id    UUID NOT NULL REFERENCES ${schemaName}.audit_log(audit_id) ON DELETE CASCADE,
      entity_type TEXT NOT NULL,
      entity_id   BIGINT NOT NULL,
      PRIMARY KEY (audit_id, entity_type, entity_id)
    );
  `);

  // ── 3. Migration 025: crm_sync_mapping, crm_sync_outbox, trigger function ─
  await pool.query(`
    CREATE TABLE ${schemaName}.crm_sync_mapping (
      entity_type   TEXT NOT NULL CHECK (entity_type IN ('client','order')),
      erp_id        TEXT NOT NULL,
      twenty_object TEXT NOT NULL,
      twenty_id     TEXT,
      status        TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','deleted','failed')),
      attempts      INTEGER NOT NULL DEFAULT 0,
      last_hash     TEXT,
      last_error    TEXT,
      last_synced_at TIMESTAMPTZ,
      created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
      CONSTRAINT pk_crm_sync_mapping PRIMARY KEY (entity_type, erp_id),
      CONSTRAINT uq_crm_sync_mapping_twenty UNIQUE (entity_type, twenty_id)
    );

    CREATE TABLE ${schemaName}.crm_sync_outbox (
      outbox_event_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      event_type      TEXT NOT NULL,
      aggregate_type  TEXT NOT NULL,
      aggregate_id    TEXT NOT NULL,
      payload_json    JSONB NOT NULL,
      status          TEXT NOT NULL DEFAULT 'pending',
      attempts        INTEGER NOT NULL DEFAULT 0,
      next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      locked_at       TIMESTAMPTZ,
      locked_by       TEXT,
      lock_token      TEXT,
      idempotency_key TEXT,
      created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
      processed_at    TIMESTAMPTZ,
      CONSTRAINT chk_crm_sync_outbox_status CHECK (status IN ('pending','processing','processed','failed'))
    );

    CREATE INDEX idx_crm_outbox_pending_${schemaName.replace(/-/g, '_')}
      ON ${schemaName}.crm_sync_outbox (next_attempt_at, created_at) WHERE status = 'pending';

    CREATE INDEX idx_crm_outbox_key_pending_${schemaName.replace(/-/g, '_')}
      ON ${schemaName}.crm_sync_outbox (idempotency_key) WHERE status = 'pending';
  `);

  // Trigger function scoped to this schema
  await pool.query(`
    CREATE OR REPLACE FUNCTION ${schemaName}.crm_sync_enqueue() RETURNS trigger AS $$
    DECLARE
      v_entity TEXT := TG_ARGV[0];
      v_op TEXT;
      v_id TEXT;
      v_key TEXT;
    BEGIN
      IF TG_OP = 'DELETE' THEN
        v_op := 'delete'; v_id := (CASE v_entity WHEN 'client' THEN OLD.client_id ELSE OLD.order_id END)::text;
      ELSE
        v_op := 'upsert'; v_id := (CASE v_entity WHEN 'client' THEN NEW.client_id ELSE NEW.order_id END)::text;
      END IF;
      v_key := v_entity || ':' || v_id;
      DELETE FROM ${schemaName}.crm_sync_outbox WHERE idempotency_key = v_key AND status = 'pending';
      INSERT INTO ${schemaName}.crm_sync_outbox (event_type, aggregate_type, aggregate_id, payload_json, idempotency_key)
      VALUES ('crm.sync.' || v_entity || '.' || v_op, 'crm_sync', v_id,
              jsonb_build_object('entity', v_entity, 'id', v_id, 'op', v_op), v_key);
      RETURN NULL;
    END;
    $$ LANGUAGE plpgsql;

    CREATE TRIGGER trg_crm_sync_clients
      AFTER INSERT OR UPDATE OR DELETE ON ${schemaName}.clients
      FOR EACH ROW EXECUTE FUNCTION ${schemaName}.crm_sync_enqueue('client');

    CREATE TRIGGER trg_crm_sync_orders
      AFTER INSERT OR UPDATE OR DELETE ON ${schemaName}.orders
      FOR EACH ROW EXECUTE FUNCTION ${schemaName}.crm_sync_enqueue('order');
  `);
}

// ── Stub TwentyApiPort ────────────────────────────────────────────────────────
class StubTwentyApiClient implements TwentyApiPort {
  readonly records: Map<string, Record<string, unknown>> = new Map();
  createCalls = 0;
  updateCalls = 0;
  private shouldThrow = false;

  setThrow(enabled: boolean): void {
    this.shouldThrow = enabled;
  }

  async createRecord(
    object: TwentyObject,
    body: Record<string, unknown>,
  ): Promise<{ id: string }> {
    if (this.shouldThrow) {
      throw new Error('Stub Twenty: simulated API error');
    }
    this.createCalls++;
    const id = `stub-${object}-${randomUUID()}`;
    this.records.set(id, { ...body, object });
    return { id };
  }

  async updateRecord(
    object: TwentyObject,
    id: string,
    body: Record<string, unknown>,
  ): Promise<void> {
    if (this.shouldThrow) {
      throw new Error('Stub Twenty: simulated API error');
    }
    this.updateCalls++;
    const existing = this.records.get(id) ?? {};
    this.records.set(id, { ...existing, ...body, object });
  }

  async findIdByErpId(_object: TwentyObject, _erpId: string): Promise<string | null> {
    return null;
  }

  async deleteRecord(_object: TwentyObject, _id: string): Promise<void> {
    // no-op in stub
  }
}

// ── DatabaseService stub backed by the throwaway-schema pool ─────────────────
function makeDatabase(pool: Pool): DatabaseService {
  const query = <T extends Record<string, unknown>>(
    text: string,
    params: readonly unknown[] = [],
  ) => pool.query<T>(text, [...params]);

  return {
    isConfigured: true,
    query,
    async transaction<T>(handler: (client: TransactionClient) => Promise<T>): Promise<T> {
      const raw = await pool.connect();
      try {
        await raw.query('BEGIN');
        await raw.query(`SET search_path TO ${schemaName}`);
        const tx: TransactionClient = {
          raw: raw as never,
          query: <R extends Record<string, unknown>>(
            text: string,
            params: readonly unknown[] = [],
          ) => raw.query<R>(text, [...params]),
        };
        const result = await handler(tx);
        await raw.query('COMMIT');
        return result;
      } catch (err) {
        await raw.query('ROLLBACK').catch(() => undefined);
        throw err;
      } finally {
        raw.release();
      }
    },
  } as unknown as DatabaseService;
}

// ── Stub CrmSyncRuntimeConfigService ─────────────────────────────────────────
function makeConfig(): CrmSyncRuntimeConfigService {
  return {
    getFlags: () => ({
      enabled: true,
      relayOwner: 'test',
      dryRun: false,
      pollIntervalMs: 5000,
      batchSize: 10,
      maxAttempts: 3,
      workerId: 'integration-test-worker',
      leaseMs: 300_000,
    }),
    getTwenty: () => ({ baseUrl: null, apiKey: null }),
  } as unknown as CrmSyncRuntimeConfigService;
}

// ── Test suite ────────────────────────────────────────────────────────────────

describeIntegration('CRM sync pipeline end-to-end (integration)', () => {
  let pool: Pool;
  let db: DatabaseService;
  let outboxRepo: PgCrmSyncOutboxRepository;
  let mappingRepo: PgCrmSyncMappingRepository;
  let stub: StubTwentyApiClient;
  let relay: CrmSyncRelayService;

  beforeAll(async () => {
    pool = new Pool({ connectionString: databaseUrl, max: 4 });

    // Create schema first (dedicated client, before pool.on)
    const setupClient = await pool.connect();
    try {
      await setupClient.query(`CREATE SCHEMA ${schemaName}`);
      await setupClient.query(`SET search_path TO ${schemaName}`);
    } finally {
      setupClient.release();
    }

    // Pin search_path for ALL future pooled connections
    pool.on('connect', (c) => void c.query(`SET search_path TO ${schemaName}`));

    // Bootstrap schema tables and triggers
    await bootstrapSchema(pool);

    // Wire up services
    db = makeDatabase(pool);
    outboxRepo = new PgCrmSyncOutboxRepository();
    mappingRepo = new PgCrmSyncMappingRepository();
    const sourceRepo = new PgCrmSourceRepository(db);
    stub = new StubTwentyApiClient();
    const audit = new AuditService();
    const config = makeConfig();

    const consumer = new TwentySyncConsumer({
      source: sourceRepo,
      twenty: stub,
      mapping: mappingRepo,
      db,
    });

    const dryRunConsumer = new TwentySyncConsumer({
      source: sourceRepo,
      twenty: stub,
      mapping: mappingRepo,
      db,
    });

    relay = new CrmSyncRelayService({
      outboxRepo,
      consumer,
      dryRunConsumer,
      mapping: mappingRepo,
      audit,
      db,
      config,
    });
  });

  afterAll(async () => {
    if (pool) {
      await pool.query(`DROP SCHEMA IF EXISTS ${schemaName} CASCADE`);
      await pool.end();
    }
  });

  // ── Scenario 1: INSERT client → one pending outbox row ───────────────────

  let insertedClientId: string;

  it('SC-1: INSERT client fires trigger → exactly ONE pending crm_sync_outbox row', async () => {
    const res = await pool.query<{ client_id: string }>(
      `INSERT INTO ${schemaName}.clients (client_name, notes, is_active)
       VALUES ('Тест Компания А', 'Тестовые заметки', true)
       RETURNING client_id`,
    );
    insertedClientId = String(res.rows[0].client_id);

    const outbox = await pool.query<{ count: string; aggregate_id: string; status: string }>(
      `SELECT COUNT(*)::text AS count, aggregate_id, status
         FROM ${schemaName}.crm_sync_outbox
        WHERE aggregate_id = $1
        GROUP BY aggregate_id, status`,
      [insertedClientId],
    );
    expect(outbox.rows).toHaveLength(1);
    expect(outbox.rows[0].count).toBe('1');
    expect(outbox.rows[0].status).toBe('pending');
  });

  // ── Scenario 2: runTick → mapping.twenty_id set, audit_log NOT NULL request_id, outbox='processed' ─

  it('SC-2: relay.runTick() → mapping.twenty_id set, audit_log.request_id NOT NULL, outbox=processed', async () => {
    const result = await relay.runTick();
    expect(result.claimed).toBeGreaterThanOrEqual(1);
    expect(result.processed).toBeGreaterThanOrEqual(1);
    expect(result.failed).toBe(0);

    // Mapping should now have a twenty_id
    const mapping = await pool.query<{
      entity_type: string;
      twenty_id: string | null;
      status: string;
    }>(
      `SELECT entity_type, twenty_id, status
         FROM ${schemaName}.crm_sync_mapping
        WHERE entity_type = 'client' AND erp_id = $1`,
      [insertedClientId],
    );
    expect(mapping.rows).toHaveLength(1);
    expect(mapping.rows[0].twenty_id).toBeTruthy();
    expect(mapping.rows[0].status).toBe('active');

    // Outbox row should be 'processed'
    const outbox = await pool.query<{ status: string }>(
      `SELECT status FROM ${schemaName}.crm_sync_outbox WHERE aggregate_id = $1 ORDER BY created_at DESC LIMIT 1`,
      [insertedClientId],
    );
    expect(outbox.rows[0]?.status).toBe('processed');

    // audit_log must have a row with non-null request_id (proves NOT NULL contract)
    const audit = await pool.query<{ request_id: string | null; source: string }>(
      `SELECT request_id, source
         FROM ${schemaName}.audit_log
        WHERE entity_type = 'client' AND entity_id = $1
        ORDER BY created_at DESC
        LIMIT 1`,
      [insertedClientId],
    );
    expect(audit.rows).toHaveLength(1);
    expect(audit.rows[0].request_id).not.toBeNull();
    expect(audit.rows[0].request_id).toBeTruthy();
    expect(audit.rows[0].source).toBe('crm-sync');
  });

  // ── Scenario 3: UPDATE is_active=false → tick → mapping.status='deleted' ─

  it('SC-3: UPDATE clients SET is_active=false → tick → mapping.status=deleted', async () => {
    stub.setThrow(false);
    const beforeCreateCalls = stub.createCalls;

    await pool.query(
      `UPDATE ${schemaName}.clients SET is_active = false WHERE client_id = $1`,
      [insertedClientId],
    );

    // Trigger should have produced a new pending outbox row
    const pending = await pool.query<{ count: string }>(
      `SELECT COUNT(*)::text AS count FROM ${schemaName}.crm_sync_outbox
        WHERE aggregate_id = $1 AND status = 'pending'`,
      [insertedClientId],
    );
    expect(Number(pending.rows[0].count)).toBeGreaterThanOrEqual(1);

    const result = await relay.runTick();
    expect(result.processed).toBeGreaterThanOrEqual(1);
    expect(result.failed).toBe(0);

    // isActive=false → erpStatusFor(!isActive)=erpStatusFor(true)='deleted'
    const mapping = await pool.query<{ status: string; twenty_id: string }>(
      `SELECT status, twenty_id FROM ${schemaName}.crm_sync_mapping
        WHERE entity_type = 'client' AND erp_id = $1`,
      [insertedClientId],
    );
    expect(mapping.rows[0].status).toBe('deleted');

    // Stub Company record must have received erpStatus='deleted'
    const stubCompany = stub.records.get(mapping.rows[0].twenty_id);
    expect(stubCompany?.erpStatus).toBe('deleted');

    // No new create — existing twenty_id reused via updateRecord
    expect(stub.createCalls).toBe(beforeCreateCalls);
    expect(mapping.rows[0].twenty_id).toBeTruthy();
  });

  // ── Scenario 4: Re-run same upsert → no duplicate create (idempotency) ───

  it('SC-4: re-processing same client does NOT call createRecord again (hash no-op)', async () => {
    const beforeCreate = stub.createCalls;

    // Force a new pending outbox row (simulating a re-trigger with a unique idempotency key)
    await pool.query(
      `INSERT INTO ${schemaName}.crm_sync_outbox
         (event_type, aggregate_type, aggregate_id, payload_json, idempotency_key, next_attempt_at)
       VALUES ('crm.sync.client.upsert', 'crm_sync', $1,
               jsonb_build_object('entity', 'client', 'id', $1, 'op', 'upsert'),
               $2, now() - interval '1 second')`,
      [insertedClientId, `client:${insertedClientId}:rerun-${randomUUID()}`],
    );

    const result = await relay.runTick();
    // Consumer detects hash match (already synced, same body hash) → returns []
    // The relay processes the event but no new create is called
    expect(stub.createCalls).toBe(beforeCreate);
    expect(result.failed).toBe(0);
    expect(result.processed).toBeGreaterThanOrEqual(1);
  });

  // ── Scenario 5: Forced Twenty error → mapping.status='failed' ────────────

  it('SC-5: Twenty API throws → tick marks outbox+mapping as failed', async () => {
    const res = await pool.query<{ client_id: string }>(
      `INSERT INTO ${schemaName}.clients (client_name, is_active)
       VALUES ('Тест Компания Б', true)
       RETURNING client_id`,
    );
    const failClientId = String(res.rows[0].client_id);

    // Pre-bump attempts to maxAttempts-1 (=2) so next markRetry → attempts+1=3 >= 3 → status=failed
    await pool.query(
      `UPDATE ${schemaName}.crm_sync_outbox SET attempts = 2
        WHERE aggregate_id = $1 AND status = 'pending'`,
      [failClientId],
    );

    stub.setThrow(true);
    const result = await relay.runTick();
    stub.setThrow(false);

    expect(result.failed).toBeGreaterThanOrEqual(1);

    // Mapping should be 'failed'
    const mapping = await pool.query<{ status: string; last_error: string | null }>(
      `SELECT status, last_error FROM ${schemaName}.crm_sync_mapping
        WHERE entity_type = 'client' AND erp_id = $1`,
      [failClientId],
    );
    expect(mapping.rows).toHaveLength(1);
    expect(mapping.rows[0].status).toBe('failed');
    expect(mapping.rows[0].last_error).toBeTruthy();
  });

  // ── Scenario 6: Coalescing — two rapid UPDATEs → ONE pending outbox row ──

  it('SC-6: two rapid UPDATEs coalesce to ONE pending outbox row', async () => {
    const res = await pool.query<{ client_id: string }>(
      `INSERT INTO ${schemaName}.clients (client_name, is_active)
       VALUES ('Тест Компания В', true)
       RETURNING client_id`,
    );
    const coalesceClientId = String(res.rows[0].client_id);

    // Process the initial insert outbox event so we start clean
    await relay.runTick();

    // Two rapid UPDATEs — trigger coalesces (DELETE pending + INSERT fresh)
    await pool.query(
      `UPDATE ${schemaName}.clients SET notes = 'Первое обновление' WHERE client_id = $1`,
      [coalesceClientId],
    );
    await pool.query(
      `UPDATE ${schemaName}.clients SET notes = 'Второе обновление' WHERE client_id = $1`,
      [coalesceClientId],
    );

    const pending = await pool.query<{ count: string }>(
      `SELECT COUNT(*)::text AS count
         FROM ${schemaName}.crm_sync_outbox
        WHERE aggregate_id = $1 AND status = 'pending'`,
      [coalesceClientId],
    );
    // Trigger coalesces: DELETE old pending then INSERT new → exactly 1 pending row
    expect(pending.rows[0].count).toBe('1');
  });
});
