import { randomUUID } from 'node:crypto';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { Pool, type PoolClient } from 'pg';
import type { DatabaseClient, TransactionClient } from '../../database/database.types';
import { PgOrgRepository } from './org.repository';

// Opt-in DB-backed coverage. Skips cleanly unless an integration database URL is
// provided (operator-window only — mirrors the deadline/notification harnesses).
const databaseUrl = process.env.ORG_REPOSITORY_INTEGRATION_DATABASE_URL;
const describeIntegration = databaseUrl ? describe : describe.skip;

const adminUser = {
  id: '1',
  username: 'e2e-admin',
  role: 'admin',
  roleId: 1,
  permissions: ['org.view', 'org.manage'],
} as any;

describeIntegration('PgOrgRepository idempotent replace integration', () => {
  const schemaName = `org_repo_${randomUUID().replaceAll('-', '_')}`;
  let pool: Pool;
  let repository: PgOrgRepository;

  function makeDatabase(): DatabaseClient & {
    transaction<T>(handler: (client: TransactionClient) => Promise<T>): Promise<T>;
  } {
    return {
      query: (text: string, params?: readonly unknown[]) => pool.query(text, params as unknown[]),
      async transaction<T>(handler: (client: TransactionClient) => Promise<T>): Promise<T> {
        const client: PoolClient = await pool.connect();
        try {
          await client.query('BEGIN');
          const tx: TransactionClient = {
            query: (text: string, params?: readonly unknown[]) => client.query(text, params as unknown[]),
            raw: client,
          };
          const result = await handler(tx);
          await client.query('COMMIT');
          return result;
        } catch (error) {
          await client.query('ROLLBACK');
          throw error;
        } finally {
          client.release();
        }
      },
    };
  }

  beforeAll(async () => {
    pool = new Pool({ connectionString: databaseUrl, max: 1 });
    await pool.query(`CREATE SCHEMA ${schemaName}`);
    await pool.query(`SET search_path TO ${schemaName}, public`);
    await createMinimalSchema(pool, schemaName);
    repository = new PgOrgRepository(makeDatabase());
  });

  afterAll(async () => {
    if (pool) {
      await pool.query(`DROP SCHEMA IF EXISTS ${schemaName} CASCADE`);
      await pool.end();
    }
  });

  it('replays the original response and writes no duplicate head audit rows when an idempotency key repeats', async () => {
    const direction = await repository.createDirection({
      currentUser: adminUser,
      name: `E2E-Тест направление ${randomUUID()}`,
      description: null,
      isActive: true,
    });

    const idempotencyKey = `e2e-org-heads-${randomUUID()}`;
    const first = await repository.replaceDirectionHeads({
      currentUser: adminUser,
      directionId: direction.directionId,
      idempotencyKey,
      ids: [10],
      reason: null,
    });
    expect(first.heads.map((h) => h.userId)).toEqual([10]);

    const auditBefore = await countHeadAudit(pool, direction.directionId);

    // Drift the underlying rows out-of-band: deactivate the head and add a second.
    await pool.query(
      `UPDATE ${schemaName}.direction_heads SET is_active = false WHERE direction_id = $1 AND user_id = 10`,
      [direction.directionId],
    );
    await pool.query(
      `INSERT INTO ${schemaName}.direction_heads (direction_id, user_id, is_active) VALUES ($1, 11, true)`,
      [direction.directionId],
    );

    // Replay with the SAME key + request → must return the ORIGINAL committed
    // response (head 10), not the drifted current state (head 11).
    const replay = await repository.replaceDirectionHeads({
      currentUser: adminUser,
      directionId: direction.directionId,
      idempotencyKey,
      ids: [10],
      reason: null,
    });
    expect(replay.heads.map((h) => h.userId)).toEqual([10]);

    const auditAfter = await countHeadAudit(pool, direction.directionId);
    expect(auditAfter).toBe(auditBefore);
  });
});

async function countHeadAudit(pool: Pool, directionId: number): Promise<number> {
  const r = await pool.query(
    `SELECT count(*)::int AS n FROM audit_log
      WHERE entity_type = 'direction' AND entity_id = $1::text
        AND event IN ('ORG_DIRECTION_HEAD_ADDED', 'ORG_DIRECTION_HEAD_REMOVED')`,
    [directionId],
  );
  return Number(r.rows[0].n);
}

async function createMinimalSchema(pool: Pool, schema: string): Promise<void> {
  await pool.query(`
    CREATE TABLE ${schema}.employees (
      employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      full_name VARCHAR(200) NOT NULL
    );
    CREATE TABLE ${schema}.users (
      user_id BIGINT PRIMARY KEY,
      username TEXT NOT NULL,
      full_name TEXT,
      employee_id BIGINT REFERENCES ${schema}.employees(employee_id),
      is_active BOOLEAN NOT NULL DEFAULT true
    );
    CREATE TABLE ${schema}.workshops (
      workshop_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      workshop_name VARCHAR(128) NOT NULL,
      is_active BOOLEAN NOT NULL DEFAULT true
    );
    CREATE TABLE ${schema}.work_centers (
      workcenter_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      workshop_id SMALLINT REFERENCES ${schema}.workshops(workshop_id),
      workcenter_name VARCHAR(128) NOT NULL,
      is_active BOOLEAN NOT NULL DEFAULT true
    );
    CREATE TABLE ${schema}.directions (
      direction_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      direction_name VARCHAR(128) NOT NULL UNIQUE,
      description TEXT,
      is_active BOOLEAN NOT NULL DEFAULT true,
      created_by BIGINT,
      edited_by BIGINT,
      updated_at TIMESTAMP NOT NULL DEFAULT now()
    );
    CREATE TABLE ${schema}.direction_workshops (
      direction_id SMALLINT NOT NULL,
      workshop_id SMALLINT NOT NULL,
      created_by BIGINT,
      PRIMARY KEY (direction_id, workshop_id)
    );
    CREATE TABLE ${schema}.direction_work_centers (
      direction_id SMALLINT NOT NULL,
      workcenter_id SMALLINT NOT NULL,
      created_by BIGINT,
      PRIMARY KEY (direction_id, workcenter_id)
    );
    CREATE TABLE ${schema}.direction_heads (
      direction_id SMALLINT NOT NULL,
      user_id BIGINT NOT NULL,
      is_active BOOLEAN NOT NULL DEFAULT true,
      created_by BIGINT,
      PRIMARY KEY (direction_id, user_id)
    );
    CREATE TABLE ${schema}.workshop_heads (
      workshop_id SMALLINT NOT NULL,
      user_id BIGINT NOT NULL,
      is_active BOOLEAN NOT NULL DEFAULT true,
      created_by BIGINT,
      PRIMARY KEY (workshop_id, user_id)
    );
    CREATE TABLE ${schema}.command_idempotency_keys (
      idempotency_key TEXT PRIMARY KEY,
      command_name TEXT NOT NULL,
      actor_user_id BIGINT,
      entity_type TEXT NOT NULL,
      entity_id TEXT NOT NULL,
      request_hash TEXT NOT NULL,
      response_json JSONB,
      status TEXT NOT NULL DEFAULT 'processing',
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      completed_at TIMESTAMPTZ
    );
    CREATE TABLE ${schema}.audit_log (
      audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      event TEXT NOT NULL,
      entity_type TEXT NOT NULL,
      entity_id TEXT NOT NULL,
      user_id BIGINT,
      username TEXT,
      role_code TEXT,
      role TEXT,
      request_id TEXT,
      source TEXT,
      related_order_id BIGINT,
      related_client_id BIGINT,
      related_payment_id BIGINT,
      related_production_event_id BIGINT,
      related_deadline_id BIGINT,
      related_user_id BIGINT,
      status_field TEXT,
      status_id BIGINT,
      status_name TEXT,
      status_code TEXT,
      stage_code TEXT,
      before_json JSONB,
      after_json JSONB,
      diff_json JSONB,
      metadata_json JSONB,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    INSERT INTO ${schema}.users (user_id, username, full_name, is_active)
      VALUES (1, 'e2e-admin', 'E2E Админ', true), (10, 'e2e-head-10', 'E2E Голова 10', true),
             (11, 'e2e-head-11', 'E2E Голова 11', true);
  `);
}
