import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const modal = readFileSync('src/pages/cut/CutSvgUploadModal.tsx', 'utf8');
const cutPage = readFileSync('src/pages/cut/CutPage.tsx', 'utf8');
const orderList = readFileSync('src/pages/orders/list.tsx', 'utf8');
const orderShow = readFileSync('src/pages/orders/show.tsx', 'utf8');
const globalAction = readFileSync('src/components/GlobalSvgCutUploadAction.tsx', 'utf8');
const appHeader = readFileSync('src/components/AppHeader.tsx', 'utf8');
const headerUtilities = readFileSync('src/ui-evolution/shell/EvolutionHeaderUtilities.tsx', 'utf8');
const tabletUtilities = readFileSync('src/ui-evolution/shell/EvolutionTabletUtilities.tsx', 'utf8');
const cncApi = readFileSync('src/api/cncTelegramApi.ts', 'utf8');

describe('manual SVG cut upload UI guard', () => {
  it('uses backend manual SVG command and exact MDF-card question', () => {
    expect(cncApi).toContain('manualSvgUpload');
    expect(cncApi).toContain('Idempotency-Key');
    expect(modal).toContain('parseSvgCutUploadFile');
    expect(modal).toContain('parseSvgCutUploadFileNameHints');
    expect(modal).toContain('applyFileNameOrderHints');
    expect(modal).toContain('создать карточку файла станка для Доски МДФ из раскроя?');
    expect(modal).toContain('createMdfMachineFileCard');
    expect(modal).toContain('requestedCutJobId');
    expect(modal).toContain('№ задания');
    expect(modal).toContain('Оставьте пустым для авто-номера');
    expect(modal).toContain('checkRequestedCutJobNumber');
    expect(modal).toContain('suggestAvailableCutJobNumbers');
    expect(modal).toContain('cutApi.list({ jobNumber: String(cutJobId) })');
    expect(modal).toContain('buildSvgMatchProblems');
    expect(modal).toContain('Детали SVG не сопоставлены с выбранными заказами');
    expect(modal).toContain('Размер в SVG');
    expect(modal).toContain('showManualSvgApiMatchError');
    expect(modal).toContain('MANUAL_SVG_UNMATCHED_DETAILS');
    expect(modal).toContain('MANUAL_SVG_ORDER_SCOPE_MISMATCH');
    expect(modal).toContain('Деталь уже есть в активных раскроях');
    expect(modal).toContain('warningMatchProblems');
    expect(modal).toContain('confirmSvgMatchWarnings');
    expect(modal).toContain('Формировать всё равно');
    expect(modal).toContain('Это предупреждение не запрещает новый раскрой');
    expect(modal).toContain('SvgUploadPreview');
    expect(modal).toContain('FloatingSvgPreview');
    expect(modal).toContain('Превью SVG');
    expect(modal).toContain('Контраст скрина');
    expect(modal).toContain('MANUAL_SVG_SCREENSHOT_CONTRAST_DEFAULT');
    expect(modal).toContain('manualSvgScreenshotPreviewFilter');
    expect(modal).toContain('manualSvgGeneratedScreenshotContrastKey');
    expect(modal).toContain('generatedScreenshot');
    expect(modal).toContain('<Slider');
    expect(modal).toContain('Превью SVG-раскроя');
    expect(modal).toContain('Крупное превью SVG-раскроя');
    expect(modal).toContain('Открыть крупное превью SVG');
    expect(modal).toContain('onPointerDown');
    expect(modal).toContain('setPointerCapture');
    expect(modal).toContain('stopFloatingSvgPreviewActionPointerDown');
    expect(modal).toContain('resizeFloatingSvgPreviewRect');
    expect(modal).toContain('floatingSvgPreviewResizeHandleStyle');
    expect(modal).toContain('FLOATING_SVG_PREVIEW_MIN_WIDTH');
    expect(modal).toContain('bottom-right');
    expect(modal).toContain('printSvgPreview');
    expect(modal).toContain('Распечатать SVG');
    expect(modal).toContain('URL.createObjectURL');
    expect(modal).toContain('URL.revokeObjectURL');
    expect(modal).toContain("objectFit: 'contain'");
    expect(modal).toContain("flex: '0 0 320px'");
    expect(modal).toContain('replaceSvgPreview(null)');
    expect(modal).toContain('uploadMatchMode');
    expect(modal).toContain("matchMode: uploadMatchMode");
    expect(modal).toContain('validationMode');
    expect(modal).toContain('lenientValidation');
    expect(modal).toContain('Нестрогий режим');
    expect(modal).toContain('appendCommentLineBreak');
    expect(modal).toContain('Перенос строки');
    expect(modal).toContain('<Input.TextArea');
    expect(modal).toContain('svgUploadMaterialIsInformational');
    expect(modal).toContain('allowGeometryFallbackItems: parseAsInformational');
    expect(modal).not.toContain('allowGeometryFallbackItems: parseAsInformational || lenientValidation');
    expect(modal).toContain('без сверки ERP-деталей');
    expect(modal).toContain('Задание будет связано с выбранными заказами без привязки к деталям заказа');
    expect(modal).toContain('manual-svg-preset:${asciiHash(commentText)}');
    expect(modal).toContain('Фрезы для ХДФ: 8');
    expect(modal).toContain('Черновой с двух сторон!!!');
    expect(modal).toContain('Присадка №');
    expect(modal).toContain('Фрезы для 18мм:');
    expect(modal).toContain('Фрезы для ЛДСП: 8');
    expect(modal).toContain('Фрезы для 10мм:');
    expect(modal).toContain('Ламинированная сторона МДФ !!!');
    expect(modal).toContain('Фреза для ламинированной стороны:');
    expect(modal).toContain('appendCommentPreset');
    expect(modal).toContain('normalizeManualSvgCommentForSubmit');
    expect(modal).toContain('comments: uploadComment ? [uploadComment] : []');
    expect(modal).toContain('Сохранить комментарий как пресет');
    expect(modal).toContain('formatDefaultOrderOptionLabel');
    expect(modal).toContain('formatOrderOptionLabel');
    expect(modal).toContain('resolveManualSvgCutJobDisplayNumber');
    expect(modal).toContain('formatCutJobDisplayLabel');
    expect(modal).toContain('cutJobDisplayLabel');
    expect(modal).toContain("okText: cutJobPath ? 'Открыть задание' : 'OK'");
    expect(modal).toContain('onOk: openCutJob');
    expect(modal).toContain('minimized');
    expect(modal).toContain('MinimizedSvgUpload');
    expect(modal).toContain('Свернуть загрузку SVG-раскроя');
    expect(modal).toContain('manual-svg-upload-minimized');
  });

  it('wires upload into cut screen and global app actions, not orders screens', () => {
    expect(cutPage).toContain('<CutSvgUploadModal');
    expect(cutPage).toContain('setSvgUploadOpen(true)');
    expect(globalAction).toContain('Загрузка SVG раскроя');
    expect(globalAction).toContain('<CutSvgUploadModal');
    expect(globalAction).toContain('featureFlags.useBackendCut');
    expect(globalAction).toContain("can('cut.manage')");
    expect(appHeader).toContain('<GlobalSvgCutUploadAction');
    expect(headerUtilities).toContain('<GlobalSvgCutUploadAction');
    expect(tabletUtilities).toContain('<GlobalSvgCutUploadAction');
    expect(headerUtilities.indexOf('<GlobalSvgCutUploadAction')).toBeLessThan(headerUtilities.indexOf('<QrcodeOutlined'));
    expect(orderList).not.toContain('<CutSvgUploadModal');
    expect(orderList).not.toContain('setSvgUploadOpen(true)');
    expect(orderShow).not.toContain('<CutSvgUploadModal');
    expect(orderShow).not.toContain('setSvgUploadOpen(true)');
  });
});
