import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import type { DatabaseService } from '../../../database/database.service';
import type { TransactionClient } from '../../../database/database.types';
import { PgCrmSourceRepository } from './pg-crm-source-repository';

// Integration tests for PgCrmSourceRepository.
// Gated on CRM_SYNC_INTEGRATION_DATABASE_URL (falls back to TEST_DATABASE_URL).
// Skips cleanly without a database. Throwaway schema only.
const databaseUrl =
  process.env.CRM_SYNC_INTEGRATION_DATABASE_URL ?? process.env.TEST_DATABASE_URL;
const describeIntegration = databaseUrl ? describe : describe.skip;

const schemaName = `crm_src_${randomUUID().replaceAll('-', '_')}`;

async function createSchema(pool: Pool): Promise<void> {
  await pool.query(`
    CREATE TABLE order_statuses (
      order_status_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_status_name TEXT NOT NULL
    );
    INSERT INTO order_statuses (order_status_id, order_status_name) VALUES (1, 'Новый'), (2, 'В работе');

    CREATE TABLE payment_statuses (
      payment_status_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      payment_status_name TEXT NOT NULL
    );
    INSERT INTO payment_statuses (payment_status_id, payment_status_name) VALUES (1, 'Не оплачен'), (2, 'Частично оплачен');

    CREATE TABLE clients (
      client_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      client_name CITEXT NOT NULL,
      notes TEXT,
      is_active BOOLEAN NOT NULL DEFAULT true
    );
    INSERT INTO clients (client_id, client_name, notes, is_active) VALUES
      (1, 'Клиент А', 'Примечание', true),
      (2, 'Клиент Б', NULL, false),
      (3, 'Клиент В', NULL, true);

    CREATE TABLE orders (
      order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_name TEXT NOT NULL,
      client_id BIGINT NOT NULL REFERENCES clients(client_id),
      total_amount NUMERIC(12,2),
      final_amount NUMERIC(12,2),
      paid_amount NUMERIC(12,2),
      order_date DATE,
      completion_date DATE,
      delete_flag BOOLEAN NOT NULL DEFAULT false,
      order_status_id SMALLINT REFERENCES order_statuses(order_status_id),
      payment_status_id SMALLINT REFERENCES payment_statuses(payment_status_id)
    );
    INSERT INTO orders (order_id, order_name, client_id, total_amount, final_amount, paid_amount,
                        order_date, completion_date, delete_flag, order_status_id, payment_status_id) VALUES
      (10, 'Заказ 10', 1, 15000.00, 14500.00, 7250.00, '2026-01-15', '2026-02-28', false, 1, 2),
      (20, 'Заказ 20', 2, NULL, NULL, NULL, NULL, NULL, true, NULL, NULL),
      (30, 'Заказ 30', 3, 5000.00, 5000.00, 5000.00, '2026-03-01', NULL, false, 2, NULL);
  `);
}

/** Minimal DatabaseService backed by a pool in the throwaway schema. */
function makeDatabase(pool: Pool): DatabaseService {
  const query = (text: string, params: readonly unknown[] = []) => pool.query(text, [...params]);
  return {
    isConfigured: true,
    query,
    async transaction<T>(handler: (client: TransactionClient) => Promise<T>): Promise<T> {
      const client = await pool.connect();
      try {
        await client.query('BEGIN');
        await client.query(`SET search_path TO ${schemaName}`);
        const tx: TransactionClient = {
          raw: client as never,
          query: (text: string, params: readonly unknown[] = []) => client.query(text, [...params]),
        };
        const result = await handler(tx);
        await client.query('COMMIT');
        return result;
      } catch (error) {
        await client.query('ROLLBACK').catch(() => undefined);
        throw error;
      } finally {
        client.release();
      }
    },
  } as unknown as DatabaseService;
}

describeIntegration('PgCrmSourceRepository (integration)', () => {
  let pool: Pool;
  let repo: PgCrmSourceRepository;

  beforeAll(async () => {
    pool = new Pool({ connectionString: databaseUrl, max: 4 });
    await pool.query(`CREATE SCHEMA ${schemaName}`);
    await pool.query(`SET search_path TO ${schemaName}`);
    await createSchema(pool);
    // Pin search_path for every pooled connection.
    pool.on('connect', (client) => void client.query(`SET search_path TO ${schemaName}`));
    const database = makeDatabase(pool);
    repo = new PgCrmSourceRepository(database);
  });

  afterAll(async () => {
    if (pool) {
      await pool.query(`DROP SCHEMA IF EXISTS ${schemaName} CASCADE`);
      await pool.end();
    }
  });

  // ── getClientById ──────────────────────────────────────────────────────────

  it('getClientById returns a mapped ClientRow for an existing client', async () => {
    const row = await repo.getClientById('1');
    expect(row).not.toBeNull();
    expect(row!.clientId).toBe('1');
    expect(row!.clientName).toBe('Клиент А');
    expect(row!.notes).toBe('Примечание');
    expect(row!.isActive).toBe(true);
  });

  it('getClientById maps null notes and is_active=false correctly', async () => {
    const row = await repo.getClientById('2');
    expect(row).not.toBeNull();
    expect(row!.notes).toBeNull();
    expect(row!.isActive).toBe(false);
  });

  it('getClientById returns null for a missing client', async () => {
    const row = await repo.getClientById('9999');
    expect(row).toBeNull();
  });

  // ── getOrderById ───────────────────────────────────────────────────────────

  it('getOrderById returns a mapped OrderRow with joined status names', async () => {
    const row = await repo.getOrderById('10');
    expect(row).not.toBeNull();
    expect(row!.orderId).toBe('10');
    expect(row!.orderNumber).toBe('10');
    expect(row!.orderName).toBe('Заказ 10');
    expect(row!.clientId).toBe('1');
    expect(row!.totalAmount).toBe(15000);
    expect(row!.finalAmount).toBe(14500);
    expect(row!.paidAmount).toBe(7250);
    expect(row!.orderStatusName).toBe('Новый');
    expect(row!.paymentStatusName).toBe('Частично оплачен');
    // Regression lock (2026-06-19): a pg DATE must serialize to a date-only
    // 'YYYY-MM-DD' string, NOT a leaked Date.toString(). order_date='2026-01-15'.
    expect(row!.orderDate).toBe('2026-01-15');
    expect(row!.completionDate).toBe('2026-02-28');
    expect(row!.deleteFlag).toBe(false);
  });

  it('getOrderById maps null amounts and status names when FKs are null', async () => {
    const row = await repo.getOrderById('20');
    expect(row).not.toBeNull();
    expect(row!.totalAmount).toBeNull();
    expect(row!.finalAmount).toBeNull();
    expect(row!.paidAmount).toBeNull();
    expect(row!.orderStatusName).toBeNull();
    expect(row!.paymentStatusName).toBeNull();
    expect(row!.completionDate).toBeNull();
    expect(row!.deleteFlag).toBe(true);
  });

  it('getOrderById returns null for a missing order', async () => {
    const row = await repo.getOrderById('9999');
    expect(row).toBeNull();
  });

  // ── listClientIds ──────────────────────────────────────────────────────────

  it('listClientIds returns ids > afterId ordered ASC, respecting limit', async () => {
    // afterId='0' => all three clients: 1, 2, 3
    const all = await repo.listClientIds('0', 100);
    expect(all).toEqual(['1', '2', '3']);

    // afterId='1' => 2, 3
    const page2 = await repo.listClientIds('1', 100);
    expect(page2).toEqual(['2', '3']);

    // limit=1
    const one = await repo.listClientIds('0', 1);
    expect(one).toEqual(['1']);
  });

  it('listClientIds returns empty array when afterId is past all records', async () => {
    const result = await repo.listClientIds('9999', 100);
    expect(result).toEqual([]);
  });

  // ── listOrderIds ───────────────────────────────────────────────────────────

  it('listOrderIds returns ids > afterId ordered ASC, respecting limit', async () => {
    // afterId='0' => all three orders: 10, 20, 30
    const all = await repo.listOrderIds('0', 100);
    expect(all).toEqual(['10', '20', '30']);

    // afterId='10' => 20, 30
    const page2 = await repo.listOrderIds('10', 100);
    expect(page2).toEqual(['20', '30']);

    // limit=1
    const one = await repo.listOrderIds('0', 1);
    expect(one).toEqual(['10']);
  });

  it('listOrderIds returns empty array when afterId is past all records', async () => {
    const result = await repo.listOrderIds('9999', 100);
    expect(result).toEqual([]);
  });
});
