-- Migration 016: org recipient model (additive)
-- Adds the minimal org structure needed for the notification engine's
-- `workshop_head` and `direction_head` recipient resolvers.
-- Additive only: does NOT alter workshops, work_centers, order_workshops,
-- users, notification_rules, outbox_events, or notifications.
-- Design: spec_erp/docs/domains/notifications/2026-06-11-org-recipient-model-design.md
BEGIN;

-- Reference catalog of производственные направления. May be standalone
-- (no workshop and no work-center links).
CREATE TABLE IF NOT EXISTS directions (
  direction_id   SMALLINT GENERATED BY DEFAULT AS IDENTITY,
  direction_name VARCHAR(128) NOT NULL,
  description    TEXT,
  is_active      BOOLEAN NOT NULL DEFAULT true,
  ref_key_1c     UUID NULL,
  created_by     BIGINT,
  edited_by      BIGINT,
  created_at     TIMESTAMP NOT NULL DEFAULT now(),
  updated_at     TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT pk_directions PRIMARY KEY (direction_id),
  CONSTRAINT uq_directions_name UNIQUE (direction_name)
);

-- Направление includes a whole цех.
CREATE TABLE IF NOT EXISTS direction_workshops (
  direction_id SMALLINT NOT NULL,
  workshop_id  SMALLINT NOT NULL,
  created_by   BIGINT,
  created_at   TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT pk_direction_workshops PRIMARY KEY (direction_id, workshop_id),
  CONSTRAINT fk_direction_workshops_direction
    FOREIGN KEY (direction_id) REFERENCES directions(direction_id) ON DELETE CASCADE,
  CONSTRAINT fk_direction_workshops_workshop
    FOREIGN KEY (workshop_id) REFERENCES workshops(workshop_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_direction_workshops_workshop_id
  ON direction_workshops(workshop_id);

-- Направление includes only specific участки.
CREATE TABLE IF NOT EXISTS direction_work_centers (
  direction_id  SMALLINT NOT NULL,
  workcenter_id SMALLINT NOT NULL,
  created_by    BIGINT,
  created_at    TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT pk_direction_work_centers PRIMARY KEY (direction_id, workcenter_id),
  CONSTRAINT fk_direction_work_centers_direction
    FOREIGN KEY (direction_id) REFERENCES directions(direction_id) ON DELETE CASCADE,
  CONSTRAINT fk_direction_work_centers_workcenter
    FOREIGN KEY (workcenter_id) REFERENCES work_centers(workcenter_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_direction_work_centers_workcenter_id
  ON direction_work_centers(workcenter_id);

-- Руководители цеха (multiple). user_id, not employee_id: a head must be a
-- login user to receive a notification (notifications.user_id).
CREATE TABLE IF NOT EXISTS workshop_heads (
  workshop_id SMALLINT NOT NULL,
  user_id     BIGINT   NOT NULL,
  is_active   BOOLEAN NOT NULL DEFAULT true,
  created_by  BIGINT,
  created_at  TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT pk_workshop_heads PRIMARY KEY (workshop_id, user_id),
  CONSTRAINT fk_workshop_heads_workshop
    FOREIGN KEY (workshop_id) REFERENCES workshops(workshop_id) ON DELETE CASCADE,
  CONSTRAINT fk_workshop_heads_user
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_workshop_heads_workshop_id
  ON workshop_heads(workshop_id);

-- Руководители направления (multiple).
CREATE TABLE IF NOT EXISTS direction_heads (
  direction_id SMALLINT NOT NULL,
  user_id      BIGINT   NOT NULL,
  is_active    BOOLEAN NOT NULL DEFAULT true,
  created_by   BIGINT,
  created_at   TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT pk_direction_heads PRIMARY KEY (direction_id, user_id),
  CONSTRAINT fk_direction_heads_direction
    FOREIGN KEY (direction_id) REFERENCES directions(direction_id) ON DELETE CASCADE,
  CONSTRAINT fk_direction_heads_user
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_direction_heads_direction_id
  ON direction_heads(direction_id);

COMMIT;
