-- Migration 021: sheet_material_types reference (additive)
-- A dedicated sheet-material reference carrying the physical sheet spec
-- (dims + thickness + material_type link). It is BOTH the order-side material
-- spec AND the freecut stock spec. Decision 2026-06-18: a layer over
-- material_types, NOT props piled onto the generic materials catalog.
-- Plan: spec_erp/plans/2026-06-18-freecut-cut-jobs-and-svg-render-plan.md §4.1
-- Additive only: does NOT touch order_details (phased integration §19).
BEGIN;

CREATE TABLE IF NOT EXISTS sheet_material_types (
  sheet_material_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name             VARCHAR(200) NOT NULL,
  material_type_id SMALLINT NOT NULL,
  thickness_mm     NUMERIC(10,2) NOT NULL,
  width_mm         NUMERIC(10,2) NOT NULL,
  height_mm        NUMERIC(10,2) NOT NULL,
  is_active        BOOLEAN NOT NULL DEFAULT true,
  ref_key_1c       UUID NULL,
  created_by       BIGINT,
  edited_by        BIGINT,
  created_at       TIMESTAMP NOT NULL DEFAULT now(),
  updated_at       TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT pk_sheet_material_types PRIMARY KEY (sheet_material_type_id),
  CONSTRAINT uq_sheet_material_types_name UNIQUE (name),
  CONSTRAINT fk_sheet_material_types_material_type
    FOREIGN KEY (material_type_id) REFERENCES material_types(material_type_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT chk_sheet_material_types_thickness_positive CHECK (thickness_mm > 0),
  CONSTRAINT chk_sheet_material_types_width_positive CHECK (width_mm > 0),
  CONSTRAINT chk_sheet_material_types_height_positive CHECK (height_mm > 0)
);

CREATE INDEX IF NOT EXISTS idx_sheet_material_types_material_type_id
  ON sheet_material_types(material_type_id);

-- Additive order-side link: a sheet material maps to its raw sheet spec WITHOUT
-- touching order_details yet. Nullable; the dominant Day-0 state is NULL until
-- specs are seeded and linked (eligibility surfaces this as `no_sheet_spec`).
ALTER TABLE materials
  ADD COLUMN IF NOT EXISTS sheet_material_type_id BIGINT NULL;

-- Idempotent FK add (re-runnable; ADD CONSTRAINT has no IF NOT EXISTS).
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_materials_sheet_material_type'
  ) THEN
    ALTER TABLE materials
      ADD CONSTRAINT fk_materials_sheet_material_type
        FOREIGN KEY (sheet_material_type_id)
        REFERENCES sheet_material_types(sheet_material_type_id)
        ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_materials_sheet_material_type_id
  ON materials(sheet_material_type_id);

COMMIT;
