-- Migration 022: cut-jobs domain (additive)
-- Cut-job domain: details from MULTIPLE orders grouped by flexible criteria into
-- one cutting set (NOT an attribute of a single order). Backend-owned command
-- domain (CLAUDE.md principle 2).
-- Plan: spec_erp/plans/2026-06-18-freecut-cut-jobs-and-svg-render-plan.md §3/§4.2
--
-- ID-type contract (§3): ALL cut-domain PKs are BIGINT GENERATED BY DEFAULT AS
-- IDENTITY (consistent with order_id/project_id), NOT UUID, because the audit
-- bridge audit_log_related_entity.entity_id is BIGINT (migration 020).
-- Additive only. Rollback drops these tables in reverse FK-dependency order.
BEGIN;

-- Named selection / cutting run.
CREATE TABLE IF NOT EXISTS cut_job (
  cut_job_id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name                VARCHAR(200) NOT NULL,
  status              TEXT NOT NULL DEFAULT 'draft',
  source              TEXT NOT NULL DEFAULT 'manual',
  selection_criteria  JSONB,                       -- snapshot of filters used
  params              JSONB,                       -- kerf/spacing/trim/objective/seed snapshot
  request_hash        TEXT,                        -- idempotency anchor (resolved items + params)
  pdf_prewarm_state   TEXT NOT NULL DEFAULT 'pending',   -- async PDF pre-warm (§7 N3 / F1)
  pdf_prewarm_failure_reason TEXT,
  created_by          BIGINT,
  created_at          TIMESTAMP NOT NULL DEFAULT now(),
  updated_at          TIMESTAMP NOT NULL DEFAULT now(),
  version             INTEGER NOT NULL DEFAULT 0,  -- optimistic concurrency
  CONSTRAINT pk_cut_job PRIMARY KEY (cut_job_id),
  CONSTRAINT chk_cut_job_status
    CHECK (status IN ('draft','calculating','ready','archived','failed')),
  CONSTRAINT chk_cut_job_source
    CHECK (source IN ('manual','auto','api')),
  CONSTRAINT chk_cut_job_pdf_prewarm_state
    CHECK (pdf_prewarm_state IN ('pending','ready','failed'))
);

-- Homogeneous slice = ONE freecut call. Cuttable key = (sheet_material_type, film).
CREATE TABLE IF NOT EXISTS cut_group (
  cut_group_id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
  cut_job_id             BIGINT NOT NULL,
  sheet_material_type_id BIGINT,                   -- dims+thickness from sheet_material_type
  film_id                BIGINT,                   -- grain via films.film_texture
  freecut_seed           BIGINT,
  status                 TEXT NOT NULL DEFAULT 'pending',
  summary                JSONB,                    -- used_stock_count, waste_percent, layout_mode
  svg                    TEXT,                     -- DEBUG-only glued svg; NULL in prod (§6)
  created_at             TIMESTAMP NOT NULL DEFAULT now(),
  updated_at             TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT pk_cut_group PRIMARY KEY (cut_group_id),
  CONSTRAINT fk_cut_group_job
    FOREIGN KEY (cut_job_id) REFERENCES cut_job(cut_job_id) ON DELETE CASCADE,
  CONSTRAINT fk_cut_group_sheet_material_type
    FOREIGN KEY (sheet_material_type_id) REFERENCES sheet_material_types(sheet_material_type_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_cut_group_film
    FOREIGN KEY (film_id) REFERENCES films(film_id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_cut_group_job_id ON cut_group(cut_job_id);

-- TYPED high-integrity link part <-> source (not generic links).
-- One row per detail (no `instance` column); per-piece distribution lives in
-- cut_group_sheet.placements JSONB.
CREATE TABLE IF NOT EXISTS cut_job_item (
  cut_job_item_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
  cut_job_id       BIGINT NOT NULL,
  cut_group_id     BIGINT,                         -- assigned at calculate
  order_detail_id  BIGINT NOT NULL,
  order_id         BIGINT NOT NULL,                -- N5: FK-constrained, not a loose copy
  qty              INTEGER NOT NULL,
  is_active        BOOLEAN NOT NULL DEFAULT true,  -- reservation guard (set in same INSERT)
  freecut_item_id  TEXT,                           -- "det-<detail_id>" sent to freecut
  created_at       TIMESTAMP NOT NULL DEFAULT now(),
  updated_at       TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT pk_cut_job_item PRIMARY KEY (cut_job_item_id),
  CONSTRAINT chk_cut_job_item_qty CHECK (qty >= 1),
  CONSTRAINT fk_cut_job_item_job
    FOREIGN KEY (cut_job_id) REFERENCES cut_job(cut_job_id) ON DELETE CASCADE,
  CONSTRAINT fk_cut_job_item_group
    FOREIGN KEY (cut_group_id) REFERENCES cut_group(cut_group_id) ON DELETE SET NULL,
  CONSTRAINT fk_cut_job_item_detail
    FOREIGN KEY (order_detail_id) REFERENCES order_details(detail_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_cut_job_item_order
    FOREIGN KEY (order_id) REFERENCES orders(order_id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_cut_job_item_job_id ON cut_job_item(cut_job_id);
CREATE INDEX IF NOT EXISTS idx_cut_job_item_group_id ON cut_job_item(cut_group_id);
CREATE INDEX IF NOT EXISTS idx_cut_job_item_order_id ON cut_job_item(order_id);

-- Reservation guard (BLOCKER-1): a detail piece belongs to at most one ACTIVE
-- cut job. The partial UNIQUE INDEX is the ONLY enforcement; PostgreSQL
-- serializes concurrent index-tuple inserts and raises 23505 at COMMIT even
-- under READ COMMITTED. Release = UPDATE is_active=false (removes from index).
CREATE UNIQUE INDEX IF NOT EXISTS uq_cut_job_item_active_detail
  ON cut_job_item (order_detail_id)
  WHERE is_active = true;

-- Per-sheet artifact metadata; placements JSONB is the render source of truth.
CREATE TABLE IF NOT EXISTS cut_group_sheet (
  cut_group_sheet_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
  cut_group_id           BIGINT NOT NULL,
  sheet_index            INTEGER NOT NULL,
  sheet_material_type_id BIGINT,
  png_cache_key          TEXT,
  pdf_generated          BOOLEAN NOT NULL DEFAULT false,
  placements             JSONB NOT NULL,           -- backend-normalized per-sheet placements
  created_at             TIMESTAMP NOT NULL DEFAULT now(),
  updated_at             TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT pk_cut_group_sheet PRIMARY KEY (cut_group_sheet_id),
  CONSTRAINT uq_cut_group_sheet_index UNIQUE (cut_group_id, sheet_index),
  CONSTRAINT fk_cut_group_sheet_group
    FOREIGN KEY (cut_group_id) REFERENCES cut_group(cut_group_id) ON DELETE CASCADE,
  CONSTRAINT fk_cut_group_sheet_material_type
    FOREIGN KEY (sheet_material_type_id) REFERENCES sheet_material_types(sheet_material_type_id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_cut_group_sheet_group_id ON cut_group_sheet(cut_group_id);

COMMIT;
