import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const sql = readFileSync(new URL('./022_cut_jobs.sql', import.meta.url), 'utf8');

describe('022_cut_jobs migration', () => {
  it('creates the four cut-domain tables additively', () => {
    expect(sql).toMatch(/CREATE TABLE IF NOT EXISTS cut_job\b/i);
    expect(sql).toMatch(/CREATE TABLE IF NOT EXISTS cut_group\b/i);
    expect(sql).toMatch(/CREATE TABLE IF NOT EXISTS cut_job_item\b/i);
    expect(sql).toMatch(/CREATE TABLE IF NOT EXISTS cut_group_sheet\b/i);
  });

  it('all cut-domain PKs are BIGINT GENERATED BY DEFAULT AS IDENTITY (audit bridge is BIGINT)', () => {
    expect(sql).toMatch(/cut_job_id\s+BIGINT GENERATED BY DEFAULT AS IDENTITY/i);
    expect(sql).toMatch(/cut_group_id\s+BIGINT GENERATED BY DEFAULT AS IDENTITY/i);
    expect(sql).toMatch(/cut_job_item_id\s+BIGINT GENERATED BY DEFAULT AS IDENTITY/i);
    expect(sql).toMatch(/cut_group_sheet_id\s+BIGINT GENERATED BY DEFAULT AS IDENTITY/i);
  });

  it('enforces the reservation guard as a partial unique index on active items only', () => {
    expect(sql).toMatch(
      /CREATE UNIQUE INDEX[\s\S]*uq_cut_job_item_active_detail[\s\S]*ON cut_job_item\s*\(\s*order_detail_id\s*\)[\s\S]*WHERE\s+is_active\s*=\s*true/i,
    );
  });

  it('cut_job_item.is_active is NOT NULL (set in the same INSERT as the reservation)', () => {
    expect(sql).toMatch(/is_active\s+BOOLEAN NOT NULL/i);
  });

  it('cut_job_item.order_id is an FK to orders (N5: no stale bridge rows)', () => {
    expect(sql).toMatch(/order_id\s+BIGINT NOT NULL/i);
    expect(sql).toMatch(/REFERENCES orders\(order_id\)/i);
  });

  it('cut_job_item links the source detail by its real key', () => {
    expect(sql).toMatch(/order_detail_id\s+BIGINT NOT NULL/i);
    expect(sql).toMatch(/REFERENCES order_details\(detail_id\)/i);
  });

  it('cut_job.pdf_prewarm_state has a CHECK over pending/ready/failed (F1)', () => {
    expect(sql).toMatch(/pdf_prewarm_state\s+TEXT NOT NULL DEFAULT 'pending'/i);
    expect(sql).toMatch(
      /pdf_prewarm_state\s+IN\s*\(\s*'pending'\s*,\s*'ready'\s*,\s*'failed'\s*\)/i,
    );
    expect(sql).toMatch(/pdf_prewarm_failure_reason\s+TEXT/i);
  });

  it('cut_job carries optimistic version + request_hash idempotency anchor', () => {
    expect(sql).toMatch(/version\s+INTEGER NOT NULL DEFAULT 0/i);
    expect(sql).toMatch(/request_hash\s+TEXT/i);
  });

  it('cut_group_sheet stores normalized placements JSONB (render source of truth)', () => {
    expect(sql).toMatch(/placements\s+JSONB NOT NULL/i);
  });

  it('cut_group references sheet_material_types and films by their real keys', () => {
    expect(sql).toMatch(/REFERENCES sheet_material_types\(sheet_material_type_id\)/i);
    expect(sql).toMatch(/REFERENCES films\(film_id\)/i);
  });

  it('child rows cascade from the job (rollback = DROP in reverse FK order)', () => {
    expect(sql).toMatch(/REFERENCES cut_job\(cut_job_id\)\s+ON DELETE CASCADE/i);
  });

  it('is additive: no ALTER/DROP of existing order or material tables', () => {
    expect(sql).not.toMatch(/ALTER TABLE (public\.)?order_details/i);
    expect(sql).not.toMatch(/ALTER TABLE (public\.)?orders\b/i);
    expect(sql).not.toMatch(/DROP TABLE/i);
  });
});
