import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const sql = readFileSync(new URL('./023_cut_config.sql', import.meta.url), 'utf8');

describe('023_cut_config migration', () => {
  it('creates the config tables additively', () => {
    expect(sql).toMatch(/CREATE TABLE IF NOT EXISTS cut_param_profiles\b/i);
    expect(sql).toMatch(/CREATE TABLE IF NOT EXISTS cut_render_presets\b/i);
    expect(sql).toMatch(/CREATE TABLE IF NOT EXISTS cut_pdf_templates\b/i);
    expect(sql).toMatch(/CREATE TABLE IF NOT EXISTS cut_settings\b/i);
  });

  it('config catalog PKs are BIGINT GENERATED BY DEFAULT AS IDENTITY', () => {
    expect(sql).toMatch(/cut_param_profile_id\s+BIGINT GENERATED BY DEFAULT AS IDENTITY/i);
    expect(sql).toMatch(/cut_render_preset_id\s+BIGINT GENERATED BY DEFAULT AS IDENTITY/i);
    expect(sql).toMatch(/cut_pdf_template_id\s+BIGINT GENERATED BY DEFAULT AS IDENTITY/i);
  });

  it('param profiles + render presets + settings carry optimistic version', () => {
    expect(sql).toMatch(/cut_param_profiles[\s\S]*version\s+INTEGER NOT NULL DEFAULT 0/i);
    expect(sql).toMatch(/cut_settings[\s\S]*version\s+INTEGER NOT NULL DEFAULT 0/i);
  });

  it('enforces at most one default param profile via a partial unique index', () => {
    expect(sql).toMatch(
      /CREATE UNIQUE INDEX[\s\S]*uq_cut_param_profiles_default[\s\S]*WHERE\s+is_default\s*=\s*true/i,
    );
  });

  it('cut_settings is a keyed single-source-of-truth table (key PK, JSONB value)', () => {
    expect(sql).toMatch(/cut_settings\s*\([\s\S]*key\s+TEXT[\s\S]*PRIMARY KEY/i);
    expect(sql).toMatch(/value\s+JSONB NOT NULL/i);
  });

  it('seeds defaults = the Slice-1 constants (eligibility statuses + freecut params)', () => {
    // Ready-to-cut status codes match the Slice-1 READY_STATUS_CODES constant.
    expect(sql).toMatch(/eligibility\.statuses/);
    expect(sql).toMatch(/new[\s\S]*drawn[\s\S]*film_purchase/);
    // Default freecut param profile carries the calibrated budget (commit dcfa2db).
    expect(sql).toMatch(/time_limit_ms/);
    expect(sql).toMatch(/retry_strategy/);
    expect(sql).toMatch(/is_default\s*\)?\s*VALUES|is_default[\s\S]*true/i);
  });

  it('seeds the grain.rules mapping (film_texture -> rotation/pattern_direction)', () => {
    expect(sql).toMatch(/grain\.rules/);
    expect(sql).toMatch(/forbid/);
    expect(sql).toMatch(/along_height/);
    expect(sql).toMatch(/allow_90/);
  });

  it('seeds the three render presets (thumb/screen/print)', () => {
    expect(sql).toMatch(/thumb/);
    expect(sql).toMatch(/screen/);
    expect(sql).toMatch(/print/);
  });

  it('seeds standard and bath PDF templates', () => {
    expect(sql).toMatch(/cut_pdf_templates/i);
    expect(sql).toMatch(/standard/i);
    expect(sql).toMatch(/bath_profiles/i);
  });

  it('seeds an auto_trigger settings row (Slice 3 consumes the thresholds)', () => {
    expect(sql).toMatch(/auto_trigger/);
  });

  it('seeds are idempotent (re-runnable via ON CONFLICT DO NOTHING)', () => {
    expect(sql).toMatch(/ON CONFLICT[\s\S]*DO NOTHING/i);
  });

  it('is additive: no ALTER/DROP of existing cut or order tables', () => {
    expect(sql).not.toMatch(/ALTER TABLE (public\.)?cut_job\b/i);
    expect(sql).not.toMatch(/ALTER TABLE (public\.)?order_details/i);
    expect(sql).not.toMatch(/DROP TABLE/i);
  });
});
