-- Migration 023: cut configuration (additive, config-driven)
-- Rules-as-data for the cut domain so sheet specs, freecut param profiles,
-- render presets, eligibility statuses and grain rules are editable under the
-- /configuration "Раскрой" tab WITHOUT code (plan §4a). Bounded catalog + a
-- keyed app_settings-style table; NOT a turing-complete rule engine.
-- Plan: spec_erp/plans/2026-06-18-freecut-cut-jobs-and-svg-render-plan.md §4a
--
-- Seed defaults reproduce the Slice-1 constants (READY_STATUS_CODES +
-- DEFAULT_FREECUT_PARAMS) so behaviour is unchanged when the operator has not
-- touched config yet. The cut repo sources these from config with a documented
-- in-code fallback for an empty/absent table.
-- Additive only. Rollback drops these three tables in reverse order; nothing
-- existing is altered.
BEGIN;

-- Named freecut parameter profiles ("МДФ быстрый", "ЛДСП качество", ...).
-- params JSONB = kerf/spacing/trim/objective/time_limit_ms/restarts/
-- retry_strategy/layout_mode (validated against the freecut contract on write).
CREATE TABLE IF NOT EXISTS cut_param_profiles (
  cut_param_profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name        VARCHAR(200) NOT NULL,
  params      JSONB NOT NULL,
  is_default  BOOLEAN NOT NULL DEFAULT false,
  is_active   BOOLEAN NOT NULL DEFAULT true,
  created_by  BIGINT,
  edited_by   BIGINT,
  created_at  TIMESTAMP NOT NULL DEFAULT now(),
  updated_at  TIMESTAMP NOT NULL DEFAULT now(),
  version     INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT pk_cut_param_profiles PRIMARY KEY (cut_param_profile_id),
  CONSTRAINT uq_cut_param_profiles_name UNIQUE (name)
);
-- At most one default profile (partial unique index over is_default=true).
CREATE UNIQUE INDEX IF NOT EXISTS uq_cut_param_profiles_default
  ON cut_param_profiles (is_default)
  WHERE is_default = true;

-- Render presets (thumb/screen/print): cap the longest rendered side in px.
CREATE TABLE IF NOT EXISTS cut_render_presets (
  cut_render_preset_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name        VARCHAR(100) NOT NULL,
  target_px   INTEGER NOT NULL,
  background  TEXT NOT NULL DEFAULT '#ffffff',
  is_active   BOOLEAN NOT NULL DEFAULT true,
  created_by  BIGINT,
  edited_by   BIGINT,
  created_at  TIMESTAMP NOT NULL DEFAULT now(),
  updated_at  TIMESTAMP NOT NULL DEFAULT now(),
  version     INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT pk_cut_render_presets PRIMARY KEY (cut_render_preset_id),
  CONSTRAINT uq_cut_render_presets_name UNIQUE (name),
  CONSTRAINT chk_cut_render_presets_target_px_positive CHECK (target_px > 0)
);

-- Keyed single-source-of-truth rule table (app_settings style). Each row is one
-- bounded rule set edited in the UI: eligibility.statuses, grain.rules,
-- defaults, auto_trigger. Changing config never retro-mutates existing cut_jobs
-- (they snapshot params/criteria at creation — stale-safe).
CREATE TABLE IF NOT EXISTS cut_settings (
  key         TEXT NOT NULL,
  value       JSONB NOT NULL,
  version     INTEGER NOT NULL DEFAULT 0,
  updated_by  BIGINT,
  updated_at  TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT pk_cut_settings PRIMARY KEY (key)
);

-- ---------------------------------------------------------------------------
-- Seed defaults (idempotent). These mirror the Slice-1 in-code constants.
-- ---------------------------------------------------------------------------

-- Default freecut param profile = DEFAULT_FREECUT_PARAMS (calibrated budget,
-- commit dcfa2db: 1200ms/5 restarts + retry_strategy=disabled => ~1.5s SLA).
INSERT INTO cut_param_profiles (name, params, is_default)
VALUES (
  'default',
  '{
    "kerf_mm": 2,
    "spacing_mm": 1,
    "trim_mm": { "left": 10, "right": 10, "top": 10, "bottom": 10 },
    "objective": "min_waste",
    "time_limit_ms": 1200,
    "restarts": 5,
    "layout_mode": "guillotine",
    "retry_strategy": "disabled"
  }'::jsonb,
  true
)
ON CONFLICT (name) DO NOTHING;

-- Render presets = the Slice-1 RENDER_PRESETS (cap longest side).
INSERT INTO cut_render_presets (name, target_px)
VALUES ('thumb', 360), ('screen', 1400), ('print', 3500)
ON CONFLICT (name) DO NOTHING;

-- Ready-to-cut statuses = READY_STATUS_CODES. Stored as production-status CODES
-- (resolved to ids at query time so it stays DB-portable; the eligibility SQL
-- pushes the resolved ids into its WHERE clause).
INSERT INTO cut_settings (key, value)
VALUES (
  'eligibility.statuses',
  '{ "codes": ["new", "drawn", "film_purchase"] }'::jsonb
)
ON CONFLICT (key) DO NOTHING;

-- Grain rules: films.film_texture -> rotation / pattern_direction (plan §6).
-- Write-time enum-validated by the config CRUD (rotation in {forbid,allow_90};
-- pattern_direction in {none,along_width,along_height}).
INSERT INTO cut_settings (key, value)
VALUES (
  'grain.rules',
  '{
    "textured": { "rotation": "forbid", "pattern_direction": "along_height" },
    "plain":    { "rotation": "allow_90", "pattern_direction": "none" }
  }'::jsonb
)
ON CONFLICT (key) DO NOTHING;

-- Defaults: which named profile/preset the engine picks when unspecified.
INSERT INTO cut_settings (key, value)
VALUES (
  'defaults',
  '{ "param_profile": "default", "render_preset": "screen" }'::jsonb
)
ON CONFLICT (key) DO NOTHING;

-- Auto-trigger thresholds (Slice 3 consumes these; the row exists now so the
-- config UI can edit them and Slice 3 only wires the event hooks). Off here.
INSERT INTO cut_settings (key, value)
VALUES (
  'auto_trigger',
  '{
    "enabled": false,
    "area_sheet_fill": { "enabled": false, "min_sheets": 1 },
    "detail_count":    { "enabled": false, "threshold": 0 },
    "status_completeness": { "enabled": false }
  }'::jsonb
)
ON CONFLICT (key) DO NOTHING;

COMMIT;
