-- 033: committed conversion manifest (idempotent). Extend ONLY by a reviewed commit
-- to THIS file; prove zero-unmapped on the restore rehearsal BEFORE go-live. NEVER
-- edit the map during the cutover window. The manifest carries the FULL target-type
-- attributes (Critic R10 B2) — unit_id/material_type_id/dims/thickness — so 034 creates
-- each target type with the CORRECT attrs (not hardcoded), matching the SP3 contract:
--   не определён: mtype 3, 16мм; черновой МДФ 16мм: mtype 1, 16мм; МДФ 10мм: mtype 1,
--   10мм; ФАНЕРА: mtype 3, 18мм. Non-cuttable types use placeholder dims=1.
CREATE TABLE IF NOT EXISTS sheet_material_conversion_map (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_material_id   BIGINT,
  legacy_material_name TEXT,
  target_key           TEXT     NOT NULL,   -- IMMUTABLE identity of the target sheet type (Critic R22 B1)
  target_sheet_name    TEXT     NOT NULL,   -- DISPLAY name (operator-editable; NOT used as rerun identity)
  is_cuttable          BOOLEAN  NOT NULL DEFAULT true,
  target_unit_id          SMALLINT NOT NULL DEFAULT 1,
  target_material_type_id SMALLINT NOT NULL,
  target_width_mm         NUMERIC  NOT NULL,
  target_height_mm        NUMERIC  NOT NULL,
  target_thickness_mm     NUMERIC  NOT NULL,
  CONSTRAINT chk_map_key  CHECK (legacy_material_id IS NOT NULL OR legacy_material_name IS NOT NULL),
  CONSTRAINT chk_map_dims CHECK (target_width_mm > 0 AND target_height_mm > 0 AND target_thickness_mm > 0),
  CONSTRAINT uq_map_id    UNIQUE (legacy_material_id),
  CONSTRAINT uq_map_name  UNIQUE (legacy_material_name)
);
-- Critic R22 B1: add an immutable conversion key to sheet_material_types so 034
-- joins/creates targets by a STABLE key, not the mutable display name.
ALTER TABLE sheet_material_types
  ADD COLUMN IF NOT EXISTS conversion_key TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS uq_sheet_material_types_conversion_key
  ON sheet_material_types(conversion_key) WHERE conversion_key IS NOT NULL;

-- FULL REPLACE so the manifest is truly re-runnable (Critic R18 B1): editing this
-- committed seed + re-applying 033 corrects attrs/targets AND drops stale rows. The
-- table is a config manifest (no FKs into it), so a clean replace inside the migration
-- tx is safe. (NOT ON CONFLICT DO NOTHING — that could never fix a bad existing row.)
DELETE FROM sheet_material_conversion_map;

-- panel materials not covered by the SP2 auto-derive (by legacy material_id). Each row
-- carries an IMMUTABLE target_key (identity) + a display target_sheet_name + full attrs:
INSERT INTO sheet_material_conversion_map
  (legacy_material_id, target_key, target_sheet_name, is_cuttable, target_unit_id, target_material_type_id, target_width_mm, target_height_mm, target_thickness_mm) VALUES
  (0,   'NOT_DEFINED',       'не определён',      true, 1, 3, 2800, 2070, 16),
  (161, 'ROUGH_MDF_16',      'черновой МДФ 16мм', true, 1, 1, 2800, 2070, 16),
  (175, 'ROUGH_MDF_16',      'черновой МДФ 16мм', true, 1, 1, 2800, 2070, 16),
  (206, 'ROUGH_MDF_16',      'черновой МДФ 16мм', true, 1, 1, 2800, 2070, 16),
  (15,  'MDF_10',            'МДФ 10мм',          true, 1, 1, 2800, 2070, 10),
  (46,  'PLYWOOD',           'ФАНЕРА',            true, 1, 3, 2800, 2070, 18);

-- non-panel header materials (by legacy material_name) -> non-cuttable target (placeholder dims):
INSERT INTO sheet_material_conversion_map
  (legacy_material_name, target_key, target_sheet_name, is_cuttable, target_unit_id, target_material_type_id, target_width_mm, target_height_mm, target_thickness_mm) VALUES
  ('краска', 'PAINT', 'краска', false, 1, 3, 1, 1, 1);

-- A target_key must have ONE consistent attr set across rows — assert below.
DO $$
DECLARE v_dup INT;
BEGIN
  SELECT count(*) INTO v_dup FROM (
    SELECT target_key FROM sheet_material_conversion_map
    GROUP BY target_key
    HAVING count(DISTINCT (target_sheet_name, is_cuttable, target_unit_id, target_material_type_id, target_width_mm, target_height_mm, target_thickness_mm)) > 1
  ) q;
  IF v_dup > 0 THEN RAISE EXCEPTION 'manifest: % target_key(s) have inconsistent attrs', v_dup; END IF;
END $$;

-- PREP sheet_material_types in 033 (Critic R27 B2/B3): add is_cuttable, adopt conversion_key
-- on any pre-existing target type BY NAME ONCE, create missing target types BY key, and set
-- is_cuttable — so that AFTER 033 (i.e. at PREFLIGHT time, before 034) every target is keyed
-- + cuttability-flagged and the preflight can resolve by conversion_key (not mutable name).
ALTER TABLE sheet_material_types ADD COLUMN IF NOT EXISTS is_cuttable BOOLEAN NOT NULL DEFAULT true;
UPDATE sheet_material_types s SET conversion_key = mk.target_key
  FROM (SELECT DISTINCT target_key, target_sheet_name FROM sheet_material_conversion_map) mk
 WHERE s.conversion_key IS NULL AND s.name = mk.target_sheet_name;
INSERT INTO sheet_material_types (name, unit_id, material_type_id, width_mm, height_mm, thickness_mm, is_active, is_cuttable, conversion_key)
SELECT DISTINCT ON (t.target_key) t.target_sheet_name, t.target_unit_id, t.target_material_type_id,
       t.target_width_mm, t.target_height_mm, t.target_thickness_mm, true, t.is_cuttable, t.target_key
FROM sheet_material_conversion_map t
WHERE NOT EXISTS (SELECT 1 FROM sheet_material_types s WHERE s.conversion_key = t.target_key)
ORDER BY t.target_key;
-- Reconcile EXISTING target rows to manifest-owned STRUCTURAL attrs (Critic R7 B1): if 033
-- is reapplied after a manifest edit, already-keyed types must be updated so that 034's
-- structural-attr fail-closed check (0.0b2) converges instead of aborting. DISPLAY attrs
-- (name, dims) are intentionally NOT overwritten — they are operator-editable via the SP1
-- UI and 034 does NOT assert them. Only manifest-owned structural attrs are reconciled:
-- unit_id, material_type_id, is_cuttable.
UPDATE sheet_material_types s
   SET unit_id           = mk.target_unit_id,
       material_type_id  = mk.target_material_type_id,
       is_cuttable       = mk.is_cuttable
  FROM (
    SELECT DISTINCT ON (target_key) target_key, target_unit_id, target_material_type_id, is_cuttable
    FROM sheet_material_conversion_map
    ORDER BY target_key
  ) mk
 WHERE s.conversion_key = mk.target_key
   AND (s.unit_id <> mk.target_unit_id
     OR s.material_type_id <> mk.target_material_type_id
     OR s.is_cuttable <> mk.is_cuttable);
