-- 039_labels.sql
-- Additive labels foundation. RBAC permissions are static in
-- backend/src/permissions/permissions.ts:
-- labels.view, labels.manage_templates, labels.generate.

BEGIN;

CREATE TABLE IF NOT EXISTS label_templates (
  label_template_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  version INTEGER NOT NULL DEFAULT 1,
  is_active BOOLEAN NOT NULL DEFAULT true,
  canvas_width_mm NUMERIC(10, 3) NOT NULL,
  canvas_height_mm NUMERIC(10, 3) NOT NULL,
  dpi INTEGER NOT NULL DEFAULT 203,
  default_export_formats TEXT[] NOT NULL DEFAULT ARRAY['bmp']::TEXT[],
  custom_field_schema JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  CONSTRAINT chk_label_templates_canvas_positive
    CHECK (canvas_width_mm > 0 AND canvas_height_mm > 0),
  CONSTRAINT chk_label_templates_dpi_positive
    CHECK (dpi > 0),
  CONSTRAINT chk_label_templates_default_export_formats
    CHECK (default_export_formats <@ ARRAY['bmp', 'png', 'emf']::TEXT[]),
  CONSTRAINT chk_label_templates_custom_field_schema_object
    CHECK (jsonb_typeof(custom_field_schema) = 'object')
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_label_templates_name_live
  ON label_templates (lower(name))
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_label_templates_active
  ON label_templates (is_active, updated_at DESC)
  WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS label_template_elements (
  label_template_element_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label_template_id BIGINT NOT NULL REFERENCES label_templates(label_template_id) ON DELETE CASCADE,
  element_key TEXT NOT NULL,
  kind TEXT NOT NULL,
  source_field TEXT,
  static_text TEXT,
  x_mm NUMERIC(10, 3) NOT NULL,
  y_mm NUMERIC(10, 3) NOT NULL,
  width_mm NUMERIC(10, 3) NOT NULL,
  height_mm NUMERIC(10, 3) NOT NULL,
  rotation_deg NUMERIC(10, 3) NOT NULL DEFAULT 0,
  z_index INTEGER NOT NULL DEFAULT 0,
  style_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  condition_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ux_label_template_elements_template_key
    UNIQUE (label_template_id, element_key),
  CONSTRAINT chk_label_template_elements_kind
    CHECK (kind IN ('text', 'line', 'rect')),
  CONSTRAINT chk_label_template_elements_box_non_negative
    CHECK (x_mm >= 0 AND y_mm >= 0 AND width_mm >= 0 AND height_mm >= 0),
  CONSTRAINT chk_label_template_elements_style_object
    CHECK (jsonb_typeof(style_json) = 'object'),
  CONSTRAINT chk_label_template_elements_condition_object
    CHECK (jsonb_typeof(condition_json) = 'object')
);

CREATE INDEX IF NOT EXISTS idx_label_template_elements_template_id
  ON label_template_elements (label_template_id, z_index, label_template_element_id);

CREATE TABLE IF NOT EXISTS order_label_detail_data (
  order_label_detail_data_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
  detail_id BIGINT NOT NULL REFERENCES order_details(detail_id) ON DELETE CASCADE,
  label_template_id BIGINT NOT NULL REFERENCES label_templates(label_template_id) ON DELETE RESTRICT,
  bazis_fields JSONB NOT NULL DEFAULT '{}'::JSONB,
  custom_fields JSONB NOT NULL DEFAULT '{}'::JSONB,
  custom_field_schema_snapshot JSONB NOT NULL DEFAULT '{}'::JSONB,
  version INTEGER NOT NULL DEFAULT 1,
  created_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
  edited_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ux_order_label_detail_data_scope
    UNIQUE (order_id, detail_id, label_template_id),
  CONSTRAINT chk_order_label_detail_data_bazis_object
    CHECK (jsonb_typeof(bazis_fields) = 'object'),
  CONSTRAINT chk_order_label_detail_data_custom_object
    CHECK (jsonb_typeof(custom_fields) = 'object'),
  CONSTRAINT chk_order_label_detail_data_schema_snapshot_object
    CHECK (jsonb_typeof(custom_field_schema_snapshot) = 'object')
);

CREATE INDEX IF NOT EXISTS idx_order_label_detail_data_order_template
  ON order_label_detail_data (order_id, label_template_id);

CREATE INDEX IF NOT EXISTS idx_order_label_detail_data_detail
  ON order_label_detail_data (detail_id);

CREATE TABLE IF NOT EXISTS order_label_generations (
  order_label_generation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
  label_template_id BIGINT NOT NULL REFERENCES label_templates(label_template_id) ON DELETE RESTRICT,
  template_version INTEGER NOT NULL,
  idempotency_key TEXT NOT NULL,
  request_hash TEXT NOT NULL,
  preview_token_hash TEXT NOT NULL,
  detail_filters JSONB NOT NULL DEFAULT '{}'::JSONB,
  template_snapshot JSONB NOT NULL,
  rows_snapshot JSONB NOT NULL,
  label_count INTEGER NOT NULL,
  export_formats TEXT[] NOT NULL,
  export_artifacts JSONB NOT NULL DEFAULT '{}'::JSONB,
  generated_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
  request_id TEXT NOT NULL,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_order_label_generations_template_version_positive
    CHECK (template_version > 0),
  CONSTRAINT chk_order_label_generations_label_count_non_negative
    CHECK (label_count >= 0),
  CONSTRAINT chk_order_label_generations_export_formats
    CHECK (export_formats <@ ARRAY['bmp', 'png', 'emf']::TEXT[]),
  CONSTRAINT chk_order_label_generations_detail_filters_object
    CHECK (jsonb_typeof(detail_filters) = 'object'),
  CONSTRAINT chk_order_label_generations_template_snapshot_object
    CHECK (jsonb_typeof(template_snapshot) = 'object'),
  CONSTRAINT chk_order_label_generations_rows_snapshot_array
    CHECK (jsonb_typeof(rows_snapshot) = 'array'),
  CONSTRAINT chk_order_label_generations_export_artifacts_object
    CHECK (jsonb_typeof(export_artifacts) = 'object')
);

CREATE INDEX IF NOT EXISTS idx_order_label_generations_order_generated_at
  ON order_label_generations (order_id, generated_at DESC);

CREATE INDEX IF NOT EXISTS idx_order_label_generations_template
  ON order_label_generations (label_template_id, template_version);

CREATE INDEX IF NOT EXISTS idx_order_label_generations_request_id
  ON order_label_generations (request_id);

CREATE INDEX IF NOT EXISTS idx_order_label_generations_idempotency_key
  ON order_label_generations (idempotency_key);

COMMIT;

-- ── Down ────────────────────────────────────────────────────────────────────
-- DROP TABLE IF EXISTS order_label_generations;
-- DROP TABLE IF EXISTS order_label_detail_data;
-- DROP TABLE IF EXISTS label_template_elements;
-- DROP TABLE IF EXISTS label_templates;
