import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const sql = readFileSync(new URL('./045_cut_group_manual_layout.sql', import.meta.url), 'utf8');
const liveSql = sql.split(/--[^\n]*Down/i)[0];

describe('migration 045 cut_group_manual_layout', () => {
  it('creates cut_group_manual_layout table with GENERATED BY DEFAULT AS IDENTITY PK', () => {
    expect(liveSql).toMatch(
      /CREATE TABLE IF NOT EXISTS cut_group_manual_layout/i,
    );
    expect(liveSql).toMatch(
      /cut_group_manual_layout_id\s+BIGINT\s+GENERATED BY DEFAULT AS IDENTITY/i,
    );
    expect(liveSql).toMatch(
      /CONSTRAINT pk_cut_group_manual_layout PRIMARY KEY \(cut_group_manual_layout_id\)/i,
    );
  });

  it('has required columns: cut_job_id FK with CASCADE, group_key, sheets, is_active, is_stale, based_on_job_version, version, created_by, created_at, updated_at', () => {
    expect(liveSql).toMatch(/cut_job_id\s+BIGINT\s+NOT NULL/i);
    expect(liveSql).toMatch(/REFERENCES cut_job\(cut_job_id\) ON DELETE CASCADE/i);
    expect(liveSql).toMatch(/group_key\s+TEXT\s+NOT NULL/i);
    expect(liveSql).toMatch(/sheets\s+JSONB\s+NOT NULL/i);
    expect(liveSql).toMatch(/is_active\s+BOOLEAN\s+NOT NULL\s+DEFAULT FALSE/i);
    expect(liveSql).toMatch(/is_stale\s+BOOLEAN\s+NOT NULL\s+DEFAULT FALSE/i);
    expect(liveSql).toMatch(/based_on_job_version\s+INTEGER\s+NOT NULL/i);
    expect(liveSql).toMatch(/version\s+INTEGER\s+NOT NULL\s+DEFAULT 1/i);
    expect(liveSql).toMatch(/created_by\s+BIGINT\s+REFERENCES users\(user_id\)/i);
    expect(liveSql).toMatch(/created_at\s+TIMESTAMPTZ\s+NOT NULL/i);
    expect(liveSql).toMatch(/updated_at\s+TIMESTAMPTZ\s+NOT NULL/i);
  });

  it('has UNIQUE constraint on (cut_job_id, group_key)', () => {
    expect(liveSql).toMatch(/UNIQUE\s*\(\s*cut_job_id\s*,\s*group_key\s*\)/i);
  });

  it('creates index idx_cut_group_manual_layout_job on cut_group_manual_layout(cut_job_id)', () => {
    expect(liveSql).toMatch(
      /CREATE INDEX IF NOT EXISTS idx_cut_group_manual_layout_job\s+ON cut_group_manual_layout\s*\(cut_job_id\)/i,
    );
  });

  it('adds nullable group_key column to cut_group (no NOT NULL, no DEFAULT)', () => {
    expect(liveSql).toMatch(
      /ALTER TABLE cut_group\s+ADD COLUMN IF NOT EXISTS group_key TEXT/i,
    );
    // Must NOT have NOT NULL constraint (it must remain nullable)
    const addGroupKeyLine = liveSql.match(
      /ALTER TABLE cut_group\s+ADD COLUMN IF NOT EXISTS group_key TEXT[^\n;]*/i,
    )?.[0] ?? '';
    expect(addGroupKeyLine).not.toMatch(/NOT NULL/i);
  });

  it('creates partial unique index uq_cut_group_job_key WHERE group_key IS NOT NULL', () => {
    expect(liveSql).toMatch(
      /CREATE UNIQUE INDEX IF NOT EXISTS uq_cut_group_job_key\s+ON cut_group\s*\(cut_job_id\s*,\s*group_key\s*\)\s+WHERE group_key IS NOT NULL/i,
    );
  });

  it('adds last_calc_params JSONB to cut_job', () => {
    expect(liveSql).toMatch(
      /ALTER TABLE cut_job\s+ADD COLUMN IF NOT EXISTS last_calc_params JSONB/i,
    );
  });

  it('adds last_calc_basis TEXT to cut_job', () => {
    expect(liveSql).toMatch(
      /ALTER TABLE cut_job\s+ADD COLUMN IF NOT EXISTS last_calc_basis TEXT/i,
    );
  });

  it('documents Down migration drops in reverse order', () => {
    expect(sql).toMatch(/DROP INDEX IF EXISTS uq_cut_group_job_key/i);
    expect(sql).toMatch(/DROP COLUMN IF EXISTS group_key/i);
    expect(sql).toMatch(/DROP INDEX IF EXISTS idx_cut_group_manual_layout_job/i);
    expect(sql).toMatch(/DROP TABLE IF EXISTS cut_group_manual_layout/i);
    expect(sql).toMatch(/DROP COLUMN IF EXISTS last_calc_params/i);
    expect(sql).toMatch(/DROP COLUMN IF EXISTS last_calc_basis/i);
  });
});
