-- 045_cut_group_manual_layout.sql
--
-- ADDITIVE migration — manual layout editor persistence + stable group identity.
-- Safe to apply while the OLD backend is still running:
--   • cut_group.group_key is NULLABLE (no backfill). Old writer omits it (NULL).
--     The PARTIAL UNIQUE index enforces uniqueness only WHERE group_key IS NOT NULL,
--     so legacy NULL rows are never rejected.
--   • cut_job.last_calc_params / last_calc_basis are NULLABLE. Existing jobs get
--     NULL → editorParams=null → manual editor disabled until operator re-calculates
--     (one-time, non-destructive cutover; no auto batch-recalc).
--
-- ID-type contract: ALL cut-domain PKs are BIGINT GENERATED BY DEFAULT AS IDENTITY
-- (consistent with 022_cut_jobs.sql §3 and the audit bridge integer constraint).
-- GENERATED BY DEFAULT (not ALWAYS) keeps restore/seq-reset working.

-- ── cut_group_manual_layout ───────────────────────────────────────────────────
-- Stores operator-adjusted sheet placements for one cut group.
-- One row per (job, group_key, variant); at most one is_active=true per group_key.
CREATE TABLE IF NOT EXISTS cut_group_manual_layout (
  cut_group_manual_layout_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  cut_job_id                 BIGINT NOT NULL,
  group_key                  TEXT NOT NULL,
  sheets                     JSONB NOT NULL,
  is_active                  BOOLEAN NOT NULL DEFAULT FALSE,
  is_stale                   BOOLEAN NOT NULL DEFAULT FALSE,
  based_on_job_version       INTEGER NOT NULL,
  version                    INTEGER NOT NULL DEFAULT 1,
  created_by                 BIGINT REFERENCES users(user_id),
  created_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT pk_cut_group_manual_layout PRIMARY KEY (cut_group_manual_layout_id),
  CONSTRAINT uq_cut_group_manual_layout_job_key UNIQUE (cut_job_id, group_key),
  CONSTRAINT fk_cut_group_manual_layout_job
    FOREIGN KEY (cut_job_id) REFERENCES cut_job(cut_job_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_cut_group_manual_layout_job
  ON cut_group_manual_layout (cut_job_id);

-- ── cut_group.group_key ───────────────────────────────────────────────────────
-- Stable text identity for a group within a job (e.g. "mat:5:film:3").
-- NULLABLE — no backfill. The new writer sets it on every recalc; legacy rows
-- keep NULL and cannot use the editor until their next recalculation.
ALTER TABLE cut_group
  ADD COLUMN IF NOT EXISTS group_key TEXT;

-- PARTIAL UNIQUE: only non-NULL keys must be unique per job.
-- Old-backend NULL inserts are excluded from the constraint — safe with old writer.
CREATE UNIQUE INDEX IF NOT EXISTS uq_cut_group_job_key
  ON cut_group (cut_job_id, group_key)
  WHERE group_key IS NOT NULL;

-- ── cut_job.last_calc_params / last_calc_basis ────────────────────────────────
-- Snapshot of resolved params and stable hash of inputs used in the last
-- successful calculate. Consumed by requiresRecalc and the save guard (Task 4/5).
-- NULLABLE — NULL on all pre-migration jobs (no backfill; see header note).
ALTER TABLE cut_job
  ADD COLUMN IF NOT EXISTS last_calc_params JSONB;
ALTER TABLE cut_job
  ADD COLUMN IF NOT EXISTS last_calc_basis TEXT;

-- ── Down ─────────────────────────────────────────────────────────────────────
-- Reverse in dependency order:
--   DROP INDEX IF EXISTS uq_cut_group_job_key;
--   ALTER TABLE cut_group DROP COLUMN IF EXISTS group_key;
--   DROP INDEX IF EXISTS idx_cut_group_manual_layout_job;
--   DROP TABLE IF EXISTS cut_group_manual_layout;
--   ALTER TABLE cut_job DROP COLUMN IF EXISTS last_calc_params;
--   ALTER TABLE cut_job DROP COLUMN IF EXISTS last_calc_basis;
