-- Migration 048: PDF template catalog for cut group exports.
BEGIN;

CREATE TABLE IF NOT EXISTS cut_pdf_templates (
  cut_pdf_template_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  code        VARCHAR(100) NOT NULL,
  name        VARCHAR(200) NOT NULL,
  is_active   BOOLEAN NOT NULL DEFAULT true,
  created_by  BIGINT,
  edited_by   BIGINT,
  created_at  TIMESTAMP NOT NULL DEFAULT now(),
  updated_at  TIMESTAMP NOT NULL DEFAULT now(),
  version     INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT pk_cut_pdf_templates PRIMARY KEY (cut_pdf_template_id),
  CONSTRAINT uq_cut_pdf_templates_code UNIQUE (code),
  CONSTRAINT chk_cut_pdf_templates_code_safe CHECK (code ~ '^[A-Za-z0-9_-]+$')
);

INSERT INTO cut_pdf_templates (code, name)
VALUES ('standard', 'Стандартный'), ('bath_profiles', 'Профили ванны')
ON CONFLICT (code) DO NOTHING;

COMMIT;
