import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const sql = readFileSync(new URL('./048_cut_pdf_templates.sql', import.meta.url), 'utf8');

describe('048_cut_pdf_templates migration', () => {
  it('creates a PDF template catalog and seeds standard templates', () => {
    expect(sql).toMatch(/CREATE TABLE IF NOT EXISTS cut_pdf_templates\b/i);
    expect(sql).toMatch(/cut_pdf_template_id\s+BIGINT GENERATED BY DEFAULT AS IDENTITY/i);
    expect(sql).toMatch(/code\s+VARCHAR\(100\) NOT NULL/i);
    expect(sql).toMatch(/standard/i);
    expect(sql).toMatch(/bath_profiles/i);
    expect(sql).toMatch(/ON CONFLICT \(code\) DO NOTHING/i);
  });
});
