BEGIN;

ALTER TABLE public.project_projects RENAME TO group_groups;
ALTER TABLE public.project_order_projects RENAME TO group_order_groups;
ALTER TABLE public.project_members RENAME TO group_members;
ALTER TABLE public.project_entity_types RENAME TO group_entity_types;
ALTER TABLE public.project_entity_links RENAME TO group_entity_links;
ALTER TABLE public.project_participant_roles RENAME TO group_participant_roles;
ALTER TABLE public.project_participants RENAME TO group_participants;

ALTER TABLE public.group_order_groups RENAME COLUMN project_id TO group_id;
ALTER TABLE public.group_members RENAME COLUMN project_id TO group_id;
ALTER TABLE public.group_entity_links RENAME COLUMN project_id TO group_id;
ALTER TABLE public.group_participants RENAME COLUMN project_id TO group_id;
ALTER TABLE public.notification_rules RENAME COLUMN project_id TO group_id;

ALTER TABLE public.group_groups RENAME CONSTRAINT project_projects_pkey TO group_groups_pkey;
ALTER TABLE public.group_groups RENAME CONSTRAINT chk_project_projects_status TO chk_group_groups_status;
ALTER TABLE public.group_groups RENAME CONSTRAINT chk_project_projects_code_format TO chk_group_groups_code_format;
ALTER TABLE public.group_groups RENAME CONSTRAINT chk_project_projects_name_length TO chk_group_groups_name_length;
ALTER TABLE public.group_groups RENAME CONSTRAINT chk_project_projects_dates_order TO chk_group_groups_dates_order;
ALTER TABLE public.group_groups RENAME CONSTRAINT project_projects_owner_user_id_fkey TO group_groups_owner_user_id_fkey;
ALTER TABLE public.group_groups RENAME CONSTRAINT project_projects_created_by_fkey TO group_groups_created_by_fkey;

ALTER TABLE public.group_order_groups RENAME CONSTRAINT project_order_projects_pkey TO group_order_groups_pkey;
ALTER TABLE public.group_order_groups RENAME CONSTRAINT chk_project_order_projects_relation_type TO chk_group_order_groups_relation_type;
ALTER TABLE public.group_order_groups RENAME CONSTRAINT chk_project_order_projects_valid_range TO chk_group_order_groups_valid_range;
ALTER TABLE public.group_order_groups RENAME CONSTRAINT ex_project_order_projects_no_relation_overlap TO ex_group_order_groups_no_relation_overlap;
ALTER TABLE public.group_order_groups RENAME CONSTRAINT ex_project_order_projects_one_primary_overlap TO ex_group_order_groups_one_primary_overlap;
ALTER TABLE public.group_order_groups RENAME CONSTRAINT project_order_projects_order_id_fkey TO group_order_groups_order_id_fkey;
ALTER TABLE public.group_order_groups RENAME CONSTRAINT project_order_projects_project_id_fkey TO group_order_groups_group_id_fkey;
ALTER TABLE public.group_order_groups RENAME CONSTRAINT project_order_projects_created_by_fkey TO group_order_groups_created_by_fkey;
ALTER TABLE public.group_order_groups RENAME CONSTRAINT project_order_projects_ended_by_fkey TO group_order_groups_ended_by_fkey;

ALTER TABLE public.group_members RENAME CONSTRAINT project_members_pkey TO group_members_pkey;
ALTER TABLE public.group_members RENAME CONSTRAINT chk_project_members_role_not_blank TO chk_group_members_role_not_blank;
ALTER TABLE public.group_members RENAME CONSTRAINT chk_project_members_valid_range TO chk_group_members_valid_range;
ALTER TABLE public.group_members RENAME CONSTRAINT ex_project_members_no_role_overlap TO ex_group_members_no_role_overlap;
ALTER TABLE public.group_members RENAME CONSTRAINT project_members_project_id_fkey TO group_members_group_id_fkey;
ALTER TABLE public.group_members RENAME CONSTRAINT project_members_user_id_fkey TO group_members_user_id_fkey;
ALTER TABLE public.group_members RENAME CONSTRAINT project_members_created_by_fkey TO group_members_created_by_fkey;
ALTER TABLE public.group_members RENAME CONSTRAINT project_members_ended_by_fkey TO group_members_ended_by_fkey;

ALTER TABLE public.group_entity_types RENAME CONSTRAINT project_entity_types_pkey TO group_entity_types_pkey;
ALTER TABLE public.group_entity_types RENAME CONSTRAINT chk_project_entity_types_code TO chk_group_entity_types_code;

ALTER TABLE public.group_entity_links RENAME CONSTRAINT project_entity_links_pkey TO group_entity_links_pkey;
ALTER TABLE public.group_entity_links RENAME CONSTRAINT chk_project_entity_links_entity_id_text TO chk_group_entity_links_entity_id_text;
ALTER TABLE public.group_entity_links RENAME CONSTRAINT chk_project_entity_links_relation_type TO chk_group_entity_links_relation_type;
ALTER TABLE public.group_entity_links RENAME CONSTRAINT chk_project_entity_links_valid_range TO chk_group_entity_links_valid_range;
ALTER TABLE public.group_entity_links RENAME CONSTRAINT ex_project_entity_links_no_relation_overlap TO ex_group_entity_links_no_relation_overlap;
ALTER TABLE public.group_entity_links RENAME CONSTRAINT project_entity_links_project_id_fkey TO group_entity_links_group_id_fkey;
ALTER TABLE public.group_entity_links RENAME CONSTRAINT project_entity_links_entity_type_code_fkey TO group_entity_links_entity_type_code_fkey;
ALTER TABLE public.group_entity_links RENAME CONSTRAINT project_entity_links_created_by_fkey TO group_entity_links_created_by_fkey;
ALTER TABLE public.group_entity_links RENAME CONSTRAINT project_entity_links_ended_by_fkey TO group_entity_links_ended_by_fkey;

ALTER TABLE public.group_participant_roles RENAME CONSTRAINT project_participant_roles_pkey TO group_participant_roles_pkey;
ALTER TABLE public.group_participant_roles RENAME CONSTRAINT project_participant_roles_code_key TO group_participant_roles_code_key;
ALTER TABLE public.group_participant_roles RENAME CONSTRAINT chk_project_participant_roles_code TO chk_group_participant_roles_code;

ALTER TABLE public.group_participants RENAME CONSTRAINT project_participants_pkey TO group_participants_pkey;
ALTER TABLE public.group_participants RENAME CONSTRAINT chk_project_participants_participant_id_text TO chk_group_participants_participant_id_text;
ALTER TABLE public.group_participants RENAME CONSTRAINT chk_project_participants_participant_id_numeric TO chk_group_participants_participant_id_numeric;
ALTER TABLE public.group_participants RENAME CONSTRAINT chk_project_participants_valid_range TO chk_group_participants_valid_range;
ALTER TABLE public.group_participants RENAME CONSTRAINT project_participants_participant_type_check TO group_participants_participant_type_check;
ALTER TABLE public.group_participants RENAME CONSTRAINT ex_project_participants_no_participant_overlap TO ex_group_participants_no_participant_overlap;
ALTER TABLE public.group_participants RENAME CONSTRAINT project_participants_project_id_fkey TO group_participants_group_id_fkey;
ALTER TABLE public.group_participants RENAME CONSTRAINT project_participants_role_code_fkey TO group_participants_role_code_fkey;
ALTER TABLE public.group_participants RENAME CONSTRAINT project_participants_created_by_fkey TO group_participants_created_by_fkey;
ALTER TABLE public.group_participants RENAME CONSTRAINT project_participants_ended_by_fkey TO group_participants_ended_by_fkey;

ALTER TABLE public.notification_rules RENAME CONSTRAINT notification_rules_project_id_fkey TO notification_rules_group_id_fkey;

ALTER INDEX public.uq_project_projects_active_code RENAME TO uq_group_groups_active_code;
ALTER INDEX public.idx_project_projects_status RENAME TO idx_group_groups_status;
ALTER INDEX public.idx_project_projects_owner RENAME TO idx_group_groups_owner;
ALTER INDEX public.idx_project_projects_archived_at RENAME TO idx_group_groups_archived_at;
ALTER INDEX public.uq_project_order_projects_current_relation RENAME TO uq_group_order_groups_current_relation;
ALTER INDEX public.uq_project_order_projects_current_primary RENAME TO uq_group_order_groups_current_primary;
ALTER INDEX public.idx_project_order_projects_order_current RENAME TO idx_group_order_groups_order_current;
ALTER INDEX public.idx_project_order_projects_project_current RENAME TO idx_group_order_groups_group_current;
ALTER INDEX public.idx_project_order_projects_validity RENAME TO idx_group_order_groups_validity;
ALTER INDEX public.uq_project_members_current_role RENAME TO uq_group_members_current_role;
ALTER INDEX public.idx_project_members_project_current RENAME TO idx_group_members_group_current;
ALTER INDEX public.idx_project_members_user_current RENAME TO idx_group_members_user_current;
ALTER INDEX public.idx_project_members_validity RENAME TO idx_group_members_validity;
ALTER INDEX public.uq_project_entity_links_current_relation RENAME TO uq_group_entity_links_current_relation;
ALTER INDEX public.idx_project_entity_links_project_current RENAME TO idx_group_entity_links_group_current;
ALTER INDEX public.uq_project_participants_current_participant RENAME TO uq_group_participants_current_participant;
ALTER INDEX public.idx_project_participants_project_current RENAME TO idx_group_participants_group_current;
ALTER INDEX public.idx_notification_rules_project_event RENAME TO idx_notification_rules_group_event;

ALTER TRIGGER project_projects_updated_at ON public.group_groups RENAME TO group_groups_updated_at;
ALTER FUNCTION public.project_projects_set_updated_at() RENAME TO group_groups_set_updated_at;

-- resolver seed lives inside the recipients_json JSONB (e.g. {"resolvers": ["project_participants"]}),
-- NOT a top-level column. Rewrite the value within recipients_json.
UPDATE notification_rules SET recipients_json = replace(recipients_json::text, 'project_participants', 'group_participants')::jsonb
WHERE recipients_json::text LIKE '%project_participants%';

UPDATE notification_rules SET rule_code = 'deadline-expired-group-participants'
WHERE rule_code = 'deadline-expired-project-participants';

COMMIT;
