-- 068_bazis_cut_sets.sql
-- Persistent typed snapshots for the production "Bazis cut" BIFF8 export workflow.

BEGIN;

CREATE TABLE IF NOT EXISTS bazis_cut_sets (
  bazis_cut_set_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name             VARCHAR(200) NOT NULL,
  version          INTEGER NOT NULL DEFAULT 0,
  created_by       BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
  updated_by       BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT pk_bazis_cut_sets PRIMARY KEY (bazis_cut_set_id),
  CONSTRAINT chk_bazis_cut_sets_name
    CHECK (length(btrim(name)) BETWEEN 1 AND 200),
  CONSTRAINT chk_bazis_cut_sets_version
    CHECK (version >= 0)
);

CREATE INDEX IF NOT EXISTS idx_bazis_cut_sets_created
  ON bazis_cut_sets (created_at DESC, bazis_cut_set_id DESC);

CREATE TABLE IF NOT EXISTS bazis_cut_set_details (
  bazis_cut_set_detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  bazis_cut_set_id        BIGINT NOT NULL,
  sort_order              INTEGER NOT NULL,

  -- Live provenance links are nullable so saved snapshots survive source deletion.
  source_order_detail_id  BIGINT,
  source_order_id         BIGINT,
  source_project_id       BIGINT,
  source_bazis_project_id BIGINT,
  source_bazis_revision_id BIGINT,
  source_bazis_node_id    BIGINT,

  -- Frozen display provenance used by list/card/export after source changes.
  source_order_name        TEXT,
  source_order_full_number TEXT,
  source_project_code      TEXT,
  source_bazis_project_name TEXT,
  source_bazis_order_no    TEXT,

  -- Exact 33-column "Details for cutting" export row.
  cut_enabled          BOOLEAN NOT NULL DEFAULT true,
  material_type        VARCHAR(100) NOT NULL DEFAULT 'Площадной',
  material_name        VARCHAR(200) NOT NULL,
  material_article     VARCHAR(200) NOT NULL DEFAULT '',
  thickness_mm         NUMERIC(10,2) NOT NULL,
  position             VARCHAR(200) NOT NULL,
  part_name            VARCHAR(300) NOT NULL,
  finished_length_mm   NUMERIC(12,2) NOT NULL,
  finished_width_mm    NUMERIC(12,2) NOT NULL,
  cut_length_mm        NUMERIC(12,2) NOT NULL,
  cut_width_mm         NUMERIC(12,2) NOT NULL,
  quantity             INTEGER NOT NULL,
  orientation          VARCHAR(50) NOT NULL DEFAULT 'Не задана',
  groove               VARCHAR(500) NOT NULL DEFAULT '',
  l1_name              VARCHAR(200) NOT NULL DEFAULT '',
  l1_designation       VARCHAR(200) NOT NULL DEFAULT '',
  l1_thickness_mm      NUMERIC(10,2) NOT NULL DEFAULT 0,
  l2_name              VARCHAR(200) NOT NULL DEFAULT '',
  l2_designation       VARCHAR(200) NOT NULL DEFAULT '',
  l2_thickness_mm      NUMERIC(10,2) NOT NULL DEFAULT 0,
  w1_name              VARCHAR(200) NOT NULL DEFAULT '',
  w1_designation       VARCHAR(200) NOT NULL DEFAULT '',
  w1_thickness_mm      NUMERIC(10,2) NOT NULL DEFAULT 0,
  w2_name              VARCHAR(200) NOT NULL DEFAULT '',
  w2_designation       VARCHAR(200) NOT NULL DEFAULT '',
  w2_thickness_mm      NUMERIC(10,2) NOT NULL DEFAULT 0,
  priority             INTEGER,
  comment              TEXT NOT NULL DEFAULT '',
  custom_property      TEXT NOT NULL DEFAULT '',
  glue                 VARCHAR(500) NOT NULL DEFAULT '',
  milling              VARCHAR(200) NOT NULL DEFAULT '',
  route                VARCHAR(500) NOT NULL DEFAULT '',
  film                 VARCHAR(200) NOT NULL DEFAULT '',

  created_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT pk_bazis_cut_set_details PRIMARY KEY (bazis_cut_set_detail_id),
  CONSTRAINT fk_bazis_cut_set_details_set
    FOREIGN KEY (bazis_cut_set_id) REFERENCES bazis_cut_sets(bazis_cut_set_id) ON DELETE CASCADE,
  CONSTRAINT fk_bazis_cut_set_details_order_detail
    FOREIGN KEY (source_order_detail_id) REFERENCES order_details(detail_id) ON DELETE SET NULL,
  CONSTRAINT fk_bazis_cut_set_details_order
    FOREIGN KEY (source_order_id) REFERENCES orders(order_id) ON DELETE SET NULL,
  CONSTRAINT fk_bazis_cut_set_details_project
    FOREIGN KEY (source_project_id) REFERENCES projects(project_id) ON DELETE SET NULL,
  CONSTRAINT fk_bazis_cut_set_details_bazis_project
    FOREIGN KEY (source_bazis_project_id) REFERENCES bazis_projects(bazis_project_id) ON DELETE SET NULL,
  CONSTRAINT fk_bazis_cut_set_details_bazis_revision
    FOREIGN KEY (source_bazis_revision_id) REFERENCES bazis_project_revisions(bazis_revision_id) ON DELETE SET NULL,
  CONSTRAINT fk_bazis_cut_set_details_bazis_node
    FOREIGN KEY (source_bazis_node_id) REFERENCES bazis_nodes(bazis_node_id) ON DELETE SET NULL,
  CONSTRAINT uq_bazis_cut_set_details_sort
    UNIQUE (bazis_cut_set_id, sort_order),
  CONSTRAINT chk_bazis_cut_set_details_sort
    CHECK (sort_order >= 0),
  CONSTRAINT chk_bazis_cut_set_details_material_type
    CHECK (length(btrim(material_type)) BETWEEN 1 AND 100),
  CONSTRAINT chk_bazis_cut_set_details_material_name
    CHECK (length(btrim(material_name)) BETWEEN 1 AND 200),
  CONSTRAINT chk_bazis_cut_set_details_thickness
    CHECK (thickness_mm > 0),
  CONSTRAINT chk_bazis_cut_set_details_position
    CHECK (length(btrim(position)) BETWEEN 1 AND 200),
  CONSTRAINT chk_bazis_cut_set_details_part_name
    CHECK (length(btrim(part_name)) BETWEEN 1 AND 300),
  CONSTRAINT chk_bazis_cut_set_details_finished_dimensions
    CHECK (finished_length_mm > 0 AND finished_width_mm > 0),
  CONSTRAINT chk_bazis_cut_set_details_cut_dimensions
    CHECK (cut_length_mm > 0 AND cut_width_mm > 0),
  CONSTRAINT chk_bazis_cut_set_details_quantity
    CHECK (quantity > 0),
  CONSTRAINT chk_bazis_cut_set_details_edge_thickness
    CHECK (
      l1_thickness_mm >= 0 AND l2_thickness_mm >= 0
      AND w1_thickness_mm >= 0 AND w2_thickness_mm >= 0
    ),
  CONSTRAINT chk_bazis_cut_set_details_priority
    CHECK (priority IS NULL OR priority BETWEEN 0 AND 1000000),
  CONSTRAINT chk_bazis_cut_set_details_comment_length
    CHECK (length(comment) <= 2000),
  CONSTRAINT chk_bazis_cut_set_details_custom_property_length
    CHECK (length(custom_property) <= 2000)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_bazis_cut_set_details_source_detail
  ON bazis_cut_set_details (bazis_cut_set_id, source_order_detail_id)
  WHERE source_order_detail_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_bazis_cut_set_details_source_order_detail
  ON bazis_cut_set_details (source_order_detail_id)
  WHERE source_order_detail_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_bazis_cut_set_details_source_order
  ON bazis_cut_set_details (source_order_id)
  WHERE source_order_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_bazis_cut_set_details_source_project
  ON bazis_cut_set_details (source_project_id)
  WHERE source_project_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_bazis_cut_set_details_source_bazis_project
  ON bazis_cut_set_details (source_bazis_project_id)
  WHERE source_bazis_project_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_bazis_cut_set_details_source_bazis_revision
  ON bazis_cut_set_details (source_bazis_revision_id)
  WHERE source_bazis_revision_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_bazis_cut_set_details_source_bazis_node
  ON bazis_cut_set_details (source_bazis_node_id)
  WHERE source_bazis_node_id IS NOT NULL;

CREATE OR REPLACE FUNCTION bazis_cut_set_touch_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger
    WHERE tgname = 'bazis_cut_sets_updated_at'
      AND tgrelid = 'bazis_cut_sets'::regclass
  ) THEN
    CREATE TRIGGER bazis_cut_sets_updated_at
      BEFORE UPDATE ON bazis_cut_sets
      FOR EACH ROW
      EXECUTE FUNCTION bazis_cut_set_touch_updated_at();
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger
    WHERE tgname = 'bazis_cut_set_details_updated_at'
      AND tgrelid = 'bazis_cut_set_details'::regclass
  ) THEN
    CREATE TRIGGER bazis_cut_set_details_updated_at
      BEFORE UPDATE ON bazis_cut_set_details
      FOR EACH ROW
      EXECUTE FUNCTION bazis_cut_set_touch_updated_at();
  END IF;
END;
$$;

COMMIT;
