import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const sql = readFileSync(new URL('./068_bazis_cut_sets.sql', import.meta.url), 'utf8');

describe('068_bazis_cut_sets migration', () => {
  it('creates the set header and typed detail snapshot tables additively', () => {
    expect(sql).toMatch(/BEGIN;/i);
    expect(sql).toMatch(/CREATE TABLE IF NOT EXISTS bazis_cut_sets\s*\(/i);
    expect(sql).toMatch(/CREATE TABLE IF NOT EXISTS bazis_cut_set_details\s*\(/i);
    expect(sql).toMatch(/COMMIT;/i);
    expect(sql).not.toMatch(/DROP TABLE|DROP COLUMN|TRUNCATE|DELETE FROM/i);
  });

  it('defines named, versioned sets with actor and timestamp dimensions', () => {
    expect(sql).toMatch(/bazis_cut_set_id\s+BIGINT GENERATED BY DEFAULT AS IDENTITY/i);
    expect(sql).toMatch(/name\s+VARCHAR\(200\) NOT NULL/i);
    expect(sql).toMatch(/CHECK \(length\(btrim\(name\)\) BETWEEN 1 AND 200\)/i);
    expect(sql).toMatch(/version\s+INTEGER NOT NULL DEFAULT 0/i);
    expect(sql).toMatch(/CHECK \(version >= 0\)/i);
    expect(sql).toMatch(/created_by\s+BIGINT REFERENCES users\(user_id\) ON DELETE SET NULL/i);
    expect(sql).toMatch(/updated_by\s+BIGINT REFERENCES users\(user_id\) ON DELETE SET NULL/i);
    expect(sql).toMatch(/created_at\s+TIMESTAMPTZ NOT NULL DEFAULT now\(\)/i);
    expect(sql).toMatch(/updated_at\s+TIMESTAMPTZ NOT NULL DEFAULT now\(\)/i);
  });

  it('keeps ordered detail snapshots and nullable typed provenance', () => {
    expect(sql).toMatch(/FOREIGN KEY \(bazis_cut_set_id\) REFERENCES bazis_cut_sets\(bazis_cut_set_id\) ON DELETE CASCADE/i);
    expect(sql).toMatch(/UNIQUE \(bazis_cut_set_id, sort_order\)/i);
    expect(sql).toMatch(/CHECK \(sort_order >= 0\)/i);

    const sourceForeignKeys = [
      ['source_order_detail_id', 'order_details', 'detail_id'],
      ['source_order_id', 'orders', 'order_id'],
      ['source_project_id', 'projects', 'project_id'],
      ['source_bazis_project_id', 'bazis_projects', 'bazis_project_id'],
      ['source_bazis_revision_id', 'bazis_project_revisions', 'bazis_revision_id'],
      ['source_bazis_node_id', 'bazis_nodes', 'bazis_node_id'],
    ] as const;

    for (const [column, table, target] of sourceForeignKeys) {
      expect(sql).toMatch(new RegExp(`FOREIGN KEY \\(${column}\\) REFERENCES ${table}\\(${target}\\) ON DELETE SET NULL`, 'i'));
    }

    for (const snapshot of [
      'source_order_name',
      'source_order_full_number',
      'source_project_code',
      'source_bazis_project_name',
      'source_bazis_order_no',
    ]) {
      expect(sql).toMatch(new RegExp(`${snapshot}\\s+TEXT`, 'i'));
    }

    expect(sql).toMatch(/CREATE UNIQUE INDEX IF NOT EXISTS uq_bazis_cut_set_details_source_detail[\s\S]*?\(bazis_cut_set_id, source_order_detail_id\)[\s\S]*?WHERE source_order_detail_id IS NOT NULL/i);
  });

  it('defines all 33 export columns with fixed SQL types', () => {
    const columnPatterns = [
      /cut_enabled\s+BOOLEAN NOT NULL DEFAULT true/i,
      /material_type\s+VARCHAR\(100\) NOT NULL DEFAULT 'Площадной'/i,
      /material_name\s+VARCHAR\(200\) NOT NULL/i,
      /material_article\s+VARCHAR\(200\) NOT NULL DEFAULT ''/i,
      /thickness_mm\s+NUMERIC\(10,2\) NOT NULL/i,
      /position\s+VARCHAR\(200\) NOT NULL/i,
      /part_name\s+VARCHAR\(300\) NOT NULL/i,
      /finished_length_mm\s+NUMERIC\(12,2\) NOT NULL/i,
      /finished_width_mm\s+NUMERIC\(12,2\) NOT NULL/i,
      /cut_length_mm\s+NUMERIC\(12,2\) NOT NULL/i,
      /cut_width_mm\s+NUMERIC\(12,2\) NOT NULL/i,
      /quantity\s+INTEGER NOT NULL/i,
      /orientation\s+VARCHAR\(50\) NOT NULL DEFAULT 'Не задана'/i,
      /groove\s+VARCHAR\(500\) NOT NULL DEFAULT ''/i,
      /l1_name\s+VARCHAR\(200\) NOT NULL DEFAULT ''/i,
      /l1_designation\s+VARCHAR\(200\) NOT NULL DEFAULT ''/i,
      /l1_thickness_mm\s+NUMERIC\(10,2\) NOT NULL DEFAULT 0/i,
      /l2_name\s+VARCHAR\(200\) NOT NULL DEFAULT ''/i,
      /l2_designation\s+VARCHAR\(200\) NOT NULL DEFAULT ''/i,
      /l2_thickness_mm\s+NUMERIC\(10,2\) NOT NULL DEFAULT 0/i,
      /w1_name\s+VARCHAR\(200\) NOT NULL DEFAULT ''/i,
      /w1_designation\s+VARCHAR\(200\) NOT NULL DEFAULT ''/i,
      /w1_thickness_mm\s+NUMERIC\(10,2\) NOT NULL DEFAULT 0/i,
      /w2_name\s+VARCHAR\(200\) NOT NULL DEFAULT ''/i,
      /w2_designation\s+VARCHAR\(200\) NOT NULL DEFAULT ''/i,
      /w2_thickness_mm\s+NUMERIC\(10,2\) NOT NULL DEFAULT 0/i,
      /priority\s+INTEGER,/i,
      /comment\s+TEXT NOT NULL DEFAULT ''/i,
      /custom_property\s+TEXT NOT NULL DEFAULT ''/i,
      /glue\s+VARCHAR\(500\) NOT NULL DEFAULT ''/i,
      /milling\s+VARCHAR\(200\) NOT NULL DEFAULT ''/i,
      /route\s+VARCHAR\(500\) NOT NULL DEFAULT ''/i,
      /film\s+VARCHAR\(200\) NOT NULL DEFAULT ''/i,
    ];

    expect(columnPatterns).toHaveLength(33);
    for (const pattern of columnPatterns) {
      expect(sql).toMatch(pattern);
    }
  });

  it('enforces export-row bounds and blank/default semantics', () => {
    expect(sql).toMatch(/CHECK \(thickness_mm > 0\)/i);
    expect(sql).toMatch(/finished_length_mm > 0 AND finished_width_mm > 0/i);
    expect(sql).toMatch(/cut_length_mm > 0 AND cut_width_mm > 0/i);
    expect(sql).toMatch(/CHECK \(quantity > 0\)/i);
    expect(sql).toMatch(/l1_thickness_mm >= 0 AND l2_thickness_mm >= 0[\s\S]*?w1_thickness_mm >= 0 AND w2_thickness_mm >= 0/i);
    expect(sql).toMatch(/priority IS NULL OR priority BETWEEN 0 AND 1000000/i);
    expect(sql).toMatch(/CHECK \(length\(comment\) <= 2000\)/i);
    expect(sql).toMatch(/CHECK \(length\(custom_property\) <= 2000\)/i);
  });

  it('indexes source dimensions and touches updated_at on both tables', () => {
    for (const index of [
      'idx_bazis_cut_sets_created',
      'idx_bazis_cut_set_details_source_order_detail',
      'idx_bazis_cut_set_details_source_order',
      'idx_bazis_cut_set_details_source_project',
      'idx_bazis_cut_set_details_source_bazis_project',
      'idx_bazis_cut_set_details_source_bazis_revision',
      'idx_bazis_cut_set_details_source_bazis_node',
    ]) {
      expect(sql).toMatch(new RegExp(`CREATE INDEX IF NOT EXISTS ${index}`, 'i'));
    }

    expect(sql).toMatch(/CREATE OR REPLACE FUNCTION bazis_cut_set_touch_updated_at\(\)/i);
    expect(sql).toMatch(/CREATE TRIGGER bazis_cut_sets_updated_at[\s\S]*?BEFORE UPDATE ON bazis_cut_sets/i);
    expect(sql).toMatch(/CREATE TRIGGER bazis_cut_set_details_updated_at[\s\S]*?BEFORE UPDATE ON bazis_cut_set_details/i);
  });
});
