-- 082_label_cut_maps.sql
-- Exact, immutable cut placements for adaptive cut-sheet miniatures on labels.

BEGIN;

CREATE TABLE IF NOT EXISTS cut_result_sheet_map (
  cut_result_sheet_map_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cut_result_id BIGINT NOT NULL REFERENCES cut_result(cut_result_id) ON DELETE RESTRICT,
  cut_job_id BIGINT NOT NULL,
  cut_group_id BIGINT NOT NULL,
  group_key TEXT NOT NULL,
  variant TEXT NOT NULL,
  sheet_index INTEGER NOT NULL,
  sheet_ordinal INTEGER NOT NULL,
  is_effective BOOLEAN NOT NULL,
  sheet_width_mm NUMERIC(14, 3) NOT NULL,
  sheet_height_mm NUMERIC(14, 3) NOT NULL,
  base_svg TEXT NOT NULL,
  CONSTRAINT uq_cut_result_sheet_map
    UNIQUE (cut_result_id, cut_group_id, variant, sheet_index),
  CONSTRAINT chk_cut_result_sheet_map_variant
    CHECK (variant IN ('auto', 'manual')),
  CONSTRAINT chk_cut_result_sheet_map_dimensions
    CHECK (sheet_width_mm > 0 AND sheet_height_mm > 0 AND sheet_ordinal > 0),
  CONSTRAINT chk_cut_result_sheet_map_svg
    CHECK (base_svg LIKE '<svg%'),
  CONSTRAINT fk_cut_result_sheet_map_same_job
    FOREIGN KEY (cut_job_id, cut_result_id)
    REFERENCES cut_result(cut_job_id, cut_result_id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_cut_result_sheet_map_result
  ON cut_result_sheet_map (cut_result_id, variant, sheet_ordinal);

ALTER TABLE cut_result_sheet_map
  ADD CONSTRAINT uq_cut_result_sheet_map_identity
  UNIQUE (cut_result_sheet_map_id, cut_result_id, cut_job_id, cut_group_id, variant, sheet_index);

CREATE TABLE IF NOT EXISTS cut_result_placement (
  cut_result_placement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cut_result_sheet_map_id BIGINT NOT NULL
    REFERENCES cut_result_sheet_map(cut_result_sheet_map_id) ON DELETE RESTRICT,
  cut_result_id BIGINT NOT NULL REFERENCES cut_result(cut_result_id) ON DELETE RESTRICT,
  cut_job_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  order_detail_id BIGINT NOT NULL,
  item_id TEXT NOT NULL,
  instance INTEGER NOT NULL,
  variant TEXT NOT NULL,
  cut_group_id BIGINT NOT NULL,
  sheet_index INTEGER NOT NULL,
  x_mm NUMERIC(14, 3) NOT NULL,
  y_mm NUMERIC(14, 3) NOT NULL,
  width_mm NUMERIC(14, 3) NOT NULL,
  height_mm NUMERIC(14, 3) NOT NULL,
  detail_width_mm NUMERIC(14, 3) NOT NULL,
  detail_height_mm NUMERIC(14, 3) NOT NULL,
  rotated BOOLEAN NOT NULL,
  CONSTRAINT uq_cut_result_placement_instance
    UNIQUE (cut_result_id, variant, item_id, instance),
  CONSTRAINT chk_cut_result_placement_variant
    CHECK (variant IN ('auto', 'manual')),
  CONSTRAINT chk_cut_result_placement_instance
    CHECK (instance > 0),
  CONSTRAINT chk_cut_result_placement_geometry
    CHECK (
      x_mm >= 0 AND y_mm >= 0
      AND width_mm > 0 AND height_mm > 0
      AND detail_width_mm > 0 AND detail_height_mm > 0
    ),
  CONSTRAINT fk_cut_result_placement_same_job
    FOREIGN KEY (cut_job_id, cut_result_id)
    REFERENCES cut_result(cut_job_id, cut_result_id) ON DELETE RESTRICT,
  CONSTRAINT fk_cut_result_placement_exact_sheet
    FOREIGN KEY (
      cut_result_sheet_map_id, cut_result_id, cut_job_id,
      cut_group_id, variant, sheet_index
    ) REFERENCES cut_result_sheet_map (
      cut_result_sheet_map_id, cut_result_id, cut_job_id,
      cut_group_id, variant, sheet_index
    ) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_cut_result_placement_detail_candidates
  ON cut_result_placement (order_detail_id, instance, cut_result_id DESC, variant);

CREATE INDEX IF NOT EXISTS idx_cut_result_placement_order_candidates
  ON cut_result_placement (order_id, order_detail_id, instance, cut_result_id DESC);

CREATE TABLE IF NOT EXISTS cut_result_label_map_projection (
  cut_result_id BIGINT PRIMARY KEY REFERENCES cut_result(cut_result_id) ON DELETE RESTRICT,
  snapshot_digest TEXT NOT NULL,
  sheet_count INTEGER NOT NULL,
  placement_count INTEGER NOT NULL,
  completed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_cut_result_label_map_projection_counts
    CHECK (sheet_count >= 0 AND placement_count >= 0)
);

CREATE OR REPLACE FUNCTION cut_result_label_map_expected_counts(p_snapshot JSONB)
RETURNS TABLE(sheet_count INTEGER, placement_count INTEGER)
LANGUAGE sql
IMMUTABLE
STRICT
PARALLEL SAFE
AS $$
  WITH sheet_rows AS (
    SELECT sheet.value AS sheet_json
    FROM jsonb_array_elements(p_snapshot -> 'groups') AS group_entry(value)
    CROSS JOIN LATERAL jsonb_array_elements(group_entry.value -> 'sheets') AS sheet(value)
    UNION ALL
    SELECT sheet.value AS sheet_json
    FROM jsonb_array_elements(p_snapshot -> 'groups') AS group_entry(value)
    CROSS JOIN LATERAL jsonb_array_elements(
      CASE WHEN jsonb_typeof(group_entry.value -> 'manualLayout') = 'object'
        THEN group_entry.value #> '{manualLayout,sheets}'
        ELSE '[]'::JSONB
      END
    ) AS sheet(value)
  )
  SELECT
    count(*)::INTEGER,
    COALESCE(sum(jsonb_array_length(sheet_json #> '{placements,pieces}')), 0)::INTEGER
  FROM sheet_rows
$$;

CREATE OR REPLACE FUNCTION project_cut_result_label_maps(p_cut_result_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
  result_row RECORD;
  group_entry RECORD;
  sheet_entry RECORD;
  piece_json JSONB;
  item_json JSONB;
  group_json JSONB;
  sheet_json JSONB;
  sheet_map_id BIGINT;
  group_id BIGINT;
  group_key_value TEXT;
  item_id_value TEXT;
  items_by_id JSONB;
  has_active_manual BOOLEAN;
  expected_sheet_count INTEGER := 0;
  expected_placement_count INTEGER := 0;
  snapshot_sheet_count INTEGER;
  snapshot_placement_count INTEGER;
BEGIN
  IF EXISTS (
    SELECT 1 FROM cut_result_label_map_projection WHERE cut_result_id = p_cut_result_id
  ) THEN
    RETURN;
  END IF;

  IF EXISTS (
    SELECT 1 FROM cut_result_sheet_map WHERE cut_result_id = p_cut_result_id
  ) THEN
    RAISE EXCEPTION 'cut result % has an incomplete label-map projection', p_cut_result_id;
  END IF;

  SELECT cut_result_id, cut_job_id, snapshot_job, snapshot_digest
  INTO result_row
  FROM cut_result
  WHERE cut_result_id = p_cut_result_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'cut result % not found for label-map projection', p_cut_result_id;
  END IF;

  SELECT COALESCE(
    jsonb_object_agg('det-' || (value ->> 'orderDetailId'), value),
    '{}'::JSONB
  )
  INTO items_by_id
  FROM jsonb_array_elements(result_row.snapshot_job -> 'items');

  SELECT counts.sheet_count, counts.placement_count
  INTO snapshot_sheet_count, snapshot_placement_count
  FROM cut_result_label_map_expected_counts(result_row.snapshot_job) AS counts;

  PERFORM set_config('erp.cut_label_projection_result_id', p_cut_result_id::TEXT, TRUE);

  BEGIN
  FOR group_entry IN
    SELECT value AS group_json
    FROM jsonb_array_elements(result_row.snapshot_job -> 'groups')
  LOOP
    group_json := group_entry.group_json;
    group_id := (group_json ->> 'cutGroupId')::BIGINT;
    group_key_value := COALESCE(group_json ->> 'groupKey', 'group:' || group_id::TEXT);
    has_active_manual :=
      jsonb_typeof(group_json -> 'manualLayout') = 'object'
      AND COALESCE((group_json #>> '{manualLayout,isActive}')::BOOLEAN, FALSE)
      AND NOT COALESCE((group_json #>> '{manualLayout,isStale}')::BOOLEAN, TRUE);

    FOR sheet_entry IN
      SELECT value AS sheet_json, ordinality::INTEGER AS sheet_ordinal
      FROM jsonb_array_elements(group_json -> 'sheets') WITH ORDINALITY
    LOOP
      sheet_json := sheet_entry.sheet_json;
      expected_sheet_count := expected_sheet_count + 1;
      INSERT INTO cut_result_sheet_map (
        cut_result_id, cut_job_id, cut_group_id, group_key, variant,
        sheet_index, sheet_ordinal, is_effective, sheet_width_mm,
        sheet_height_mm, base_svg
      ) VALUES (
        result_row.cut_result_id,
        result_row.cut_job_id,
        group_id,
        group_key_value,
        'auto',
        (sheet_json ->> 'sheetIndex')::INTEGER,
        sheet_entry.sheet_ordinal,
        NOT has_active_manual,
        (sheet_json #>> '{placements,sheet_width_mm}')::NUMERIC,
        (sheet_json #>> '{placements,sheet_height_mm}')::NUMERIC,
        sheet_json #>> ARRAY['renderSnapshot', 'views', 'r0:raw:top-left:labels-off', 'svg']
      )
      RETURNING cut_result_sheet_map_id INTO sheet_map_id;

      FOR piece_json IN
        SELECT value FROM jsonb_array_elements(sheet_json #> '{placements,pieces}')
      LOOP
        expected_placement_count := expected_placement_count + 1;
        item_id_value := piece_json ->> 'item_id';
        item_json := items_by_id -> item_id_value;
        IF item_json IS NULL THEN
          RAISE EXCEPTION 'cut result % has unknown item %', p_cut_result_id, item_id_value;
        END IF;
        INSERT INTO cut_result_placement (
          cut_result_sheet_map_id, cut_result_id, cut_job_id, order_id,
          order_detail_id, item_id, instance, variant, cut_group_id,
          sheet_index, x_mm, y_mm, width_mm, height_mm,
          detail_width_mm, detail_height_mm, rotated
        ) VALUES (
          sheet_map_id,
          result_row.cut_result_id,
          result_row.cut_job_id,
          (item_json ->> 'orderId')::BIGINT,
          (item_json ->> 'orderDetailId')::BIGINT,
          item_id_value,
          (piece_json ->> 'instance')::INTEGER,
          'auto',
          group_id,
          (sheet_json ->> 'sheetIndex')::INTEGER,
          (sheet_json #>> '{placements,trim_mm,left}')::NUMERIC + (piece_json ->> 'x_mm')::NUMERIC,
          (sheet_json #>> '{placements,trim_mm,top}')::NUMERIC + (piece_json ->> 'y_mm')::NUMERIC,
          (piece_json ->> 'width_mm')::NUMERIC,
          (piece_json ->> 'height_mm')::NUMERIC,
          CASE WHEN (piece_json ->> 'rotated')::BOOLEAN
            THEN (piece_json ->> 'height_mm')::NUMERIC ELSE (piece_json ->> 'width_mm')::NUMERIC END,
          CASE WHEN (piece_json ->> 'rotated')::BOOLEAN
            THEN (piece_json ->> 'width_mm')::NUMERIC ELSE (piece_json ->> 'height_mm')::NUMERIC END,
          (piece_json ->> 'rotated')::BOOLEAN
        );
      END LOOP;
    END LOOP;

    IF jsonb_typeof(group_json -> 'manualLayout') = 'object' THEN
      FOR sheet_entry IN
        SELECT value AS sheet_json, ordinality::INTEGER AS sheet_ordinal
        FROM jsonb_array_elements(group_json #> '{manualLayout,sheets}') WITH ORDINALITY
      LOOP
        sheet_json := sheet_entry.sheet_json;
        expected_sheet_count := expected_sheet_count + 1;
        INSERT INTO cut_result_sheet_map (
          cut_result_id, cut_job_id, cut_group_id, group_key, variant,
          sheet_index, sheet_ordinal, is_effective, sheet_width_mm,
          sheet_height_mm, base_svg
        ) VALUES (
          result_row.cut_result_id,
          result_row.cut_job_id,
          group_id,
          group_key_value,
          'manual',
          (sheet_json ->> 'sheetIndex')::INTEGER,
          sheet_entry.sheet_ordinal,
          has_active_manual,
          (sheet_json #>> '{placements,sheet_width_mm}')::NUMERIC,
          (sheet_json #>> '{placements,sheet_height_mm}')::NUMERIC,
          sheet_json #>> ARRAY['renderSnapshot', 'views', 'r0:raw:top-left:labels-off', 'svg']
        )
        RETURNING cut_result_sheet_map_id INTO sheet_map_id;

        FOR piece_json IN
          SELECT value FROM jsonb_array_elements(sheet_json #> '{placements,pieces}')
        LOOP
          expected_placement_count := expected_placement_count + 1;
          item_id_value := piece_json ->> 'item_id';
          item_json := items_by_id -> item_id_value;
          IF item_json IS NULL THEN
            RAISE EXCEPTION 'cut result % has unknown manual item %', p_cut_result_id, item_id_value;
          END IF;
          INSERT INTO cut_result_placement (
            cut_result_sheet_map_id, cut_result_id, cut_job_id, order_id,
            order_detail_id, item_id, instance, variant, cut_group_id,
            sheet_index, x_mm, y_mm, width_mm, height_mm,
            detail_width_mm, detail_height_mm, rotated
          ) VALUES (
            sheet_map_id,
            result_row.cut_result_id,
            result_row.cut_job_id,
            (item_json ->> 'orderId')::BIGINT,
            (item_json ->> 'orderDetailId')::BIGINT,
            item_id_value,
            (piece_json ->> 'instance')::INTEGER,
            'manual',
            group_id,
            (sheet_json ->> 'sheetIndex')::INTEGER,
            (sheet_json #>> '{placements,trim_mm,left}')::NUMERIC + (piece_json ->> 'x_mm')::NUMERIC,
            (sheet_json #>> '{placements,trim_mm,top}')::NUMERIC + (piece_json ->> 'y_mm')::NUMERIC,
            (piece_json ->> 'width_mm')::NUMERIC,
            (piece_json ->> 'height_mm')::NUMERIC,
            CASE WHEN (piece_json ->> 'rotated')::BOOLEAN
              THEN (piece_json ->> 'height_mm')::NUMERIC ELSE (piece_json ->> 'width_mm')::NUMERIC END,
            CASE WHEN (piece_json ->> 'rotated')::BOOLEAN
              THEN (piece_json ->> 'width_mm')::NUMERIC ELSE (piece_json ->> 'height_mm')::NUMERIC END,
            (piece_json ->> 'rotated')::BOOLEAN
          );
        END LOOP;
      END LOOP;
    END IF;
  END LOOP;

  IF expected_sheet_count IS DISTINCT FROM snapshot_sheet_count
     OR expected_placement_count IS DISTINCT FROM snapshot_placement_count
     OR expected_sheet_count IS DISTINCT FROM (
       SELECT count(*)::INTEGER FROM cut_result_sheet_map WHERE cut_result_id = p_cut_result_id
     ) OR expected_placement_count IS DISTINCT FROM (
       SELECT count(*)::INTEGER FROM cut_result_placement WHERE cut_result_id = p_cut_result_id
     ) THEN
    RAISE EXCEPTION 'cut result % label-map projection count mismatch', p_cut_result_id;
  END IF;

  INSERT INTO cut_result_label_map_projection (
    cut_result_id, snapshot_digest, sheet_count, placement_count
  ) VALUES (
    p_cut_result_id,
    result_row.snapshot_digest,
    expected_sheet_count,
    expected_placement_count
  );
  EXCEPTION WHEN OTHERS THEN
    PERFORM set_config('erp.cut_label_projection_result_id', '', TRUE);
    RAISE;
  END;

  PERFORM set_config('erp.cut_label_projection_result_id', '', TRUE);
END;
$$;

CREATE OR REPLACE FUNCTION project_new_cut_result_label_maps()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  PERFORM project_cut_result_label_maps(NEW.cut_result_id);
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_cut_result_label_map_projection ON cut_result;
CREATE TRIGGER trg_cut_result_label_map_projection
AFTER INSERT ON cut_result
FOR EACH ROW EXECUTE FUNCTION project_new_cut_result_label_maps();

CREATE OR REPLACE FUNCTION reject_cut_result_label_map_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'cut result label-map projection is append-only'
    USING ERRCODE = '55000';
END;
$$;

CREATE OR REPLACE FUNCTION guard_cut_result_label_map_projection_insert()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF current_setting('erp.cut_label_projection_result_id', TRUE)
     IS DISTINCT FROM NEW.cut_result_id::TEXT THEN
    RAISE EXCEPTION 'cut result label-map rows are written only by the projection function'
      USING ERRCODE = '55000';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_cut_result_sheet_map_projection_insert
BEFORE INSERT ON cut_result_sheet_map
FOR EACH ROW EXECUTE FUNCTION guard_cut_result_label_map_projection_insert();

CREATE TRIGGER trg_cut_result_placement_projection_insert
BEFORE INSERT ON cut_result_placement
FOR EACH ROW EXECUTE FUNCTION guard_cut_result_label_map_projection_insert();

CREATE TRIGGER trg_cut_result_label_map_projection_insert
BEFORE INSERT ON cut_result_label_map_projection
FOR EACH ROW EXECUTE FUNCTION guard_cut_result_label_map_projection_insert();

CREATE TRIGGER trg_cut_result_sheet_map_append_only
BEFORE UPDATE OR DELETE ON cut_result_sheet_map
FOR EACH ROW EXECUTE FUNCTION reject_cut_result_label_map_mutation();

CREATE TRIGGER trg_cut_result_placement_append_only
BEFORE UPDATE OR DELETE ON cut_result_placement
FOR EACH ROW EXECUTE FUNCTION reject_cut_result_label_map_mutation();

CREATE TRIGGER trg_cut_result_label_map_projection_append_only
BEFORE UPDATE OR DELETE ON cut_result_label_map_projection
FOR EACH ROW EXECUTE FUNCTION reject_cut_result_label_map_mutation();

CREATE TABLE IF NOT EXISTS label_generation_cut_placement (
  order_label_generation_id BIGINT NOT NULL
    REFERENCES order_label_generations(order_label_generation_id) ON DELETE CASCADE,
  row_index INTEGER NOT NULL,
  detail_id BIGINT NOT NULL,
  copy_index INTEGER NOT NULL,
  cut_result_placement_id BIGINT NOT NULL
    REFERENCES cut_result_placement(cut_result_placement_id) ON DELETE RESTRICT,
  CONSTRAINT pk_label_generation_cut_placement
    PRIMARY KEY (order_label_generation_id, row_index),
  CONSTRAINT uq_label_generation_cut_placement_copy
    UNIQUE (order_label_generation_id, detail_id, copy_index),
  CONSTRAINT chk_label_generation_cut_placement_indices
    CHECK (row_index > 0 AND copy_index > 0)
);

CREATE INDEX IF NOT EXISTS idx_label_generation_cut_placement_result
  ON label_generation_cut_placement (cut_result_placement_id, order_label_generation_id);

ALTER TABLE label_template_elements
  DROP CONSTRAINT IF EXISTS chk_label_template_elements_kind;

ALTER TABLE label_template_elements
  ADD CONSTRAINT chk_label_template_elements_kind
  CHECK (kind IN ('text', 'line', 'rect', 'qr', 'cut_map'));

COMMIT;

-- Down (manual, destructive):
-- DROP TRIGGER IF EXISTS trg_cut_result_label_map_projection ON cut_result;
-- DROP FUNCTION IF EXISTS project_new_cut_result_label_maps();
-- DROP FUNCTION IF EXISTS project_cut_result_label_maps(BIGINT);
-- DROP TABLE IF EXISTS label_generation_cut_placement;
-- DROP TABLE IF EXISTS cut_result_placement;
-- DROP TABLE IF EXISTS cut_result_sheet_map;
-- DROP TABLE IF EXISTS cut_result_label_map_projection;
