-- Flexible, backend-evaluated export templates. Initial format: BIFF8 XLS.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS export_templates (
  export_template_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT,
  name TEXT NOT NULL,
  description TEXT,
  target_screen TEXT NOT NULL,
  source_type TEXT NOT NULL,
  format TEXT NOT NULL,
  sheet_name TEXT NOT NULL,
  schema_version SMALLINT NOT NULL DEFAULT 1,
  template_hash TEXT NOT NULL,
  columns_json JSONB NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  is_default BOOLEAN NOT NULL DEFAULT false,
  version INTEGER NOT NULL DEFAULT 1,
  created_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
  deleted_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  CONSTRAINT chk_export_templates_target CHECK (target_screen IN ('bazis_cut_set', 'bazis_project_card')),
  CONSTRAINT chk_export_templates_source CHECK (source_type IN ('bazis_cut_set_detail', 'bazis_project_panel')),
  CONSTRAINT chk_export_templates_target_source CHECK (
    (target_screen='bazis_cut_set' AND source_type='bazis_cut_set_detail') OR
    (target_screen='bazis_project_card' AND source_type='bazis_project_panel')
  ),
  CONSTRAINT chk_export_templates_format CHECK (format='xls_biff8'),
  CONSTRAINT chk_export_templates_name CHECK (length(btrim(name)) BETWEEN 1 AND 200),
  CONSTRAINT chk_export_templates_sheet_name CHECK (
    length(btrim(sheet_name)) BETWEEN 1 AND 31 AND sheet_name !~ '[\[\]:*?/\\]'
  ),
  CONSTRAINT chk_export_templates_schema_version CHECK (schema_version=1),
  CONSTRAINT chk_export_templates_hash CHECK (template_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT chk_export_templates_columns_array CHECK (jsonb_typeof(columns_json)='array'),
  CONSTRAINT chk_export_templates_version CHECK (version > 0),
  CONSTRAINT chk_export_templates_default_active CHECK (NOT is_default OR (is_active AND deleted_at IS NULL))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_export_templates_code
  ON export_templates (code) WHERE code IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_export_templates_live_name
  ON export_templates (target_screen, source_type, format, lower(name))
  WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_export_templates_active_default
  ON export_templates (target_screen, source_type, format)
  WHERE deleted_at IS NULL AND is_active=true AND is_default=true;

CREATE INDEX IF NOT EXISTS idx_export_templates_runtime
  ON export_templates (target_screen, source_type, format, is_default DESC, name)
  WHERE deleted_at IS NULL AND is_active=true;

WITH seed(columns_json) AS (
  VALUES ('[
    {"columnKey":"cut","header":"Кроить","expression":{"type":"field","field":"legacy.cutEnabled"}},
    {"columnKey":"materialType","header":"Тип материала","expression":{"type":"field","field":"detail.materialType"}},
    {"columnKey":"material","header":"Материал","expression":{"type":"field","field":"detail.materialName"}},
    {"columnKey":"materialArticle","header":"Артикул материала","expression":{"type":"field","field":"detail.materialArticle"}},
    {"columnKey":"thickness","header":"Толщина","expression":{"type":"field","field":"detail.thicknessMm"}},
    {"columnKey":"order","header":"Заказ","expression":{"type":"field","field":"legacy.order"}},
    {"columnKey":"product","header":"Изделие","expression":{"type":"field","field":"legacy.product"}},
    {"columnKey":"position","header":"Позиция","expression":{"type":"field","field":"legacy.position"}},
    {"columnKey":"qr","header":"QR-code","expression":{"type":"field","field":"legacy.qr"}},
    {"columnKey":"name","header":"Наименования","expression":{"type":"field","field":"detail.partName"}},
    {"columnKey":"finishedLength","header":"Длина готовая","expression":{"type":"field","field":"detail.finishedLengthMm"}},
    {"columnKey":"finishedWidth","header":"Ширина готовая","expression":{"type":"field","field":"detail.finishedWidthMm"}},
    {"columnKey":"cutLength","header":"Длина распиловочная","expression":{"type":"field","field":"detail.cutLengthMm"}},
    {"columnKey":"cutWidth","header":"Ширина распиловочная","expression":{"type":"field","field":"detail.cutWidthMm"}},
    {"columnKey":"quantity","header":"Кол-во","expression":{"type":"field","field":"detail.quantity"}},
    {"columnKey":"orientation","header":"Ориентация","expression":{"type":"field","field":"detail.orientation"}},
    {"columnKey":"groove","header":"Паз","expression":{"type":"field","field":"detail.groove"}},
    {"columnKey":"l1Name","header":"L1 - Наим.","expression":{"type":"field","field":"detail.l1Name"}},
    {"columnKey":"l1Designation","header":"L1 - Обозн.","expression":{"type":"field","field":"detail.l1Designation"}},
    {"columnKey":"l1Thickness","header":"L1 - Толщина","expression":{"type":"field","field":"detail.l1ThicknessMm"}},
    {"columnKey":"l2Name","header":"L2 - Наим.","expression":{"type":"field","field":"detail.l2Name"}},
    {"columnKey":"l2Designation","header":"L2 - Обозн.","expression":{"type":"field","field":"detail.l2Designation"}},
    {"columnKey":"l2Thickness","header":"L2 - Толщина","expression":{"type":"field","field":"detail.l2ThicknessMm"}},
    {"columnKey":"w1Name","header":"W1 - Наим.","expression":{"type":"field","field":"detail.w1Name"}},
    {"columnKey":"w1Designation","header":"W1 - Обозн.","expression":{"type":"field","field":"detail.w1Designation"}},
    {"columnKey":"w1Thickness","header":"W1 - Толщина","expression":{"type":"field","field":"detail.w1ThicknessMm"}},
    {"columnKey":"w2Name","header":"W2 - Наим.","expression":{"type":"field","field":"detail.w2Name"}},
    {"columnKey":"w2Designation","header":"W2 - Обозн.","expression":{"type":"field","field":"detail.w2Designation"}},
    {"columnKey":"w2Thickness","header":"W2 - Толщина","expression":{"type":"field","field":"detail.w2ThicknessMm"}},
    {"columnKey":"priority","header":"Приоритет","expression":{"type":"field","field":"detail.priority"}},
    {"columnKey":"comment","header":"Комментарий","expression":{"type":"field","field":"detail.comment"}},
    {"columnKey":"customProperty","header":"%Пользовательское свойство","expression":{"type":"field","field":"detail.customProperty"}},
    {"columnKey":"glue","header":"%Склейка","expression":{"type":"field","field":"detail.glue"}},
    {"columnKey":"milling","header":"%Фрезировка","expression":{"type":"field","field":"detail.milling"}},
    {"columnKey":"route","header":"%Маршрут","expression":{"type":"field","field":"detail.route"}},
    {"columnKey":"bath","header":"Ванна","expression":{"type":"field","field":"source.sourceBathCutNumber"}},
    {"columnKey":"film","header":"%Пленка","expression":{"type":"field","field":"detail.film"}}
  ]'::jsonb)
), template_seed(code, name, target_screen, source_type) AS (
  VALUES
    ('bazis-cut-set-standard-v1', 'Базис-раскрой — стандартный', 'bazis_cut_set', 'bazis_cut_set_detail'),
    ('bazis-project-cut-standard-v1', 'Базис-проект — стандартный', 'bazis_project_card', 'bazis_project_panel')
)
INSERT INTO export_templates (
  code, name, description, target_screen, source_type, format, sheet_name,
  schema_version, template_hash, columns_json, is_active, is_default, version
)
SELECT template_seed.code, template_seed.name,
       'Системный шаблон, повторяющий экспорт до появления конфигуратора.',
       template_seed.target_screen, template_seed.source_type, 'xls_biff8', 'Детали для раскроя',
       1, encode(digest(jsonb_build_object('schemaVersion', 1, 'columns', seed.columns_json)::text, 'sha256'), 'hex'),
       seed.columns_json, true, true, 1
FROM template_seed CROSS JOIN seed
ON CONFLICT (code) WHERE code IS NOT NULL DO NOTHING;

COMMIT;

-- Rollback (manual, only after confirming no user templates exist):
-- DROP TABLE export_templates;
