-- 110_cnc_telegram_label_maps.sql
-- Immutable Telegram evidence and label-only map/media projections.

BEGIN;

CREATE TABLE IF NOT EXISTS cnc_telegram_packet_evidence_set (
  packet_id UUID NOT NULL REFERENCES cnc_telegram_packets(packet_id) ON DELETE RESTRICT,
  source_version BIGINT NOT NULL,
  payload_hash TEXT NOT NULL,
  evidence_set_digest TEXT NOT NULL,
  item_count INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
  request_id TEXT NOT NULL,
  source TEXT NOT NULL,
  CONSTRAINT pk_cnc_telegram_packet_evidence_set PRIMARY KEY (packet_id, source_version),
  CONSTRAINT chk_cnc_telegram_packet_evidence_set_version CHECK (source_version > 0),
  CONSTRAINT chk_cnc_telegram_packet_evidence_set_count CHECK (item_count > 0),
  CONSTRAINT chk_cnc_telegram_packet_evidence_set_source
    CHECK (source IN ('ingest', 'authoritative_replay'))
);

CREATE TABLE IF NOT EXISTS cnc_telegram_packet_item_evidence (
  packet_item_evidence_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  packet_id UUID NOT NULL,
  source_version BIGINT NOT NULL,
  payload_hash TEXT NOT NULL,
  source_item_key TEXT NOT NULL,
  order_name TEXT NOT NULL,
  detail_number INTEGER,
  width_mm NUMERIC(10, 2),
  height_mm NUMERIC(10, 2),
  quantity INTEGER NOT NULL,
  source TEXT NOT NULL,
  confidence NUMERIC(5, 4) NOT NULL,
  match_order_id BIGINT REFERENCES orders(order_id) ON DELETE RESTRICT,
  match_detail_id BIGINT REFERENCES order_details(detail_id) ON DELETE RESTRICT,
  match_status TEXT NOT NULL,
  review_note TEXT,
  item_digest TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_cnc_telegram_packet_item_evidence_key
    UNIQUE (packet_id, source_version, source_item_key),
  CONSTRAINT fk_cnc_telegram_packet_item_evidence_set
    FOREIGN KEY (packet_id, source_version)
    REFERENCES cnc_telegram_packet_evidence_set(packet_id, source_version) DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT chk_cnc_telegram_packet_item_evidence_version CHECK (source_version > 0),
  CONSTRAINT chk_cnc_telegram_packet_item_evidence_detail CHECK (detail_number IS NULL OR detail_number > 0),
  CONSTRAINT chk_cnc_telegram_packet_item_evidence_dimensions
    CHECK ((width_mm IS NULL OR width_mm > 0) AND (height_mm IS NULL OR height_mm > 0)),
  CONSTRAINT chk_cnc_telegram_packet_item_evidence_quantity CHECK (quantity > 0),
  CONSTRAINT chk_cnc_telegram_packet_item_evidence_source
    CHECK (source IN ('vector', 'ocr', 'gcode', 'manual')),
  CONSTRAINT chk_cnc_telegram_packet_item_evidence_confidence CHECK (confidence BETWEEN 0 AND 1),
  CONSTRAINT chk_cnc_telegram_packet_item_evidence_match_status
    CHECK (match_status IN ('unmatched', 'matched', 'conflict', 'needs_review')),
  CONSTRAINT chk_cnc_telegram_packet_item_evidence_match_ids CHECK (
    (match_status = 'matched' AND match_order_id IS NOT NULL AND match_detail_id IS NOT NULL)
    OR (match_status <> 'matched')
  )
);

CREATE INDEX IF NOT EXISTS idx_cnc_telegram_packet_item_evidence_detail
  ON cnc_telegram_packet_item_evidence(match_order_id, match_detail_id, packet_id, source_version);

CREATE TABLE IF NOT EXISTS cnc_telegram_label_sheet_map (
  telegram_label_sheet_map_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  packet_id UUID NOT NULL REFERENCES cnc_telegram_packets(packet_id) ON DELETE RESTRICT,
  source_version BIGINT NOT NULL,
  payload_hash TEXT NOT NULL,
  evidence_set_digest TEXT NOT NULL,
  layout_digest TEXT NOT NULL,
  sheet_width_mm NUMERIC(14, 3) NOT NULL,
  sheet_height_mm NUMERIC(14, 3) NOT NULL,
  base_svg TEXT NOT NULL,
  source_chat_id TEXT NOT NULL,
  source_message_id BIGINT,
  source_created_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ,
  total_contour_count INTEGER NOT NULL,
  safe_placement_count INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
  request_id TEXT NOT NULL,
  projection_source TEXT NOT NULL,
  CONSTRAINT uq_cnc_telegram_label_sheet_map_packet_version UNIQUE (packet_id, source_version),
  CONSTRAINT uq_cnc_telegram_label_sheet_map_identity
    UNIQUE (telegram_label_sheet_map_id, packet_id, source_version),
  CONSTRAINT fk_cnc_telegram_label_sheet_map_evidence
    FOREIGN KEY (packet_id, source_version)
    REFERENCES cnc_telegram_packet_evidence_set(packet_id, source_version) ON DELETE RESTRICT,
  CONSTRAINT chk_cnc_telegram_label_sheet_map_dimensions
    CHECK (sheet_width_mm > 0 AND sheet_height_mm > 0),
  CONSTRAINT chk_cnc_telegram_label_sheet_map_svg CHECK (base_svg LIKE '<svg%'),
  CONSTRAINT chk_cnc_telegram_label_sheet_map_counts
    CHECK (total_contour_count > 0 AND safe_placement_count > 0 AND safe_placement_count <= total_contour_count),
  CONSTRAINT chk_cnc_telegram_label_sheet_map_source
    CHECK (projection_source IN ('ingest', 'backfill'))
);

CREATE INDEX IF NOT EXISTS idx_cnc_telegram_label_sheet_map_packet_current
  ON cnc_telegram_label_sheet_map(packet_id, source_version DESC);

CREATE TABLE IF NOT EXISTS cnc_telegram_label_placement (
  telegram_label_placement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  telegram_label_sheet_map_id BIGINT NOT NULL
    REFERENCES cnc_telegram_label_sheet_map(telegram_label_sheet_map_id) ON DELETE RESTRICT,
  order_id BIGINT NOT NULL REFERENCES orders(order_id) ON DELETE RESTRICT,
  order_detail_id BIGINT NOT NULL REFERENCES order_details(detail_id) ON DELETE RESTRICT,
  instance INTEGER NOT NULL,
  source_item_key TEXT NOT NULL,
  source_width_mm NUMERIC(10, 2) NOT NULL,
  source_height_mm NUMERIC(10, 2) NOT NULL,
  source_type TEXT NOT NULL,
  tolerance_mm NUMERIC(6, 3) NOT NULL,
  x_mm NUMERIC(14, 3) NOT NULL,
  y_mm NUMERIC(14, 3) NOT NULL,
  width_mm NUMERIC(14, 3) NOT NULL,
  height_mm NUMERIC(14, 3) NOT NULL,
  rotated BOOLEAN NOT NULL,
  CONSTRAINT uq_cnc_telegram_label_placement_instance
    UNIQUE (telegram_label_sheet_map_id, order_detail_id, instance),
  CONSTRAINT uq_cnc_telegram_label_placement_identity
    UNIQUE (telegram_label_sheet_map_id, telegram_label_placement_id),
  CONSTRAINT chk_cnc_telegram_label_placement_instance CHECK (instance > 0),
  CONSTRAINT chk_cnc_telegram_label_placement_geometry CHECK (
    x_mm >= 0 AND y_mm >= 0 AND width_mm > 0 AND height_mm > 0
    AND source_width_mm > 0 AND source_height_mm > 0 AND tolerance_mm > 0
  ),
  CONSTRAINT chk_cnc_telegram_label_placement_source
    CHECK (source_type IN ('vector', 'ocr', 'gcode', 'manual'))
);

CREATE INDEX IF NOT EXISTS idx_cnc_telegram_label_placement_detail
  ON cnc_telegram_label_placement(order_id, order_detail_id, instance, telegram_label_sheet_map_id DESC);

CREATE TABLE IF NOT EXISTS label_generation_media_asset (
  order_label_generation_id BIGINT NOT NULL
    REFERENCES order_label_generations(order_label_generation_id) ON DELETE RESTRICT,
  asset_key TEXT NOT NULL,
  content_type TEXT NOT NULL,
  content_bytes BYTEA NOT NULL,
  content_sha256 TEXT NOT NULL,
  byte_count INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT pk_label_generation_media_asset PRIMARY KEY (order_label_generation_id, asset_key),
  CONSTRAINT chk_label_generation_media_asset_type CHECK (content_type = 'image/png'),
  CONSTRAINT chk_label_generation_media_asset_bytes
    CHECK (byte_count > 0 AND byte_count <= 524288 AND octet_length(content_bytes) = byte_count)
);

CREATE TABLE IF NOT EXISTS label_generation_telegram_source (
  order_label_generation_id BIGINT NOT NULL
    REFERENCES order_label_generations(order_label_generation_id) ON DELETE RESTRICT,
  row_index INTEGER NOT NULL,
  detail_id BIGINT NOT NULL REFERENCES order_details(detail_id) ON DELETE RESTRICT,
  copy_index INTEGER NOT NULL,
  source_kind TEXT NOT NULL,
  packet_id UUID NOT NULL REFERENCES cnc_telegram_packets(packet_id) ON DELETE RESTRICT,
  source_version BIGINT NOT NULL,
  source_message_id BIGINT,
  asset_key TEXT NOT NULL,
  media_asset_key TEXT,
  source_digest TEXT NOT NULL,
  telegram_label_sheet_map_id BIGINT,
  telegram_label_placement_id BIGINT,
  CONSTRAINT pk_label_generation_telegram_source PRIMARY KEY (order_label_generation_id, row_index),
  CONSTRAINT uq_label_generation_telegram_source_copy
    UNIQUE (order_label_generation_id, detail_id, copy_index),
  CONSTRAINT chk_label_generation_telegram_source_indices CHECK (row_index > 0 AND copy_index > 0),
  CONSTRAINT chk_label_generation_telegram_source_kind CHECK (source_kind IN ('telegram_svg', 'telegram_image')),
  CONSTRAINT chk_label_generation_telegram_source_variant CHECK (
    (source_kind = 'telegram_svg' AND media_asset_key IS NULL AND telegram_label_sheet_map_id IS NOT NULL AND telegram_label_placement_id IS NOT NULL)
    OR (source_kind = 'telegram_image' AND media_asset_key IS NOT NULL AND media_asset_key = asset_key AND telegram_label_sheet_map_id IS NULL AND telegram_label_placement_id IS NULL)
  ),
  CONSTRAINT fk_label_generation_telegram_source_media
    FOREIGN KEY (order_label_generation_id, media_asset_key)
    REFERENCES label_generation_media_asset(order_label_generation_id, asset_key)
    DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT fk_label_generation_telegram_source_sheet
    FOREIGN KEY (telegram_label_sheet_map_id, packet_id, source_version)
    REFERENCES cnc_telegram_label_sheet_map(telegram_label_sheet_map_id, packet_id, source_version)
    ON DELETE RESTRICT,
  CONSTRAINT fk_label_generation_telegram_source_placement
    FOREIGN KEY (telegram_label_sheet_map_id, telegram_label_placement_id)
    REFERENCES cnc_telegram_label_placement(telegram_label_sheet_map_id, telegram_label_placement_id)
    ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_label_generation_telegram_source_packet
  ON label_generation_telegram_source(packet_id, source_version, order_label_generation_id);

CREATE OR REPLACE FUNCTION reject_cnc_telegram_label_immutable_mutation()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'Telegram label evidence/projection is append-only' USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER trg_cnc_telegram_packet_evidence_set_immutable
BEFORE UPDATE OR DELETE ON cnc_telegram_packet_evidence_set
FOR EACH ROW EXECUTE FUNCTION reject_cnc_telegram_label_immutable_mutation();

CREATE TRIGGER trg_cnc_telegram_packet_item_evidence_immutable
BEFORE UPDATE OR DELETE ON cnc_telegram_packet_item_evidence
FOR EACH ROW EXECUTE FUNCTION reject_cnc_telegram_label_immutable_mutation();

CREATE TRIGGER trg_cnc_telegram_label_sheet_map_immutable
BEFORE UPDATE OR DELETE ON cnc_telegram_label_sheet_map
FOR EACH ROW EXECUTE FUNCTION reject_cnc_telegram_label_immutable_mutation();

CREATE TRIGGER trg_cnc_telegram_label_placement_immutable
BEFORE UPDATE OR DELETE ON cnc_telegram_label_placement
FOR EACH ROW EXECUTE FUNCTION reject_cnc_telegram_label_immutable_mutation();

CREATE TRIGGER trg_label_generation_media_asset_immutable
BEFORE UPDATE OR DELETE ON label_generation_media_asset
FOR EACH ROW EXECUTE FUNCTION reject_cnc_telegram_label_immutable_mutation();

CREATE TRIGGER trg_label_generation_telegram_source_immutable
BEFORE UPDATE OR DELETE ON label_generation_telegram_source
FOR EACH ROW EXECUTE FUNCTION reject_cnc_telegram_label_immutable_mutation();

CREATE TRIGGER trg_label_generation_cut_placement_immutable
BEFORE UPDATE OR DELETE ON label_generation_cut_placement
FOR EACH ROW EXECUTE FUNCTION reject_cnc_telegram_label_immutable_mutation();

CREATE OR REPLACE FUNCTION guard_label_generation_cut_source_exclusive()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended(NEW.order_label_generation_id::TEXT || ':' || NEW.row_index::TEXT, 0));
  IF TG_TABLE_NAME = 'label_generation_cut_placement' THEN
    IF EXISTS (
      SELECT 1 FROM label_generation_telegram_source
      WHERE order_label_generation_id = NEW.order_label_generation_id AND row_index = NEW.row_index
    ) THEN
      RAISE EXCEPTION 'label generation row already has Telegram source' USING ERRCODE = '23505';
    END IF;
  ELSE
    IF EXISTS (
      SELECT 1 FROM label_generation_cut_placement
      WHERE order_label_generation_id = NEW.order_label_generation_id AND row_index = NEW.row_index
    ) THEN
      RAISE EXCEPTION 'label generation row already has cut-result source' USING ERRCODE = '23505';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_label_generation_cut_source_exclusive_cut
BEFORE INSERT ON label_generation_cut_placement
FOR EACH ROW EXECUTE FUNCTION guard_label_generation_cut_source_exclusive();

CREATE TRIGGER trg_label_generation_cut_source_exclusive_telegram
BEFORE INSERT ON label_generation_telegram_source
FOR EACH ROW EXECUTE FUNCTION guard_label_generation_cut_source_exclusive();

COMMIT;
