-- 125_order_hdf_details.sql
-- HDF calculated order child rows + HDF tech-process settings.

BEGIN;

ALTER TABLE app_settings
  ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 1;

ALTER TABLE milling_types
  ADD COLUMN IF NOT EXISTS hdf_enabled BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS hdf_edge_mm NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 1;

UPDATE milling_types
SET hdf_enabled = true,
    hdf_edge_mm = 60,
    version = version + 1
WHERE lower(regexp_replace(btrim(milling_type_name), '\s+', ' ', 'g')) = 'выборка'
  AND (hdf_enabled IS DISTINCT FROM true OR hdf_edge_mm IS DISTINCT FROM 60);

UPDATE milling_types
SET hdf_enabled = true,
    hdf_edge_mm = 67,
    version = version + 1
WHERE lower(regexp_replace(btrim(milling_type_name), '\s+', ' ', 'g')) = 'выборка-2ступени'
  AND (hdf_enabled IS DISTINCT FROM true OR hdf_edge_mm IS DISTINCT FROM 67);

ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS hdf_min_threshold_mm NUMERIC(10,2);

CREATE TABLE IF NOT EXISTS hdf_calculation_config_state (
  id SMALLINT PRIMARY KEY DEFAULT 1,
  revision BIGINT NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_hdf_calculation_config_state_singleton CHECK (id = 1),
  CONSTRAINT chk_hdf_calculation_config_state_revision CHECK (revision > 0)
);

INSERT INTO hdf_calculation_config_state (id, revision)
VALUES (1, 1)
ON CONFLICT (id) DO NOTHING;

INSERT INTO app_settings (setting_key, value_json, description, is_active)
VALUES
  (
    'production.hdf.min_side_threshold_mm',
    '{"value":15}'::jsonb,
    'HDF minimum usable side threshold, mm',
    true
  ),
  (
    'production.hdf.sheet_material_type_id',
    '{"value":null}'::jsonb,
    'HDF sheet material type id',
    true
  )
ON CONFLICT (setting_key) DO NOTHING;

CREATE TABLE IF NOT EXISTS order_hdf_details (
  order_hdf_detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
  source_order_detail_id BIGINT REFERENCES order_details(detail_id) ON DELETE SET NULL,
  source_order_detail_id_snapshot BIGINT NOT NULL,
  source_detail_number INTEGER,
  source_detail_name TEXT,
  source_height_mm NUMERIC(10,2),
  source_width_mm NUMERIC(10,2),
  source_quantity NUMERIC(12,3),
  source_sheet_material_type_id BIGINT,
  source_sheet_material_name TEXT,
  milling_type_id BIGINT REFERENCES milling_types(milling_type_id) ON DELETE SET NULL,
  milling_type_name TEXT,
  hdf_enabled BOOLEAN NOT NULL DEFAULT false,
  edge_mm NUMERIC(10,2),
  threshold_mm NUMERIC(10,2),
  hdf_sheet_material_type_id BIGINT REFERENCES sheet_material_types(sheet_material_type_id) ON DELETE RESTRICT,
  hdf_sheet_material_name TEXT,
  hdf_height_mm NUMERIC(10,2),
  hdf_width_mm NUMERIC(10,2),
  quantity NUMERIC(12,3),
  area_m2 NUMERIC(14,4),
  status TEXT NOT NULL,
  config_errors JSONB NOT NULL DEFAULT '[]'::jsonb,
  source_snapshot_hash TEXT NOT NULL,
  source_snapshot_json JSONB NOT NULL,
  config_revision BIGINT NOT NULL,
  production_status_id SMALLINT REFERENCES production_statuses(production_status_id) ON DELETE SET NULL,
  production_status_locked BOOLEAN NOT NULL DEFAULT false,
  delete_flag BOOLEAN NOT NULL DEFAULT false,
  deleted_at TIMESTAMPTZ,
  created_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
  edited_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  version INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT chk_order_hdf_details_status
    CHECK (status IN ('ok','too_narrow','invalid_dimensions','config_missing','source_changed','disabled')),
  CONSTRAINT chk_order_hdf_details_version CHECK (version > 0),
  CONSTRAINT chk_order_hdf_details_config_revision CHECK (config_revision > 0),
  CONSTRAINT chk_order_hdf_details_positive_ok CHECK (
    status <> 'ok'
    OR (
      hdf_sheet_material_type_id IS NOT NULL
      AND edge_mm > 0
      AND threshold_mm > 0
      AND hdf_height_mm > 0
      AND hdf_width_mm > 0
      AND quantity > 0
      AND area_m2 > 0
    )
  ),
  CONSTRAINT chk_order_hdf_details_config_missing_reason CHECK (
    status <> 'config_missing'
    OR jsonb_array_length(config_errors) > 0
  ),
  CONSTRAINT chk_order_hdf_details_source_changed_hash CHECK (
    status <> 'source_changed'
    OR source_snapshot_hash <> ''
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_order_hdf_details_active_source
  ON order_hdf_details(order_id, source_order_detail_id)
  WHERE delete_flag = false AND source_order_detail_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_order_hdf_details_order_read
  ON order_hdf_details(order_id, delete_flag, order_hdf_detail_id);

CREATE INDEX IF NOT EXISTS idx_order_hdf_details_resource_demand
  ON order_hdf_details(hdf_sheet_material_type_id, config_revision)
  WHERE delete_flag = false AND status = 'ok';

CREATE INDEX IF NOT EXISTS idx_order_hdf_details_source_active
  ON order_hdf_details(source_order_detail_id)
  WHERE delete_flag = false;

CREATE INDEX IF NOT EXISTS idx_order_hdf_details_cut_eligibility
  ON order_hdf_details(production_status_id)
  WHERE delete_flag = false AND status = 'ok';

CREATE INDEX IF NOT EXISTS idx_order_hdf_details_snapshot_hash
  ON order_hdf_details(source_snapshot_hash)
  WHERE delete_flag = false;

CREATE OR REPLACE FUNCTION recalc_order_production_status(p_order_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
    v_new_status_id SMALLINT;
    v_current_status_id SMALLINT;
BEGIN
    IF current_setting('erp.order_status_to_details_sync', true) = 'on' THEN
        RETURN;
    END IF;

    SELECT production_status_id
    INTO v_current_status_id
    FROM orders
    WHERE order_id = p_order_id;

    IF NOT FOUND THEN
        RETURN;
    END IF;

    WITH candidate_statuses AS (
      SELECT od.production_status_id
      FROM order_details od
      WHERE od.order_id = p_order_id
        AND COALESCE(od.delete_flag, false) = false
        AND od.production_status_id IS NOT NULL
      UNION ALL
      SELECT hdf.production_status_id
      FROM order_hdf_details hdf
      JOIN hdf_calculation_config_state state ON state.id = 1
      WHERE hdf.order_id = p_order_id
        AND COALESCE(hdf.delete_flag, false) = false
        AND hdf.status = 'ok'
        AND hdf.config_revision = state.revision
        AND hdf.production_status_id IS NOT NULL
    )
    SELECT ps.production_status_id
    INTO v_new_status_id
    FROM candidate_statuses candidate
    JOIN production_statuses ps ON ps.production_status_id = candidate.production_status_id
    ORDER BY ps.sort_order ASC
    LIMIT 1;

    IF v_new_status_id IS NULL THEN
        RETURN;
    END IF;

    IF v_current_status_id IS DISTINCT FROM v_new_status_id THEN
        PERFORM set_config('erp.detail_status_to_order_recalc', 'on', true);
        UPDATE orders
        SET production_status_id = v_new_status_id,
            updated_at = now()
        WHERE order_id = p_order_id;
        PERFORM set_config('erp.detail_status_to_order_recalc', 'off', true);
    END IF;
END $$;

COMMENT ON FUNCTION recalc_order_production_status(BIGINT) IS
  'Пересчитывает production_status_id заказа из самой отстающей активной обычной или свежей HDF-детали.';

ALTER TABLE cut_job_item
  ADD COLUMN IF NOT EXISTS source_type TEXT NOT NULL DEFAULT 'order_detail',
  ADD COLUMN IF NOT EXISTS order_hdf_detail_id BIGINT REFERENCES order_hdf_details(order_hdf_detail_id) ON DELETE RESTRICT;

ALTER TABLE cut_job_item
  ALTER COLUMN order_detail_id DROP NOT NULL;

UPDATE cut_job_item
SET source_type = 'order_detail'
WHERE order_detail_id IS NOT NULL
  AND source_type IS DISTINCT FROM 'order_detail';

COMMIT;
BEGIN;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'chk_cut_job_item_source_exactly_one'
  ) THEN
    ALTER TABLE cut_job_item
      ADD CONSTRAINT chk_cut_job_item_source_exactly_one
      CHECK (
        (source_type = 'order_detail' AND order_detail_id IS NOT NULL AND order_hdf_detail_id IS NULL)
        OR
        (source_type = 'order_hdf_detail' AND order_hdf_detail_id IS NOT NULL AND order_detail_id IS NULL)
      ) NOT VALID;
    ALTER TABLE cut_job_item VALIDATE CONSTRAINT chk_cut_job_item_source_exactly_one;
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_cut_job_item_active_hdf_detail
  ON cut_job_item(cut_job_id, order_hdf_detail_id)
  WHERE is_active = true AND order_hdf_detail_id IS NOT NULL;

ALTER TABLE bazis_cut_set_details
  ADD COLUMN IF NOT EXISTS source_type TEXT,
  ADD COLUMN IF NOT EXISTS source_order_hdf_detail_id BIGINT REFERENCES order_hdf_details(order_hdf_detail_id) ON DELETE RESTRICT;

UPDATE bazis_cut_set_details
SET source_type = CASE
  WHEN source_order_detail_id IS NOT NULL THEN 'order_detail'
  WHEN source_bazis_node_id IS NOT NULL THEN 'bazis_node'
  ELSE source_type
END
WHERE source_type IS NULL;

COMMIT;
BEGIN;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'chk_bazis_cut_set_details_hdf_source_exclusive'
  ) THEN
    ALTER TABLE bazis_cut_set_details
      ADD CONSTRAINT chk_bazis_cut_set_details_hdf_source_exclusive
      CHECK (
        source_order_hdf_detail_id IS NULL
        OR (
          source_type = 'order_hdf_detail'
          AND source_order_detail_id IS NULL
          AND source_bazis_node_id IS NULL
        )
      ) NOT VALID;
    ALTER TABLE bazis_cut_set_details VALIDATE CONSTRAINT chk_bazis_cut_set_details_hdf_source_exclusive;
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_bazis_cut_set_details_hdf_source
  ON bazis_cut_set_details(bazis_cut_set_id, source_order_hdf_detail_id)
  WHERE source_order_hdf_detail_id IS NOT NULL;

ALTER TABLE order_realtime_stream
  ADD COLUMN IF NOT EXISTS hdf_details_revision BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS materials_revision BIGINT NOT NULL DEFAULT 0;

ALTER TABLE realtime_event_log
  ADD COLUMN IF NOT EXISTS hdf_details_revision BIGINT,
  ADD COLUMN IF NOT EXISTS materials_revision BIGINT;

COMMIT;
