-- 127_milling_extra_resources.sql
-- Flexible extra resources attached to milling types.

BEGIN;

CREATE TABLE IF NOT EXISTS milling_type_extra_resources (
  milling_type_extra_resource_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  milling_type_id SMALLINT NOT NULL REFERENCES milling_types(milling_type_id) ON DELETE CASCADE,
  resource_kind TEXT NOT NULL DEFAULT 'other',
  resource_ref_type TEXT,
  resource_ref_id BIGINT,
  resource_name TEXT NOT NULL DEFAULT '',
  unit_id SMALLINT REFERENCES units(unit_id) ON DELETE SET NULL,
  accounting_method TEXT NOT NULL DEFAULT '',
  parameter_name TEXT NOT NULL DEFAULT '',
  parameter_mm NUMERIC(10,2),
  hdf_auto_enabled BOOLEAN NOT NULL DEFAULT false,
  comment TEXT NOT NULL DEFAULT '',
  is_active BOOLEAN NOT NULL DEFAULT true,
  sort_order SMALLINT NOT NULL DEFAULT 100,
  version BIGINT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_milling_type_extra_resources_resource_kind CHECK (btrim(resource_kind) <> ''),
  CONSTRAINT chk_milling_type_extra_resources_resource_ref CHECK (
    resource_ref_type IS NULL OR btrim(resource_ref_type) <> ''
  ),
  CONSTRAINT chk_milling_type_extra_resources_resource_name CHECK (btrim(resource_name) <> ''),
  CONSTRAINT chk_milling_type_extra_resources_parameter_mm CHECK (parameter_mm IS NULL OR parameter_mm > 0),
  CONSTRAINT chk_milling_type_extra_resources_version CHECK (version > 0)
);

CREATE INDEX IF NOT EXISTS idx_milling_type_extra_resources_milling
  ON milling_type_extra_resources(milling_type_id, sort_order, milling_type_extra_resource_id);

CREATE INDEX IF NOT EXISTS idx_milling_type_extra_resources_hdf_auto
  ON milling_type_extra_resources(milling_type_id)
  WHERE hdf_auto_enabled = true AND is_active = true;

INSERT INTO milling_type_extra_resources (
  milling_type_id,
  resource_kind,
  resource_ref_type,
  resource_ref_id,
  resource_name,
  unit_id,
  accounting_method,
  parameter_name,
  parameter_mm,
  hdf_auto_enabled,
  is_active,
  sort_order
)
SELECT
  mt.milling_type_id,
  'sheet_material',
  CASE WHEN smt.sheet_material_type_id IS NULL THEN NULL ELSE 'sheet_material_type' END,
  smt.sheet_material_type_id,
  COALESCE(smt.name, 'ХДФ'),
  smt.unit_id,
  'Автоматический расчет ХДФ-детали по размерам исходной детали',
  'Отступ от края',
  mt.hdf_edge_mm,
  true,
  true,
  100
FROM milling_types mt
LEFT JOIN LATERAL (
  SELECT CASE WHEN COALESCE(value_json->>'value', '') ~ '^[1-9][0-9]*$'
    THEN (value_json->>'value')::bigint ELSE NULL END AS sheet_material_type_id
  FROM app_settings
  WHERE setting_key = 'production.hdf.sheet_material_type_id'
    AND is_active = true
  LIMIT 1
) hdf_setting ON true
LEFT JOIN sheet_material_types smt
  ON smt.sheet_material_type_id = hdf_setting.sheet_material_type_id
WHERE mt.hdf_enabled = true
  AND mt.hdf_edge_mm IS NOT NULL
  AND NOT EXISTS (
    SELECT 1
    FROM milling_type_extra_resources existing
    WHERE existing.milling_type_id = mt.milling_type_id
      AND existing.hdf_auto_enabled = true
  );

COMMIT;
