import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const sql = readFileSync(new URL('./129_extra_resources_directory.sql', import.meta.url), 'utf8');
const runner = readFileSync(new URL('../../../ops/apply-migrations.sh', import.meta.url), 'utf8');

describe('129_extra_resources_directory migration', () => {
  it('creates an independent extra_resources directory', () => {
    expect(sql).toMatch(/CREATE TABLE IF NOT EXISTS extra_resources/i);
    expect(sql).toMatch(/extra_resource_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/i);
    expect(sql).toContain('resource_name TEXT NOT NULL');
    expect(sql).toContain('default_parameter_mm NUMERIC(10,2)');
    expect(sql).toContain('hdf_auto_default BOOLEAN NOT NULL DEFAULT false');
    expect(sql).toContain('uq_extra_resources_active_kind_name');
  });

  it('links existing milling resources to the new directory without dropping legacy fields', () => {
    expect(sql).toMatch(/ALTER TABLE milling_type_extra_resources[\s\S]*ADD COLUMN IF NOT EXISTS extra_resource_id/i);
    expect(sql).toMatch(/INSERT INTO extra_resources/i);
    expect(sql).toMatch(/UPDATE milling_type_extra_resources link/i);
    expect(sql).not.toMatch(/DROP COLUMN/i);
  });

  it('is covered by the migration runner probes', () => {
    expect(runner).toContain('129_extra_resources_directory*) probe_all');
    expect(runner).toContain('q_tbl extra_resources');
    expect(runner).toContain('milling_type_extra_resources extra_resource_id');
    expect(runner).toContain('129_*');
  });
});
