-- 129_extra_resources_directory.sql
-- Independent directory for flexible production extra resources.

BEGIN;

CREATE TABLE IF NOT EXISTS extra_resources (
  extra_resource_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource_kind TEXT NOT NULL DEFAULT 'other',
  resource_ref_type TEXT,
  resource_ref_id BIGINT,
  resource_name TEXT NOT NULL,
  unit_id SMALLINT REFERENCES units(unit_id) ON DELETE SET NULL,
  accounting_method TEXT NOT NULL DEFAULT '',
  default_parameter_name TEXT NOT NULL DEFAULT '',
  default_parameter_mm NUMERIC(10,2),
  hdf_auto_default BOOLEAN NOT NULL DEFAULT false,
  comment TEXT NOT NULL DEFAULT '',
  is_active BOOLEAN NOT NULL DEFAULT true,
  sort_order SMALLINT NOT NULL DEFAULT 100,
  version BIGINT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_extra_resources_resource_kind CHECK (btrim(resource_kind) <> ''),
  CONSTRAINT chk_extra_resources_resource_ref CHECK (
    resource_ref_type IS NULL OR btrim(resource_ref_type) <> ''
  ),
  CONSTRAINT chk_extra_resources_resource_name CHECK (btrim(resource_name) <> ''),
  CONSTRAINT chk_extra_resources_default_parameter_mm CHECK (
    default_parameter_mm IS NULL OR default_parameter_mm > 0
  ),
  CONSTRAINT chk_extra_resources_version CHECK (version > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_extra_resources_active_kind_name
  ON extra_resources (lower(btrim(resource_kind)), lower(btrim(resource_name)))
  WHERE is_active = true;

CREATE INDEX IF NOT EXISTS idx_extra_resources_sort
  ON extra_resources(is_active DESC, sort_order, resource_name, extra_resource_id);

ALTER TABLE milling_type_extra_resources
  ADD COLUMN IF NOT EXISTS extra_resource_id BIGINT REFERENCES extra_resources(extra_resource_id) ON DELETE RESTRICT;

INSERT INTO extra_resources (
  resource_kind,
  resource_ref_type,
  resource_ref_id,
  resource_name,
  unit_id,
  accounting_method,
  default_parameter_name,
  default_parameter_mm,
  hdf_auto_default,
  comment,
  is_active,
  sort_order
)
SELECT DISTINCT ON (lower(btrim(resource_kind)), lower(btrim(resource_name)))
  resource_kind,
  resource_ref_type,
  resource_ref_id,
  resource_name,
  unit_id,
  accounting_method,
  parameter_name,
  parameter_mm,
  hdf_auto_enabled,
  comment,
  is_active,
  sort_order
FROM milling_type_extra_resources source
WHERE btrim(resource_name) <> ''
  AND NOT EXISTS (
    SELECT 1
    FROM extra_resources existing
    WHERE lower(btrim(existing.resource_kind)) = lower(btrim(source.resource_kind))
      AND lower(btrim(existing.resource_name)) = lower(btrim(source.resource_name))
      AND existing.is_active = true
  )
ORDER BY lower(btrim(resource_kind)), lower(btrim(resource_name)), is_active DESC, sort_order, milling_type_extra_resource_id;

UPDATE milling_type_extra_resources link
SET extra_resource_id = resource.extra_resource_id
FROM extra_resources resource
WHERE link.extra_resource_id IS NULL
  AND lower(btrim(resource.resource_kind)) = lower(btrim(link.resource_kind))
  AND lower(btrim(resource.resource_name)) = lower(btrim(link.resource_name))
  AND resource.is_active = true;

CREATE INDEX IF NOT EXISTS idx_milling_type_extra_resources_extra_resource
  ON milling_type_extra_resources(extra_resource_id)
  WHERE extra_resource_id IS NOT NULL;

COMMENT ON TABLE extra_resources IS 'Independent directory of extra production resources selectable by milling types.';
COMMENT ON COLUMN milling_type_extra_resources.extra_resource_id IS 'Selected extra resource directory item for this milling type relation.';

COMMIT;
