-- Match common reference metadata; existing audit/activity columns are retained.
ALTER TABLE public.catalog_items
  ADD COLUMN IF NOT EXISTS ref_key_1c uuid,
  ADD COLUMN IF NOT EXISTS sort_order smallint NOT NULL DEFAULT 100;
CREATE INDEX IF NOT EXISTS catalog_items_sort_idx
  ON public.catalog_items (is_active, sort_order, name, id);
CREATE UNIQUE INDEX IF NOT EXISTS catalog_items_ref_key_1c_unique
  ON public.catalog_items (ref_key_1c) WHERE ref_key_1c IS NOT NULL;
COMMENT ON COLUMN public.catalog_items.ref_key_1c IS 'Optional 1C reference UUID; entered explicitly, never generated by ERP';
