-- Multiple WhatsApp broadcasts (stage A).
-- New tables only: the daily digest tables of 183/184 keep their schema, so an
-- older backend still works on this database. Cutover (once): broadcast #1 is
-- copied from the digest singleton and the singleton is disabled in the same
-- transaction; the migration refuses to run while the legacy queue still has
-- unfinished work (it would never be delivered by the new code).
BEGIN;

CREATE TABLE IF NOT EXISTS whatsapp_broadcasts (
  broadcast_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL CHECK (name = btrim(name) AND char_length(name) BETWEEN 1 AND 120),
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  group_chat_id TEXT CHECK (group_chat_id IS NULL OR group_chat_id ~ '^[0-9]{5,24}(-[0-9]{5,24})?@g[.]us$'),
  weekdays SMALLINT[] NOT NULL DEFAULT '{1,2,3,4,5,6,7}',
  send_time TIME NOT NULL DEFAULT TIME '08:45',
  send_window_minutes INTEGER NOT NULL DEFAULT 0 CHECK (send_window_minutes BETWEEN 0 AND 1439),
  catch_up_policy TEXT NOT NULL DEFAULT 'until_deadline' CHECK (catch_up_policy IN ('skip','until_deadline','end_of_day')),
  catch_up_deadline TIME NOT NULL DEFAULT TIME '10:00',
  partial_policy TEXT NOT NULL DEFAULT 'remaining' CHECK (partial_policy IN ('remaining','repeat_all','manual')),
  schedule_generation INTEGER NOT NULL DEFAULT 1 CHECK (schedule_generation > 0),
  order_date_offset_days SMALLINT NOT NULL DEFAULT 0 CHECK (order_date_offset_days BETWEEN 0 AND 14),
  order_filter JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(order_filter) = 'object'),
  attach_cards BOOLEAN NOT NULL DEFAULT TRUE,
  cards_per_message SMALLINT NOT NULL DEFAULT 2 CHECK (cards_per_message IN (1,2)),
  caption_template TEXT NOT NULL DEFAULT '' CHECK (char_length(caption_template) <= 1000),
  text_template TEXT CHECK (text_template IS NULL OR char_length(text_template) BETWEEN 1 AND 4000),
  counter_next BIGINT NOT NULL DEFAULT 1 CHECK (counter_next >= 1),
  required_permissions TEXT[] NOT NULL DEFAULT '{whatsapp.manage,calendar.view,orders.view,orders.view_financials}',
  created_by BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by BIGINT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  archived_by BIGINT,
  archived_at TIMESTAMPTZ,
  CONSTRAINT chk_whatsapp_broadcasts_content CHECK (attach_cards OR text_template IS NOT NULL),
  CONSTRAINT chk_whatsapp_broadcasts_weekdays CHECK (
    cardinality(weekdays) <= 7 AND weekdays <@ ARRAY[1,2,3,4,5,6,7]::smallint[] AND array_position(weekdays, NULL) IS NULL),
  CONSTRAINT chk_whatsapp_broadcasts_enabled CHECK (
    NOT enabled OR (group_chat_id IS NOT NULL AND cardinality(weekdays) > 0 AND archived_at IS NULL)),
  CONSTRAINT chk_whatsapp_broadcasts_window_same_day CHECK (EXTRACT(EPOCH FROM send_time) + send_window_minutes * 60 < 86400),
  CONSTRAINT chk_whatsapp_broadcasts_deadline_after_window CHECK (catch_up_policy <> 'until_deadline'
    OR EXTRACT(EPOCH FROM catch_up_deadline) >= EXTRACT(EPOCH FROM send_time) + send_window_minutes * 60)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_whatsapp_broadcasts_name_active
  ON whatsapp_broadcasts (lower(name)) WHERE archived_at IS NULL;

-- Global send barrier («Остановить все рассылки»): while paused no command,
-- automatic run or send intent is created (lock order: control -> broadcast -> run -> message).
CREATE TABLE IF NOT EXISTS whatsapp_broadcast_control (
  singleton_id SMALLINT PRIMARY KEY DEFAULT 1 CHECK (singleton_id = 1),
  paused BOOLEAN NOT NULL DEFAULT FALSE,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  paused_by BIGINT,
  paused_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO whatsapp_broadcast_control (singleton_id) VALUES (1) ON CONFLICT DO NOTHING;

-- Durable command ledger: one row per idempotency key and broadcast, written in
-- the same transaction as the effect; replay returns the stored result.
CREATE TABLE IF NOT EXISTS whatsapp_broadcast_commands (
  command_id UUID PRIMARY KEY,
  broadcast_id BIGINT NOT NULL REFERENCES whatsapp_broadcasts(broadcast_id) ON DELETE RESTRICT,
  kind TEXT NOT NULL CHECK (kind IN ('manual','retry','replan')),
  idempotency_key UUID NOT NULL,
  fingerprint TEXT NOT NULL CHECK (fingerprint ~ '^[a-f0-9]{64}$'),
  result JSONB NOT NULL CHECK (jsonb_typeof(result) = 'object'),
  created_by BIGINT,
  request_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_whatsapp_broadcast_commands_key UNIQUE (broadcast_id, idempotency_key)
);

-- Durable chosen dispatch minute per broadcast, business date and replan generation.
CREATE TABLE IF NOT EXISTS whatsapp_broadcast_schedules (
  broadcast_id BIGINT NOT NULL REFERENCES whatsapp_broadcasts(broadcast_id) ON DELETE RESTRICT,
  business_date DATE NOT NULL,
  generation INTEGER NOT NULL CHECK (generation > 0),
  scheduled_at TIMESTAMPTZ NOT NULL,
  window_start TIME NOT NULL,
  window_end TIME NOT NULL,
  send_window_minutes INTEGER NOT NULL CHECK (send_window_minutes BETWEEN 0 AND 1439),
  catch_up_policy TEXT NOT NULL CHECK (catch_up_policy IN ('skip','until_deadline','end_of_day')),
  catch_up_deadline TIME NOT NULL,
  settings_version INTEGER NOT NULL CHECK (settings_version > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (broadcast_id, business_date, generation),
  CHECK (scheduled_at = date_trunc('minute', scheduled_at)),
  CHECK (EXTRACT(EPOCH FROM window_end) = EXTRACT(EPOCH FROM window_start) + send_window_minutes * 60
         AND EXTRACT(EPOCH FROM window_end) < 86400),
  CHECK ((scheduled_at AT TIME ZONE 'Asia/Almaty')::date = business_date),
  CHECK ((scheduled_at AT TIME ZONE 'Asia/Almaty')::time >= window_start
         AND ((send_window_minutes = 0 AND (scheduled_at AT TIME ZONE 'Asia/Almaty')::time = window_start)
           OR (send_window_minutes > 0 AND (scheduled_at AT TIME ZONE 'Asia/Almaty')::time < window_end))),
  CHECK (catch_up_policy <> 'until_deadline' OR catch_up_deadline >= window_end)
);

CREATE TABLE IF NOT EXISTS whatsapp_broadcast_runs (
  run_id UUID PRIMARY KEY,
  broadcast_id BIGINT NOT NULL REFERENCES whatsapp_broadcasts(broadcast_id) ON DELETE RESTRICT,
  business_date DATE NOT NULL,
  target_date DATE NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('auto','manual','retry')),
  auto_origin BOOLEAN NOT NULL DEFAULT FALSE,
  parent_run_id UUID REFERENCES whatsapp_broadcast_runs(run_id) ON DELETE RESTRICT,
  root_run_id UUID NOT NULL REFERENCES whatsapp_broadcast_runs(run_id) ON DELETE RESTRICT,
  command_id UUID REFERENCES whatsapp_broadcast_commands(command_id) ON DELETE RESTRICT,
  schedule_generation INTEGER CHECK (schedule_generation IS NULL OR schedule_generation > 0),
  scheduled_at TIMESTAMPTZ,
  settings_version INTEGER NOT NULL CHECK (settings_version > 0),
  snapshot_author_user_id BIGINT,
  initiated_by_user_id BIGINT,
  required_permissions TEXT[] NOT NULL,
  counter_value BIGINT CHECK (counter_value IS NULL OR counter_value >= 1),
  destination_chat_id TEXT NOT NULL CHECK (destination_chat_id ~ '^[0-9]{5,24}(-[0-9]{5,24})?@g[.]us$'),
  catch_up_policy TEXT NOT NULL CHECK (catch_up_policy IN ('skip','until_deadline','end_of_day')),
  deadline_at TIMESTAMPTZ,
  partial_policy TEXT NOT NULL CHECK (partial_policy IN ('remaining','repeat_all','manual')),
  cards_per_message SMALLINT NOT NULL CHECK (cards_per_message IN (1,2)),
  snapshot JSONB,
  renderer_version TEXT NOT NULL,
  order_count INTEGER NOT NULL DEFAULT 0 CHECK (order_count BETWEEN 0 AND 500),
  total_area NUMERIC(14,3) NOT NULL DEFAULT 0 CHECK (total_area >= 0),
  state TEXT NOT NULL CHECK (state IN ('preparing','queued','sending','sent','partial','failed','unknown','cancelled','expired','empty','skipped')),
  reason TEXT CHECK (reason IS NULL OR reason ~ '^[A-Z0-9_]{1,64}$'),
  retry_depth SMALLINT NOT NULL DEFAULT 0 CHECK (retry_depth BETWEEN 0 AND 3),
  request_id TEXT,
  image_expires_at TIMESTAMPTZ,
  snapshot_purged_at TIMESTAMPTZ,
  content_purged_at TIMESTAMPTZ,
  superseded_at TIMESTAMPTZ,
  superseded_by_request_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_whatsapp_broadcast_runs_target CHECK (target_date BETWEEN business_date AND business_date + 14),
  CONSTRAINT chk_whatsapp_broadcast_runs_auto_generation CHECK ((kind = 'auto') = (schedule_generation IS NOT NULL)),
  CONSTRAINT chk_whatsapp_broadcast_runs_root CHECK ((parent_run_id IS NULL) = (root_run_id = run_id)),
  CONSTRAINT chk_whatsapp_broadcast_runs_command CHECK (kind = 'auto' OR auto_origin OR command_id IS NOT NULL)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_whatsapp_broadcast_runs_auto_slot
  ON whatsapp_broadcast_runs (broadcast_id, business_date) WHERE kind = 'auto' AND superseded_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_whatsapp_broadcast_runs_recent
  ON whatsapp_broadcast_runs (broadcast_id, created_at DESC, run_id DESC);
CREATE INDEX IF NOT EXISTS idx_whatsapp_broadcast_runs_active
  ON whatsapp_broadcast_runs (state, created_at) WHERE state IN ('preparing','queued','sending');
CREATE INDEX IF NOT EXISTS idx_whatsapp_broadcast_runs_root ON whatsapp_broadcast_runs (root_run_id);

-- Delivery messages: images first (delivery_seq 1..M, image_index 1..M for the
-- file store), text messages after them (stage B; not produced in stage A).
CREATE TABLE IF NOT EXISTS whatsapp_broadcast_messages (
  run_id UUID NOT NULL REFERENCES whatsapp_broadcast_runs(run_id) ON DELETE RESTRICT,
  delivery_seq SMALLINT NOT NULL CHECK (delivery_seq BETWEEN 1 AND 560),
  message_kind TEXT NOT NULL CHECK (message_kind IN ('image','text')),
  image_index SMALLINT CHECK (image_index IS NULL OR image_index BETWEEN 1 AND 500),
  order_ids JSONB NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(order_ids) = 'array' AND jsonb_array_length(order_ids) <= 2),
  file_key TEXT CHECK (file_key IS NULL OR file_key ~ '^[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}-(1|[1-9][0-9]?|[1-4][0-9]{2}|500)[.]png$'),
  sha256 TEXT CHECK (sha256 IS NULL OR sha256 ~ '^[a-f0-9]{64}$'),
  size_bytes INTEGER CHECK (size_bytes IS NULL OR size_bytes BETWEEN 1 AND 1048576),
  caption TEXT CHECK (caption IS NULL OR char_length(caption) <= 1024),
  text_body TEXT CHECK (text_body IS NULL OR char_length(text_body) BETWEEN 1 AND 4096),
  expires_at TIMESTAMPTZ NOT NULL,
  state TEXT NOT NULL CHECK (state IN ('pending','sending','sent','failed','unknown','cancelled','expired')),
  attempt_count SMALLINT NOT NULL DEFAULT 0 CHECK (attempt_count BETWEEN 0 AND 4),
  preflight_attempt_count SMALLINT NOT NULL DEFAULT 0 CHECK (preflight_attempt_count BETWEEN 0 AND 3),
  next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  provider_message_id TEXT,
  error_code TEXT CHECK (error_code IS NULL OR error_code ~ '^[A-Z0-9_]{1,64}$'),
  send_started_at TIMESTAMPTZ,
  lock_token UUID,
  sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (run_id, delivery_seq),
  CONSTRAINT chk_whatsapp_broadcast_messages_image CHECK (message_kind <> 'image' OR (
    image_index IS NOT NULL AND file_key IS NOT NULL AND sha256 IS NOT NULL AND size_bytes IS NOT NULL
    AND jsonb_array_length(order_ids) BETWEEN 1 AND 2 AND text_body IS NULL)),
  CONSTRAINT chk_whatsapp_broadcast_messages_text CHECK (message_kind <> 'text' OR (
    image_index IS NULL AND file_key IS NULL AND sha256 IS NULL AND size_bytes IS NULL
    AND jsonb_array_length(order_ids) = 0 AND caption IS NULL))
);
CREATE INDEX IF NOT EXISTS idx_whatsapp_broadcast_messages_file ON whatsapp_broadcast_messages (file_key) WHERE file_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_whatsapp_broadcast_messages_due
  ON whatsapp_broadcast_messages (state, expires_at, run_id, delivery_seq);

DO $cutover$
DECLARE
  digest RECORD;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM whatsapp_broadcasts WHERE broadcast_id = 1) THEN
    IF EXISTS (SELECT 1 FROM whatsapp_daily_digest_runs WHERE state IN ('queued','sending'))
       OR EXISTS (SELECT 1 FROM whatsapp_daily_digest_pages WHERE state IN ('pending','sending')) THEN
      RAISE EXCEPTION 'WHATSAPP_DIGEST_QUEUE_NOT_DRAINED: finish the queued daily digest delivery with the old backend before this migration';
    END IF;
    SELECT * INTO digest FROM whatsapp_daily_digest_settings WHERE singleton_id = 1 FOR UPDATE;
    IF FOUND THEN
      INSERT INTO whatsapp_broadcasts (
        broadcast_id, name, enabled, group_chat_id, weekdays, send_time, send_window_minutes,
        catch_up_policy, catch_up_deadline, partial_policy, cards_per_message, caption_template,
        created_by, updated_by, updated_at)
      VALUES (
        1, 'Рассылка заказов', digest.enabled AND digest.group_chat_id IS NOT NULL, digest.group_chat_id,
        '{1,2,3,4,5,6,7}', digest.send_time, digest.send_window_minutes,
        digest.catch_up_policy, digest.catch_up_deadline, digest.partial_policy, digest.cards_per_message,
        'Заказы на сегодня', digest.updated_by, digest.updated_by, now());
      UPDATE whatsapp_daily_digest_settings
        SET enabled = FALSE, version = version + 1, updated_at = now()
        WHERE singleton_id = 1;
      INSERT INTO audit_log (event, entity_type, entity_id, request_id, source, before_json, after_json, metadata_json)
      VALUES ('whatsapp.daily_digest.settings.disabled_by_cutover', 'whatsapp_daily_digest', 'settings',
        'migration-209', 'migration',
        jsonb_build_object('enabled', digest.enabled, 'version', digest.version),
        jsonb_build_object('enabled', FALSE, 'version', digest.version + 1),
        jsonb_build_object('broadcastId', 1));
    ELSE
      INSERT INTO whatsapp_broadcasts (broadcast_id, name, caption_template) VALUES (1, 'Рассылка заказов', 'Заказы на сегодня');
    END IF;
  END IF;
  PERFORM setval(pg_get_serial_sequence('whatsapp_broadcasts', 'broadcast_id'),
    GREATEST((SELECT max(broadcast_id) FROM whatsapp_broadcasts), 1));
END
$cutover$;

COMMIT;
