-- Рабочие контакты сотрудников и сотрудник как получатель отправки заказа из карточки.
-- Additive. The previous backend (the employee-compat step) reads these rows and never delivers an
-- employee recipient; the feature backend comes after this migration.
BEGIN;

-- Runs while the backend works: every application table it changes is locked up front with NOWAIT, so the
-- migration never waits while holding one of them (no deadlock cycle with card commands, deliveries or
-- reads); a table in use makes it fail at once without changes — run it again.
SET LOCAL lock_timeout = '5s';
LOCK TABLE employees IN ACCESS EXCLUSIVE MODE NOWAIT;
LOCK TABLE whatsapp_order_send_settings IN ACCESS EXCLUSIVE MODE NOWAIT;
LOCK TABLE whatsapp_order_sends IN ACCESS EXCLUSIVE MODE NOWAIT;
-- (employee_work_contacts and whatsapp_order_send_employees are new: nothing else uses them yet.)

-- Version of an employee's whole set of work contacts (the row always exists, also for an empty set).
ALTER TABLE employees ADD COLUMN IF NOT EXISTS work_contacts_version INTEGER NOT NULL DEFAULT 0;

-- Work contacts: phones, emails, Telegram accounts; one primary per kind. Changed only through the backend
-- command (version compare-and-swap + audit); RESTRICT keeps a direct employee delete from dropping them.
CREATE TABLE IF NOT EXISTS employee_work_contacts (
  contact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id BIGINT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('phone','email','telegram')),
  value TEXT NOT NULL CHECK (char_length(btrim(value)) BETWEEN 1 AND 200),
  value_normalized TEXT NOT NULL CHECK (
    (kind = 'phone' AND value_normalized ~ '^7[0-9]{10}$')
    OR (kind = 'email' AND value_normalized ~ '^[^@[:space:]]+@[^@[:space:]]+$' AND value_normalized = lower(value_normalized))
    OR (kind = 'telegram' AND value_normalized ~ '^[a-z0-9_]{5,32}$')),
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  note TEXT CHECK (note IS NULL OR char_length(note) <= 200),
  position SMALLINT NOT NULL DEFAULT 0 CHECK (position BETWEEN 0 AND 99),
  created_by BIGINT,
  updated_by BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- Named and re-created on every run: a rerun also repairs a schema that lost the link.
ALTER TABLE employee_work_contacts DROP CONSTRAINT IF EXISTS fk_employee_work_contacts_employee;
ALTER TABLE employee_work_contacts ADD CONSTRAINT fk_employee_work_contacts_employee
  FOREIGN KEY (employee_id) REFERENCES employees(employee_id) ON DELETE RESTRICT;
CREATE UNIQUE INDEX IF NOT EXISTS uq_employee_work_contacts_primary ON employee_work_contacts (employee_id, kind) WHERE is_primary;
CREATE UNIQUE INDEX IF NOT EXISTS uq_employee_work_contacts_value ON employee_work_contacts (employee_id, kind, value_normalized);

-- Employees offered in the order card menu (as chats): channel, forms, caption. A row never changes its
-- employee or channel — a change archives it and adds a new one; RESTRICT keeps archived rows' employee.
CREATE TABLE IF NOT EXISTS whatsapp_order_send_employees (
  recipient_key UUID PRIMARY KEY,
  employee_id BIGINT NOT NULL,
  channel TEXT NOT NULL CHECK (channel IN ('whatsapp','telegram')),
  forms TEXT[] NOT NULL DEFAULT '{}'
    CHECK (forms <@ ARRAY['production_pdf','order_pdf','production_excel','order_excel','production_image','order_image']::text[]),
  caption TEXT NOT NULL DEFAULT 'Заказ {order_name}' CHECK (char_length(caption) <= 1000),
  position SMALLINT NOT NULL CHECK (position BETWEEN 0 AND 99),
  archived_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by BIGINT
);
ALTER TABLE whatsapp_order_send_employees DROP CONSTRAINT IF EXISTS fk_whatsapp_order_send_employees_employee;
ALTER TABLE whatsapp_order_send_employees ADD CONSTRAINT fk_whatsapp_order_send_employees_employee
  FOREIGN KEY (employee_id) REFERENCES employees(employee_id) ON DELETE RESTRICT;
CREATE UNIQUE INDEX IF NOT EXISTS idx_whatsapp_order_send_employees_active
  ON whatsapp_order_send_employees (employee_id, channel) WHERE archived_at IS NULL;

CREATE OR REPLACE FUNCTION whatsapp_order_send_employees_immutable() RETURNS trigger AS $$
BEGIN
  IF NEW.recipient_key <> OLD.recipient_key OR NEW.employee_id <> OLD.employee_id OR NEW.channel <> OLD.channel THEN
    RAISE EXCEPTION 'whatsapp_order_send_employees: recipient_key, employee_id and channel are immutable' USING ERRCODE = 'check_violation';
  END IF;
  IF OLD.archived_at IS NOT NULL THEN
    RAISE EXCEPTION 'whatsapp_order_send_employees: an archived recipient cannot change' USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS trg_whatsapp_order_send_employees_immutable ON whatsapp_order_send_employees;
CREATE TRIGGER trg_whatsapp_order_send_employees_immutable BEFORE UPDATE ON whatsapp_order_send_employees
  FOR EACH ROW EXECUTE FUNCTION whatsapp_order_send_employees_immutable();

-- Salt of this installation for recipient fingerprints (never returned by the API).
ALTER TABLE whatsapp_order_send_settings ADD COLUMN IF NOT EXISTS identity_salt TEXT NOT NULL
  DEFAULT (gen_random_uuid()::text || gen_random_uuid()::text);

-- The employee target of a send: the recipient row, the employee, the contact used and a fingerprint of
-- the recipient that survives retention (the phone itself is purged after 7 days).
ALTER TABLE whatsapp_order_sends DROP CONSTRAINT IF EXISTS whatsapp_order_sends_target_kind_check;
ALTER TABLE whatsapp_order_sends DROP CONSTRAINT IF EXISTS chk_whatsapp_order_sends_target_kind;
ALTER TABLE whatsapp_order_sends ADD CONSTRAINT chk_whatsapp_order_sends_target_kind CHECK (target_kind IN ('client','chat','employee'));
ALTER TABLE whatsapp_order_sends ADD COLUMN IF NOT EXISTS recipient_key UUID;
ALTER TABLE whatsapp_order_sends DROP CONSTRAINT IF EXISTS fk_whatsapp_order_sends_recipient;
ALTER TABLE whatsapp_order_sends ADD CONSTRAINT fk_whatsapp_order_sends_recipient
  FOREIGN KEY (recipient_key) REFERENCES whatsapp_order_send_employees(recipient_key) ON DELETE RESTRICT;
ALTER TABLE whatsapp_order_sends ADD COLUMN IF NOT EXISTS employee_id BIGINT;
ALTER TABLE whatsapp_order_sends ADD COLUMN IF NOT EXISTS employee_contact_id BIGINT;
ALTER TABLE whatsapp_order_sends ADD COLUMN IF NOT EXISTS recipient_fingerprint TEXT
  CHECK (recipient_fingerprint IS NULL OR recipient_fingerprint ~ '^[0-9a-f]{64}$');
ALTER TABLE whatsapp_order_sends DROP CONSTRAINT IF EXISTS chk_whatsapp_order_sends_target;
ALTER TABLE whatsapp_order_sends ADD CONSTRAINT chk_whatsapp_order_sends_target CHECK (
  (target_kind = 'chat' AND chat_key IS NOT NULL AND phone_normalized IS NULL AND recipient_key IS NULL AND employee_id IS NULL)
  OR (target_kind = 'client' AND chat_key IS NULL AND recipient_key IS NULL AND employee_id IS NULL)
  OR (target_kind = 'employee' AND chat_key IS NULL AND recipient_key IS NOT NULL AND employee_id IS NOT NULL
      AND recipient_fingerprint IS NOT NULL));
CREATE INDEX IF NOT EXISTS idx_whatsapp_order_sends_employee_identity
  ON whatsapp_order_sends (order_id, form_code, recipient_fingerprint) WHERE recipient_fingerprint IS NOT NULL;

COMMIT;
