-- Контакты поставщиков, производителей и клиентов (телефоны, email, Telegram; один основной на вид).
-- Additive. The previous backend ignores these tables and columns.
BEGIN;

-- Runs while the backend works. The owner tables are NOT altered (clients has a CRM-sync trigger on every
-- update, and its rows are hot): only new tables are created. Adding a foreign key needs a short
-- SHARE ROW EXCLUSIVE lock on the referenced table — taken up front with NOWAIT, so the migration never waits
-- while holding one of them; a table in use makes it fail at once without changes — run it again.
SET LOCAL lock_timeout = '5s';
LOCK TABLE suppliers, vendors, clients IN SHARE ROW EXCLUSIVE MODE NOWAIT;

-- Version of the whole contact set of an owner, kept apart from the owner row: bumping it must not touch
-- suppliers/vendors/clients (updated_at, edited_by, the CRM-sync trigger of clients). No row = version 0.
-- The command serializes on the owner row (FOR NO KEY UPDATE) and then compares and bumps this version.
-- For a client it covers emails and Telegram accounts only: client phones stay in client_phones.
CREATE TABLE IF NOT EXISTS party_contact_versions (
  party_kind TEXT NOT NULL CHECK (party_kind IN ('supplier','vendor','client')),
  party_id BIGINT NOT NULL,
  version INTEGER NOT NULL CHECK (version > 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (party_kind, party_id)
);

-- Changed only through the backend command (version compare-and-swap + audit); RESTRICT keeps a direct delete
-- of the owner from dropping its contacts. Named FKs are re-created on every run (a rerun repairs the schema).
CREATE TABLE IF NOT EXISTS supplier_contacts (
  contact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_id SMALLINT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('phone','email','telegram')),
  value TEXT NOT NULL CHECK (char_length(btrim(value)) BETWEEN 1 AND 200),
  value_normalized TEXT NOT NULL CHECK (
    (kind = 'phone' AND value_normalized ~ '^7[0-9]{10}$')
    OR (kind = 'email' AND value_normalized ~ '^[^@[:space:]]+@[^@[:space:]]+$' AND value_normalized = lower(value_normalized))
    OR (kind = 'telegram' AND value_normalized ~ '^[a-z0-9_]{5,32}$')),
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  note TEXT CHECK (note IS NULL OR char_length(note) <= 200),
  position SMALLINT NOT NULL DEFAULT 0 CHECK (position BETWEEN 0 AND 99),
  created_by BIGINT,
  updated_by BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE supplier_contacts DROP CONSTRAINT IF EXISTS fk_supplier_contacts_owner;
ALTER TABLE supplier_contacts ADD CONSTRAINT fk_supplier_contacts_owner
  FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id) ON DELETE RESTRICT;
CREATE UNIQUE INDEX IF NOT EXISTS uq_supplier_contacts_primary ON supplier_contacts (supplier_id, kind) WHERE is_primary;
CREATE UNIQUE INDEX IF NOT EXISTS uq_supplier_contacts_value ON supplier_contacts (supplier_id, kind, value_normalized);

CREATE TABLE IF NOT EXISTS vendor_contacts (
  contact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_id SMALLINT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('phone','email','telegram')),
  value TEXT NOT NULL CHECK (char_length(btrim(value)) BETWEEN 1 AND 200),
  value_normalized TEXT NOT NULL CHECK (
    (kind = 'phone' AND value_normalized ~ '^7[0-9]{10}$')
    OR (kind = 'email' AND value_normalized ~ '^[^@[:space:]]+@[^@[:space:]]+$' AND value_normalized = lower(value_normalized))
    OR (kind = 'telegram' AND value_normalized ~ '^[a-z0-9_]{5,32}$')),
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  note TEXT CHECK (note IS NULL OR char_length(note) <= 200),
  position SMALLINT NOT NULL DEFAULT 0 CHECK (position BETWEEN 0 AND 99),
  created_by BIGINT,
  updated_by BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE vendor_contacts DROP CONSTRAINT IF EXISTS fk_vendor_contacts_owner;
ALTER TABLE vendor_contacts ADD CONSTRAINT fk_vendor_contacts_owner
  FOREIGN KEY (vendor_id) REFERENCES vendors(vendor_id) ON DELETE RESTRICT;
CREATE UNIQUE INDEX IF NOT EXISTS uq_vendor_contacts_primary ON vendor_contacts (vendor_id, kind) WHERE is_primary;
CREATE UNIQUE INDEX IF NOT EXISTS uq_vendor_contacts_value ON vendor_contacts (vendor_id, kind, value_normalized);

-- A client's phones are client_phones (export, CRM and 1C read them): only emails and Telegram accounts here.
CREATE TABLE IF NOT EXISTS client_contacts (
  contact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('email','telegram')),
  value TEXT NOT NULL CHECK (char_length(btrim(value)) BETWEEN 1 AND 200),
  value_normalized TEXT NOT NULL CHECK (
    (kind = 'email' AND value_normalized ~ '^[^@[:space:]]+@[^@[:space:]]+$' AND value_normalized = lower(value_normalized))
    OR (kind = 'telegram' AND value_normalized ~ '^[a-z0-9_]{5,32}$')),
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  note TEXT CHECK (note IS NULL OR char_length(note) <= 200),
  position SMALLINT NOT NULL DEFAULT 0 CHECK (position BETWEEN 0 AND 99),
  created_by BIGINT,
  updated_by BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE client_contacts DROP CONSTRAINT IF EXISTS fk_client_contacts_owner;
ALTER TABLE client_contacts ADD CONSTRAINT fk_client_contacts_owner
  FOREIGN KEY (client_id) REFERENCES clients(client_id) ON DELETE RESTRICT;
CREATE UNIQUE INDEX IF NOT EXISTS uq_client_contacts_primary ON client_contacts (client_id, kind) WHERE is_primary;
CREATE UNIQUE INDEX IF NOT EXISTS uq_client_contacts_value ON client_contacts (client_id, kind, value_normalized);

-- The old single «Телефон» of a supplier becomes its primary phone contact when the backend would read it as a
-- number: the same pattern as normalizeClientPhone (order-send-phone.ts) — +7/8, formatting, an extension or a
-- second number after a separator — so every copied value can be saved again by the contacts command. The
-- column stays; anything else stays only there. A supplier whose set the command has already saved (it has a
-- version row) is never backfilled again: a rerun must not bring back a contact the user removed.
INSERT INTO supplier_contacts (supplier_id, kind, value, value_normalized, is_primary, position)
SELECT s.supplier_id, 'phone', btrim(s.phone), '7' || m.parts[1] || m.parts[2] || m.parts[3] || m.parts[4], TRUE, 0
  FROM suppliers s
  CROSS JOIN LATERAL (SELECT regexp_match(s.phone,
    '^\s*\+?[78][\s()-]*(\d{3})[\s()-]*(\d{3})[\s-]*(\d{2})[\s-]*(\d{2})(?:\s*(?:[-,;/]|доб\.?|вн\.?)\s*.*)?\s*$', 'i') AS parts) m
 WHERE m.parts IS NOT NULL AND char_length(btrim(s.phone)) <= 200
   AND NOT EXISTS (SELECT 1 FROM supplier_contacts c WHERE c.supplier_id = s.supplier_id)
   AND NOT EXISTS (SELECT 1 FROM party_contact_versions v WHERE v.party_kind = 'supplier' AND v.party_id = s.supplier_id);

COMMIT;
