import React from 'react';
import {
  AimOutlined,
  ApartmentOutlined,
  AppstoreOutlined,
  ArrowsAltOutlined,
  AuditOutlined,
  BarChartOutlined,
  BorderOutlined,
  CalculatorOutlined,
  CalendarOutlined,
  CheckCircleOutlined,
  CheckSquareOutlined,
  CreditCardOutlined,
  DeleteOutlined,
  DollarCircleOutlined,
  DollarOutlined,
  EnvironmentOutlined,
  FileImageOutlined,
  FileSearchOutlined,
  FileTextOutlined,
  HomeOutlined,
  IdcardOutlined,
  InboxOutlined,
  LayoutOutlined,
  ProjectOutlined,
  QrcodeOutlined,
  ScissorOutlined,
  SettingOutlined,
  ShopOutlined,
  ShoppingCartOutlined,
  SwapOutlined,
  SyncOutlined,
  TagsOutlined,
  TableOutlined,
  ToolOutlined,
  TransactionOutlined,
  UserOutlined,
  WalletOutlined,
} from '@ant-design/icons';

/** Shared semantic icons for every resource that can appear in desktop/mobile navigation. */
export const SIDER_RESOURCE_ICONS: Record<string, React.ReactNode> = {
  orders_view: <FileTextOutlined />,
  calendar: <CalendarOutlined />,
  'order-status-board': <LayoutOutlined />,
  'mdf-work-board': <TableOutlined />,
  scan: <QrcodeOutlined />,
  'orders-trash': <DeleteOutlined />,
  groups: <ProjectOutlined />,
  projects: <ProjectOutlined />,
  'cut-jobs': <ScissorOutlined />,
  'bazis-cut-sets': <TableOutlined />,
  bazis: <FileSearchOutlined />,
  clients: <UserOutlined />,
  clients_analytics_view: <BarChartOutlined />,
  suppliers: <ShopOutlined />,
  vendors: <ShopOutlined />,
  film_vendors: <ShopOutlined />,
  payments: <DollarOutlined />,
  payments_view: <WalletOutlined />,
  films: <FileImageOutlined />,
  materials: <InboxOutlined />,
  order_resource_requirements: <ShoppingCartOutlined />,
  film_types: <TagsOutlined />,
  units: <CalculatorOutlined />,
  material_types: <AppstoreOutlined />,
  edge_types: <BorderOutlined />,
  milling_types: <ToolOutlined />,
  extra_resources: <ToolOutlined />,
  order_statuses: <CheckCircleOutlined />,
  payment_statuses: <DollarCircleOutlined />,
  production_statuses: <SyncOutlined />,
  requisition_statuses: <FileSearchOutlined />,
  resource_requirements_statuses: <CheckSquareOutlined />,
  workshops: <HomeOutlined />,
  work_centers: <ApartmentOutlined />,
  payment_types: <CreditCardOutlined />,
  transaction_direction: <SwapOutlined />,
  material_transaction_types: <TransactionOutlined />,
  employees: <IdcardOutlined />,
  users: <UserOutlined />,
  movements_statuses: <ArrowsAltOutlined />,
  order_workshops: <EnvironmentOutlined />,
  doweling_orders_view: <AimOutlined />,
  configuration: <SettingOutlined />,
  audit: <AuditOutlined />,
  sheet_material_types: <BorderOutlined />,
};
