// One catalog for readable journals and filters. Values sent to the API stay unchanged.
export const AUDIT_EVENT_TITLES: Record<string, string> = {
  'bitrix24.payment_system_catalog_refreshed': 'Обновлён справочник платёжных систем Bitrix24',
  'bitrix24.user_mapping_upserted': 'Сохранено соответствие пользователя Bitrix24',
  'bitrix24.widget.installation_promoted': 'Активирована установка виджета Bitrix24',
  'bitrix24.widget_payment.ambiguity_resolved': 'Разрешена неоднозначность платежа Bitrix24',
  'bitrix24.widget_payment.command_started': 'Начата регистрация платежа виджета Bitrix24',
  'bitrix24.widget_payment.failed': 'Ошибка платежа виджета Bitrix24',
  'bitrix24.widget_payment.materialized': 'Сохранён платёж виджета Bitrix24 в ERP',
  'bitrix24.widget_payment.remote_created': 'Создан платёж виджета в Bitrix24',
  'bitrix24_reverse.client_archive': 'Архивирован клиент из Bitrix24',
  'bitrix24_reverse.client_upsert': 'Синхронизирован клиент из Bitrix24',
  'bitrix24_reverse.deal_state_upsert': 'Синхронизировано состояние сделки Bitrix24',
  'bitrix24_reverse.incoming_request_upsert': 'Синхронизирована входящая заявка Bitrix24',
  'bitrix24_reverse.installation_saved': 'Сохранена установка интеграции Bitrix24',
  'bitrix24_reverse.mapped_order_payments_materialize': 'Перенесены платежи связанного заказа Bitrix24',
  'bitrix24_reverse.order_payments_reconcile': 'Сверены платежи заказа с Bitrix24',
  'bitrix24_reverse.payment_type_mapping_upsert': 'Сохранено соответствие типа платежа Bitrix24',
  'bitrix24_reverse.payments_materialize': 'Перенесены платежи Bitrix24 в ERP',
  'bitrix24_reverse.request_payments_reconcile': 'Сверены платежи заявки с Bitrix24',
  'bitrix24_reverse.retry_failed': 'Повторная обработка ошибок синхронизации Bitrix24',
  'permissions.roles_matrix.reset': 'Сброшена матрица прав ролей',
  'permissions.roles_matrix.update': 'Изменена матрица прав ролей',
  'doweling.created': 'Создано задание на присадку',
  'orders.status_board.read': 'Просмотрена доска статусов заказов',
  'vlm.analyze': 'Выполнен анализ документа',
  'vlm.upload': 'Загружен документ для распознавания',
  'export_template.created': 'Создан шаблон экспорта',
  'export_template.updated': 'Изменён шаблон экспорта',
  'export_template.deleted': 'Удалён шаблон экспорта',
  'export_template.permission_denied': 'Отказано в изменении шаблона экспорта',
  'label_template.created': 'Создан шаблон бирок',
  'label_template.updated': 'Изменён шаблон бирок',
  'label_template.deleted': 'Удалён шаблон бирок',
  'label_template.permission_denied': 'Отказано в изменении шаблона бирок',
  'label_qr_template.created': 'Создан QR-шаблон бирок',
  'label_qr_template.updated': 'Изменён QR-шаблон бирок',
  'label_qr_template.deleted': 'Удалён QR-шаблон бирок',
  'label_qr_template.permission_denied': 'Отказано в изменении QR-шаблона бирок',
  'label_ocr_template.created': 'Создан OCR-шаблон бирок',
  'label_ocr_template.updated': 'Изменён OCR-шаблон бирок',
  'label_ocr_template.deleted': 'Удалён OCR-шаблон бирок',
  'label_ocr_template.permission_denied': 'Отказано в изменении OCR-шаблона бирок',
  'export_template.default_changed': 'Изменён шаблон экспорта по умолчанию',
  'bazis.pdf_table_pattern.create': 'Создан шаблон PDF-таблицы БАЗИС',
  'bazis.pdf_table_pattern.update': 'Изменён шаблон PDF-таблицы БАЗИС',
  'bazis_pdf_table_pattern.permission_denied': 'Отказано в изменении шаблона PDF-таблицы БАЗИС',
  'groups.create': 'Создана группа',
  'groups.update': 'Изменена группа',
  'groups.archive': 'Архивирована группа',
  'groups.entity_links_changed': 'Изменены связи объектов группы',
  'groups.order_links_changed': 'Изменены связи заказов группы',
  'groups.members_changed': 'Изменён состав группы',
  'groups.participants_changed': 'Изменены участники группы',
  'group_batch_link.role_denied': 'Отказано в массовом связывании группы',
  'notification.rule_created': 'Создано правило уведомлений',
  'notification.rule_updated': 'Изменено правило уведомлений',
  'notification.rule_deleted': 'Удалено правило уведомлений',
  'notification.rule_create_denied': 'Отказано в создании правила уведомлений',
  'notification.rule_update_denied': 'Отказано в изменении правила уведомлений',
  'notification.rule_delete_denied': 'Отказано в удалении правила уведомлений',
  'notification.telegram_link_started': 'Начата привязка Telegram для уведомлений',
  'notification.telegram_linked': 'Привязан Telegram для уведомлений',
  'notification.telegram_unlinked': 'Отвязан Telegram для уведомлений',
  'deadlines.policy.created': 'Создана политика дедлайнов',
  'deadlines.policy.updated': 'Изменена политика дедлайнов',
  'deadlines.settings.updated': 'Изменены настройки дедлайнов',
  'deadline.default_schedule.updated': 'Изменено расписание дедлайнов по умолчанию',
  'deadline.order_sync_requested': 'Запрошена синхронизация дедлайнов заказа',
  'cad.mapping.updated': 'Изменены соответствия CAD',
  'cad.package.completed': 'Сформирован пакет CAD',
  'cad.package.failed': 'Ошибка формирования пакета CAD',
  'cad.package.requested': 'Запрошено формирование пакета CAD',
  'cad.render.completed': 'Завершена визуализация CAD',
  'cad.render.failed': 'Ошибка визуализации CAD',
  'cad.render.requested': 'Запрошена визуализация CAD',
  'cad.source.captured': 'Сохранён оригинал CAD',
  'cad.variant.created': 'Создана рабочая версия CAD',
  'cad.variant.refreshed': 'Обновлена рабочая версия CAD',
  'cad.variant.saved': 'Сохранена рабочая версия CAD',
  'cad.workspace.created': 'Создано рабочее пространство CAD',
  'ORG_DIRECTION_CREATED': 'Создано направление',
  'ORG_DIRECTION_UPDATED': 'Изменено направление',
  'ORG_DIRECTION_DEACTIVATED': 'Деактивировано направление',
  'ORG_DIRECTION_DELETED': 'Удалено направление',
  'ORG_DIRECTION_MEMBERSHIP_REPLACED': 'Изменён состав направления',
  'ORG_DIRECTION_HEAD_ADDED': 'Назначен руководитель направления',
  'ORG_DIRECTION_HEAD_REMOVED': 'Снят руководитель направления',
  'ORG_WORKSHOP_HEAD_ADDED': 'Назначен руководитель цеха',
  'ORG_WORKSHOP_HEAD_REMOVED': 'Снят руководитель цеха',
  'DEADLINE_TRANSITION_RULE_CREATED': 'Создано правило перехода дедлайна',
  'DEADLINE_TRANSITION_RULE_UPDATED': 'Изменено правило перехода дедлайна',
  'DEADLINE_TRANSITION_RULE_DELETED': 'Удалено правило перехода дедлайна',
  'deadline.timer_rule_created': 'Создано правило таймера дедлайна',
  'deadline.timer_rule_updated': 'Изменено правило таймера дедлайна',
  'deadline.timer_rule_removed': 'Удалено правило таймера дедлайна',
  'deadline.timer_rule_enabled': 'Включено правило таймера дедлайна',
  'deadline.timer_rule_disabled': 'Отключено правило таймера дедлайна',
  'deadline.action_rule_created': 'Создано правило действия дедлайна',
  'deadline.action_rule_updated': 'Изменено правило действия дедлайна',
  'deadline.action_rule_removed': 'Удалено правило действия дедлайна',
  'deadline.action_rule_enabled': 'Включено правило действия дедлайна',
  'deadline.action_rule_disabled': 'Отключено правило действия дедлайна',
  'deadline.order_override_created': 'Создано исключение дедлайна заказа',
  'deadline.order_override_updated': 'Изменено исключение дедлайна заказа',
  'deadline.order_override_removed': 'Удалено исключение дедлайна заказа',
  'deadline.order_override_enabled': 'Включено исключение дедлайна заказа',
  'deadline.order_override_disabled': 'Отключено исключение дедлайна заказа',
  'deadlines.deadline_created': 'Создан дедлайн',
  'deadlines.deadline_updated': 'Изменён дедлайн',
  'deadlines.deadline_upcoming': 'Приближается дедлайн',
  'deadlines.deadline_expired': 'Истёк дедлайн',
  'deadlines.deadline_completed_on_time': 'Дедлайн выполнен вовремя',
  'deadlines.deadline_completed_late': 'Дедлайн выполнен с опозданием',
  'deadlines.deadline_paused': 'Приостановлен дедлайн',
  'deadlines.deadline_resumed': 'Возобновлён дедлайн',
  'deadlines.deadline_cancelled': 'Отменён дедлайн',
  'deadlines.deadline_escalated': 'Эскалирован дедлайн',
  'deadlines.order_final_deadline_expired': 'Истёк конечный срок заказа',
  'deadlines.order_stage_deadline_expired': 'Истёк срок этапа заказа',
  'deadlines.client_action_deadline_expired': 'Истёк срок действия клиента',
  'cut_job.deleted': 'Удалено задание на раскрой',
  'cut_job.archived': 'Архивировано задание на раскрой',
  'cut_job.created': 'Создано задание на раскрой',
  'cut_job.calculated': 'Рассчитано задание на раскрой',
  'cut_job.calculate_failed': 'Ошибка расчёта задания на раскрой',
  'cut_job.item_added': 'Добавлены детали в задание на раскрой',
  'cut_job.item_removed': 'Удалена деталь из задания на раскрой',
  'cut_job.name_changed': 'Изменено название задания на раскрой',
  'cut_job.profile_changed': 'Изменён профиль задания на раскрой',
  'cut_job.combine_films_changed': 'Изменено объединение плёнок задания на раскрой',
  'cut_job.split_by_material_changed': 'Изменено разделение задания по материалам',
  'cut_job.rotation_allowed_changed': 'Изменено разрешение поворота деталей раскроя',
  'cut_job.texture_direction_changed': 'Изменено направление текстуры задания на раскрой',
  'cut_job.sheet_material_changed': 'Изменён листовой материал задания на раскрой',
  'cut_job.manual_layout_saved': 'Сохранена ручная раскладка задания на раскрой',
  'cut_job.current_result_changed': 'Изменён текущий результат задания на раскрой',
  'cut_job.result_archived': 'Архивирован результат задания на раскрой',
  'cut_job.result_unarchived': 'Восстановлен результат задания на раскрой из архива',
  'cut_job.permission_denied': 'Отказано в доступе к заданию на раскрой',
  'cut_job.mdf_bath_card.auto_created': 'Автоматически создана карточка ванн раскроя',
  'cut_job.mdf_bath_card.auto_create_failed': 'Ошибка автоматического создания карточки ванн раскроя',
  'cut_job.mdf_bath_card.created': 'Создана карточка МДФ по заданию на раскрой',
  'cut_job.mdf_bath_card.hidden': 'Скрыта карточка ванн раскроя',
  'cut_job.mdf_bath_card.restored': 'Восстановлена карточка ванн раскроя',
  'cut_config.param_profile_upserted': 'Сохранён профиль параметров раскроя',
  'cut_config.param_profile_deleted': 'Удалён профиль параметров раскроя',
  'cut_config.pdf_template_updated': 'Изменён PDF-шаблон раскроя',
  'cut_config.setting_updated': 'Изменена настройка раскроя',
  'cut_config.render_preset_upserted': 'Сохранён профиль отображения раскроя',
  'cut_config.render_preset_deleted': 'Удалён профиль отображения раскроя',
  'cut_config.permission_denied': 'Отказано в настройке раскроя',
  'auth.identity.linked': 'Привязана внешняя учётная запись',
  'auth.identity.unlinked': 'Отвязана внешняя учётная запись',
  'auth.identity.link_failed': 'Ошибка привязки внешней учётной записи',
  'auth.identity.settings_updated': 'Изменены настройки внешнего входа',
  'auth.identity.settings_read_denied': 'Отказано в чтении настроек внешнего входа',
  'auth.identity.settings_update_denied': 'Отказано в изменении настроек внешнего входа',
  'auth.identity.list_denied': 'Отказано в просмотре внешних учётных записей',
  'auth.identity.unlink_denied': 'Отказано в отвязке внешней учётной записи',
  'auth.identity.invitation_created': 'Создано приглашение внешнего входа',
  'auth.identity.invitation_revoked': 'Отозвано приглашение внешнего входа',
  'auth.identity.invitation_create_denied': 'Отказано в создании приглашения внешнего входа',
  'auth.identity.invitation_revoke_denied': 'Отказано в отзыве приглашения внешнего входа',
  'auth.login.failed': 'Неудачная попытка входа',
  'auth.login.success': 'Выполнен вход',
  'auth.logout': 'Выполнен выход',
  'auth.refresh': 'Обновлена сессия',
  'auth.refresh.reuse_detected': 'Обнаружено повторное использование токена обновления',
  'users.create': 'Создан пользователь',
  'users.update': 'Изменён пользователь',
  'users.activate': 'Активирован пользователь',
  'users.deactivate': 'Деактивирован пользователь',
  'users.change_password': 'Изменён пароль пользователя',
  'users.change_password.rollback': 'Отменено изменение пароля пользователя',
  'user.permission_denied': 'Отказано в действии с пользователем',
  'bazis.material_mapping_set': 'Настроено соответствие материала БАЗИС',
  'bazis.order_created': 'Создан заказ из БАЗИС',
  'bazis.order_details_added': 'Добавлены детали БАЗИС в заказ',
  'bazis.project_created': 'Создан проект БАЗИС',
  'bazis.project_deleted': 'Удалён проект БАЗИС',
  'bazis.project_renamed': 'Переименован проект БАЗИС',
  'bazis.project_design_engineer_changed': 'Изменён конструктор проекта БАЗИС',
  'bazis.revision_imported': 'Импортирована редакция БАЗИС',
  'bazis.revision_pruned': 'Удалена старая редакция БАЗИС',
  'bazis.cut_xls_exported': 'Экспортирован раскрой БАЗИС в Excel',
  'bazis.node_notes_changed': 'Изменены примечания узла БАЗИС',
  'bazis.panel_order_links_reconciled': 'Сверены связи панелей БАЗИС с заказами',
  'bazis.permission_denied': 'Отказано в действии БАЗИС',
  'bazis_cut_set.created': 'Создан набор раскроя БАЗИС',
  'bazis_cut_set.deleted': 'Удалён набор раскроя БАЗИС',
  'bazis_cut_set.detail_removed': 'Удалена деталь набора раскроя БАЗИС',
  'bazis_cut_set.detail_updated': 'Изменена деталь набора раскроя БАЗИС',
  'bazis_cut_set.details_added': 'Добавлены детали в набор раскроя БАЗИС',
  'bazis_cut_set.exported': 'Экспортирован набор раскроя БАЗИС',
  'bazis_cut_set.order_scope_denied': 'Отказано в доступе к заказам набора раскроя БАЗИС',
  'bazis_cut_set.permission_denied': 'Отказано в действии с набором раскроя БАЗИС',
  'bazis_cut_set.renamed': 'Переименован набор раскроя БАЗИС',
  'client_phones.primary_demote': 'Снят признак основного телефона клиента',
  'clients.update': 'Изменён клиент',
  'cnc.manual_svg_comment_preset.created': 'Создан шаблон комментария SVG',
  'cnc.manual_svg_comment_preset.create_denied': 'Отказано в создании шаблона комментария SVG',
  'cnc.manual_svg_upload.created': 'Создана ручная загрузка SVG',
  'cnc.manual_svg_upload.denied': 'Отказано в ручной загрузке SVG',
  'cnc.manual_svg_upload.mdf_card_created': 'Создана карточка МДФ из SVG',
  'cnc.manual_svg_upload.telegram_send_claimed': 'Начата отправка файлов раскроя в Telegram',
  'cnc.telegram_import.item_claimed': 'Начат импорт файла из Telegram',
  'cnc.telegram_import.item_imported': 'Импортирован файл из Telegram',
  'cnc.telegram_import.item_failed': 'Ошибка импорта файла из Telegram',
  'cnc.telegram_import.scan_claimed': 'Начат поиск файлов в Telegram',
  'cnc.telegram_import.scan_completed': 'Завершён поиск файлов в Telegram',
  'cnc.telegram_import.scan_failed': 'Ошибка поиска файлов в Telegram',
  'cnc.telegram_import.scan_requested': 'Запрошен поиск файлов в Telegram',
  'cnc.telegram_import.selection_confirmed': 'Подтверждён выбор файлов Telegram',
  'cnc.telegram_import.selection_prepared': 'Подготовлен выбор файлов Telegram',
  'cnc.telegram_import.confirmation_required': 'Требуется подтверждение импорта из Telegram',
  'cnc.telegram_import.draft_replaced': 'Заменён черновик импорта из Telegram',
  'cnc.telegram_import.duplicate_acknowledged': 'Подтверждён дубликат импорта из Telegram',
  'cnc.telegram_packet.auto_cut_status_applied': 'Применён автостатус распила пакета Telegram',
  'cnc.telegram_packet.auto_cut_status_configured': 'Настроен автостатус распила пакета Telegram',
  'cnc.telegram_packet.auto_cut_status_configure_denied': 'Отказано в настройке автостатуса пакета Telegram',
  'cnc.telegram_packet.ingested': 'Принят пакет Telegram',
  'cnc.telegram_packet.ingest_denied': 'Отказано в приёме пакета Telegram',
  'cnc.telegram_packet.completed': 'Завершена обработка пакета Telegram',
  'cnc.telegram_media.restore_requested': 'Запрошено восстановление медиа Telegram',
  'cnc.telegram_media.restore_completed': 'Восстановлены медиа Telegram',
  'cnc.telegram_media.restore_failed': 'Ошибка восстановления медиа Telegram',
  'cnc.telegram_worker.audit_write_denied': 'Отказано в записи аудита Telegram-бота',
  'cnc_telegram.item_evidence_persisted': 'Сохранены данные обработки файла Telegram',
  'cnc_telegram.label_map_projected': 'Обновлено соответствие бирок Telegram',
  'crm_sync.failed': 'Ошибка синхронизации CRM',
  'crm_sync.upsert': 'Синхронизирована запись CRM',
  'crm_sync.delete': 'Удалена синхронизированная запись CRM',
  'crm_sync.remote_deleted_skipped': 'Пропущена удалённая запись CRM',
  'detail_labels.generated': 'Сформированы бирки деталей',
  'order_labels.generated': 'Сформированы бирки заказа',
  'order_labels.permission_denied': 'Отказано в формировании бирок заказа',
  'order_label_data.updated': 'Изменены данные бирок заказа',
  'mdf_board.manual_move.created': 'Создан ручной перенос карточки МДФ',
  'mdf_board.manual_move.updated': 'Изменён ручной перенос карточки МДФ',
  'mdf_board.manual_move.deleted': 'Удалён ручной перенос карточки МДФ',
  'orders.calendar_move': 'Перенесён заказ в календаре',
  'orders.export': 'Экспортирован заказ',
  'orders.export.requested': 'Запрошен экспорт заказа',
  'orders.hdf_reconciled': 'Пересчитаны детали ХДФ заказа',
  'orders.hdf_detail_production_status_change': 'Изменён производственный статус детали ХДФ',
  'orders.snapshot_export': 'Экспортирован снимок заказа',
  'orders.snapshot_import': 'Импортирован снимок заказа',
  'orders.snapshot_import.noop': 'Снимок заказа импортирован без изменений',
  'orders.snapshot_import.skipped': 'Пропущен импорт снимка заказа',
  'orders.payment_status_change': 'Изменён статус оплаты заказа',
  'orders.production_initialized': 'Инициализировано производство заказа',
  'orders.details_doweling_auto_set': 'Автоматически назначена присадка деталей заказа',
  'orders.converted_to_production': 'Заявка преобразована в производственный заказ',
  'orders.crm_request_created': 'Создана заявка CRM',
  'orders.crm_request_updated': 'Изменена заявка CRM',
  'orders.crm_request_archived': 'Архивирована заявка CRM',
  'orders.crm_request_restored': 'Восстановлена заявка CRM',
  'orders.crm_request_sync_conflict': 'Обнаружен конфликт синхронизации заявки CRM',
  'payment.permission_denied': 'Отказано в действии с платежом',
  'production.stage_activate': 'Активирован этап производства',
  'production.stage_deactivate': 'Деактивирован этап производства',
  'production.detail_stage_activate': 'Активирован этап производства детали',
  'project.created': 'Создан проект',
  'project.updated': 'Изменён проект',
  'project.archived': 'Архивирован проект',
  'project.merged': 'Объединены проекты',
  'project.order_moved': 'Перенесён заказ между проектами',
  'settings.extra_resource_changed': 'Изменён дополнительный ресурс',
  'settings.extra_resource_created': 'Создан дополнительный ресурс',
  'settings.production_hdf_material_changed': 'Изменён материал ХДФ производства',
  'settings.production_hdf_milling_changed': 'Изменена фрезеровка ХДФ производства',
  'settings.production_hdf_threshold_changed': 'Изменён порог размеров ХДФ производства',
  'sheet_material.created': 'Создан листовой материал',
  'sheet_material.updated': 'Изменён листовой материал',
  'sheet_material.deactivated': 'Деактивирован листовой материал',
  'sheet_material.permission_denied': 'Отказано в действии с листовым материалом',
  'status_automation.rule_created': 'Создано правило автостатусов',
  'status_automation.rule_updated': 'Изменено правило автостатусов',
  'status_automation.rule_deleted': 'Удалено правило автостатусов',
  'status_automation.rule_view_denied': 'Отказано в просмотре правила автостатусов',
  'orders.create': 'Создан заказ',
  'orders.update': 'Обновлён заказ',
  'orders.delete': 'Удалён заказ',
  'orders.restore': 'Восстановлен заказ',
  'orders.detail_transfer': 'Перенесены детали заказа',
  'orders.status_change': 'Изменён статус заказа',
  'orders.production_status_change': 'Изменён производственный статус заказа',
  'orders.detail_production_status_change': 'Изменён производственный статус детали',
  'orders.detail_production_status_batch_change':
    'Изменён производственный статус деталей заказа',
  'orders.production_status_mode_restore': 'Включён авторасчёт производственного статуса',
  'orders.production_status_mode_manual': 'Включён ручной производственный статус',
  'payments.create': 'Добавлен платёж',
  'payments.update': 'Изменён платёж',
  'payments.delete': 'Удалён платёж',
  'client_phones.create': 'Добавлен телефон клиента',
  'client_phones.update': 'Изменён телефон клиента',
  'client_phones.delete': 'Удалён телефон клиента',
  'deadlines.create': 'Создан дедлайн',
  'deadlines.update': 'Изменён дедлайн',
  'deadlines.delete': 'Удалён дедлайн',
  'groups.notification_created': 'Создано уведомление по группе',
  'org.direction_head_added': 'Назначен руководитель направления',
  'org.direction_head_removed': 'Снят руководитель направления',
  'production.action_denied': 'Отказано в производственном действии',
  'cnc.manual_svg_upload.file_uploaded': 'Загружен файл раскроя',
  'cnc.manual_svg_upload.telegram_send_requested': 'Файлы раскроя поставлены в очередь Telegram',
  'cnc.manual_svg_upload.telegram_send_completed': 'Файлы раскроя отправлены в Telegram',
  'cnc.manual_svg_upload.telegram_send_failed': 'Ошибка отправки файлов раскроя в Telegram',
  'cnc.manual_svg_upload.telegram_send_unknown': 'Статус отправки файлов раскроя неизвестен',
  'status_automation.rule_applied': 'Применено правило автостатусов',
  'status_automation.rule_skipped': 'Правило автостатусов не применено',
};

export function auditEventTitle(event: string): string {
  return Object.prototype.hasOwnProperty.call(AUDIT_EVENT_TITLES, event)
    ? AUDIT_EVENT_TITLES[event]
    : `Событие ERP: ${event}`;
}

export function auditEventOptions(events: readonly string[]) {
  return [...new Set(events)]
    .map((value) => ({ value, label: `${auditEventTitle(value)} — ${value}` }))
    .sort((a, b) => auditEventTitle(a.value).localeCompare(auditEventTitle(b.value), 'ru') || a.value.localeCompare(b.value, 'en'));
}
