import { randomBytes } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

// Explicit opt-in. Only a randomly named disposable DB is mutated; no application
// tables, ledger, settings or remote APIs are touched. Requires CREATEDB rights.
const enabled = process.env.ERP_MIGRATION_PROBE_INTEGRATION === 'true';
const container = process.env.PG_CONTAINER || 'erp_test-postgresdb-1';
const db = `e2e_migration_probe_${randomBytes(10).toString('hex')}`;
const script = resolve(__dirname, 'apply-migrations.sh');
const source = readFileSync(script, 'utf8');
const dir = resolve(__dirname, '../backend/db/migrations');
const files = readdirSync(dir).filter((f) => /^16[4-9]_.*\.sql$/.test(f)
  || ['174_mdf_execution_context.sql','175_mdf_command_placement.sql','177_cut_result_typed_hdf.sql',
    '178_mdf_correction_receipts.sql','179_mdf_active_return.sql','180_mdf_cnc_observations.sql',
    '181_cnc_manual_send_observation.sql','182_mdf_physical_lineage.sql',
    '185_mdf_bazis_composition.sql','187_mdf_bazis_refill_rows.sql','188_mdf_order_cascade_intents.sql'].includes(f)).sort();
const helpers = source.slice(source.indexOf('q_col()'), source.indexOf('# These migrations contain conditional'));
const queries = (file: string) => execFileSync('bash', ['-s', '--', file], {
  input: `${helpers}\nprobe_all() { printf '%s\\n' "$@"; }\nprobe_file "$1"`, encoding: 'utf8',
});
function sql(query: string, database = db) {
  return execFileSync('docker', ['exec', '-i', container, 'sh', '-lc',
    'exec psql -U "$POSTGRES_USER" -d "$1" -X -qAt -v ON_ERROR_STOP=1', 'probe-test', database],
  { input: query, encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'], timeout: 30000 });
}
const present = (file: string, mutation = '') => {
  const out = sql(`BEGIN; SET LOCAL statement_timeout='10s'; SET LOCAL lock_timeout='1s'; ${mutation}\n${queries(file)}\nROLLBACK;`);
  const values = out.trim().split('\n');
  expect(values.length).toBeGreaterThan(0);
  return values.every((v) => v === 't');
};
const fileFor = (version: number) => files.find((f) => f.startsWith(`${version}_`))!;

describe.skipIf(!enabled)('migration runner effect probes against actual SQL on isolated PostgreSQL', () => {
  let created = false;
  beforeAll(() => {
    sql(`CREATE DATABASE ${db} TEMPLATE template0;`, 'postgres');
    created = true;
    // Minimal pre-existing dependencies. New objects are created ONLY by the
    // committed migration SQL, not by a duplicated test schema.
    sql(`CREATE TABLE projects(code text);
      CREATE TABLE group_groups(code text);
      CREATE TABLE cnc_telegram_packet_whole_order_keys(order_key text);
      CREATE TABLE cnc_telegram_packets(packet_id uuid PRIMARY KEY);
      CREATE TABLE cnc_telegram_import_candidates(candidate_id uuid PRIMARY KEY);
      CREATE TABLE cnc_telegram_import_items(import_item_id uuid PRIMARY KEY);
      CREATE TABLE cnc_manual_svg_telegram_send_requests(request_id uuid PRIMARY KEY);
      CREATE TABLE cnc_manual_svg_telegram_send_request_files(request_id uuid NOT NULL,file_id uuid NOT NULL,send_order integer NOT NULL,PRIMARY KEY(request_id,file_id));
      CREATE TABLE cnc_manual_svg_upload_files(file_id uuid PRIMARY KEY);
      CREATE TABLE users(user_id bigint PRIMARY KEY);
      CREATE TABLE order_statuses(order_status_id smallint PRIMARY KEY);
      CREATE TABLE bitrix24_app_installation(member_id text PRIMARY KEY);
      CREATE TABLE orders(order_id bigint PRIMARY KEY,order_status_id smallint,edited_by bigint,order_kind text,delete_flag boolean);
      CREATE TABLE crm_sync_mapping(entity_type text,bitrix_object text,bitrix_id text,status text,erp_id text);`);
    sql(`CREATE TABLE bazis_cut_sets(set_id bigint PRIMARY KEY);
      CREATE TABLE bazis_cut_set_details(detail_id bigint PRIMARY KEY);`);
    sql(`CREATE TABLE cut_job(cut_job_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name text);
      CREATE TABLE order_label_generations(order_label_generation_id bigint PRIMARY KEY);
      CREATE TABLE label_template_elements(kind text);`);
    for(const f of ['079_cut_result_history_expand.sql','080_cut_result_history_finalize.sql','081_label_cut_maps.sql',
      '085_cut_result_manual_revisions.sql','121_cut_result_informational_snapshots.sql','122_cut_result_informational_label_maps.sql',
      '153_svg_partial_label_maps.sql','154_svg_source_instance_sequences.sql']) sql(readFileSync(resolve(dir,f),'utf8'));
    for (const f of files) {
      if (f === '181_cnc_manual_send_observation.sql') {
        // Migration 181 extends (rather than invalidates) the 180 CNC probe.
        // Assert that the actual 180 end-state remains recognized before applying
        // the successor, then the ordinary per-file tests cover it afterwards.
        const before181 = sql(queries('180_mdf_cnc_observations.sql'));
        expect(before181.trim().split('\n').every((value) => value === 't')).toBe(true);
      }
      sql(readFileSync(resolve(dir, f), 'utf8'));
    }
  }, 60000);
  afterAll(() => {
    if (created) sql(`DROP DATABASE ${db};`, 'postgres');
  });

  it.each(files)('%s: complete effect is PRESENT', (f) => {
    const probeSql = queries(f).trim().split('\n');
    const out = sql(`BEGIN; SET LOCAL statement_timeout='10s'; SET LOCAL lock_timeout='1s'; ${probeSql.join(';\n')}; ROLLBACK;`);
    const values = out.trim().split('\n');
    const falseChecks = values.flatMap((value, index) => value === 't' ? [] : [`${index + 1}: ${probeSql[index]}`]);
    const indexFacts = f.startsWith('181_') && falseChecks.length ? sql(`SELECT tablename||' '||md5(string_agg(indexname||'|'||indexdef, ', ' ORDER BY indexname))||E'\\n'||string_agg(indexname||'|'||indexdef,E'\\n' ORDER BY indexname) FROM pg_indexes WHERE schemaname='public' AND tablename IN ('cnc_manual_svg_observation_claim_snapshots','cnc_manual_svg_observation_send_bindings','cnc_manual_svg_observation_registration_work','mdf_cnc_observation_targets') GROUP BY tablename ORDER BY tablename;`) : '';
    expect(falseChecks, `failed end-state checks for ${f}${indexFacts ? `\nactual index facts:\n${indexFacts}` : ''}`).toEqual([]);
  });

  it.each(files)('%s: real runner probe uses the same read-only checks', (f) => {
    const out = execFileSync('bash', [script, 'probe', f, '--container', container, '--db', db],
      { encoding: 'utf8', timeout: 60000 });
    expect(out).toContain(`${f} PRESENT`);
  }, 60000);

  it.each([
    [164, "ALTER TABLE projects DROP CONSTRAINT chk_projects_code; ALTER TABLE projects ADD CONSTRAINT chk_projects_code CHECK(code ~ '^[A-Za-z0-9-]{1,20}$');"],
    [164, "ALTER TABLE group_groups DROP CONSTRAINT chk_group_groups_code_format; ALTER TABLE group_groups ADD CONSTRAINT chk_group_groups_code_format CHECK(code ~ '^[[:alnum:]][[:alnum:]_-]{1,63}$') NOT VALID;"],
    [165, 'ALTER TABLE mdf_evidence_lines ALTER COLUMN quantity DROP NOT NULL;'],
    [165, 'ALTER TABLE mdf_source_heads DROP CONSTRAINT mdf_source_heads_source_kind_source_id_accepted_revision_k_fkey;'],
    [165, 'DROP INDEX idx_mdf_allocation_supply;'],
    [165, 'ALTER TABLE mdf_evidence_lines DISABLE TRIGGER mdf_line_immutable;'],
    [165, 'CREATE OR REPLACE FUNCTION mdf_guard_allocation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;'],
    [166, 'ALTER TABLE mdf_source_heads DISABLE TRIGGER mdf_source_fence_guard;'],
    [166, 'CREATE OR REPLACE FUNCTION mdf_guard_published_fence() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;'],
    [167, 'ALTER TABLE mdf_shadow_observations DROP COLUMN candidate_quantities;'],
    [167, 'ALTER TABLE mdf_shadow_observations DISABLE TRIGGER mdf_shadow_immutable;'],
    [168, 'ALTER TABLE bitrix24_stage_config ALTER COLUMN enabled SET DEFAULT true;'],
    [168, 'ALTER TABLE bitrix24_stage_work DROP CONSTRAINT bitrix24_stage_work_pkey;'],
    [168, 'DROP INDEX idx_bitrix24_stage_work_due;'],
    [168, 'ALTER TABLE orders DISABLE TRIGGER trg_bitrix24_stage_order_changed;'],
    [168, 'ALTER TABLE crm_sync_mapping DISABLE TRIGGER trg_bitrix24_stage_mapping_available;'],
    [168, 'CREATE OR REPLACE FUNCTION bitrix24_stage_enqueue(p_order_id bigint) RETURNS void LANGUAGE plpgsql AS $$ BEGIN RETURN; END $$;'],
    [168, 'DELETE FROM bitrix24_stage_config;'],
    [169, 'ALTER TABLE mdf_shadow_comparison_attempts DROP CONSTRAINT mdf_shadow_comparison_attempts_attempts_check;'],
    [169, 'ALTER TABLE mdf_shadow_comparisons DISABLE TRIGGER mdf_shadow_comparison_immutable;'],
    [169, 'DROP INDEX idx_mdf_shadow_comparison_created;'],
    [174, 'ALTER TABLE mdf_revision_context ALTER COLUMN acceptance_requested SET DEFAULT true;'],
    [174, 'ALTER TABLE mdf_revision_demand ALTER COLUMN quantity DROP NOT NULL;'],
    [174, 'ALTER TABLE mdf_published_sources DROP CONSTRAINT mdf_published_sources_source_kind_source_id_fkey;'],
    [174, 'ALTER TABLE mdf_published_source_members DROP CONSTRAINT mdf_published_source_members_quantity_check;'],
    [174, 'ALTER TABLE mdf_published_positions DROP CONSTRAINT mdf_published_positions_check;'],
    [174, 'DROP INDEX idx_mdf_published_source_window;'],
    [174, 'DROP INDEX idx_mdf_published_member_order;'],
    [174, 'ALTER TABLE mdf_revision_context DISABLE TRIGGER mdf_context_insert_guard;'],
    [174, 'ALTER TABLE mdf_revision_demand DISABLE TRIGGER mdf_demand_insert_guard;'],
    [174, 'ALTER TABLE mdf_revision_context DISABLE TRIGGER mdf_context_immutable;'],
    [174, 'ALTER TABLE mdf_revision_demand DISABLE TRIGGER mdf_demand_immutable;'],
    [174, 'CREATE OR REPLACE FUNCTION mdf_guard_execution_context_insert() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;'],
    [174, 'DROP TRIGGER mdf_context_insert_guard ON mdf_revision_context; CREATE TRIGGER mdf_context_insert_guard BEFORE INSERT ON mdf_revision_context FOR EACH ROW WHEN (NEW.acceptance_requested) EXECUTE FUNCTION mdf_guard_execution_context_insert();'],
    [175, 'DROP TABLE mdf_manual_command_results;'],
    [175, 'ALTER TABLE mdf_manual_command_results DROP CONSTRAINT mdf_manual_command_results_pkey;'],
    [175, 'ALTER TABLE mdf_manual_command_results ALTER COLUMN response DROP NOT NULL;'],
    [175, 'ALTER TABLE mdf_manual_command_results DISABLE TRIGGER mdf_manual_command_result_immutable;'],
    [175, "ALTER TABLE mdf_revision_context DROP CONSTRAINT mdf_context_manual_placement_check; ALTER TABLE mdf_revision_context ADD CONSTRAINT mdf_context_manual_placement_check CHECK(true);"],
    [175, 'DROP TRIGGER mdf_manual_command_result_immutable ON mdf_manual_command_results; CREATE TRIGGER mdf_manual_command_result_immutable BEFORE UPDATE ON mdf_manual_command_results FOR EACH ROW EXECUTE FUNCTION mdf_reject_evidence_change();'],
    [177, 'ALTER TABLE cut_result_placement DROP COLUMN order_hdf_detail_id CASCADE;'],
    [177, 'DROP INDEX idx_cut_result_placement_hdf_candidates;'],
    [177, 'ALTER TABLE cut_result_placement DROP CONSTRAINT chk_cut_result_placement_source_only_order; ALTER TABLE cut_result_placement ADD CONSTRAINT chk_cut_result_placement_source_only_order CHECK(true);'],
    [177, "CREATE OR REPLACE FUNCTION cut_result_item_identity(p_item jsonb) RETURNS text LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE AS $$ SELECT 'det-' || (p_item->>'orderDetailId') $$;"],
    [177, 'CREATE OR REPLACE FUNCTION cut_result_snapshot_is_complete(p_snapshot jsonb,p_manifest jsonb,p_digest text) RETURNS boolean LANGUAGE sql IMMUTABLE STRICT AS $$ SELECT true $$;'],
    [177, 'CREATE OR REPLACE FUNCTION project_cut_result_label_maps(p_cut_result_id bigint) RETURNS void LANGUAGE plpgsql AS $$ BEGIN RETURN; END $$;'],
    [178, 'ALTER TABLE mdf_revision_context ALTER COLUMN effect_policy DROP NOT NULL;'],
    [178, 'ALTER TABLE mdf_recalculation_jobs ALTER COLUMN effect_policy DROP NOT NULL;'],
    [178, "ALTER TABLE mdf_revision_context ALTER COLUMN effect_policy SET DEFAULT 'publish_only';"],
    [178, "ALTER TABLE mdf_recalculation_jobs ALTER COLUMN effect_policy SET DEFAULT 'publish_only';"],
    [178, "ALTER TABLE mdf_revision_context DROP CONSTRAINT mdf_revision_context_effect_policy_check; ALTER TABLE mdf_revision_context ADD CONSTRAINT mdf_revision_context_effect_policy_check CHECK(effect_policy IN ('forward','publish_only','evil'));"],
    [178, "ALTER TABLE mdf_recalculation_jobs DROP CONSTRAINT mdf_recalculation_jobs_effect_policy_check; ALTER TABLE mdf_recalculation_jobs ADD CONSTRAINT mdf_recalculation_jobs_effect_policy_check CHECK(effect_policy IN ('forward','publish_only','evil'));"],
    [178, 'ALTER TABLE mdf_recalculation_jobs DISABLE TRIGGER mdf_job_effect_policy_binding;'],
    [178, 'CREATE OR REPLACE FUNCTION mdf_guard_job_effect_policy_binding() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;'],
    [178, 'DROP TRIGGER mdf_job_effect_policy_binding ON mdf_recalculation_jobs; CREATE TRIGGER mdf_job_effect_policy_binding BEFORE INSERT ON mdf_recalculation_jobs FOR EACH ROW EXECUTE FUNCTION mdf_guard_job_effect_policy_binding();'],
    [179, 'ALTER TABLE mdf_correction_command_results ALTER COLUMN response DROP NOT NULL;'],
    [179, 'ALTER TABLE mdf_correction_command_results DROP CONSTRAINT mdf_correction_command_results_response_check; ALTER TABLE mdf_correction_command_results ADD CONSTRAINT mdf_correction_command_results_response_check CHECK(true);'],
    [179, 'DROP INDEX idx_mdf_correction_job_effect_suppressions_order;'],
    [179, 'ALTER TABLE mdf_correction_command_results DISABLE TRIGGER mdf_correction_command_result_immutable;'],
    [179, 'ALTER TABLE mdf_correction_job_effect_suppressions ADD CONSTRAINT e2e_job_fk FOREIGN KEY(job_id) REFERENCES mdf_recalculation_jobs(job_id);'],
    [179, 'ALTER TABLE mdf_cnc_return_fences DISABLE TRIGGER mdf_cnc_return_fence_guard;'],
    [179, "ALTER TABLE mdf_cnc_return_fences DROP CONSTRAINT mdf_cnc_return_fences_state_check; ALTER TABLE mdf_cnc_return_fences ADD CONSTRAINT mdf_cnc_return_fences_state_check CHECK(true);"],
    [179, 'CREATE OR REPLACE FUNCTION mdf_guard_cnc_return_fence() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;'],
    [180, 'ALTER TABLE mdf_cnc_observation_targets ALTER COLUMN accepted_revision_key DROP NOT NULL;'],
    [180, 'ALTER TABLE mdf_cnc_observation_receipts DISABLE TRIGGER mdf_cnc_observation_receipt_immutable;'],
    [180, 'ALTER TABLE mdf_cnc_observation_job_authorities DISABLE TRIGGER mdf_cnc_observation_job_authority_immutable;'],
    [180, 'DROP INDEX idx_mdf_cnc_observation_due;'],
    [180, 'CREATE OR REPLACE FUNCTION mdf_guard_cnc_observation_target() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;'],
    [181, 'ALTER TABLE cnc_manual_svg_observation_claim_snapshots ALTER COLUMN files_qualified DROP NOT NULL;'],
    [181, 'ALTER TABLE cnc_manual_svg_observation_send_bindings DROP CONSTRAINT chk_cnc_manual_svg_observation_binding_choice; ALTER TABLE cnc_manual_svg_observation_send_bindings ADD CONSTRAINT chk_cnc_manual_svg_observation_binding_choice CHECK(true);'],
    [181, 'ALTER TABLE cnc_manual_svg_observation_registration_work DISABLE TRIGGER cnc_manual_svg_observation_work_guard;'],
    [181, 'CREATE OR REPLACE FUNCTION mdf_guard_cnc_manual_svg_observation_append_only() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;'],
    [181, 'CREATE OR REPLACE FUNCTION mdf_guard_cnc_manual_svg_observation_work() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;'],
    [181, 'CREATE OR REPLACE FUNCTION mdf_guard_cnc_observation_target() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;'],
    [181, 'DROP INDEX idx_cnc_manual_svg_observation_registration_due;'],
    [181, 'DROP INDEX uq_mdf_cnc_observation_manual_send;'],
    [181, 'ALTER TABLE mdf_cnc_observation_targets DISABLE TRIGGER mdf_cnc_observation_target_guard;'],
    [181, 'ALTER TABLE mdf_cnc_observation_targets DROP CONSTRAINT chk_mdf_cnc_observation_target_registration_kind; ALTER TABLE mdf_cnc_observation_targets ADD CONSTRAINT chk_mdf_cnc_observation_target_registration_kind CHECK(true);'],
    [181, 'ALTER TABLE cnc_manual_svg_observation_registration_work ADD CONSTRAINT e2e_job_fk FOREIGN KEY(send_request_id) REFERENCES mdf_recalculation_jobs(job_id);'],
    [182, 'ALTER TABLE mdf_physical_lineage_contracts DISABLE TRIGGER mdf_physical_lineage_contract_insert_guard;'],
    [182, 'ALTER TABLE mdf_physical_lineage_transitions DROP CONSTRAINT mdf_physical_lineage_transitions_action_check;'],
    [182, 'ALTER TABLE mdf_physical_lineage_transitions ADD CONSTRAINT e2e_job_fk FOREIGN KEY(evidence_line_id) REFERENCES mdf_recalculation_jobs(job_id);'],
    [182, 'CREATE OR REPLACE FUNCTION mdf_guard_physical_lineage_insert() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;'],
    [182, 'CREATE OR REPLACE FUNCTION mdf_guard_accepted_revision() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;'],
    [182, 'CREATE OR REPLACE FUNCTION mdf_guard_source_fence() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;'],
    [185, 'ALTER TABLE mdf_bazis_assignment_states DISABLE TRIGGER mdf_bazis_assignment_state_insert_guard;'],
    [185, 'ALTER TABLE mdf_bazis_assignment_states ALTER COLUMN intentional_empty DROP NOT NULL;'],
    [185, 'ALTER TABLE mdf_bazis_composition_intents DISABLE TRIGGER mdf_bazis_composition_intent_job_guard;'],
    [185, 'ALTER TABLE mdf_bazis_assignment_states DROP CONSTRAINT fk_mdf_bazis_assignment_root_intent;'],
    [185, 'DROP INDEX idx_mdf_bazis_assignment_state_id;'],
    [185, 'DROP INDEX idx_mdf_bazis_composition_intent_job;'],
    [185, 'CREATE OR REPLACE FUNCTION mdf_guard_bazis_assignment_state_insert() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;'],
    [185, 'CREATE OR REPLACE FUNCTION mdf_guard_bazis_assignment_state_seal() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;'],
    [185, 'CREATE OR REPLACE FUNCTION mdf_guard_bazis_composition_intent_insert() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;'],
    [185, 'CREATE OR REPLACE FUNCTION mdf_validate_bazis_composition_intent_job() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;'],
    [185, 'CREATE OR REPLACE FUNCTION mdf_reject_bazis_composition_marker_change() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;'],
  ] as const)('%s: rejects drift %s', (version, mutation) => {
    expect(present(fileFor(version), mutation)).toBe(false);
    expect(present(fileFor(version))).toBe(true); // rollback restored fixture
  });

  it('migration 180 remains PRESENT after 181 but rejects corruption of its 181 successor guard', () => {
    expect(present(fileFor(180))).toBe(true);
    expect(present(fileFor(180), 'ALTER TABLE mdf_cnc_observation_targets DISABLE TRIGGER mdf_cnc_observation_target_guard;')).toBe(false);
    expect(present(fileFor(180))).toBe(true); // rollback restored fixture
  });

  it('does not confuse legitimate runtime settings with a missing migration', () => {
    expect(present(fileFor(165), "UPDATE mdf_engine_state SET mode='shadow',published_revision=10;")).toBe(true);
    expect(present(fileFor(168), `INSERT INTO users VALUES(1); INSERT INTO order_statuses VALUES(1);
      INSERT INTO bitrix24_app_installation VALUES('E2E-member');
      UPDATE bitrix24_stage_config SET member_id='E2E-member',domain='example.invalid',category_id=0,
      completed_status_id=1,enabled=true,binding_locked=true,version=3,epoch=2;`)).toBe(true);
  });
  it('177 preserves the effect probes of153/154',()=>{
    expect(present('153_svg_partial_label_maps.sql')).toBe(true);
    expect(present('154_svg_source_instance_sequences.sql')).toBe(true);
  });
});
