import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { randomUUID } from 'node:crypto';
import { Pool, type PoolClient } from 'pg';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import type { DatabaseService } from '../../../database/database.service';
import type { TransactionClient } from '../../../database/database.types';
import type { CurrentUser } from '../../../permissions/current-user';
import { PgSheetMaterialsRepository } from './pg-sheet-materials-repository';
import {
  SheetMaterialNotFoundError,
  SheetMaterialStaleVersionError,
} from '../errors/sheet-materials.errors';

// Fail-fast: the dedicated `test:backend:sheet-integration` script sets
// SHEET_INTEGRATION_REQUIRED=1. In that mode ONLY SHEET_INTEGRATION_DATABASE_URL
// is honored (no TEST_DATABASE_URL fallback that could silently route the suite to
// a different database); a missing value is a hard error, not a silent skip.
const required = process.env.SHEET_INTEGRATION_REQUIRED === '1';
const databaseUrl = required
  ? process.env.SHEET_INTEGRATION_DATABASE_URL
  : process.env.SHEET_INTEGRATION_DATABASE_URL ?? process.env.TEST_DATABASE_URL;
if (required && !databaseUrl) {
  throw new Error('SHEET_INTEGRATION_DATABASE_URL is required for test:backend:sheet-integration');
}
const describeIntegration = databaseUrl ? describe : describe.skip;
const schemaName = `sheet_materials_${randomUUID().replaceAll('-', '_')}`;

const MIGRATIONS = resolve(__dirname, '../../../../db/migrations');
function migration(file: string): string {
  return readFileSync(resolve(MIGRATIONS, file), 'utf8');
}

function currentUser(): CurrentUser {
  return {
    id: '1',
    username: 'sheet',
    role: 'operator',
    permissions: ['sheet_materials.view', 'sheet_materials.manage'],
  } as unknown as CurrentUser;
}

const baseInput = {
  name: 'ЛДСП 16 Дуб',
  materialTypeId: 1,
  unitId: 1,
  thicknessMm: 16,
  widthMm: 2800,
  heightMm: 2070,
  supplierId: 1,
  vendorId: 1,
  supplierArticle: 'ART-1',
  texture: true,
  color: 'Дуб',
};

/**
 * Build prerequisite base tables (their PRE-021 shape), then apply the REAL
 * migration files 021 -> 024 -> 025 in order. This exercises the actual chain,
 * including migration 021's `ALTER TABLE materials ADD sheet_material_type_id`,
 * so the gate cannot pass on a hand-rolled mirror that drifts from the migrations.
 */
async function createSchema(client: PoolClient): Promise<void> {
  await client.query(`
    CREATE FUNCTION set_session_user(p_user TEXT) RETURNS void AS $$ BEGIN PERFORM 1; END; $$ LANGUAGE plpgsql;

    CREATE TABLE material_types (material_type_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, material_type_name TEXT);
    INSERT INTO material_types (material_type_id, material_type_name) VALUES (1, 'ЛДСП');

    CREATE TABLE units (unit_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, unit_name TEXT);
    INSERT INTO units (unit_id, unit_name) VALUES (1, 'шт');

    CREATE TABLE suppliers (supplier_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, supplier_name TEXT);
    INSERT INTO suppliers (supplier_id, supplier_name) VALUES (1, 'Поставщик-1');

    CREATE TABLE vendors (vendor_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, vendor_name TEXT);
    INSERT INTO vendors (vendor_id, vendor_name) VALUES (1, 'Производитель-1');

    -- base materials = its PRE-021 shape (021 will ADD sheet_material_type_id).
    CREATE TABLE materials (
      material_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      material_name VARCHAR(200) NOT NULL,
      unit_id SMALLINT NOT NULL REFERENCES units(unit_id),
      material_type_id SMALLINT REFERENCES material_types(material_type_id),
      default_supplier_id SMALLINT REFERENCES suppliers(supplier_id),
      vendor_id SMALLINT REFERENCES vendors(vendor_id),
      is_active BOOLEAN NOT NULL DEFAULT true,
      ref_key_1c UUID NULL,
      created_by BIGINT, edited_by BIGINT,
      created_at TIMESTAMP NOT NULL DEFAULT now(), updated_at TIMESTAMP NOT NULL DEFAULT now()
    );

    CREATE TABLE audit_log (
      audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      event TEXT NOT NULL, entity_type TEXT, entity_id TEXT,
      user_id BIGINT, username TEXT, role_code TEXT, role TEXT, request_id TEXT, source TEXT,
      related_order_id BIGINT, related_client_id BIGINT, related_payment_id BIGINT,
      related_production_event_id BIGINT, related_deadline_id BIGINT, related_user_id BIGINT,
      status_field TEXT, status_id BIGINT, status_name TEXT, status_code TEXT, stage_code TEXT,
      before_json JSONB, after_json JSONB, diff_json JSONB, metadata_json JSONB,
      created_at TIMESTAMP NOT NULL DEFAULT now()
    );
    CREATE TABLE audit_log_related_entity (
      audit_id BIGINT NOT NULL, entity_type TEXT NOT NULL, entity_id BIGINT NOT NULL,
      UNIQUE (audit_id, entity_type, entity_id)
    );
  `);

  // Apply the REAL migration chain in order (each file carries its own BEGIN/COMMIT).
  await client.query(migration('021_sheet_material_types.sql'));
  await client.query(migration('024_sheet_material_type_version.sql'));
  await client.query(migration('026_sheet_material_types_reference_columns.sql'));
}

function makeDatabase(pool: Pool): DatabaseService {
  const query = (text: string, params: readonly unknown[] = []) => pool.query(text, [...params]);
  return {
    isConfigured: true,
    query,
    async transaction<T>(handler: (client: TransactionClient) => Promise<T>): Promise<T> {
      const client = await pool.connect();
      try {
        await client.query('BEGIN');
        await client.query(`SET search_path TO ${schemaName}`);
        const tx: TransactionClient = {
          raw: client as never,
          query: (text: string, params: readonly unknown[] = []) => client.query(text, [...params]),
        };
        const result = await handler(tx);
        await client.query('COMMIT');
        return result;
      } catch (error) {
        await client.query('ROLLBACK').catch(() => undefined);
        throw error;
      } finally {
        client.release();
      }
    },
  } as unknown as DatabaseService;
}

describeIntegration('PgSheetMaterialsRepository (integration, real migration chain)', () => {
  let pool: Pool;
  let repo: PgSheetMaterialsRepository;

  beforeAll(async () => {
    pool = new Pool({ connectionString: databaseUrl, max: 4 });
    const client = await pool.connect();
    try {
      await client.query(`CREATE SCHEMA ${schemaName}`);
      await client.query(`SET search_path TO ${schemaName}`);
      await createSchema(client);
    } finally {
      client.release();
    }
    pool.on('connect', (c) => void c.query(`SET search_path TO ${schemaName}`));
    repo = new PgSheetMaterialsRepository(makeDatabase(pool));
  });

  afterAll(async () => {
    if (pool) {
      await pool.query(`DROP SCHEMA IF EXISTS ${schemaName} CASCADE`);
      await pool.end();
    }
  });

  beforeEach(async () => {
    await pool.query('TRUNCATE sheet_material_types, audit_log, audit_log_related_entity RESTART IDENTITY CASCADE');
  });

  it('creates a row with all new columns, version 0, is_active true', async () => {
    const ctx = { currentUser: currentUser(), requestId: 'r-create' };
    const created = await repo.create({ ...ctx, input: baseInput });
    expect(created).toMatchObject({
      name: 'ЛДСП 16 Дуб',
      materialTypeId: 1,
      unitId: 1,
      supplierId: 1,
      vendorId: 1,
      supplierArticle: 'ART-1',
      texture: true,
      color: 'Дуб',
      isActive: true,
      version: 0,
    });
    const got = await repo.getById({ ...ctx, id: created.sheetMaterialTypeId });
    expect(got.sheetMaterialTypeId).toBe(created.sheetMaterialTypeId);

    const audit = await pool.query(`SELECT event, entity_type FROM audit_log WHERE event = 'sheet_material.created'`);
    expect(audit.rowCount).toBe(1);
    const bridge = await pool.query(
      `SELECT entity_type FROM audit_log_related_entity WHERE entity_type = 'sheet_material_type'`,
    );
    expect(bridge.rowCount).toBeGreaterThanOrEqual(1);
  });

  it('list(includeInactive=false) excludes deactivated rows', async () => {
    const ctx = { currentUser: currentUser(), requestId: 'r' };
    const a = await repo.create({ ...ctx, input: { ...baseInput, name: 'A' } });
    await repo.create({ ...ctx, input: { ...baseInput, name: 'B' } });
    await repo.deactivate({ ...ctx, id: a.sheetMaterialTypeId, expectedVersion: 0 });

    const active = await repo.list({ ...ctx, includeInactive: false });
    expect(active.map((r) => r.name)).toEqual(['B']);
    const all = await repo.list({ ...ctx, includeInactive: true });
    expect(all.map((r) => r.name).sort()).toEqual(['A', 'B']);
  });

  it('update bumps version and writes sheet_material.updated audit with diff', async () => {
    const ctx = { currentUser: currentUser(), requestId: 'r' };
    const created = await repo.create({ ...ctx, input: baseInput });
    const updated = await repo.update({
      ...ctx,
      id: created.sheetMaterialTypeId,
      expectedVersion: 0,
      input: { ...baseInput, color: 'Орех' },
    });
    expect(updated.version).toBe(1);
    expect(updated.color).toBe('Орех');
    const audit = await pool.query(`SELECT diff_json FROM audit_log WHERE event = 'sheet_material.updated'`);
    expect(audit.rowCount).toBe(1);
    expect(audit.rows[0].diff_json).toMatchObject({ color: { from: 'Дуб', to: 'Орех' } });
  });

  it('rejects a stale version update with 409', async () => {
    const ctx = { currentUser: currentUser(), requestId: 'r' };
    const created = await repo.create({ ...ctx, input: baseInput });
    await expect(
      repo.update({ ...ctx, id: created.sheetMaterialTypeId, expectedVersion: 99, input: baseInput }),
    ).rejects.toBeInstanceOf(SheetMaterialStaleVersionError);
  });

  it('rejects a duplicate name with 409 SHEET_MATERIAL_CONFLICT', async () => {
    const ctx = { currentUser: currentUser(), requestId: 'r' };
    await repo.create({ ...ctx, input: baseInput });
    await expect(repo.create({ ...ctx, input: baseInput })).rejects.toMatchObject({
      statusCode: 409,
      code: 'SHEET_MATERIAL_CONFLICT',
    });
  });

  it('deactivate sets is_active false + audit + bridge row', async () => {
    const ctx = { currentUser: currentUser(), requestId: 'r' };
    const created = await repo.create({ ...ctx, input: baseInput });
    await repo.deactivate({ ...ctx, id: created.sheetMaterialTypeId, expectedVersion: 0 });
    const got = await repo.getById({ ...ctx, id: created.sheetMaterialTypeId });
    expect(got.isActive).toBe(false);
    const audit = await pool.query(`SELECT event FROM audit_log WHERE event = 'sheet_material.deactivated'`);
    expect(audit.rowCount).toBe(1);
  });

  it('getById throws SheetMaterialNotFoundError for a missing id', async () => {
    const ctx = { currentUser: currentUser(), requestId: 'r' };
    await expect(repo.getById({ ...ctx, id: 999999 })).rejects.toBeInstanceOf(SheetMaterialNotFoundError);
  });

  it('surfaces an FK violation for a bad unitId', async () => {
    const ctx = { currentUser: currentUser(), requestId: 'r' };
    await expect(repo.create({ ...ctx, input: { ...baseInput, unitId: 9999 } })).rejects.toBeTruthy();
  });

  it('recordPermissionDenied writes a sheet_material.permission_denied audit row (pool-backed)', async () => {
    await repo.recordPermissionDenied({
      currentUser: currentUser(),
      requiredPermissions: ['sheet_materials.manage'],
      requestId: 'r-denied',
    });
    const audit = await pool.query(`SELECT event, entity_id FROM audit_log WHERE event = 'sheet_material.permission_denied'`);
    expect(audit.rowCount).toBe(1);
    expect(audit.rows[0].entity_id).toBe('sheet_material_types');
  });
});
