// sheet-materials-copy.integration.ts
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { randomUUID } from 'node:crypto';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { Pool, type PoolClient } from 'pg';
import { runSheetCopy, reverseSheetCopy, SheetCopyConflictError, SheetCopySourceDriftError, SheetReverseBlockedError, SheetReverseDriftError } from '../../../../scripts/sheet-materials-copy/runner';

// Poll until the EXACT session under test (identified by its libpq application_name) is waiting on a
// lock — NOT any ungranted lock in the whole DB, which an unrelated/parallel backend could satisfy early
// and make these tests false-positive (tier2). Deterministically sequences a blocked-then-released op.
async function waitForBlockedQuery(pg: Pool, appName: string, max = 300): Promise<void> {
  for (let i = 0; i < max; i += 1) {
    const n = (await pg.query(
      `SELECT count(*)::int n FROM pg_stat_activity a JOIN pg_locks l ON l.pid = a.pid
       WHERE a.application_name = $1 AND NOT l.granted`, [appName])).rows[0].n;
    if (n > 0) return;
    await new Promise((res) => setTimeout(res, 10));
  }
  throw new Error(`expected a blocked query for application_name=${appName} but none appeared`);
}

const REQUIRED = process.env.SHEET_INTEGRATION_REQUIRED === '1';
const DATABASE_URL = REQUIRED
  ? (process.env.SHEET_INTEGRATION_DATABASE_URL ?? '')
  : (process.env.SHEET_INTEGRATION_DATABASE_URL ?? process.env.TEST_DATABASE_URL ?? '');
if (REQUIRED && !DATABASE_URL) throw new Error('SHEET_INTEGRATION_DATABASE_URL is required for the dedicated sheet integration run');

const schemaName = `sheet_copy_${randomUUID().replaceAll('-', '_')}`;
const MIGRATIONS = resolve(__dirname, '../../../../db/migrations');
const migration = (f: string) => readFileSync(resolve(MIGRATIONS, f), 'utf8');
const describeIf = DATABASE_URL ? describe : describe.skip;
let pool: Pool;
// A dedicated pool whose session is identifiable by application_name (for the lock-sequenced tests).
const underTestPool = (appName: string) =>
  new Pool({ connectionString: DATABASE_URL, application_name: appName, options: `-c search_path=${schemaName}` });

async function createSchema(client: PoolClient): Promise<void> {
  await client.query(`CREATE SCHEMA ${schemaName}; SET search_path TO ${schemaName};`);
  await client.query(`
    CREATE TABLE material_types (material_type_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, material_type_name TEXT);
    INSERT INTO material_types (material_type_id, material_type_name) VALUES (1,'МДФ'),(2,'ЛДСП'),(3,'нд');
    CREATE TABLE units (unit_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, unit_name TEXT);
    INSERT INTO units (unit_id, unit_name) VALUES (1,'лист'),(2,'шт');
    CREATE TABLE suppliers (supplier_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, supplier_name TEXT);
    INSERT INTO suppliers (supplier_id, supplier_name) VALUES (1,'Поставщик-1');
    CREATE TABLE vendors (vendor_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, vendor_name TEXT);
    INSERT INTO vendors (vendor_id, vendor_name) VALUES (1,'Производитель-1');
    CREATE TABLE materials (
      material_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      material_name VARCHAR(200) NOT NULL, unit_id SMALLINT NOT NULL REFERENCES units(unit_id),
      material_type_id SMALLINT REFERENCES material_types(material_type_id),
      default_supplier_id SMALLINT REFERENCES suppliers(supplier_id), vendor_id SMALLINT REFERENCES vendors(vendor_id),
      is_active BOOLEAN NOT NULL DEFAULT true, ref_key_1c UUID NULL,
      created_by BIGINT, edited_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT now(), updated_at TIMESTAMP NOT NULL DEFAULT now());
    CREATE TABLE audit_log (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event TEXT, payload JSONB, created_at TIMESTAMP DEFAULT now());
    CREATE TABLE audit_log_related_entity (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, audit_log_id BIGINT, entity_type TEXT, entity_id TEXT);
  `);
  await client.query(migration('021_sheet_material_types.sql'));
  await client.query(migration('024_sheet_material_type_version.sql'));
  await client.query(migration('026_sheet_material_types_reference_columns.sql'));
  await client.query(migration('027_sheet_material_copy_runs.sql'));
  // One PRE-EXISTING sheet row (e.g. manually created earlier) that the copy must NOT delete on reverse.
  await client.query(`INSERT INTO sheet_material_types (name, material_type_id, unit_id, thickness_mm, width_mm, height_mm) VALUES ('PREEXISTING ручной лист', 2, 1, 10, 2440, 1220);`);
  // 3 eligible (2 МДФ + 1 ЛДСП), 1 inactive, 1 non-sheet 'нд'.
  await client.query(`
    INSERT INTO materials (material_name, unit_id, material_type_id, default_supplier_id, vendor_id, is_active, ref_key_1c) VALUES
      ('МДФ Эггер 2800x2070 16мм', 1, 1, 1, 1, true,  '11111111-1111-1111-1111-111111111111'),
      ('МДФ белый',               1, 1, 1, 1, true,  NULL),
      ('ЛДСП 2750х1830 18мм',     1, 2, 1, 1, true,  NULL),
      ('МДФ снятый с производства',1, 1, 1, 1, false, NULL),
      ('Кромка ПВХ 2мм',          2, 3, 1, 1, true,  NULL);`);
}

beforeAll(async () => {
  if (!DATABASE_URL) return;
  // search_path is set as a connection-STARTUP option (libpq -c), applied synchronously before any query —
  // NOT a fire-and-forget on('connect') handler, which races the first query (Critic R9). A startup
  // search_path may reference a not-yet-existing schema; createSchema creates it first thing.
  pool = new Pool({ connectionString: DATABASE_URL, options: `-c search_path=${schemaName}` });
  const setup = await pool.connect();
  try { await createSchema(setup); } finally { setup.release(); }
});
afterAll(async () => {
  if (!pool) return;
  const c = await pool.connect();
  try { await c.query(`DROP SCHEMA IF EXISTS ${schemaName} CASCADE`); } finally { c.release(); }
  await pool.end();
});

const cfg = (mode: 'dry-run' | 'write', runId = 'it-run') => ({
  mode, databaseUrl: DATABASE_URL, targetEnv: 'backend-test', approveWrite: true,
  materialTypeAllowlist: [1, 2], allowedDbHosts: ['localhost', '127.0.0.1', '::1'],
  manifestOut: '/tmp/ignored.json', runIdArg: null, runId, expectedDbName: 'postgres', actor: 'it',
});
const reverseOpts = { actor: 'it', expectedDbName: 'postgres' };

describeIf('SP2 sheet-materials copy (real migration chain 021→024→026→027)', () => {
  it('dry-run plans 3 inserts + 3 links, writes nothing', async () => {
    const s = await runSheetCopy(pool, cfg('dry-run'));
    expect(s).toMatchObject({ mode: 'dry-run', inserted: 3, linked: 3, skipped: 2 });
    expect((await pool.query("SELECT count(*)::int n FROM sheet_material_types WHERE name <> 'PREEXISTING ручной лист'")).rows[0].n).toBe(0);
  });

  it('write creates 3 rows, links 3 materials, parses dims, flags placeholders, records the ledger', async () => {
    const s = await runSheetCopy(pool, cfg('write', 'run-A'));
    expect(s).toMatchObject({ mode: 'write', inserted: 3, linked: 3, skipped: 2 });
    const rows = (await pool.query("SELECT name, thickness_mm::int t, width_mm::int w, height_mm::int h FROM sheet_material_types WHERE name <> 'PREEXISTING ручной лист' ORDER BY name")).rows;
    expect(rows.find((r) => r.name === 'МДФ Эггер 2800x2070 16мм')).toMatchObject({ t: 16, w: 2800, h: 2070 });
    expect(rows.find((r) => r.name === 'ЛДСП 2750х1830 18мм')).toMatchObject({ t: 18, w: 2750, h: 1830 });
    expect(rows.find((r) => r.name === 'МДФ белый')).toMatchObject({ t: 16, w: 2800, h: 2070 });
    expect(s.placeholderDimensions.map((p) => p.name)).toContain('МДФ белый');
    expect((await pool.query('SELECT count(*)::int n FROM materials WHERE sheet_material_type_id IS NOT NULL')).rows[0].n).toBe(3);
    expect(s.reversalRecord?.createdSheetMaterialTypeIds).toHaveLength(3);
    // Ledger carries the full audit dimensions (this is SP2's audit substitute — Critic R4 [AUDIT-DEBT]).
    const led = (await pool.query(
      `SELECT actor, source, target_env AS "targetEnv", db_user AS "dbUser", database_name AS "databaseName",
              reversed_at AS "reversedAt", array_length(created_sheet_material_type_ids,1) AS "createdN"
       FROM sheet_material_copy_runs WHERE run_id='run-A'`)).rows[0];
    expect(led).toMatchObject({
      actor: 'it', source: 'sheet-materials-copy-runner', targetEnv: 'backend-test',
      dbUser: 'postgres', databaseName: 'postgres', reversedAt: null, createdN: 3,
    });
  });

  it('second write run is a TRUE no-op (idempotent: no inserts, no links, NO ledger row, null reversalRecord)', async () => {
    const s = await runSheetCopy(pool, cfg('write', 'run-B'));
    expect(s).toMatchObject({ inserted: 0, linked: 0, reversalRecord: null });
    expect((await pool.query("SELECT count(*)::int n FROM sheet_material_types WHERE name <> 'PREEXISTING ручной лист'")).rows[0].n).toBe(3);
    expect((await pool.query("SELECT count(*)::int n FROM sheet_material_copy_runs WHERE run_id='run-B'")).rows[0].n).toBe(0); // no durable artifact on a no-op
  });

  it('reverse ABORTS ATOMICALLY when a created row is still referenced by an FK (schema-aware guard)', async () => {
    // Simulate a future order-side referrer: a table with an FK to sheet_material_types pointing at a run-A row.
    const createdId = (await pool.query(
      "SELECT sheet_material_type_id id FROM sheet_material_types WHERE name='МДФ белый'")).rows[0].id;
    await pool.query(`CREATE TABLE it_referrer (id BIGINT PRIMARY KEY, sheet_material_type_id BIGINT REFERENCES sheet_material_types(sheet_material_type_id));`);
    await pool.query('INSERT INTO it_referrer (id, sheet_material_type_id) VALUES (1, $1)', [createdId]);
    await expect(reverseSheetCopy(pool, 'run-A', reverseOpts)).rejects.toBeInstanceOf(SheetReverseBlockedError);
    // Nothing changed: rows intact, materials still linked, run still un-reversed.
    expect((await pool.query("SELECT count(*)::int n FROM sheet_material_types WHERE name <> 'PREEXISTING ручной лист'")).rows[0].n).toBe(3);
    expect((await pool.query('SELECT count(*)::int n FROM materials WHERE sheet_material_type_id IS NOT NULL')).rows[0].n).toBe(3);
    expect((await pool.query("SELECT reversed_at IS NULL ok FROM sheet_material_copy_runs WHERE run_id='run-A'")).rows[0].ok).toBe(true);
    // Remove the referrer so the next test can reverse cleanly.
    await pool.query('DROP TABLE it_referrer');
  });

  it('reverse of the REAL ledger artifact (run-A) deletes only the 3 created rows, keeps the pre-existing one, unlinks materials', async () => {
    const r = await reverseSheetCopy(pool, 'run-A', reverseOpts);
    expect(r).toMatchObject({ runId: 'run-A', unlinked: 3, deleted: 3, refusedDeletes: [] });
    expect((await pool.query('SELECT count(*)::int n FROM materials WHERE sheet_material_type_id IS NOT NULL')).rows[0].n).toBe(0);
    expect((await pool.query("SELECT count(*)::int n FROM sheet_material_types")).rows[0].n).toBe(1); // pre-existing survives
    expect((await pool.query("SELECT name FROM sheet_material_types")).rows[0].name).toBe('PREEXISTING ручной лист');
    const rev = (await pool.query("SELECT reversed_at IS NOT NULL AS done, reversed_by AS \"reversedBy\" FROM sheet_material_copy_runs WHERE run_id='run-A'")).rows[0];
    expect(rev).toMatchObject({ done: true, reversedBy: 'it' });   // reversed_by audit dimension recorded
    await expect(reverseSheetCopy(pool, 'run-A', reverseOpts)).rejects.toThrow(/un-reversed/); // already reversed → refuse
  });

  it('links an unlinked material to a PRE-EXISTING compatible sheet row without inserting a duplicate', async () => {
    // After run-A reverse the original materials are unlinked again. Seed a compatible pre-existing
    // sheet row + a same-named material; the write must LINK to it (the plan.links→existing DB path).
    await pool.query("INSERT INTO sheet_material_types (name, material_type_id, unit_id, thickness_mm, width_mm, height_mm, supplier_id, vendor_id, is_active) VALUES ('LINKTEST лист', 1, 1, 16, 2800, 2070, 1, 1, true)");
    const preId = (await pool.query("SELECT sheet_material_type_id id FROM sheet_material_types WHERE name='LINKTEST лист'")).rows[0].id;
    await pool.query("INSERT INTO materials (material_name, unit_id, material_type_id, default_supplier_id, vendor_id, is_active) VALUES ('LINKTEST лист', 1, 1, 1, 1, true)");
    await runSheetCopy(pool, cfg('write', 'run-D'));   // re-creates the unlinked originals + links LINKTEST
    expect((await pool.query("SELECT count(*)::int n FROM sheet_material_types WHERE name='LINKTEST лист'")).rows[0].n).toBe(1); // no duplicate
    const linkedId = (await pool.query("SELECT sheet_material_type_id id FROM materials WHERE material_name='LINKTEST лист'")).rows[0].id;
    expect(Number(linkedId)).toBe(Number(preId)); // linked to the pre-existing row
  });

  it('does NOT over-lock: completes while an UNRELATED material + SP1 sheet row are locked elsewhere (no order/SP1 impact)', async () => {
    // Critic R10: SP2 must not block concurrent order saves (materials FK) or unrelated SP1 catalog edits.
    // Hold FOR UPDATE locks on rows SP2 must NOT touch: a non-eligible 'нд' material (stands in for an
    // order-save FK path) and a pre-existing sheet row SP2 will not link to. If SP2 over-locked, its run
    // would hit lock_timeout; instead it completes and copies the new eligible material.
    await pool.query("INSERT INTO materials (material_name, unit_id, material_type_id, default_supplier_id, vendor_id, is_active) VALUES ('NOLOCK лист 2800x2070 16мм', 1, 1, 1, 1, true)");
    const holder = await pool.connect();   // inherits search_path from the pool's startup options
    const ltPool = new Pool({ connectionString: DATABASE_URL, options: `-c lock_timeout=500 -c search_path=${schemaName}` });
    try {
      await holder.query('BEGIN');
      await holder.query("SELECT 1 FROM materials WHERE material_name='Кромка ПВХ 2мм' FOR UPDATE");          // unrelated (type 'нд')
      await holder.query("SELECT 1 FROM sheet_material_types WHERE name='PREEXISTING ручной лист' FOR UPDATE"); // unrelated SP1 row
      const s = await runSheetCopy(ltPool, cfg('write', 'run-NOLOCK'));
      expect(s.mode).toBe('write');   // completed within lock_timeout → not blocked by the unrelated locks
      expect((await pool.query("SELECT count(*)::int n FROM sheet_material_types WHERE name='NOLOCK лист 2800x2070 16мм'")).rows[0].n).toBe(1);
    } finally {
      await holder.query('ROLLBACK').catch(() => {});
      holder.release();
      await ltPool.end();
    }
  });

  it('aborts + full rollback when an eligible source material is edited mid-run (identity-guard catches drift)', async () => {
    // Critic R11/R12: the optimistic identity-guarded link UPDATE must catch source-row drift between the
    // unlocked snapshot and the link — WITHOUT holding a candidate lock across the run.
    await pool.query("INSERT INTO materials (material_name, unit_id, material_type_id, default_supplier_id, vendor_id, is_active) VALUES ('DRIFTSRC лист 2800x2070 16мм', 1, 1, 1, 1, true)");
    const holder = await pool.connect();
    const utPool = underTestPool('sp2-srcdrift');
    try {
      await holder.query('BEGIN');
      // Lock + change the eligible source material, UNCOMMITTED → runSheetCopy's unlocked snapshot sees the
      // OLD unit_id (1); SP2 then blocks on this row's write lock when it issues its link UPDATE.
      await holder.query("UPDATE materials SET unit_id = 2 WHERE material_name = 'DRIFTSRC лист 2800x2070 16мм'");
      const p = runSheetCopy(utPool, cfg('write', 'run-SRCDRIFT'));
      await waitForBlockedQuery(pool, 'sp2-srcdrift');   // SP2 session now waiting on the material's write lock
      await holder.query('COMMIT');       // release + publish the drift (unit_id 1→2)
      await expect(p).rejects.toBeInstanceOf(SheetCopySourceDriftError);   // link UPDATE WHERE unit_id=1 now matches 0 rows
    } finally { holder.release(); await utPool.end(); }
    // Full rollback: no created sheet row, no ledger row, material left unlinked.
    expect((await pool.query("SELECT count(*)::int n FROM sheet_material_types WHERE name='DRIFTSRC лист 2800x2070 16мм'")).rows[0].n).toBe(0);
    expect((await pool.query("SELECT count(*)::int n FROM sheet_material_copy_runs WHERE run_id='run-SRCDRIFT'")).rows[0].n).toBe(0);
    expect((await pool.query("SELECT sheet_material_type_id s FROM materials WHERE material_name='DRIFTSRC лист 2800x2070 16мм'")).rows[0].s).toBeNull();
    // Clean up so the leftover eligible material does not perturb later runs.
    await pool.query("DELETE FROM materials WHERE material_name='DRIFTSRC лист 2800x2070 16мм'");
  });

  it('reverse REFUSES atomically when a copied material was manually repointed after the copy (link drift)', async () => {
    await pool.query("INSERT INTO materials (material_name, unit_id, material_type_id, default_supplier_id, vendor_id, is_active) VALUES ('DRIFT лист 2800x2070 16мм', 1, 1, 1, 1, true)");
    await runSheetCopy(pool, cfg('write', 'run-DRIFT'));   // creates 1 sheet + links the DRIFT material
    const driftMat = (await pool.query("SELECT material_id id, sheet_material_type_id s FROM materials WHERE material_name='DRIFT лист 2800x2070 16мм'")).rows[0];
    const createdSheetId = Number(driftMat.s);
    const preId = Number((await pool.query("SELECT sheet_material_type_id id FROM sheet_material_types WHERE name='PREEXISTING ручной лист'")).rows[0].id);
    // Manual drift: repoint the copied material to a different, non-run-created sheet row.
    await pool.query('UPDATE materials SET sheet_material_type_id = $2 WHERE material_id = $1', [driftMat.id, preId]);
    await expect(reverseSheetCopy(pool, 'run-DRIFT', reverseOpts)).rejects.toBeInstanceOf(SheetReverseDriftError);
    // Atomic refusal: created row intact, current (drifted) link untouched, run still un-reversed.
    expect((await pool.query('SELECT count(*)::int n FROM sheet_material_types WHERE sheet_material_type_id=$1', [createdSheetId])).rows[0].n).toBe(1);
    expect(Number((await pool.query('SELECT sheet_material_type_id s FROM materials WHERE material_id=$1', [driftMat.id])).rows[0].s)).toBe(preId);
    expect((await pool.query("SELECT reversed_at IS NULL ok FROM sheet_material_copy_runs WHERE run_id='run-DRIFT'")).rows[0].ok).toBe(true);
  });

  it('reverses a LINK-ONLY run (created_ids=[]): unlinks materials, deletes no sheet rows, marks reversed once', async () => {
    // At this point all prior eligible materials are linked; the only eligible-unlinked one we add links to
    // a PRE-EXISTING compatible row (default dims), so this write inserts nothing — the ledger has links but
    // an empty created_sheet_material_type_ids. Then prove reverse of that link-only artifact (Critic R8).
    await pool.query("INSERT INTO sheet_material_types (name, material_type_id, unit_id, thickness_mm, width_mm, height_mm, supplier_id, vendor_id, is_active) VALUES ('LINKONLY лист', 1, 1, 16, 2800, 2070, 1, 1, true)");
    const preId = Number((await pool.query("SELECT sheet_material_type_id id FROM sheet_material_types WHERE name='LINKONLY лист'")).rows[0].id);
    await pool.query("INSERT INTO materials (material_name, unit_id, material_type_id, default_supplier_id, vendor_id, is_active) VALUES ('LINKONLY лист', 1, 1, 1, 1, true)");
    const matId = Number((await pool.query("SELECT material_id id FROM materials WHERE material_name='LINKONLY лист'")).rows[0].id);
    const s = await runSheetCopy(pool, cfg('write', 'run-LO'));
    expect(s).toMatchObject({ inserted: 0, linked: 1 });
    expect(s.reversalRecord?.createdSheetMaterialTypeIds).toEqual([]);
    expect(Number((await pool.query('SELECT sheet_material_type_id s FROM materials WHERE material_id=$1', [matId])).rows[0].s)).toBe(preId);
    const sheetCountBefore = (await pool.query('SELECT count(*)::int n FROM sheet_material_types')).rows[0].n;
    const r = await reverseSheetCopy(pool, 'run-LO', reverseOpts);
    expect(r).toMatchObject({ unlinked: 1, deleted: 0, refusedDeletes: [] });
    expect((await pool.query('SELECT sheet_material_type_id s FROM materials WHERE material_id=$1', [matId])).rows[0].s).toBeNull();       // unlinked to NULL
    expect((await pool.query('SELECT count(*)::int n FROM sheet_material_types')).rows[0].n).toBe(sheetCountBefore);                       // nothing deleted (incl pre-existing)
    expect((await pool.query("SELECT reversed_at IS NOT NULL ok FROM sheet_material_copy_runs WHERE run_id='run-LO'")).rows[0].ok).toBe(true);
    await expect(reverseSheetCopy(pool, 'run-LO', reverseOpts)).rejects.toThrow(/un-reversed/);                                            // reversed exactly once
  });

  it('reverse blocks ATOMICALLY on a CONCURRENT external referrer added during reverse (no silent SET NULL)', async () => {
    // Critic R12: FK is ON DELETE SET NULL, so a late external link to a created row must not be silently
    // nulled by the delete. Reverse locks created rows FOR UPDATE (Step 0), so a concurrent linker blocks
    // until reverse ends; reverse's preflight then sees the external ref and atomically refuses.
    await pool.query("INSERT INTO materials (material_name, unit_id, material_type_id, default_supplier_id, vendor_id, is_active) VALUES ('RR лист 2800x2070 16мм', 1, 1, 1, 1, true)");
    await pool.query("INSERT INTO materials (material_name, unit_id, material_type_id, default_supplier_id, vendor_id, is_active) VALUES ('RR2 кромка', 1, 3, 1, 1, true)"); // 'нд' → not copied
    await runSheetCopy(pool, cfg('write', 'run-RR'));
    const sRr = Number((await pool.query("SELECT sheet_material_type_id id FROM sheet_material_types WHERE name='RR лист 2800x2070 16мм'")).rows[0].id);
    const holder = await pool.connect();
    const utPool = underTestPool('sp2-revrr');
    try {
      await holder.query('BEGIN');
      await holder.query('UPDATE materials SET sheet_material_type_id = $1 WHERE material_name = $2', [sRr, 'RR2 кромка']); // external link, uncommitted
      const p = reverseSheetCopy(utPool, 'run-RR', reverseOpts);   // Step 0 `... FOR UPDATE` on sRr blocks on the link's key-share
      await waitForBlockedQuery(pool, 'sp2-revrr');
      await holder.query('COMMIT');   // publish the external referrer; reverse unblocks, preflights, refuses
      await expect(p).rejects.toBeInstanceOf(SheetReverseBlockedError);
    } finally { holder.release(); await utPool.end(); }
    // Atomic refusal: created row survives, run still un-reversed, external link intact (not nulled).
    expect((await pool.query('SELECT count(*)::int n FROM sheet_material_types WHERE sheet_material_type_id=$1', [sRr])).rows[0].n).toBe(1);
    expect((await pool.query("SELECT reversed_at IS NULL ok FROM sheet_material_copy_runs WHERE run_id='run-RR'")).rows[0].ok).toBe(true);
    expect(Number((await pool.query("SELECT sheet_material_type_id s FROM materials WHERE material_name='RR2 кромка'")).rows[0].s)).toBe(sRr);
  });

  it('aborts with a conflict (no writes) when a material name collides with an incompatible existing row', async () => {
    // Pre-existing row is ('PREEXISTING ручной лист', type=2, unit=1). Add a material with the SAME name but type=1.
    await pool.query("INSERT INTO materials (material_name, unit_id, material_type_id, default_supplier_id, vendor_id, is_active) VALUES ('PREEXISTING ручной лист', 1, 1, 1, 1, true)");
    await expect(runSheetCopy(pool, cfg('write', 'run-C'))).rejects.toBeInstanceOf(SheetCopyConflictError);
    expect((await pool.query("SELECT count(*)::int n FROM sheet_material_copy_runs WHERE run_id='run-C'")).rows[0].n).toBe(0); // nothing written
  });
});
