// backend/src/modules/orders/adapters/__fixtures__/variant-b-migration-fixture.ts
// Shared bootstrap and seed helpers for the Variant B migration 034 apply-integration test.
// Critic R7 M3: concrete bootstrap, not minimal schema.
// Critic R16 B1: reuses the PROVEN bootstrap029 from migration-029-apply.integration.ts.
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Client } from 'pg';

const mig = (n: string) =>
  readFileSync(join(__dirname, '../../../../../db/migrations', n), 'utf8');

// Critic R16 B1: DO NOT hand-roll the order schema (it omitted doweling_orders.order_id,
// which 029's orders_view JOINs on — the harness could not even apply 029). REUSE the
// PROVEN bootstrap from bootstrap029.ts (schema-create + 029-apply extracted to a
// non-test helper so importing it does NOT register the 029 test suite as duplicate
// describe blocks inside the 034 test file's collection context).
import { bootstrap029 } from '../bootstrap029';

export async function bootstrapVariantBSchema(client: Client): Promise<void> {
  await bootstrap029(client); // real order schema + clients/statuses/doweling_orders(+order_id)/... + 029 applied
  await client.query(`
    CREATE TABLE IF NOT EXISTS material_unit_conversions(material_id bigint references materials(material_id), from_unit_id smallint, to_unit_id smallint);
    CREATE TABLE IF NOT EXISTS requisition_items(material_id bigint references materials(material_id));
    CREATE TABLE IF NOT EXISTS material_transactions(material_id bigint references materials(material_id));
    CREATE TABLE IF NOT EXISTS warehouse_stock(material_id bigint references materials(material_id));
    CREATE TABLE IF NOT EXISTS order_resource_requirements(material_id bigint references materials(material_id));
  `);
  await client.query(mig('030_order_detail_shadow_pairing_trigger.sql'));
  await client.query(mig('033_order_material_conversion_map.sql')); // committed manifest 034 reads
}

// Seed the main Variant-A dataset.
// Separate from bootstrap so abort tests (applyInIsolatedSchema) can use a fresh
// schema with only the offending rows, without the main dataset.
//
// Dataset:
//   (a) sheet type id=<smtId> named 'МДФ VB тест' (the primary sheet for the live detail),
//       plus a SP2-linked real material (materials.sheet_material_type_id=<smtId>, is_sheet_shadow=false)
//   (b) a LIVE sheet detail on order_id=1 carrying shadow material_id + sheet_material_type_id=<smtId>
//       (satisfies migration-030 pairing trigger: shadow_of_sheet_material_type_id = smtId)
//   (c) a SOFT-DELETED legacy detail (delete_flag=true, sheet_material_type_id NULL pre-034,
//       material_id=161 which maps to ROUGH_MDF_16 via 033 manifest)
//   (d) a header-only legacy order (orders.material_id=161, no sheet; mapped via 033 manifest)
//   (e) a header-only order with NO material (material_id NULL, sheet NULL)
export async function seedVariantAMain(client: Client): Promise<void> {
  // (a) Sheet type for the live detail
  const smtRes = await client.query<{ sheet_material_type_id: number }>(
    `INSERT INTO sheet_material_types (name, unit_id, material_type_id, width_mm, height_mm, thickness_mm, is_active)
     VALUES ('МДФ VB тест', 1, 1, 2800, 2070, 16, true)
     RETURNING sheet_material_type_id`,
  );
  const smtId: number = smtRes.rows[0].sheet_material_type_id;

  // (a) SP2-linked real material: materials.sheet_material_type_id=smtId (SP2 link), is_sheet_shadow=false.
  //     This exercises the _matmap (a) SP2 derive path in 034.
  await client.query(
    `INSERT INTO materials (material_name, unit_id, material_type_id, is_sheet_shadow, sheet_material_type_id)
     VALUES ('МДФ VB реальный', 1, 1, false, $1)`,
    [smtId],
  );

  // (b) Shadow material for the live detail.
  //     is_sheet_shadow=true, shadow_of_sheet_material_type_id=smtId.
  //     sheet_material_type_id (the SP2 link column) must be NULL (chk_materials_shadow_shape).
  const shadowRes = await client.query<{ material_id: number }>(
    `INSERT INTO materials (material_name, unit_id, material_type_id, is_sheet_shadow, shadow_of_sheet_material_type_id, sheet_material_type_id)
     VALUES ('МДФ VB тест [лист]', 1, 1, true, $1, NULL)
     RETURNING material_id`,
    [smtId],
  );
  const shadowId: number = shadowRes.rows[0].material_id;

  // (c) Material id=161 for the soft-deleted legacy detail and the header-only legacy order.
  //     Must use OVERRIDING SYSTEM VALUE since materials uses GENERATED BY DEFAULT AS IDENTITY.
  //     161 is in the 033 manifest → maps to ROUGH_MDF_16.
  await client.query(
    `INSERT INTO materials (material_id, material_name, unit_id, material_type_id, is_sheet_shadow)
     OVERRIDING SYSTEM VALUE VALUES (161, 'ЛДСП Дуб (legacy-161)', 1, 1, false)`,
  );

  // (b) Live order — inserted first so IDENTITY sequence assigns order_id=1.
  //     No explicit id: the sequence starts at 1 in a fresh schema and no orders
  //     were inserted during bootstrap.
  await client.query(
    `INSERT INTO orders (order_name, sheet_eligible) VALUES ('VB тест заказ', true)`,
  );

  // (b) LIVE sheet detail on order_id=1.
  //     material_id=shadowId, sheet_material_type_id=smtId.
  //     Migration-030 trigger: shadow's shadow_of_sheet_material_type_id=smtId must equal sheet_material_type_id — OK.
  await client.query(
    `INSERT INTO order_details (order_id, detail_number, detail_name, height, width, quantity, area,
       material_id, sheet_material_type_id, milling_type_id, edge_type_id, priority)
     VALUES (1, 1, 'VB деталь 1', 600, 400, 1, 0.24, $1, $2, 1, 1, 100)`,
    [shadowId, smtId],
  );

  // (d) Header-only legacy order with material_id=161 and no sheet.
  //     chk_orders_sheet_xor_material: ok (sheet is NULL).
  await client.query(
    `INSERT INTO orders (order_name, material_id, sheet_eligible) VALUES ('VB заказ легаси', 161, false)`,
  );

  // (e) Header-only order with no material and no sheet (neutral — stays after 034).
  await client.query(
    `INSERT INTO orders (order_name, sheet_eligible) VALUES ('VB заказ без материала', true)`,
  );

  // (c) Soft-deleted order container for the soft-deleted detail.
  const delOrderRes = await client.query<{ order_id: number }>(
    `INSERT INTO orders (order_name, delete_flag, sheet_eligible) VALUES ('VB удалённый заказ', true, false) RETURNING order_id`,
  );
  const delOrderId: number = delOrderRes.rows[0].order_id;

  // (c) SOFT-DELETED legacy detail: delete_flag=true, material_id=161 (manifest-mapped),
  //     sheet_material_type_id=NULL pre-034. Migration 034 step 0a fills it for all details
  //     (incl. soft-deleted) before step 5 sets NOT NULL.
  await client.query(
    `INSERT INTO order_details (order_id, detail_number, detail_name, height, width, quantity, area,
       material_id, sheet_material_type_id, milling_type_id, edge_type_id, priority, delete_flag)
     VALUES ($1, 1, 'VB удалённая деталь', 500, 300, 1, 0.15, 161, NULL, 1, 1, 100, true)`,
    [delOrderId],
  );
}

// Critic R16 B2: per-test seed hook. Runs `seed(client)` (insert ONLY the offending
// row(s)) then `sql` against a FRESH isolated schema, so abort-path tests are executable.
//
// restoreSearchPath: caller passes the search_path string to restore after the nested
// schema is torn down. Required when the caller itself runs inside an isolated schema
// (e.g. the 034-apply test), so the client returns to the correct outer schema instead
// of falling back to 'public'. Pass null to restore to 'public' (original behaviour).
export async function applyInIsolatedSchema(
  client: Client,
  seed: (c: Client) => Promise<void>,
  sql: string,
  restoreSearchPath: string | null = null,
): Promise<void> {
  const schema = `vb_${process.hrtime.bigint()}`;
  await client.query(`CREATE SCHEMA ${schema}`);
  let failed = false;
  try {
    await client.query(`SET search_path TO ${schema}, public`);
    await bootstrapVariantBSchema(client); // deps in the isolated schema
    await seed(client); // ONLY the offending row(s)
    await client.query(sql); // expected to RAISE
  } catch (err) {
    failed = true;
    // migration 034 runs in an explicit BEGIN/COMMIT; when it RAISEs, Postgres
    // leaves the client in an aborted-transaction state. ROLLBACK so subsequent
    // queries (cleanup + later tests) are not poisoned by "current transaction
    // is aborted, commands ignored".
    try { await client.query('ROLLBACK'); } catch { /* ignore if no active tx */ }
    throw err; // re-throw so expect(...).rejects.toThrow() sees the real error
  } finally {
    if (!failed) {
      // nothing to roll back; cleanup normally
    }
    // Restore caller's search_path before dropping the nested schema.
    const restoreTo = restoreSearchPath ?? 'public';
    try { await client.query(`SET search_path TO ${restoreTo}`); } catch { /* ignore */ }
    await client.query(`DROP SCHEMA ${schema} CASCADE`);
  }
}
